import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Image } from 'expo-image';
import { CalendarDays, LockKeyhole, Sparkles } from 'lucide-react-native';
import { characterAssets, cityLifeAsset } from '../../src/assets';
import { EmptyState, LoadingSkeleton, PageTitle, Screen, SectionHeader } from '../../src/components';
import { colors, radius } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';
import { buildCompanionLife } from '../../src/lib/companionLife';
import type { DateSession } from '../../src/types';

const tabs=['Upcoming','Available','Past'] as const;type Tab=typeof tabs[number];
export function selectFeaturedDate(dates:DateSession[]){const rank:Record<string,number>={active:0,upcoming:1,unlocked:2,deferred:2,locked:3,completed:4};return [...dates].sort((left,right)=>(rank[left.status]??9)-(rank[right.status]??9)||new Date(right.completed_at??0).getTime()-new Date(left.completed_at??0).getTime())[0];}
export default function Dates(){const snapshot=useTogether((state)=>state.snapshot);const[tab,setTab]=useState<Tab>(()=>snapshot?.dates.some((date)=>['active','upcoming'].includes(date.status))?'Upcoming':'Available');if(!snapshot)return <LoadingSkeleton/>;const life=buildCompanionLife(snapshot);if(!life)return <EmptyState title="Nothing planned yet" body="Your shared experiences will appear as your story grows."/>;const featured=selectFeaturedDate(life.dates);const visible=useMemo(()=>life.dates.filter((date)=>tab==='Upcoming'?['active','upcoming'].includes(date.status):tab==='Available'?['unlocked','deferred','locked'].includes(date.status):date.status==='completed').sort((left,right)=>left.status.localeCompare(right.status)),[life.dates,tab]);const count=visible.length;return <Screen><View style={styles.header}><View><PageTitle>Dates</PageTitle><Text style={styles.subtitle}>Shared experiences, remembered.</Text></View><View style={styles.count}><CalendarDays size={16} color={colors.rose}/><Text style={styles.countText}>{count} {tab.toUpperCase()}</Text></View></View><View style={styles.tabs}>{tabs.map((item)=><Pressable key={item} onPress={()=>setTab(item)} style={[styles.tab,tab===item&&styles.tabActive]}><Text style={[styles.tabText,tab===item&&styles.tabTextActive]}>{item}</Text></Pressable>)}</View>{featured&&tab!=='Past'?<><SectionHeader title={featured.status==='active'?'Continue your experience':featured.status==='unlocked'?'Ready when you are':'A possibility ahead'}/><DateCard date={featured} featured onPress={()=>router.push(`/date/${featured.id}`)}/></>:null}<SectionHeader title={tab==='Upcoming'?'On the calendar':tab==='Available'?'Explore together':'Your shared history'}/>{visible.filter((date)=>date.id!==featured?.id||tab==='Past').length? <View style={styles.list}>{visible.filter((date)=>date.id!==featured?.id||tab==='Past').map((date)=><DateCard key={date.id} date={date} onPress={()=>router.push(`/date/${date.id}`)}/>)}</View>:<EmptyState title={tab==='Upcoming'?'Nothing planned yet':tab==='Available'?'Keep getting closer':'Your story is just beginning'} body={tab==='Upcoming'?'The next shared plan will find its moment.':tab==='Available'?'New experiences unlock naturally as trust and comfort grow.':'Completed experiences become part of your timeline.'}/>}</Screen>}
function DateCard({date,featured,onPress}:{date:DateSession;featured?:boolean;onPress:()=>void}){const mediaUrl=useTogether((state)=>state.snapshot?.generatedMedia?.find((item)=>item.date_session_id===date.id&&item.status==='ready')?.signed_url);const ready=['active','upcoming','unlocked','deferred','completed'].includes(date.status);const source=mediaUrl?{uri:mediaUrl}:characterAssets[date.together_date_templates.hero_asset_key??'']??cityLifeAsset;const label=date.status==='locked'?'Not quite yet':date.status==='completed'?'Shared memory':date.status==='active'?'In progress':date.status==='upcoming'?'Coming up':'Available now';return <Pressable disabled={!ready} onPress={onPress} style={({pressed})=>[styles.card,featured&&styles.featured,!ready&&styles.locked,pressed&&ready&&styles.pressed]}><Image source={source} style={styles.image} contentFit="cover"/><View style={styles.shade}/><View style={styles.cardTop}>{date.status==='locked'?<LockKeyhole size={15} color="#fff"/>:<Sparkles size={15} color="#fff"/>}<Text style={styles.cardStatus}>{label.toUpperCase()}</Text></View><View style={styles.cardBottom}><Text style={[styles.cardTitle,featured&&styles.featuredTitle]}>{date.together_date_templates.name}</Text><Text style={styles.cardCopy}>{date.status==='locked'?'Unlocks as your relationship grows.':date.together_date_templates.description}</Text></View></Pressable>}
const styles=StyleSheet.create({header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},subtitle:{color:colors.muted,marginTop:5},count:{flexDirection:'row',alignItems:'center',gap:6,paddingHorizontal:9,paddingVertical:7,borderRadius:radius.pill,backgroundColor:'rgba(241,103,154,.12)'},countText:{color:'#FFB8D0',fontSize:9,fontWeight:'800',letterSpacing:.7},tabs:{flexDirection:'row',backgroundColor:colors.surface,borderRadius:radius.md,padding:4,borderWidth:1,borderColor:colors.border},tab:{flex:1,alignItems:'center',padding:10,borderRadius:radius.sm},tabActive:{backgroundColor:colors.elevated},tabText:{color:colors.muted,fontWeight:'700',fontSize:12},tabTextActive:{color:colors.text,fontWeight:'900'},list:{gap:10},card:{height:156,borderRadius:radius.lg,overflow:'hidden',padding:13,justifyContent:'space-between',borderWidth:1,borderColor:colors.border},featured:{height:280,borderRadius:radius.xl},locked:{opacity:.7},pressed:{transform:[{scale:.985}],opacity:.9},image:{...StyleSheet.absoluteFill},shade:{...StyleSheet.absoluteFill,backgroundColor:'rgba(8,11,19,.48)'},cardTop:{zIndex:1,flexDirection:'row',alignItems:'center',gap:6},cardStatus:{color:'#fff',fontSize:9,fontWeight:'900',letterSpacing:1},cardBottom:{zIndex:1},cardTitle:{color:'#fff',fontFamily:'Georgia',fontSize:21,fontWeight:'600'},featuredTitle:{fontSize:30},cardCopy:{color:'#F2E9EE',fontSize:11,lineHeight:16,marginTop:4,maxWidth:'88%'}});
