import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Image } from 'expo-image';
import { ArrowUpRight, CalendarDays, Compass, Sparkles } from 'lucide-react-native';
import { characterAssets, cityLifeAsset } from '../../src/assets';
import { EmptyState, GlassCard, LoadingSkeleton, PageTitle, Screen, SectionHeader } from '../../src/components';
import { colors, radius, spacing } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';

export default function Discover() {
  const snapshot = useTogether((state) => state.snapshot);
  if (!snapshot) return <LoadingSkeleton label="Curating your world…" />;
  const maya = snapshot.characters.find((character) => character.together_character_templates.slug === 'maya');
  if (!maya) return <EmptyState title="Your world is waiting" body="Meet Maya at Juniper Café to begin discovering what is possible." />;
  const dinner = snapshot.dates[0];
  return <Screen>
    <View><PageTitle>Discover</PageTitle><Text style={styles.subtitle}>New ways your story can unfold.</Text></View>
    <Pressable onPress={() => router.push('/(tabs)/worlds')} style={({pressed}) => [styles.worldFeature, pressed && styles.pressed]}><Image source={cityLifeAsset} style={StyleSheet.absoluteFill} contentFit="cover"/><View style={styles.worldShade}/><View style={styles.worldTop}><View style={styles.worldPill}><Compass color="#fff" size={14}/><Text style={styles.worldPillText}>CITY LIFE</Text></View><ArrowUpRight color="#fff" size={18}/></View><View><Text style={styles.featureKicker}>YOUR LIVING WORLD</Text><Text style={styles.worldTitle}>Explore Juniper City</Text><Text style={styles.worldCopy}>People, places, and possibilities around your connection.</Text></View></Pressable>
    <SectionHeader title="People in your world" action="View world" onAction={() => router.push('/(tabs)/worlds')} />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.peopleRow}>{snapshot.characters.map((character) => { const slug = character.together_character_templates.slug; const known = slug === 'maya' || Boolean(character.introduced_at); return <Pressable key={character.id} disabled={!known} onPress={() => router.push(slug === 'maya' ? '/character/maya' : `/chat?character=${slug}`)} style={({pressed}) => [styles.person, !known && styles.personUnknown, pressed && styles.pressed]}><Image source={characterAssets[slug] ?? characterAssets.maya} style={styles.personImage} contentFit="cover" contentPosition="top"/><View style={styles.personCopy}><Text style={styles.personName}>{known ? character.together_character_templates.name : 'Someone new'}</Text><Text style={styles.personStatus}>{known ? character.current_activity : 'A connection waiting to happen'}</Text></View></Pressable>; })}</ScrollView>
    <SectionHeader title="Experiences" />
    <GlassCard style={styles.experience}><View style={styles.experienceIcon}><CalendarDays size={19} color={colors.warm}/></View><View style={{flex:1}}><Text style={styles.experienceKicker}>{dinner?.status === 'locked' ? 'UNLOCKING NATURALLY' : 'AVAILABLE NOW'}</Text><Text style={styles.experienceTitle}>Dinner at Juniper</Text><Text style={styles.experienceCopy}>{dinner?.status === 'locked' ? 'Keep getting to know Maya. When it feels right, the invitation will come.' : 'A shared night with choices, memories, and consequences.'}</Text></View><ArrowUpRight color={colors.rose} size={18}/></GlassCard>
    <SectionHeader title="Coming into focus" />
    <View style={styles.grid}><Teaser icon={<Sparkles size={21} color={colors.rose}/>} title="New Moments" copy="The important parts of your story collect here." onPress={() => router.push('/(tabs)/moments')}/><Teaser icon={<Compass size={21} color={colors.violet}/>} title="City happenings" copy="Explore the places and plans shaping Maya’s day." onPress={() => router.push('/(tabs)/worlds')}/></View>
  </Screen>;
}
function Teaser({icon,title,copy,onPress}:{icon:React.ReactNode;title:string;copy:string;onPress:()=>void}) { return <Pressable onPress={onPress} style={({pressed}) => [styles.teaser,pressed&&styles.pressed]}>{icon}<Text style={styles.teaserTitle}>{title}</Text><Text style={styles.teaserCopy}>{copy}</Text></Pressable>; }
const styles=StyleSheet.create({subtitle:{color:colors.muted,marginTop:5},worldFeature:{height:282,borderRadius:radius.xl,overflow:'hidden',padding:spacing.md,justifyContent:'space-between',borderWidth:1,borderColor:colors.border},worldShade:{...StyleSheet.absoluteFill,backgroundColor:'rgba(10,9,16,.42)'},worldTop:{zIndex:1,flexDirection:'row',justifyContent:'space-between'},worldPill:{flexDirection:'row',alignItems:'center',gap:6,paddingHorizontal:9,paddingVertical:6,borderRadius:radius.pill,backgroundColor:'rgba(10,9,16,.55)'},worldPillText:{color:'#fff',fontSize:9,fontWeight:'900',letterSpacing:1},featureKicker:{color:'#F6D4E1',fontSize:10,fontWeight:'900',letterSpacing:1.2},worldTitle:{color:'#fff',fontFamily:'Georgia',fontSize:30,marginTop:5},worldCopy:{color:'#F6E8ED',fontSize:12,marginTop:4},peopleRow:{gap:12,paddingRight:spacing.lg},person:{width:154,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,overflow:'hidden'},personUnknown:{opacity:.55},personImage:{width:'100%',height:138},personCopy:{padding:10},personName:{color:colors.text,fontSize:14,fontWeight:'800'},personStatus:{color:colors.muted,fontSize:10,lineHeight:14,marginTop:3},experience:{flexDirection:'row',alignItems:'center',gap:11},experienceIcon:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(233,160,127,.11)'},experienceKicker:{color:colors.rose,fontSize:9,fontWeight:'900',letterSpacing:1},experienceTitle:{color:colors.text,fontFamily:'Georgia',fontSize:21,marginTop:2},experienceCopy:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:3},grid:{flexDirection:'row',gap:10},teaser:{flex:1,minHeight:150,padding:14,gap:10,borderRadius:radius.lg,backgroundColor:colors.elevated,borderWidth:1,borderColor:colors.border},teaserTitle:{color:colors.text,fontSize:15,fontWeight:'800'},teaserCopy:{color:colors.muted,fontSize:11,lineHeight:16},pressed:{opacity:.88,transform:[{scale:.98}]} });
