import{useState}from'react';
import{Pressable,StyleSheet,Text,View}from'react-native';
import{router}from'expo-router';
import{ArrowUpRight,CalendarDays,LockKeyhole,Palmtree}from'lucide-react-native';
import{CharacterAvatar,EmptyState,LoadingSkeleton,PageTitle,Screen,SectionHeader}from'../../src/components';
import{colors,radius}from'../../src/theme';
import{useTogether}from'../../src/store/useTogether';
import type{Snapshot}from'../../src/types';

type Tab='People'|'Experiences';const stageOrder=['stranger','acquaintance','friend','flirting','dating','exclusive','long_term'];
export default function Discover(){const snapshot=useTogether((state)=>state.snapshot);const[tab,setTab]=useState<Tab>('People');if(!snapshot)return <LoadingSkeleton label="Curating people and experiences…"/>;return <Screen><View><PageTitle>Discover</PageTitle><Text style={styles.subtitle}>Meet someone new, or find something meaningful to do together.</Text></View><View style={styles.tabs}>{(['People','Experiences']as const).map((item)=><Pressable key={item} onPress={()=>setTab(item)} style={[styles.tab,tab===item&&styles.tabSelected]}><Text style={[styles.tabText,tab===item&&styles.tabTextSelected]}>{item}</Text></Pressable>)}</View>{tab==='People'?<People snapshot={snapshot}/>:<Experiences snapshot={snapshot}/>}</Screen>}
function People({snapshot}:{snapshot:Snapshot}){const people=snapshot.discoverableCharacters??[];if(!people.length)return <EmptyState title="New people are on the way" body="Your current relationships are still waiting on Home."/>;return <><SectionHeader title="People you might connect with"/><View style={styles.stack}>{people.map((template)=>{const instance=snapshot.characters.find((item)=>item.character_template_id===template.id);const active=instance?.id===snapshot.profile?.active_companion_instance_id;const established=Boolean(instance?.contact_added_at||instance?.introduced_at);const action=active?`Continue with ${template.name}`:established?`View your relationship`:`Meet ${template.name}`;const worldId=instance?snapshot.locations.find((item)=>item.id===instance.current_location_id)?.world_id:template.first_meeting?.world_id;const world=snapshot.worlds.find((item)=>item.id===worldId)?.name??'Available world';return <Pressable key={template.id} onPress={()=>router.push(`/character/${template.slug}` as never)} style={({pressed})=>[styles.person,pressed&&styles.pressed]}><CharacterAvatar slug={template.slug} name={template.name} size={76}/><View style={{flex:1}}><Text style={styles.personName}>{template.name}, {template.age}</Text><Text style={styles.personMeta}>{template.occupation} · {world}</Text><Text style={styles.summary} numberOfLines={2}>{template.biography}</Text><Text style={styles.interests}>{(template.together_character_versions?.interests??[]).slice(0,3).join(' · ')}</Text><Text style={styles.action}>{action}</Text></View><ArrowUpRight size={18} color={colors.rose}/></Pressable>})}</View></>}
function Experiences({snapshot}:{snapshot:Snapshot}){const active=snapshot.characters.find((item)=>item.id===snapshot.profile?.active_companion_instance_id);const stage=stageOrder.indexOf(active?.relationship_stage??'stranger');return <><SectionHeader title="Dates and shared experiences"/><View style={styles.stack}>{snapshot.dates.filter((item)=>!active||item.character_instance_id===active.id).map((date)=>{const locked=date.status==='locked';return <Pressable key={date.id} disabled={locked} onPress={()=>router.push(`/date/${date.id}` as never)} style={[styles.experience,locked&&styles.locked]}><View style={styles.icon}><CalendarDays size={21} color={colors.warm}/></View><View style={{flex:1}}><Text style={styles.kicker}>{locked?'GROW CLOSER TO UNLOCK':date.status==='completed'?'SHARED HISTORY':'AVAILABLE'}</Text><Text style={styles.title}>{date.together_date_templates.name}</Text><Text style={styles.summary}>{date.together_date_templates.description}</Text></View>{locked?<LockKeyhole size={17} color={colors.dimmed}/>:<ArrowUpRight size={18} color={colors.rose}/>}</Pressable>})}{(snapshot.trips??[]).map((trip)=>{const locked=stage<stageOrder.indexOf(trip.min_relationship_stage);return <View key={trip.slug} style={[styles.experience,locked&&styles.locked]}><View style={styles.icon}><Palmtree size={21} color={colors.violet}/></View><View style={{flex:1}}><Text style={styles.kicker}>{locked?'FUTURE EXPERIENCE':'COMING SOON'}</Text><Text style={styles.title}>{trip.title}</Text><Text style={styles.summary}>{trip.description}</Text></View><LockKeyhole size={17} color={colors.dimmed}/></View>})}</View></>}
const styles=StyleSheet.create({subtitle:{color:colors.muted,marginTop:5,lineHeight:19},tabs:{flexDirection:'row',gap:7,padding:4,backgroundColor:colors.surface,borderRadius:radius.md,borderWidth:1,borderColor:colors.border},tab:{flex:1,minHeight:40,justifyContent:'center',alignItems:'center',borderRadius:radius.sm},tabSelected:{backgroundColor:colors.rose},tabText:{color:colors.muted,fontSize:12,fontWeight:'800'},tabTextSelected:{color:'#fff'},stack:{gap:10},person:{flexDirection:'row',alignItems:'center',gap:13,padding:13,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},personName:{fontFamily:'Georgia',fontSize:21,color:colors.text},personMeta:{color:colors.rose,fontSize:11,fontWeight:'700',marginTop:2},summary:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:5},interests:{color:colors.text,fontSize:10,marginTop:5},action:{color:colors.rose,fontSize:11,fontWeight:'900',marginTop:7},experience:{flexDirection:'row',alignItems:'center',gap:11,padding:13,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},locked:{opacity:.68},icon:{width:43,height:43,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:colors.elevated},kicker:{color:colors.rose,fontSize:9,fontWeight:'900',letterSpacing:1},title:{color:colors.text,fontFamily:'Georgia',fontSize:20,marginTop:3},pressed:{opacity:.86,transform:[{scale:.985}]}});
