begin;
select plan(34);
select has_table('public','together_character_templates','Together character templates exist');
select has_table('public','together_character_versions','Together character versions exist');
select has_table('public','together_character_instances','Together instances exist');
select has_table('public','together_relationship_states','Together relationship state exists');
select has_table('public','together_relationship_milestones','Together relationship milestones exist');
select has_table('public','together_memories','Together memories exist');
select has_table('public','together_open_threads','Together open threads exist');
select has_table('public','together_life_events','Together life events exist');
select has_table('public','together_knowledge_transfers','Together knowledge transfers exist');
select has_table('public','together_date_sessions','Together dates exist');
select has_table('public','together_moments','Together moments exist');
select has_table('public','together_entitlements','Together entitlements exist');
select row_eq('select name,age,occupation from public.together_character_templates where slug=''maya''',row('Maya',26,'Photographer')::record,'Maya seed is stable');
select results_eq('select count(*)::bigint from public.together_character_templates where published',array[3::bigint],'Three initial characters are published');
select results_eq('select count(*)::bigint from public.together_locations',array[6::bigint],'Six City Life locations exist');
select results_eq('select count(*)::bigint from public.together_date_templates where active',array[1::bigint],'One active MVP date exists');
select is((select current_published_version from public.together_character_templates where slug='maya'),1,'Maya template pins version one');
select ok((select relrowsecurity from pg_class where oid='public.together_memories'::regclass),'Memory RLS is enabled');
select ok((select relrowsecurity from pg_class where oid='public.together_character_instances'::regclass),'Instance RLS is enabled');
select ok((select relrowsecurity from pg_class where oid='public.together_relationship_milestones'::regclass),'Relationship milestone RLS is enabled');
select has_column('public','together_memories','subject_key','Memories have stable subject keys');
select has_column('public','together_open_threads','dedupe_key','Open threads have dedupe keys');
select has_column('public','together_conversations','summary','Conversations retain compact summaries');
select has_column('public','together_conversations','summary_through','Conversation summaries track their boundary');
select has_column('public','together_conversations','summary_message_count','Conversation summary size is tracked');
select has_column('public','together_life_events','simulation_key','Life events have deterministic simulation keys');
select has_column('public','together_proactive_messages','dedupe_key','Proactive messages have stable dedupe keys');
select has_column('public','together_proactive_messages','context','Proactive messages retain delivery context');
select has_extension('pg_net','pg_net is available for scheduled dispatch');
select has_extension('pg_cron','pg_cron is available for scheduled dispatch');
select results_eq('select count(*)::bigint from cron.job where jobname=''together-life-dispatch''',array[1::bigint],'One proactive Life dispatcher is scheduled');
select has_column('public','together_notification_preferences','date_reminders','Date reminder preferences are stored');
select has_column('public','together_notification_preferences','world_event_updates','World event preferences are stored');
select has_column('public','together_character_instances','last_event_simulated_at','Narrative event catch-up has an independent cursor');
select * from finish();
rollback;
