begin;
select plan(29);
select has_column('public','together_worlds','access_type','World access is content-owned');
select has_column('public','together_worlds','timezone','World local time is canonical');
select has_column('public','together_worlds','visual_context','World visual context is canonical');
select has_column('public','together_worlds','default_arrival_location_id','Worlds have deterministic arrival places');
select has_column('public','together_locations','parent_location_id','Locations are hierarchical');
select has_column('public','together_locations','location_type','Location hierarchy has controlled presentation types');
select has_column('public','together_locations','canonical_visual_context','Locations own their visual identity');
select has_table('public','together_user_worlds','User world access is explicit');
select has_table('public','together_character_world_presence','Character presence is world-specific');
select has_column('public','together_generated_media','world_id','Generated media preserves its world');
select has_column('public','together_shared_plans','world_id','Plans preserve their world');
select has_column('public','together_story_arc_templates','world_scope','Stories declare world scope');
select has_column('public','together_relationship_states','interaction_turn_count','Interaction turns are distinct from sessions');
select has_column('public','together_relationship_states','conversation_session_count','Conversation sessions are counted canonically');
select has_column('public','together_relationship_states','meaningful_interaction_count','Meaningful interactions drive progression');
select has_column('public','together_relationship_states','last_interaction_quality','Latest quality is inspectable internally');
select has_column('public','together_relationship_states','last_relationship_delta','Latest bounded relationship change is inspectable');
select has_column('public','together_character_templates','first_meeting','First meetings are authored companion content');
select has_column('public','together_character_templates','discovery_metadata','Discovery metadata is server-published');
select has_column('public','together_date_templates','metadata','Date execution reads authored effects');
select trigger_is('public','together_locations','together_locations_validate_parent','public','kivelle_validate_location_parent','Cross-world parents and cycles are rejected');
select trigger_is('public','together_generated_media','together_generated_media_derive_world','public','kivelle_derive_place_world','Media world derives from canonical location');
select trigger_is('public','together_shared_plans','together_shared_plans_derive_world','public','kivelle_derive_place_world','Plan world derives from canonical location');
select trigger_is('public','together_conversations','together_conversation_session_count','public','kivelle_count_conversation_session','Conversation creation updates session count');
select is((select access_type from public.together_worlds where slug='juniper-city'),'free','Starter world access is data-driven free content');
select ok((select count(distinct first_meeting->>'location_id') from public.together_character_templates where published and can_be_selected)>1,'Selectable companions do not all share one first meeting');
select ok(not exists(select 1 from public.together_character_templates where published and can_be_selected and (first_meeting->>'world_id' is null or first_meeting->>'location_id' is null or first_meeting->>'opening_line' is null)),'Every selectable companion has complete first-meeting context');
select ok((select relrowsecurity from pg_class where oid='public.together_user_worlds'::regclass),'User world access uses RLS');
select ok((select relrowsecurity from pg_class where oid='public.together_character_world_presence'::regclass),'Character world presence uses RLS');
select * from finish();
rollback;
