begin;
select plan(35);
select has_table('public','together_relationship_evidence','Relationship history has a canonical evidence ledger');
select has_column('public','together_relationship_states','stage_entered_at','Relationship stage entry time is canonical');
select has_column('public','together_relationship_states','dating_started_at','Dating start time is canonical');
select has_column('public','together_relationship_states','exclusive_at','Exclusivity time is canonical');
select has_column('public','together_relationship_states','long_term_at','Long-term declaration time is canonical');
select has_column('public','together_relationship_states','romance_path_status','Friendship-only romance choice is canonical');
select has_column('public','together_relationship_states','relationship_health_cache','Relationship health is separate from stage');
select has_column('public','together_relationship_states','evidence_summary_cache','Evidence readiness is inspectable without exposing an XP bar');
select has_column('public','together_relationship_states','last_major_milestone_at','Major milestone cooldown has a canonical clock');
select has_column('public','together_relationship_states','next_milestone_kind','Next eligible declaration can be cached');
select has_column('public','together_relationship_states','next_milestone_presentable','Eligibility is separate from presentation timing');
select has_column('public','together_relationship_states','relationship_defining_date_session_id','Any world Date can be relationship-defining');
select has_column('public','together_relationship_states','major_conflict_started_at','Conflict repair can be required only after real major conflict');
select ok((select relrowsecurity from pg_class where oid='public.together_relationship_evidence'::regclass),'Relationship evidence uses RLS');
select ok(to_regprocedure('public.kivelle_relationship_local_date(timestamp with time zone,text)') is not null,'Relationship evidence uses world/user local dates');
select ok(to_regprocedure('public.kivelle_insert_relationship_evidence(uuid,uuid,text,text,text,timestamp with time zone,numeric,numeric,text,jsonb)') is not null,'Canonical evidence insertion helper is installed');
select ok(to_regprocedure('public.kivelle_relationship_progression_state(uuid,uuid,timestamp with time zone)') is not null,'Canonical progression evaluator is installed');
select ok(to_regprocedure('public.kivelle_evaluate_relationship_progression(uuid,uuid,timestamp with time zone)') is not null,'Progression materializer is installed');
select ok(exists(select 1 from pg_constraint where conrelid='public.together_relationship_milestones'::regclass and pg_get_constraintdef(oid) like '%dating_start%' and pg_get_constraintdef(oid) like '%exclusivity%' and pg_get_constraintdef(oid) like '%long_term%'),'Milestones support Dating, Exclusivity, and Long-term declarations');
select trigger_is('public','together_relationship_milestones','together_relationship_milestone_v2_guard','public','kivelle_guard_relationship_milestone_insert','Legacy milestone writes cannot bypass V2 eligibility');
select trigger_is('public','together_character_instances','together_character_relationship_stage_stamp','public','kivelle_stamp_relationship_stage','Explicit stage changes stamp their canonical time');
select trigger_is('public','together_relationship_states','together_relationship_major_conflict_stamp','public','kivelle_track_major_relationship_conflict','Major conflict start is tracked');
select trigger_is('public','together_relationship_milestones','together_relationship_milestone_resolution_v2','public','kivelle_relationship_milestone_resolution_v2','Explicit milestone choices update V2 relationship state');
select trigger_is('public','together_messages','together_message_relationship_evidence_v2','public','kivelle_message_relationship_evidence_v2','Future planning and romance reopening are captured from user truth');
select trigger_is('public','together_relationship_states','together_relationship_state_evidence_v2','public','kivelle_relationship_state_evidence_v2','Server-classified conversations emit progression evidence');
select trigger_is('public','together_shared_plans','together_plan_relationship_evidence_v2','public','kivelle_plan_relationship_evidence_v2','Plans and Trips emit lived relationship evidence');
select trigger_is('public','together_date_sessions','together_date_relationship_evidence_v2','public','kivelle_date_relationship_evidence_v2','Completed Dates emit relationship evidence');
select trigger_is('public','together_moments','together_moment_relationship_evidence_v2','public','kivelle_moment_relationship_evidence_v2','Major Moments emit relationship evidence');
select trigger_is('public','together_missed_plan_resolutions','together_repaired_miss_evidence_v2','public','kivelle_repaired_miss_evidence_v2','Successful miss repair emits repair evidence');
select trigger_is('public','together_character_instances','together_character_relationship_moment_recheck_v2','public','kivelle_character_relationship_moment_recheck_v2','Personal state can delay or surface a milestone');
select trigger_is('public','together_relationship_evidence','together_relationship_evidence_recheck_v2','public','kivelle_relationship_evidence_recheck_v2','New lived evidence reevaluates progression');
select ok(not exists(select 1 from public.together_date_templates where metadata #>> '{completion_effects,relationship_stage}' is not null),'Date templates no longer directly promote relationship stages');
select ok(exists(select 1 from pg_constraint where conrelid='public.together_relationship_evidence'::regclass and pg_get_constraintdef(oid) like '%trip_completed%' and pg_get_constraintdef(oid) like '%future_planning%'),'Evidence types include Trips and future planning');
select ok(exists(select 1 from pg_constraint where conrelid='public.together_relationship_evidence'::regclass and pg_get_constraintdef(oid) like '%date_session%' and pg_get_constraintdef(oid) like '%shared_plan%'),'Evidence records canonical source families');
select ok(exists(select 1 from pg_constraint where conrelid='public.together_relationship_states'::regclass and pg_get_constraintdef(oid) like '%friends_only%'),'Romance path supports an explicit friendship-only state');
select * from finish();
rollback;
