begin;
select plan(35);

select has_table('public','together_conversation_participants','group conversations have an authoritative roster');
select has_table('public','together_dialogue_turns','group turns have persistent floor state');
select has_table('public','together_message_reactions','character reactions are canonical records');
select like((select pg_get_constraintdef(oid) from pg_constraint where conrelid='public.together_conversations'::regclass and conname='together_conversations_kind_check'),'%group%','group is a first-class conversation kind');
select has_column('public','together_conversations','message_sequence','group conversations own an atomic sequence');
select has_column('public','together_conversation_participants','witnessed_from_sequence','participant knowledge has a lower witness boundary');
select has_column('public','together_conversation_participants','witnessed_to_sequence','participant knowledge has an upper witness boundary');
select has_column('public','together_conversation_participants','joined_at','participant joins are canonical');
select has_column('public','together_conversation_participants','left_at','participant leaves are canonical');
select has_column('public','together_messages','conversation_sequence','group messages preserve canonical order');
select has_column('public','together_messages','reply_to_message_id','direct replies retain their target');
select has_column('public','together_messages','mentioned_character_instance_ids','mentions retain immutable character ids');
select has_column('public','together_messages','dialogue_turn_id','generated messages retain their floor turn');
select has_column('public','together_memories','visibility','memory audience is explicit');
select has_column('public','together_memories','group_conversation_id','group-visible memory retains its source group');
select has_column('public','together_memories','learned_conversation_sequence','learned facts retain witness order');
select has_column('public','together_generated_media','subject_character_instance_ids','future group media can preserve multiple subjects');
select has_column('public','together_media_offers','subject_character_instance_ids','future group offers can preserve multiple subjects');
select has_index('public','together_conversation_participants','together_conversation_participant_active_idx','active membership is unique');
select has_index('public','together_messages','together_messages_conversation_sequence_idx','group message sequence is unique');
select has_index('public','together_dialogue_turns','together_dialogue_turns_active_idx','active group turns are indexed');
select policies_are('public','together_conversation_participants',array['together_conversation_participants_own_read'],'group membership is privately readable');
select policies_are('public','together_dialogue_turns',array['together_dialogue_turns_own_read'],'turn state is privately readable');
select policies_are('public','together_message_reactions',array['together_message_reactions_own_read'],'reactions are privately readable');
select ok(to_regprocedure('public.kivelle_commit_group_message(uuid,integer,uuid,text,jsonb)') is not null,'group message commit RPC exists');
select ok(to_regprocedure('public.kivelle_commit_group_reaction(uuid,integer,uuid,uuid,text,jsonb)') is not null,'group reaction commit RPC exists');
select ok(not has_function_privilege('authenticated','public.kivelle_commit_group_message(uuid,integer,uuid,text,jsonb)','EXECUTE'),'clients cannot commit generated group messages');
select ok(not has_function_privilege('authenticated','public.kivelle_commit_group_reaction(uuid,integer,uuid,uuid,text,jsonb)','EXECUTE'),'clients cannot commit generated reactions');
select trigger_is('public','together_messages','together_messages_group_sequence','public','kivelle_assign_group_message_sequence','group message ordering is assigned atomically');
select trigger_is('public','together_conversation_participants','together_conversation_participants_validate','public','kivelle_validate_group_participant','participant identity is validated at the database boundary');
select trigger_is('public','together_message_reactions','together_message_reactions_validate','public','kivelle_validate_group_reaction','reaction identity is validated at the database boundary');
select like(pg_get_functiondef('public.kivelle_commit_group_message(uuid,integer,uuid,text,jsonb)'::regprocedure),'%v_turn.version<>p_version%','stale turn versions cannot commit messages');
select like(pg_get_functiondef('public.kivelle_commit_group_message(uuid,integer,uuid,text,jsonb)'::regprocedure),'%p.left_at is null%','removed participants cannot commit messages');
select like(pg_get_functiondef('public.kivelle_commit_group_reaction(uuid,integer,uuid,uuid,text,jsonb)'::regprocedure),'%c.archived_at is null%','archived groups reject queued reactions');
select trigger_is('public','together_messages','together_message_relationship_evidence_v2','public','kivelle_message_relationship_evidence_v2','direct relationship evidence remains on its canonical trigger');

select * from finish();
rollback;
