import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Image } from 'expo-image';
import { ArrowLeft, CalendarDays, Sparkles, Users } from 'lucide-react-native';
import { characterAssets } from '../../src/assets';
import { Body, EmptyState, GlassCard, LoadingSkeleton, Screen, SectionHeader } from '../../src/components';
import { colors, radius } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';
import { buildCompanionLife } from '../../src/lib/companionLife';

export default function MomentDetail(){const {id}=useLocalSearchParams<{id:string}>();const snapshot=useTogether((state)=>state.snapshot);if(!snapshot)return <LoadingSkeleton/>;const moment=snapshot.moments.find((item)=>item.id===id);const life=buildCompanionLife(snapshot);if(!moment||!life)return <EmptyState title="Moment unavailable" body="This part of your story may no longer be available." action="Back to Moments" onAction={()=>router.replace('/(tabs)/moments')}/>;const location=snapshot.locations.find((item)=>moment.summary.toLowerCase().includes(item.name.toLowerCase().split(' ')[0] ?? ''));return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><ArrowLeft size={19} color={colors.text}/></Pressable><Text style={styles.kicker}>A SHARED MOMENT</Text></View><Image source={characterAssets[moment.media[0]?.asset ?? life.companion.together_character_templates.slug] ?? characterAssets.maya} style={styles.hero} contentFit="cover" contentPosition="top"/><Text style={styles.title}>{moment.title}</Text><Text style={styles.meta}>{new Date(moment.occurred_at).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}{location?` · ${location.name}`:''}</Text><SectionHeader title="What happened"/><Body muted>{moment.summary}</Body><GlassCard style={styles.memory}><Sparkles size={18} color={colors.rose}/><View style={{flex:1}}><Text style={styles.memoryTitle}>{life.companion.together_character_templates.name} remembers</Text><Text style={styles.memoryCopy}>This is part of the history you are building together.</Text></View></GlassCard><SectionHeader title="People"/><GlassCard style={styles.row}><Users size={18} color={colors.violet}/><Text style={styles.rowText}>{life.companion.together_character_templates.name} · You</Text></GlassCard><SectionHeader title="Relationship"/><GlassCard style={styles.row}><CalendarDays size={18} color={colors.warm}/><Text style={styles.rowText}>Day {life.relationshipDay} · {life.companion.relationship_stage.replace('_',' ')}</Text></GlassCard></Screen>}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},kicker:{color:colors.rose,fontSize:10,fontWeight:'900',letterSpacing:1.2},hero:{width:'100%',height:300,borderRadius:radius.xl},title:{fontFamily:'Georgia',fontSize:34,color:colors.text},meta:{color:colors.muted,fontSize:12,marginTop:-10},memory:{flexDirection:'row',gap:11,alignItems:'flex-start'},memoryTitle:{color:colors.text,fontWeight:'800'},memoryCopy:{color:colors.muted,fontSize:12,lineHeight:17,marginTop:3},row:{flexDirection:'row',gap:11,alignItems:'center'},rowText:{color:colors.text,fontWeight:'700'}});
