import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Image } from 'expo-image';
import { ArrowLeft } from 'lucide-react-native';
import { characterAssets } from '../../src/assets';
import { Body, GradientButton, LoadingSkeleton, MoodBadge, RelationshipBadge, Screen } from '../../src/components';
import { colors, radius, spacing } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';

export default function CharacterProfile(){const{slug}=useLocalSearchParams<{slug:string}>();const snapshot=useTogether((state)=>state.snapshot);if(!snapshot)return <LoadingSkeleton/>;const character=snapshot.characters.find((item)=>item.together_character_templates.slug===slug);if(!character)return null;const template=character.together_character_templates;const location=snapshot.locations.find((item)=>item.id===character.current_location_id)?.name??'City Life';return <Screen contentStyle={{padding:0}}><View style={styles.hero}><Image source={characterAssets[slug]??characterAssets.maya} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="top"/><Pressable onPress={()=>router.back()} style={styles.back}><ArrowLeft color="#fff"/></Pressable><View style={styles.shade}/><View style={styles.title}><Text style={styles.name}>{template.name}</Text><Text style={styles.job}>{template.occupation}</Text></View></View><View style={styles.body}><View style={styles.badges}><MoodBadge mood={character.current_mood}/><RelationshipBadge stage={character.relationship_stage}/></View><View style={styles.tabs}><Text style={styles.tabActive}>About</Text><Text style={styles.tab}>Relationship</Text><Text style={styles.tab}>Moments</Text></View><Text style={styles.heading}>About {template.name}</Text><Body muted>{template.biography}</Body><Info label="Age" value={String(template.age)}/><Info label="Location" value={location}/><Info label="Occupation" value={template.occupation}/><Info label="Interests" value={character.together_character_versions.interests.join(', ')}/><GradientButton label={`Talk to ${template.name}`} onPress={()=>router.push(slug==='maya'?'/chat':`/chat?character=${slug}`)}/></View></Screen>;}
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>;}
const styles=StyleSheet.create({hero:{height:520,justifyContent:'flex-end'},shade:{...StyleSheet.absoluteFill,backgroundColor:'rgba(8,11,19,.25)'},back:{position:'absolute',top:52,left:16,zIndex:2,width:42,height:42,borderRadius:21,backgroundColor:'rgba(8,11,19,.55)',alignItems:'center',justifyContent:'center'},title:{padding:spacing.lg,zIndex:1},name:{fontFamily:'Georgia',fontSize:38,color:'#fff'},job:{color:'#fff',fontSize:16,marginTop:4},body:{marginTop:-20,borderTopLeftRadius:radius.xl,borderTopRightRadius:radius.xl,backgroundColor:colors.background,padding:spacing.lg,gap:spacing.md},badges:{flexDirection:'row',gap:8},tabs:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:colors.border},tab:{flex:1,textAlign:'center',padding:12,color:colors.muted},tabActive:{flex:1,textAlign:'center',padding:12,color:colors.rose,borderBottomWidth:2,borderBottomColor:colors.rose,fontWeight:'800'},heading:{fontFamily:'Georgia',fontSize:22,color:colors.text},info:{flexDirection:'row',justifyContent:'space-between',paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.border},label:{color:colors.muted},value:{color:colors.text,maxWidth:'67%',textAlign:'right'}});
