import type{SupabaseClient}from'@supabase/supabase-js';
import{commitmentRelevanceScore,deriveCommitmentTemporalState}from'../../../packages/together-domain/src/index.ts';
type Row=Record<string,any>;
export type ConversationCommitment={id:string;title:string;activityKey:string;status:string;temporalState:string;relevance:number;startsAt:string|null;endsAt:string|null;windowStartsAt:string|null;windowEndsAt:string|null;timePrecision:string;originalTimeExpression:string|null;worldTimezone:string;userTimezone:string;locationId:string|null;location:string;participationMode:string;companionState:string;companionEtaAt:string|null;companionReason:string|null;userJoinedAt:string|null;characterJoinedAt:string|null;missReason:string|null;missResolutionStatus:string|null;missExplanation:string|null;source:string};
export async function loadConversationCommitments(db:SupabaseClient,input:{userId:string;continuityId:string;characterInstanceId:string;queryIntent:string;now?:Date}):Promise<ConversationCommitment[]>{
 const now=input.now??new Date();
 const{data}=await db.from('together_shared_plans').select('*,together_locations(name),together_plan_attendance(participant_type,joined_at,left_at),together_missed_plan_resolutions(status,miss_reason,explanation,resolved_at)').eq('user_id',input.userId).eq('continuity_id',input.continuityId).eq('character_instance_id',input.characterInstanceId).in('status',['proposed','scheduled','active','missed']).order('created_at',{ascending:false}).limit(30);
 const planningIntent=['plan','schedule','date'].includes(input.queryIntent);
 return(data??[]).map((plan:Row)=>{
   const attendance=Array.isArray(plan.together_plan_attendance)?plan.together_plan_attendance:[],resolution=Array.isArray(plan.together_missed_plan_resolutions)?plan.together_missed_plan_resolutions[0]:plan.together_missed_plan_resolutions;
   const userAttendance=attendance.find((row:Row)=>row.participant_type==='user'),characterAttendance=attendance.find((row:Row)=>row.participant_type==='character');
   const timing={status:String(plan.status),startsAt:plan.starts_at,endsAt:plan.ends_at,windowStartsAt:plan.window_starts_at,windowEndsAt:plan.window_ends_at,graceEndsAt:plan.grace_ends_at,timezone:plan.user_timezone??plan.world_timezone,participationMode:plan.participation_mode,userJoinedAt:userAttendance?.joined_at,characterJoinedAt:characterAttendance?.joined_at,missResolutionStatus:resolution?.status};
   return{id:String(plan.id),title:String(plan.title),activityKey:String(plan.activity_key),status:String(plan.status),temporalState:deriveCommitmentTemporalState(timing,now),relevance:commitmentRelevanceScore(timing,now),startsAt:plan.starts_at??null,endsAt:plan.ends_at??null,windowStartsAt:plan.window_starts_at??null,windowEndsAt:plan.window_ends_at??null,timePrecision:String(plan.time_precision??'exact'),originalTimeExpression:plan.original_time_expression??null,worldTimezone:String(plan.world_timezone??'UTC'),userTimezone:String(plan.user_timezone??'UTC'),locationId:plan.location_id?String(plan.location_id):null,location:String(plan.together_locations?.name??'Current place'),participationMode:String(plan.participation_mode??'live'),companionState:String(plan.companion_state??'expected'),companionEtaAt:plan.companion_eta_at??null,companionReason:plan.companion_reason??null,userJoinedAt:userAttendance?.joined_at??null,characterJoinedAt:characterAttendance?.joined_at??null,missReason:resolution?.miss_reason??plan.miss_reason??null,missResolutionStatus:resolution?.status??null,missExplanation:resolution?.explanation??null,source:String(plan.source??'chat')};
 }).filter((row)=>row.relevance>=.4||row.status==='missed'||planningIntent).sort((a,b)=>b.relevance-a.relevance||(a.startsAt?new Date(a.startsAt).getTime():Infinity)-(b.startsAt?new Date(b.startsAt).getTime():Infinity)).slice(0,planningIntent?8:4);
}
