import type{SupabaseClient}from'@supabase/supabase-js';
import{AppError}from'./types.ts';
import{canonicalRequestForMedia}from'./together-media-base.ts';
import{configuredMediaRegistry,providerAttemptsFromError,providerForCapability,routeCanonicalMedia,type CanonicalMediaRequest,type ProviderAttempt}from'./together-media-providers.ts';
import{failMediaBeforeProvider,failProviderMedia,finalizeProviderMedia}from'./together-media-finalizer.ts';
import{configuredWaveSpeedClient}from'./wavespeed.ts';
import{resolveSubscriptionState}from'./kivelle-subscription.ts';
import{track}from'./together.ts';
import{dispatchCreatorAppearanceJobs,dispatchLoraTrainingJobs,finalizeAuxiliaryProviderJob}from'./together-media-auxiliary.ts';
import{completeMediaUsageAttempt,recordMediaUsageAttempt}from'./together-media-usage.ts';

export async function dispatchMediaJobs(db:SupabaseClient,limit:number,correlationId:string){
  const before=await mediaQueueSnapshot(db);
  const recovered=await reconcileWaveSpeedJobs(db,limit),recoveredSynchronous=await recoverStaleSynchronousJobs(db,limit);await db.rpc('kivelle_recover_stale_media_jobs',{p_stale_minutes:12});
  const[creator,training]=await Promise.all([dispatchCreatorAppearanceJobs(db,limit),dispatchLoraTrainingJobs(db,limit)]);
  const{data:jobs,error}=await db.rpc('kivelle_claim_media_jobs_v3',{p_limit:limit,p_max_image_inflight:imageMaxInflight(),p_max_video_inflight:videoMaxInflight()});if(error)throw new AppError('INTERNAL_ERROR','Media jobs could not be claimed.',500,true);
  const results={recovered,recoveredSynchronous,creator,training,claimed:(jobs??[]).length,ready:0,submitted:0,failed:0};
  for(const job of jobs??[])try{
    const canonical=await canonicalRequestForJob(db,job,await canonicalRequestForMedia(db,job)),subscription=await resolveSubscriptionState(db,String(job.user_id)),routed=canonical.mediaType==='video'?exactVideoRoute(canonical):routeCanonicalMedia(canonical,{source:String(job.metadata?.source??'user_request'),userTier:subscription.tier}),requestId=`media:${job.id}:attempt:${job.attempt_count}`;
    if(String(job.content_level??'standard')!==canonical.contentLevel){
      await db.from('together_generated_media').update({content_level:canonical.contentLevel,metadata:{...((job.metadata??{}) as Record<string,unknown>),resolvedContentLevel:canonical.contentLevel,productionMediaDowngraded:true,productionMediaReason:'production_sexual_content_ceiling'},updated_at:new Date().toISOString()}).eq('id',job.id).eq('status','generating');
    }
    let{data:providerJob,error:createError}=await db.from('together_media_provider_jobs').insert({user_id:job.user_id,continuity_id:job.continuity_id,generated_media_id:job.id,job_type:canonical.mediaType,provider:routed.provider.id,model:routed.route.capability.model,route_id:routed.route.capability.id,request_id:requestId,status:'submitting',attempt_count:1,quoted_provider_cost_usd:job.provider_quote_usd??null,requested_duration_seconds:job.requested_duration_seconds??null,requested_resolution:job.requested_resolution??null,requested_audio_behavior:job.requested_audio_behavior??null,source_aspect_ratio:job.source_aspect_ratio??null,motion_preset:job.motion_preset??null,testing_selection:job.testing_selection===true,provider_metadata:{routingReason:routed.route.reasonCode,fallbackRouteIds:routed.route.fallbacks.map((entry)=>entry.id),referenceCount:canonical.referenceImages.length,characterIdentityReferenceCount:canonical.referenceImages.filter((item)=>item.role==='character_identity').length,characterReferenceRequired:canonical.mediaType==='image',photorealismRequired:canonical.mediaType==='image',contentLevel:canonical.contentLevel,testingSelection:canonical.mediaType==='video'&&job.testing_selection===true}}).select('*').single();
    if(createError){const{data:existing}=await db.from('together_media_provider_jobs').select('*').eq('provider',routed.provider.id).eq('request_id',requestId).maybeSingle();providerJob=existing;if(!providerJob)throw new AppError('INTERNAL_ERROR','The media provider job could not be recorded.',500,true);if(providerJob.finalized_at){results.ready+=1;continue;}if(providerJob.provider_request_id&&providerJob.status==='processing'){results.submitted+=1;continue;}await markAmbiguousExistingSubmission(db,providerJob);results.failed+=1;continue;}
    await track(db,String(job.user_id),'media_generation_started',{mediaId:job.id,provider:routed.provider.id,routeId:routed.route.capability.id,source:job.metadata?.source,queueWaitMs:Math.max(0,Date.now()-new Date(job.created_at).getTime()),queuePriority:job.queue_priority});
    let submission;try{submission=await routed.provider.submit(canonical,routed.route.capability);}catch(error){const failureCode=error instanceof AppError?error.code:'provider_failure',attempts=providerAttemptsFromError(error);if(attempts.length){await recordProviderAttempts(db,providerJob,job,subscription.tier,attempts);await db.from('together_media_provider_jobs').update({attempt_count:Math.max(...attempts.map((item)=>item.attemptNumber))}).eq('id',providerJob.id).eq('status','submitting');}else{await recordMediaUsageAttempt(db,{job:providerJob,media:job,subscriptionTier:subscription.tier,routeId:routed.route.capability.id,model:routed.route.capability.model,provider:routed.provider.id,attemptNumber:1,qualityRetry:false,estimatedCost:routed.route.capability.estimatedCost});await completeMediaUsageAttempt(db,{providerJobId:String(providerJob.id),attemptNumber:1,success:false,failureCode});}await failProviderMedia(db,{jobId:String(providerJob.id),failureCode,failureReasonSafe:error instanceof AppError?error.message:'The media could not be created right now.'});throw error;}
    const attempts=submission.result?.providerAttempts??[];if(attempts.length)await recordProviderAttempts(db,providerJob,job,subscription.tier,attempts);else await recordMediaUsageAttempt(db,{job:providerJob,media:job,subscriptionTier:subscription.tier,routeId:routed.route.capability.id,model:submission.model,provider:submission.provider,attemptNumber:1,qualityRetry:false,generationMs:submission.result?.generationMs,estimatedCost:submission.result?.estimatedCost??routed.route.capability.estimatedCost});
    const attemptCount=attempts.length?Math.max(...attempts.map((item)=>item.attemptNumber)):1,now=new Date().toISOString();await db.from('together_media_provider_jobs').update({provider_request_id:submission.providerRequestId,status:'processing',attempt_count:attemptCount,submitted_at:now,next_poll_at:new Date(Date.now()+5_000).toISOString(),provider_metadata:{...((providerJob.provider_metadata??{}) as Record<string,unknown>),model:submission.model,...(submission.result?.providerMetadata??{})},updated_at:now}).eq('id',providerJob.id).eq('status','submitting');await db.from('together_generated_media').update({provider:submission.provider,provider_request_id:submission.providerRequestId,metadata:{...((job.metadata??{}) as Record<string,unknown>),providerRouteId:routed.route.capability.id,providerJobId:providerJob.id,providerStatus:submission.status},updated_at:now}).eq('id',job.id).eq('status','generating');
    if(submission.status==='completed'&&submission.result){
      const finalized=await finalizeMediaWithRetry({
        finalize:()=>finalizeProviderMedia(db,{jobId:String(providerJob.id),result:submission.result!}),
        onTerminalFailure:async(error)=>{const failure=mediaFinalizationFailure(error);await failProviderMedia(db,{jobId:String(providerJob.id),failureCode:failure.code,failureReasonSafe:failure.reason,providerMetadata:{finalizationFailed:true}});},
      });
      if(finalized.status==='failed')results.failed+=1;
      else if(String((finalized.value as Record<string,unknown>).status)==='ready')results.ready+=1;
      else if(String((finalized.value as Record<string,unknown>).status)==='failed')results.failed+=1;
      else results.submitted+=1;
    }else results.submitted+=1;
  }catch(error){
    const failureCode=error instanceof AppError?error.code:'provider_failure',failureReasonSafe=error instanceof AppError?error.message:'The media could not be created right now.';
    try{const{data:providerJob}=await db.from('together_media_provider_jobs').select('id,status').eq('generated_media_id',job.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(providerJob&&!['completed','failed','cancelled'].includes(String(providerJob.status)))await failProviderMedia(db,{jobId:String(providerJob.id),failureCode,failureReasonSafe});else if(!providerJob)await failMediaBeforeProvider(db,{media:job,failureCode,failureReasonSafe});}catch(cleanupError){console.error(JSON.stringify({level:'error',operation:'together_media_provider_failure_cleanup',mediaId:job.id,correlationId,message:cleanupError instanceof Error?cleanupError.message:'unknown_error'}));}
    results.failed+=1;console.error(JSON.stringify({level:'error',operation:'together_media_dispatch',mediaId:job.id,correlationId,code:failureCode,message:error instanceof Error?error.message:'unknown_error'}));}
  const after=await mediaQueueSnapshot(db);
  console.log(JSON.stringify({level:'info',operation:'media_dispatch_completed',correlationId,limit,maxImageInflight:imageMaxInflight(),maxVideoInflight:videoMaxInflight(),queueDepthBefore:before.queued,queueDepthAfter:after.queued,inflightBefore:before.inflight,inflightAfter:after.inflight,oldestQueuedAgeMs:after.oldestQueuedAgeMs,...results}));
  return{...results,queue:after};
}

async function recoverStaleSynchronousJobs(db:SupabaseClient,limit:number){
  const result={checked:0,failed:0},synchronousRouteIds=new Set(configuredMediaRegistry().filter((route)=>!route.asynchronous).map((route)=>route.id));
  if(!synchronousRouteIds.size)return result;
  const staleBefore=new Date(Date.now()-2*60_000).toISOString();
  const{data:jobs}=await db.rpc('kivelle_claim_stale_synchronous_media_jobs',{p_route_ids:[...synchronousRouteIds],p_stale_before:staleBefore,p_limit:limit,p_lease_seconds:60});
  for(const job of jobs??[]){
    result.checked+=1;
    await failProviderMedia(db,{jobId:String(job.id),failureCode:'MEDIA_FINALIZATION_TIMEOUT',failureReasonSafe:'The photo could not be delivered this time. Your credits were returned.',providerMetadata:{finalizationTimedOut:true}});
    result.failed+=1;
  }
  return result;
}

async function recordProviderAttempts(db:SupabaseClient,providerJob:Record<string,any>,media:Record<string,any>,subscriptionTier:string,attempts:ProviderAttempt[]){for(const attempt of attempts){await recordMediaUsageAttempt(db,{job:providerJob,media,subscriptionTier,routeId:attempt.routeId,model:attempt.model,provider:attempt.provider,attemptNumber:attempt.attemptNumber,qualityRetry:false,generationMs:attempt.generationMs,estimatedCost:attempt.estimatedCost,attemptMetadata:{pipelineStage:attempt.stage,providerRequestId:attempt.providerRequestId??null}});await completeMediaUsageAttempt(db,{providerJobId:String(providerJob.id),attemptNumber:attempt.attemptNumber,success:attempt.success,failureCode:attempt.failureCode,generationMs:attempt.generationMs});}}

async function markAmbiguousExistingSubmission(db:SupabaseClient,job:Record<string,any>){await db.from('together_media_provider_jobs').update({status:'submission_unknown',failure_code:'PROVIDER_SUBMISSION_UNKNOWN',failure_reason_safe:'The provider did not confirm the request. No duplicate request was sent.',updated_at:new Date().toISOString()}).eq('id',job.id).eq('status','submitting');await failProviderMedia(db,{jobId:String(job.id),failureCode:'PROVIDER_SUBMISSION_UNKNOWN',failureReasonSafe:'The provider did not confirm the request. No duplicate request was sent.'});}

async function canonicalRequestForJob(db:SupabaseClient,job:Record<string,any>,image:Awaited<ReturnType<typeof canonicalRequestForMedia>>):Promise<CanonicalMediaRequest>{
  if(String(job.media_type)!=='video')return{...image,mediaType:'image'};
  const metadata=(job.metadata??{}) as Record<string,unknown>,intent=(metadata.videoRequest??{}) as Record<string,unknown>,sourceMode=String(job.video_source_mode??metadata.videoSourceMode??'source_photo');
  const videoIntent={mediaId:String(job.id),mediaType:'video' as const,videoRouteId:String(job.video_route_id??intent.routeId??metadata.videoRouteId) as CanonicalMediaRequest['videoRouteId'],motionPreset:String(job.motion_preset??intent.motionPreset??'subtle') as CanonicalMediaRequest['motionPreset'],videoAspectRatio:String(job.source_aspect_ratio??intent.aspectRatio??'9:16') as CanonicalMediaRequest['videoAspectRatio'],durationSeconds:Number(job.requested_duration_seconds??intent.durationSeconds??5)};
  if(sourceMode==='canonical_references')return{...image,...videoIntent,referenceImages:image.referenceImages.slice(0,9)};
  const parentId=String(job.parent_media_id??metadata.parentMediaId??'');if(!parentId)throw new AppError('VALIDATION_ERROR','A source image is required to create a video.',422);const{data:parent}=await db.from('together_generated_media').select('*').eq('id',parentId).eq('user_id',String(job.user_id)).eq('character_instance_id',String(job.character_instance_id)).eq('media_type','image').eq('status','ready').maybeSingle();if(!parent?.storage_path)throw new AppError('NOT_FOUND','The source photo is unavailable.',404);const{data:signed}=await db.storage.from('together-user-media').createSignedUrl(String(parent.storage_path),900);if(!signed?.signedUrl)throw new AppError('INTERNAL_ERROR','The source photo could not be prepared.',500,true);const sourceImage={role:'previous_media' as const,signedUrl:signed.signedUrl,contentType:String(parent.content_type??'image/jpeg'),name:`source-${parent.id}.jpg`,storageBucket:'together-user-media',storagePath:String(parent.storage_path)};return{...image,...videoIntent,sourceImage,referenceImages:[sourceImage,...image.referenceImages].slice(0,4)};
}

function exactVideoRoute(request:CanonicalMediaRequest){
  const capability=configuredMediaRegistry().find((route)=>route.id===request.videoRouteId&&route.enabled&&route.mediaTypes.includes('video'));
  if(!capability)throw new AppError('PROVIDER_NOT_CONFIGURED','The selected video model is no longer available. Your credits will be returned.',503);
  return{route:{capability,score:1_000,reasonCode:'user_selected_video_route',fallbacks:[]},provider:providerForCapability(capability)};
}

async function reconcileWaveSpeedJobs(db:SupabaseClient,limit:number){const result={checked:0,ready:0,failed:0},client=configuredWaveSpeedClient();if(!client)return result;const{data:jobs,error}=await db.rpc('kivelle_claim_media_provider_poll_jobs',{p_provider:'wavespeed',p_limit:limit,p_lease_seconds:60});if(error)throw new AppError('INTERNAL_ERROR','Provider jobs could not be claimed for polling.',500,true);for(const job of jobs??[]){result.checked+=1;try{const timeoutMinutes=job.job_type==='lora'?180:job.job_type==='video'?60:45;if(Date.now()-new Date(job.created_at).getTime()>timeoutMinutes*60_000){await failProviderMedia(db,{jobId:String(job.id),failureCode:'provider_timeout',failureReasonSafe:job.job_type==='lora'?'Character identity training took too long and was stopped.':'The media took too long to create. Your credits were returned.'});result.failed+=1;continue;}const prediction=await client.getResult(String(job.provider_request_id));if(prediction.status==='completed'&&prediction.outputs[0]){const providerSafetyFlag=prediction.hasNsfwContents?.some(Boolean)===true;if(providerSafetyFlag&&(job.job_type!=='image'||job.character_media_profile_id||job.creator_asset_id)){await failProviderMedia(db,{jobId:String(job.id),failureCode:'production_sexual_content_ceiling',failureReasonSafe:'The photo could not be delivered this time. Your credits were returned.',providerMetadata:{status:prediction.status,hasNsfwContents:prediction.hasNsfwContents}});result.failed+=1;continue;}const completed={outputUrl:prediction.outputs[0],providerRequestId:prediction.id,model:prediction.model,generationMs:prediction.inferenceMs,providerMetadata:{providerSafetyFlag}};const finalized=job.character_media_profile_id||job.creator_asset_id?await finalizeAuxiliaryProviderJob(db,job,completed,{status:prediction.status,hasNsfwContents:prediction.hasNsfwContents,inferenceMs:prediction.inferenceMs,outputCount:prediction.outputs.length}):await finalizeProviderMedia(db,{jobId:String(job.id),result:completed,providerStatus:{status:prediction.status,hasNsfwContents:prediction.hasNsfwContents,inferenceMs:prediction.inferenceMs,outputCount:prediction.outputs.length}});if(String((finalized as Record<string,unknown>|null)?.status)==='ready')result.ready+=1;else await scheduleNextPoll(db,job,providerSafetyFlag?'provider_safety_retry':'finalization_deferred');}else if(['failed','cancelled','timeout','deleted'].includes(prediction.status)){await failProviderMedia(db,{jobId:String(job.id),failureCode:`provider_${prediction.status}`,failureReasonSafe:job.job_type==='lora'?'Character identity training could not be completed.':'The media could not be created this time.'});result.failed+=1;}else await scheduleNextPoll(db,job,prediction.status);}catch(error){await scheduleNextPoll(db,job,error instanceof AppError?error.code:'provider_unavailable');}}return result;}
async function scheduleNextPoll(db:SupabaseClient,job:Record<string,any>,status:string){const token=String(job.poll_lease_token??'');if(!token)return;await db.from('together_media_provider_jobs').update({last_polled_at:new Date().toISOString(),next_poll_at:new Date(Date.now()+8_000).toISOString(),poll_lease_token:null,poll_lease_expires_at:null,provider_metadata:{...((job.provider_metadata??{}) as Record<string,unknown>),status},updated_at:new Date().toISOString()}).eq('id',job.id).eq('status','processing').eq('poll_lease_token',token);}

function imageMaxInflight():number{const value=Number(Deno.env.get('KIVELLE_IMAGE_MAX_INFLIGHT')??Deno.env.get('KIVELLE_MEDIA_MAX_INFLIGHT')??48);return Number.isFinite(value)?Math.min(500,Math.max(1,Math.floor(value))):48;}
function videoMaxInflight():number{const value=Number(Deno.env.get('KIVELLE_VIDEO_MAX_INFLIGHT')??4);return Number.isFinite(value)?Math.min(20,Math.max(1,Math.floor(value))):4;}
async function mediaQueueSnapshot(db:SupabaseClient):Promise<{queued:number;inflight:number;oldestQueuedAgeMs:number|null}>{
  const[queued,inflight,oldest]=await Promise.all([
    db.from('together_generated_media').select('id',{count:'exact',head:true}).eq('status','queued').in('media_type',['image','video']),
    db.from('together_generated_media').select('id',{count:'exact',head:true}).eq('status','generating').in('media_type',['image','video']),
    db.from('together_generated_media').select('created_at').eq('status','queued').in('media_type',['image','video']).order('created_at').limit(1).maybeSingle(),
  ]);
  const createdAt=oldest.data?.created_at?new Date(String(oldest.data.created_at)).getTime():NaN;
  return{queued:Number(queued.count??0),inflight:Number(inflight.count??0),oldestQueuedAgeMs:Number.isFinite(createdAt)?Math.max(0,Date.now()-createdAt):null};
}

export type MediaFinalizationResult<T>={status:'finalized';value:T;attempts:number}|{status:'failed';error:unknown;attempts:number};
export async function finalizeMediaWithRetry<T>(input:{finalize:()=>Promise<T>;onTerminalFailure:(error:unknown)=>Promise<void>;wait?:(delayMs:number)=>Promise<void>;maxAttempts?:number}):Promise<MediaFinalizationResult<T>>{
  const maxAttempts=Math.max(1,Math.min(4,input.maxAttempts??3)),wait=input.wait??((delayMs:number)=>new Promise<void>((resolve)=>setTimeout(resolve,delayMs)));let lastError:unknown,attempts=0;
  for(let attempt=1;attempt<=maxAttempts;attempt+=1){attempts=attempt;try{return{status:'finalized',value:await input.finalize(),attempts:attempt};}catch(error){lastError=error;if(!isRetryableMediaFinalizationError(error)||attempt===maxAttempts)break;await wait(750*attempt);}}
  await input.onTerminalFailure(lastError);return{status:'failed',error:lastError,attempts};
}
export function isRetryableMediaFinalizationError(error:unknown):boolean{return error instanceof AppError?error.retryable||['INTERNAL_ERROR','PROVIDER_TIMEOUT','PROVIDER_UNAVAILABLE'].includes(error.code):true;}
export function mediaFinalizationFailure(error:unknown):{code:string;reason:string}{if(error instanceof AppError&&!error.retryable&&error.code!=='INTERNAL_ERROR')return{code:error.code,reason:error.message};return{code:'MEDIA_FINALIZATION_FAILED',reason:'The photo could not be delivered this time. Your credits were returned.'};}
