export type ErrorCode = 'AUTH_REQUIRED' | 'FORBIDDEN' | 'LEGAL_ACCEPTANCE_REQUIRED' | 'VALIDATION_FAILED' | 'VALIDATION_ERROR' | 'RATE_LIMITED' | 'NOT_FOUND' | 'CONFLICT' | 'CONVERSATION_ARCHIVED' | 'PLAN_CONFLICT' | 'PLAN_LIMIT_REACHED' | 'PLAN_MISSED' | 'PLAN_TIME_UNRESOLVED' | 'TOO_EARLY' | 'WORLD_LOCKED' | 'INSUFFICIENT_CREDITS' | 'BILLING_NOT_CONFIGURED' | 'COMPANION_BUSY' | 'LOCATION_CLOSED' | 'PROVIDER_UNAVAILABLE' | 'PROVIDER_QUOTA' | 'PROVIDER_AUTH' | 'PROVIDER_MODEL' | 'PROVIDER_REQUEST_INVALID' | 'INTERNAL_ERROR';
export class AppError extends Error {
  constructor(readonly code: ErrorCode, message: string, readonly status: number, readonly retryable = false) { super(message); this.name = 'AppError'; }
}
