import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router as expoRouter, useLocalSearchParams } from 'expo-router';
import { AlertTriangle, CalendarDays, X } from 'lucide-react-native';
import { characterAssets, cityLifeAsset } from '../../src/assets';
import { Body, DateChoice, DateScene, GlassCard, GradientButton, LoadingSkeleton, Screen } from '../../src/components';
import { colors } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';
import { mutateDate } from '../../src/lib/api';
import { activeCompanion } from '../../src/lib/companionLife';
import { commitmentTimeLabel } from '../../src/lib/commitments';
import type { DateSession, Moment, SharedPlan } from '../../src/types';

const router = expoRouter as unknown as { push: (href: string) => void; replace: (href: string) => void; back: () => void };
type ChoiceResult={session:DateSession;narrative:string;completed:boolean;moment?:Moment|null};
export default function DateExperience(){
  const{id}=useLocalSearchParams<{id:string}>();const{snapshot,refresh}=useTogether();const[session,setSession]=useState<DateSession|undefined>(snapshot?.dates.find((item)=>item.id===id));const[busy,setBusy]=useState(false);const[narrative,setNarrative]=useState('');const[freeText,setFreeText]=useState('');
  if(!snapshot||!session)return <LoadingSkeleton/>;
  const template=session.together_date_templates;const companion=activeCompanion(snapshot,session.character_instance_id);if(!companion)return <Screen><Body muted>We couldn't find the companion for this experience.</Body><GradientButton label="Back to Dates" onPress={()=>router.replace('/(tabs)/dates')}/></Screen>;
  const linkedPlan:SharedPlan|undefined=session.shared_plan_id?snapshot.sharedPlans.find((item)=>item.id===session.shared_plan_id):undefined;
  const missed=linkedPlan?.status==='missed'||session.state?.commitmentMissed===true;
  const missedPlanId=linkedPlan?.id??(typeof session.state?.missedPlanId==='string'?session.state.missedPlanId:undefined);
  const total=Math.max(1,template.phases.length);const phase=template.phases[session.phase_index]??template.phases.at(-1)??{id:'resolution',title:'A shared memory',choices:[]};const location=snapshot.locations.find((item)=>item.id===template.location_id)?.name;const recentEvent=snapshot.lifeEvents.filter((event)=>event.character_instance_id===companion.id&&event.user_should_know!==false).sort((a,b)=>new Date(b.starts_at).getTime()-new Date(a.starts_at).getTime())[0];const choices=phase.choices.map((choice)=>contextualChoice(choice,companion.together_character_templates.name,recentEvent?.title));
  const source=characterAssets[template.hero_asset_key??companion.together_character_versions.portrait_asset_key??companion.together_character_templates.slug]??characterAssets[companion.together_character_templates.slug]??cityLifeAsset;
  const start=async()=>{setBusy(true);try{const next=await mutateDate<DateSession>({action:'start',sessionId:session.id});setSession(next);await refresh();}catch(error){Alert.alert('This experience is paused',error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}};
  const choose=async(choice:{id:string;label:string},isFreeText=false)=>{setBusy(true);try{const result=await mutateDate<ChoiceResult>({action:'choose',sessionId:session.id,choiceId:choice.id,choiceText:isFreeText?freeText.trim():choice.label,freeText:isFreeText});setNarrative(result.narrative);setSession(result.session);setFreeText('');await refresh();if(result.completed){Alert.alert('A new Moment',`${template.name} is now part of your shared history.`,[{text:'View Moment',onPress:()=>router.replace(result.moment?.id?`/moment/${result.moment.id}`:'/(tabs)/moments')}]);}}catch(error){Alert.alert('The scene paused',error instanceof Error?error.message:'Try that again.');}finally{setBusy(false);}};
  if(session.status==='locked')return <Screen><Text style={styles.lockTitle}>Not quite yet</Text><Body muted>{template.name} will unlock naturally as your connection with {companion.together_character_templates.name} grows.</Body><GradientButton label="Back to Dates" onPress={()=>router.replace('/(tabs)/dates')}/></Screen>;
  if(missed)return <Screen><DateScene phase={1} total={total} title={template.name} source={source}><Text style={styles.missedKicker}>MISSED DATE</Text><GlassCard style={styles.missed}><AlertTriangle color={colors.danger}/><View style={{flex:1}}><Text style={styles.missedTitle}>This Date did not happen.</Text><Body muted>{linkedPlan?.miss_reason==='user_absent'?`${companion.together_character_templates.name} arrived and waited, but you did not join before the grace period ended.`:'The scheduled Date could not happen. Kivelle keeps the reason separate from the Date experience so the relationship is not blamed for a technical or companion-side issue.'}</Body></View></GlassCard>{missedPlanId?<GradientButton label="See what happened" onPress={()=>router.push(`/plan/${missedPlanId}`)}/>:null}<Pressable onPress={()=>router.push(`/chat?character=${companion.together_character_templates.public_handle??companion.together_character_templates.slug}&draft=${encodeURIComponent(`I'm sorry we missed ${template.name}.`)}`)} style={styles.secondary}><Text style={styles.secondaryText}>Talk to {companion.together_character_templates.name}</Text></Pressable></DateScene></Screen>;
  if(session.status!=='active'&&session.status!=='completed')return <Screen><DateScene phase={1} total={total} title={template.name} source={source}><Text style={styles.kicker}>{location?.toUpperCase()??'SHARED EXPERIENCE'}</Text><Body muted>{template.description}</Body>{linkedPlan?.starts_at?<View style={styles.when}><CalendarDays size={15} color={colors.warm}/><Text style={styles.whenText}>{commitmentTimeLabel(linkedPlan,Intl.DateTimeFormat().resolvedOptions().timeZone)}</Text></View>:null}<GradientButton label={busy?'Joining…':linkedPlan?.starts_at?`Join ${template.name}`:`Begin ${template.name}`} disabled={busy} onPress={()=>void start()}/></DateScene></Screen>;
  return <Screen><View style={styles.header}><Pressable accessibilityLabel="Leave date" onPress={()=>router.back()}><X color={colors.text}/></Pressable><Text style={styles.headerTitle}>{template.name}</Text><Text style={styles.phase}>{Math.min(session.phase_index+1,total)} of {total}</Text></View><DateScene phase={Math.min(session.phase_index+1,total)} total={total} title={phase.title} source={source}><Text style={styles.kicker}>{location?.toUpperCase()??'SHARED EXPERIENCE'}</Text><Body>{narrative||phase.narrativeSeed||template.description}</Body>{session.status==='completed'?<GradientButton label="View your Moments" onPress={()=>router.replace('/(tabs)/moments')}/>:<View style={{gap:10}}>{choices.map((choice,index)=><DateChoice key={choice.id} label={choice.label} primary={index===0} locked={busy} onPress={()=>void choose(choice)}/>) }<View style={styles.free}><TextInput value={freeText} onChangeText={setFreeText} editable={!busy} placeholder="Say something else…" placeholderTextColor={colors.dimmed} style={styles.input}/><Pressable accessibilityLabel="Send your own date response" disabled={busy||!freeText.trim()} onPress={()=>void choose({id:'say_something',label:freeText},true)} style={[styles.send,!freeText.trim()&&styles.sendDisabled]}><Text style={styles.sendText}>Send</Text></Pressable></View></View>}</DateScene></Screen>;
}
function contextualChoice(choice:{id:string;label:string},name:string,recentEvent?:string){if(choice.id==='ask-day'&&recentEvent)return {...choice,label:`Ask ${name} about ${recentEvent.toLowerCase()}`};if(choice.id==='share-honestly')return {...choice,label:`Tell ${name} what's been on your mind`};if(choice.id==='listen-carefully')return {...choice,label:`Stay with ${name} and really listen`};return choice;}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:12},headerTitle:{flex:1,textAlign:'center',color:colors.text,fontWeight:'800'},phase:{color:colors.muted,fontSize:11},kicker:{color:colors.rose,fontSize:9,fontWeight:'900',letterSpacing:1.1},missedKicker:{color:colors.danger,fontSize:9,fontWeight:'900',letterSpacing:1.1},lockTitle:{fontFamily:'Georgia',fontSize:29,color:colors.text},when:{flexDirection:'row',alignItems:'center',gap:7,paddingVertical:3},whenText:{color:colors.warm,fontSize:11,fontWeight:'800'},missed:{flexDirection:'row',gap:11,alignItems:'flex-start',borderColor:'rgba(255,93,121,.25)'},missedTitle:{fontFamily:'Georgia',fontSize:20,color:colors.text,marginBottom:4},secondary:{minHeight:44,borderRadius:14,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.text,fontWeight:'800',fontSize:12},free:{flexDirection:'row',gap:8,alignItems:'center',paddingTop:3},input:{flex:1,minHeight:44,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:12,fontSize:12},send:{height:44,paddingHorizontal:13,borderRadius:14,backgroundColor:colors.rose,justifyContent:'center'},sendDisabled:{opacity:.42},sendText:{color:'#fff',fontWeight:'800',fontSize:12}});
