import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router as expoRouter, useLocalSearchParams } from 'expo-router';
import { X } from 'lucide-react-native';
import { characterAssets, cityLifeAsset } from '../../src/assets';
import { Body, DateChoice, DateScene, GradientButton, LoadingSkeleton, Screen } from '../../src/components';
import { colors } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';
import { mutateDate } from '../../src/lib/api';
import { activeCompanion } from '../../src/lib/companionLife';
import type { DateSession, Moment } from '../../src/types';

const router = expoRouter as unknown as { push: (href: string) => void; replace: (href: string) => void; back: () => void };

type ChoiceResult={session:DateSession;narrative:string;completed:boolean;moment?:Moment|null};
export default function DateExperience(){
  const{id}=useLocalSearchParams<{id:string}>();const{snapshot,refresh}=useTogether();const[session,setSession]=useState(snapshot?.dates.find((item)=>item.id===id));const[busy,setBusy]=useState(false);const[narrative,setNarrative]=useState('');const[freeText,setFreeText]=useState('');
  if(!snapshot||!session)return <LoadingSkeleton/>;
  const template=session.together_date_templates;const companion=activeCompanion(snapshot,session.character_instance_id);if(!companion)return <Screen><Body muted>We couldn't find the companion for this experience.</Body><GradientButton label="Back to Dates" onPress={()=>router.replace('/(tabs)/dates')}/></Screen>;
  const total=Math.max(1,template.phases.length);const phase=template.phases[session.phase_index]??template.phases.at(-1)??{id:'resolution',title:'A shared memory',choices:[]};const location=snapshot.locations.find((item)=>item.id===template.location_id)?.name;
  const source=characterAssets[template.hero_asset_key??companion.together_character_versions.portrait_asset_key??companion.together_character_templates.slug]??characterAssets[companion.together_character_templates.slug]??cityLifeAsset;
  const start=async()=>{setBusy(true);try{const next=await mutateDate<DateSession>({action:'start',sessionId:session.id});setSession(next);}catch(error){Alert.alert('This experience is paused',error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}};
  const choose=async(choice:{id:string;label:string},isFreeText=false)=>{setBusy(true);try{const result=await mutateDate<ChoiceResult>({action:'choose',sessionId:session.id,choiceId:choice.id,choiceText:isFreeText?freeText.trim():choice.label,freeText:isFreeText});setNarrative(result.narrative);setSession(result.session);setFreeText('');await refresh();if(result.completed){Alert.alert('A new Moment',`${template.name} is now part of your shared history.`,[{text:'View Moment',onPress:()=>router.replace(result.moment?.id?`/moment/${result.moment.id}`:'/(tabs)/moments')}]);}}catch(error){Alert.alert('The scene paused',error instanceof Error?error.message:'Try that again.');}finally{setBusy(false);}};
  if(session.status==='locked')return <Screen><Text style={styles.lockTitle}>Not quite yet</Text><Body muted>{template.name} will unlock naturally as your connection with {companion.together_character_templates.name} grows.</Body><GradientButton label="Back to Dates" onPress={()=>router.replace('/(tabs)/dates')}/></Screen>;
  if(session.status!=='active'&&session.status!=='completed')return <Screen><DateScene phase={1} total={total} title={template.name} source={source}><Text style={styles.kicker}>{location?.toUpperCase()??'SHARED EXPERIENCE'}</Text><Body muted>{template.description}</Body><GradientButton label={busy?'Startingâ€¦':`Begin ${template.name}`} disabled={busy} onPress={()=>void start()}/></DateScene></Screen>;
  return <Screen><View style={styles.header}><Pressable accessibilityLabel="Leave date" onPress={()=>router.back()}><X color={colors.text}/></Pressable><Text style={styles.headerTitle}>{template.name}</Text><Text style={styles.phase}>{Math.min(session.phase_index+1,total)} of {total}</Text></View><DateScene phase={Math.min(session.phase_index+1,total)} total={total} title={phase.title} source={source}><Text style={styles.kicker}>{location?.toUpperCase()??'SHARED EXPERIENCE'}</Text><Body>{narrative||phase.narrativeSeed||template.description}</Body>{session.status==='completed'?<GradientButton label="View your Moments" onPress={()=>router.replace('/(tabs)/moments')}/>:<View style={{gap:10}}>{phase.choices.map((choice,index)=><DateChoice key={choice.id} label={choice.label} primary={index===0} locked={busy} onPress={()=>void choose(choice)}/>) }<View style={styles.free}><TextInput value={freeText} onChangeText={setFreeText} editable={!busy} placeholder="Say something elseâ€¦" placeholderTextColor={colors.dimmed} style={styles.input}/><Pressable accessibilityLabel="Send your own date response" disabled={busy||!freeText.trim()} onPress={()=>void choose({id:'say_something',label:freeText},true)} style={[styles.send,!freeText.trim()&&styles.sendDisabled]}><Text style={styles.sendText}>Send</Text></Pressable></View></View>}</DateScene></Screen>;
}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:12},headerTitle:{flex:1,textAlign:'center',color:colors.text,fontWeight:'800'},phase:{color:colors.muted,fontSize:11},kicker:{color:colors.rose,fontSize:9,fontWeight:'900',letterSpacing:1.1},lockTitle:{fontFamily:'Georgia',fontSize:29,color:colors.text},free:{flexDirection:'row',gap:8,alignItems:'center',paddingTop:3},input:{flex:1,minHeight:44,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:12,fontSize:12},send:{height:44,paddingHorizontal:13,borderRadius:14,backgroundColor:colors.rose,justifyContent:'center'},sendDisabled:{opacity:.42},sendText:{color:'#fff',fontWeight:'800',fontSize:12}});
