import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Clock3, MapPin } from 'lucide-react-native';
import type { AroundTownItem } from '@together/domain/src/world-pulse';
import { colors, typography } from '../../theme';

export function AroundTownSection({worldName,items,onOpen}:{worldName:string;items:AroundTownItem[];onOpen:(item:AroundTownItem)=>void}){
  if(!items.length)return null;
  return <View style={styles.section}><View style={styles.heading}><View><Text style={styles.kicker}>WORLD PULSE</Text><Text accessibilityRole="header" style={styles.title}>Around {worldName}</Text></View><Text style={styles.subtitle}>What is actually unfolding nearby</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{items.map(item=><Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`${item.title}, ${item.locationName??worldName}`} onPress={()=>onOpen(item)} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.cardTop}><Text style={[styles.status,item.kind==='happening_now'&&styles.live]}>{item.kind==='happening_now'?'HAPPENING NOW':item.kind==='later_today'?'LATER TODAY':'UPCOMING'}</Text><Clock3 size={14} color="#BFA9BE"/></View><Text numberOfLines={2} style={styles.cardTitle}>{item.title}</Text><Text numberOfLines={2} style={styles.summary}>{item.summary}</Text>{item.locationName?<View style={styles.location}><MapPin size={13} color="#E79AC0"/><Text numberOfLines={1} style={styles.locationText}>{item.locationName}</Text></View>:null}{item.participantNames.length?<Text numberOfLines={1} style={styles.people}>{item.participantNames.slice(0,3).join(' · ')}</Text>:null}</Pressable>)}</ScrollView></View>;
}

const styles=StyleSheet.create({section:{gap:13},heading:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:18},kicker:{color:'#D685B2',fontSize:10,fontWeight:'900',letterSpacing:1.6},title:{color:colors.text,fontFamily:typography.display,fontSize:29,lineHeight:35},subtitle:{color:'#9D929F',fontSize:12,paddingBottom:4},rail:{gap:12,paddingRight:8},card:{width:284,minHeight:172,padding:17,borderRadius:20,borderWidth:1,borderColor:'rgba(203,105,158,.17)',backgroundColor:'rgba(26,18,29,.76)',gap:8},pressed:{opacity:.82,transform:[{scale:.992}]},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},status:{color:'#B8AEB9',fontSize:9,fontWeight:'900',letterSpacing:1.1},live:{color:'#72D7C2'},cardTitle:{color:colors.text,fontFamily:typography.display,fontSize:20,lineHeight:24},summary:{color:'#BEB4C0',fontSize:12,lineHeight:17,flex:1},location:{flexDirection:'row',alignItems:'center',gap:5},locationText:{color:'#E8C6D8',fontSize:11,fontWeight:'800',flex:1},people:{color:'#918794',fontSize:10}});
