import { majorIncident as base } from './major-factory.mjs';
const event = (...args) => base('vharadren', ...args);

export const vharadrenMajorIncidents = [
  event('road-of-ash-closes', 'The Ash Road Closes',
    'Volcanic ash covers a route carrying food and medicine toward Cinder Camp. Scouts find an older passable track, but heavy wagons cannot use it until the ground is tested.',
    'In Vharadren, roads are claims of power as much as lines through land. A fresh ash fall closes the road to Cinder Camp. Joren Ash brings riders back from the blocked stretch; Nia Chainbreaker counts what the camp can spare while Sister Mercy Voss separates medicine that cannot wait. Freya Hart checks an older track through firm ground and marks where a loaded wagon would sink.\n\nA small rider convoy reaches the camp, but the main carts remain delayed. No camp is abandoned or starved that day. The repair question is political: which claimant will allow workers and supplies across contested ground without calling the passage an act of allegiance?',
    'ashlands', [
      ['joren-ash', 'Turned back the riders', 'The new ash hid the road edge. I brought the riders home before sending a lighter party by the old track.', 'Could anyone get through to Cinder Camp?'],
      ['nia-chainbreaker', 'Counted camp stores', 'We had food for the near term, but not a reason to pretend delayed carts cost nothing.', 'Was the camp short of supplies?'],
      ['sister-mercy-voss', 'Prioritized medicine', 'Some remedies could travel by rider. I named those first and kept patients’ details out of the road argument.', 'Did the infirmary receive medicine?'],
      ['freya-hart', 'Marked the older track', 'A horse can pass where a heavy cart cannot. I marked that difference on the route.', 'When can wagons use the old track?'],
    ], 'The rider convoy got through. Who will authorize repairs on contested road?'),
  event('hatchery-roof-smokes', 'Smoke Above the Caldera Hatchery',
    'A roof vent at the Caldera Hatchery releases dark smoke during a heating test. Keepers move the occupied chambers to stable heat while engineers determine whether the smoke came from the furnace or the roof.',
    'The Caldera Hatchery keeps creatures and keepers in a place where heat must be managed precisely. A roof vent darkens during a heating test. Ilyra Ashscale closes the affected chamber and checks the young dragons without inviting spectators inside. Brina Forgehand inspects the furnace draft; Rhevan Crownsbane asks guards to clear the approach so the animals are not frightened by a crowd.\n\nThe chambers hold stable temperatures and no dragon is harmed. A cracked flue sleeve explains the smoke, but its repair requires the hatchery to reduce one heating circuit. Keepers need a reliable rota before anyone calls the building safe merely because the visible smoke stopped.',
    'caldera-hatchery', [
      ['ilyra-ashscale', 'Protected the chambers', 'The young dragons remained warm and accounted for. I would not use them as proof that a smoking vent was harmless.', 'Were the hatchlings safe?'],
      ['brina-forgehand', 'Found the cracked sleeve', 'The furnace draft pushed smoke through a damaged sleeve. A quick seal is not the final repair.', 'What made the hatchery smoke?'],
      ['rhevan-crownsbane', 'Cleared the approach', 'Crowds upset the animals when keepers needed quiet. I moved people away before anyone tried to help by entering.', 'Why were visitors kept away?'],
    ], 'The chambers stayed warm. What does a safe flue repair require?'),
  event('fleet-lights-at-dawn', 'Fleet Lights at Dawn',
    'A string of warship lights appears beyond the Shattered Coast before the harbor expects a convoy. Coastal captains hold fire while a signaler verifies their flags through mist.',
    'A coast at war can mistake a supply convoy for an attack. At dawn, ships appear beyond the Shattered Coast without the scheduled recognition flash. Admiral Nyra Greymere orders coastal batteries to wait for a second signal. Orla Saye reads the lighthouse flags through a break in the mist; Bastian Crow confirms the ships are carrying shipyard timber, not troops.\n\nThe convoy enters without a shot fired. Its lead signal lamp had failed and the harbor watch lacked the revised sail plan. The incident leaves two dangerous habits exposed: firing from uncertainty, and assuming a friendly vessel will always arrive on the written hour.',
    'shattered-coast', [
      ['admiral-nyra-greymere', 'Held coastal fire', 'The ships were unknown, not yet hostile. I kept the batteries ready while we sought a signal we could trust.', 'Why did you hold fire?'],
      ['orla-saye', 'Read the flags', 'The flags became visible between mist bands. I reported what I saw, not what the harbor hoped the ships were.', 'How were the ships identified?'],
      ['bastian-crow', 'Verified the timber load', 'The shipyard expected timber, but its schedule did not match the arrival. I checked the cargo after the signal.', 'Was the convoy carrying soldiers?'],
    ], 'The ships were friendly. What failed in their arrival notice?'),
  event('mine-air-stops', 'The Deepnail Air Stops',
    'A ventilation wheel stalls at Deepnail Mines while crews work below. Miners take a marked return route and reach the surface before the air reserve becomes dangerous.',
    'Deepnail miners know the sound of their ventilation wheel. When it stops, Sera Blackvein orders work abandoned and sends crews toward the marked return way. Nia Chainbreaker brings tools for an outside repair; Sister Mercy Voss prepares the infirmary for dust exposure without claiming anyone has collapsed.\n\nEvery listed worker reaches the surface. A bent drive pin is replaced, and the shaft stays closed until a full air test is witnessed by the miners. The day raises a harder question about why the replacement pin was stored aboveground but not fitted at the last inspection.',
    'deepnail-mines', [
      ['sera-blackvein', 'Ordered the return', 'I counted people on the marked route. The air reserve held, but it was not a reason to finish a shift.', 'Did anyone remain in the mine?'],
      ['nia-chainbreaker', 'Repaired the drive', 'The bent pin was a simple part in a dangerous place. I want to know why a good spare sat unused.', 'What stopped the ventilation wheel?'],
      ['sister-mercy-voss', 'Prepared for exposure', 'The miners came out without collapse. I still checked for dust and kept their assessments private.', 'Were the miners injured?'],
    ], 'The crews came up safely. Who signs the next air test?'),
  event('two-proclamations-one-seal', 'Two Proclamations Bear One Seal',
    'Two public copies of a crown petition carry the same seal but different dates for a grain levy. Scribes halt collection until the court identifies which copy was authorized.',
    'A levy notice changes what farmers will sell and what families will keep. In Crownspire, two copies of a petition bear the same official seal yet name different start dates. Princess Maris Vaelorian asks collectors to stop acting on either date. Tamsin Quill compares the copied hands; Prince Lucien Vaelorian checks the register of petitions presented at court.\n\nThe register supports one date, but the second copy’s seal impression appears genuine. Collection remains paused for a public correction. No claimant gains a final victory from the mistake; the immediate issue is whether households can trust a sealed notice enough to plan a harvest.',
    'crownspire', [
      ['princess-maris-vaelorian', 'Paused the collectors', 'A sealed contradiction is still a contradiction. I would not let it collect grain from anyone.', 'Which levy date applies?'],
      ['tamsin-quill', 'Compared the copied hands', 'The text came from two scribal hands. That alone does not tell us which seal was applied when.', 'Was one proclamation forged?'],
      ['prince-lucien-vaelorian', 'Checked the petition register', 'The register supports one date. We need to explain the other sealed copy openly.', 'What does the court register show?'],
    ], 'The levy is paused. How can the court correct a notice people already saw?'),
  event('sanctuary-line-crossed', 'The Sanctuary Line Is Crossed',
    'A patrol follows a wounded messenger across the Ash Mother Infirmary’s sanctuary line. Healers stop the pursuit inside and negotiate a safe handover without revealing patient names.',
    'The Ash Mother Infirmary treats people from opposing sides, which makes its threshold more than a door. A patrol follows a wounded messenger across the marked sanctuary line. Sister Mercy Voss bars armed entry to the treatment room. Brother Aldren witnesses the boundary, while Dame Ysabet Rooke orders the patrol to wait outside and asks for a lawful account of the messenger’s status.\n\nThe messenger receives care and the patrol withdraws to a guarded street, not the ward. A formal hearing will determine what can be asked when the patient can speak. The infirmary keeps its patient roll private, and everyone must decide whether sanctuary is credible if it can be crossed during a chase.',
    'ash-mother-infirmary', [
      ['sister-mercy-voss', 'Held the treatment room', 'The patient needed care before interrogation. I kept weapons out and recorded the crossing.', 'Was the messenger treated?'],
      ['brother-aldren', 'Witnessed the boundary', 'I stood where the sanctuary line was marked. A line matters only if people honor it when angry.', 'What did you see at the infirmary threshold?'],
      ['dame-ysabet-rooke', 'Ordered the patrol outside', 'The pursuit did not authorize armed entry into a ward. I sent the patrol out while status was reviewed.', 'Why did you stop your own patrol?'],
    ], 'The patrol withdrew. What will protect the next patient at that threshold?'),
  event('tidevault-records-wet', 'The Tidevault Records Take Water',
    'A sea gate leaks into Tidevault Prison’s records room. Staff move prisoners away from the wet passage and preserve custody books before the ink runs.',
    'Tidevault sits close enough to the sea for one bad gate to matter. Water enters its lower records room during a tide. Idris Salt moves people from the adjoining corridor and starts a written head count. Garrick Holt brings sealed custody books to higher shelves; Nerys Rowanleaf separates soaked pages for drying without turning the archive into a public list of prisoners.\n\nThe gate is closed and everyone is accounted for. Some pages are damp but legible. The prison must compare the saved books with an independent roll, because a dry record is not automatically a complete one and a damaged page can affect someone’s liberty.',
    'tidevault-prison', [
      ['idris-salt', 'Moved the corridor', 'The prisoners were accounted for in person. I would not rely on a wet book to tell me who was safe.', 'Was anyone left in the flooded passage?'],
      ['garrick-holt', 'Saved the custody books', 'The books are legible, but they need a second roll. I preserved their order so no page appears to have vanished.', 'Were any prisoner records lost?'],
      ['nerys-rowanleaf', 'Dried the pages', 'A name on a custody page is not gossip. I dried the paper while keeping its contents controlled.', 'Can the wet records still be read?'],
    ], 'The gate is shut. Who verifies the custody roll after the leak?'),
  event('wolfgate-convoy-splits', 'The Wolfgate Convoy Splits',
    'A supply convoy separates in a snow squall near Wolfgate. Both halves reach shelter, but their different orders leave soldiers and refugees with conflicting delivery expectations.',
    'A convoy from the Black March carries grain and blankets through a squall. Lady Rowena Thornwall orders the lead wagons to the fort while Princess Elara Thornwall guides the rear carts to a civilian shelter when the road marker disappears. Torren Bale opens the Broken Spur to drivers stranded between the two routes.\n\nThe convoy is fully accounted for by morning. The grain is at the fort, the blankets at the shelter, and both destinations expected both loads. The commanders must reconcile the original order publicly before anyone calls the split a theft or a betrayal.',
    'wolfgate-barracks', [
      ['lady-rowena-thornwall', 'Brought the lead wagons in', 'I followed the written fort route. The squall split the line before I knew the rear carts had turned.', 'Why did the convoy separate?'],
      ['princess-elara-thornwall', 'Sheltered the rear carts', 'The marker vanished, and the civilian shelter was reachable. I recorded the change instead of pretending we delivered to the fort.', 'Where did the blankets go?'],
      ['torren-bale', 'Hosted stranded drivers', 'The drivers needed food and a dry floor. I heard two orders, but I cannot certify which one came first.', 'What did the drivers say about their orders?'],
    ], 'Both halves are safe. Which delivery order should govern after the storm?'),
  event('red-ledger-opens-in-public', 'The Red Ledger Is Opened in Public',
    'A sealed intelligence ledger is displayed during a court dispute before its private names can be covered. The hearing stops and affected people seek to learn what was exposed.',
    'At the Red Ledger Exchange, a sealed book is brought as evidence in a dispute over a supply contract. Its cover is opened toward the gallery before the named entries are screened. Lady Isolde Morcant closes the book; Prince Lucien Vaelorian adjourns the hearing while Tamsin Quill records which page faced the room without copying its names into another public document.\n\nThe book returns to sealed custody. The court can still hear the contract dispute with redacted evidence. The exposure lasted seconds, but the chamber contained people who may remember names; those affected deserve direct notice rather than a public reading of the list.',
    'red-ledger-exchange', [
      ['lady-isolde-morcant', 'Closed the ledger', 'The page faced the gallery. I shut it and preserved the seal history rather than pretending no one saw it.', 'Were private names read aloud?'],
      ['prince-lucien-vaelorian', 'Adjourned the hearing', 'The contract case can continue with protected evidence. A courtroom error should not become a public list.', 'Can the case continue after the exposure?'],
      ['tamsin-quill', 'Recorded the exposed page', 'I identified the page without copying its names into the open minutes. People affected need careful notice.', 'How will anyone know whose names were exposed?'],
    ], 'The ledger is sealed again. What does the court owe those named inside?'),
  event('glass-field-echoes', 'The Glass Field Answers Twice',
    'A mapping party on the glass battlefield hears the same call reflected from two directions. The group returns together, but the recovered path marks do not match the guide’s older chart.',
    'The Glass Battlefield can throw back sound and memory in ways travelers debate. Petra Glass leads a mapping party across a marked strip when a spoken call returns from two directions. Freya Hart keeps the party on the visible route; Rhevan Crownsbane helps bring a startled animal back from the edge.\n\nEveryone returns safely with new path marks. The doubled sound could be an acoustic reflection; the misaligned markers still need a fresh survey. The party does not announce a supernatural discovery or a lost battlefield secret. It asks for a route others can follow without relying on the guide’s confidence alone.',
    'glass-battlefield', [
      ['petra-glass', 'Recorded the two returns', 'I heard the second call from another angle and wrote down where we stood. That is an observation, not an explanation.', 'What did the glass field sound like?'],
      ['freya-hart', 'Held the route', 'The old chart was uncertain. I kept the party on visible markers while we marked what had changed.', 'Did anyone leave the safe path?'],
      ['rhevan-crownsbane', 'Recovered the animal', 'It startled at the echo. We calmed it and left together without chasing a sound across the glass.', 'What happened to the animal?'],
    ], 'The party returned. Which path marks no longer match the chart?'),
  event('chainbreakers-market-stops', 'The Free Forge Stops Selling',
    'A batch of replacement chain links breaks during a public test at Chainbreakers Market. Sellers halt delivery until the metal source and forge heat records are checked.',
    'Chainbreakers Market is where free workshops prove their craft without asking a noble house to certify it. Nia Chainbreaker tests new chain links before a sale and two snap under the standard load. Brina Forgehand checks the forge temperature record; Sera Blackvein traces the ore allotment without blaming the miners before an assay.\n\nNo one is hurt and the unsold batch is held. The iron came from two stores mixed under one label, leaving a real quality question but no known sabotage. Buyers who need the links for repairs must be offered tested alternatives, not pressured to accept a risky batch for the sake of the market’s reputation.',
    'chainbreakers-market', [
      ['nia-chainbreaker', 'Held the batch', 'The links failed in front of buyers. I kept them from sale and documented the load, even though it hurt us.', 'What broke in the public test?'],
      ['brina-forgehand', 'Checked the heat record', 'The forge record was consistent. The mixed ore still needs an assay before I call the metal sound.', 'Was the forging process at fault?'],
      ['sera-blackvein', 'Traced the ore allotment', 'Two stores were labeled as one. That is a traceability problem, not proof a miner cheated anyone.', 'Where did the iron come from?'],
    ], 'The links are held. What tested replacement can buyers use now?'),
  event('widows-vineyard-harvest-claimed', 'Three Flags Over the Vineyard',
    'Collectors for three rival claimants arrive at Widow’s Vineyard on the same harvest morning. Workers pause the tithe carts and preserve the crop while advocates compare the orders.',
    'Widow’s Vineyard can feed more than its own valley, which makes its harvest attractive to competing courts. Three groups of collectors arrive with different seals. Duchess Aveline Edevane asks the workers to keep cutting grapes while the tithe carts remain empty. Princess Elara Thornwall compares transport orders; Celessa Vane tries to keep the envoys at one table instead of three rival gates.\n\nThe fruit is brought under cover before it spoils. No claimant receives a tithe that day. The documents each have a plausible authority but apply to different dates. The workers need an answer before fermentation begins, and the envoys must bargain without turning a harvest into a battlefield.',
    'widows-vineyard', [
      ['duchess-aveline-edevane', 'Kept the harvest moving', 'The grapes would not wait for a legal argument. I asked workers to bring them in while carts stayed empty.', 'Did any claimant take the harvest?'],
      ['princess-elara-thornwall', 'Compared the orders', 'The dates are not the same. I want them read side by side before any wagon leaves.', 'How can three claims all look valid?'],
      ['celessa-vane', 'Held one negotiation', 'Separate gates invite a confrontation. I kept the envoys at one table with the workers watching.', 'How did you keep the collectors from fighting?'],
    ], 'The grapes are under cover. Who can claim a share, and when?'),
  event('arena-healers-call-stop', 'The Arena Healers Call a Stop',
    'Healers halt a Wyrmglass Arena contest after the safety barrier cracks. The audience leaves safely, but sponsors demand an immediate rematch before the barrier has been independently tested.',
    'Wyrmglass Arena turns risk into spectacle, yet its barrier must hold for everyone present. During a contest, a visible crack crosses one protective panel. Mara Sable calls a stop and checks competitors. Brina Forgehand examines the panel’s mounting, while Dame Ysabet Rooke clears the nearest seating row before arguing with any sponsor.\n\nNo one is injured. A replacement panel is fitted, but the arena remains closed for an independent load test. The interrupted contest has no winner. Organizers must decide whether their promise to paying spectators can ever outrank a healer’s authority to stop the floor.',
    'wyrmglass-arena', [
      ['mara-sable', 'Stopped the contest', 'The panel cracked while people were near it. I ended the round before asking whether it could survive one more impact.', 'Were competitors hurt?'],
      ['brina-forgehand', 'Checked the mounting', 'The panel failed at a bracket. A replacement must be tested with its mount, not admired for looking clear.', 'What broke in the barrier?'],
      ['dame-ysabet-rooke', 'Cleared the seating row', 'I moved spectators before the sponsors began bargaining over a rematch. Their tickets did not make the barrier sound.', 'Why was the audience moved?'],
    ], 'The panel is replaced. Who decides when the contest may resume?'),
  event('crownspire-night-without-fire', 'Crownspire’s Watchfires Go Out',
    'A run of watchfires on the road to Crownspire dies in the same storm. Messengers use guarded riders while the capital checks whether the fuel was soaked or the signal chain was neglected.',
    'Watchfires carry simple messages across the realm when roads are slow. A storm puts out several posts leading to Crownspire. Lady Rowena Thornwall sends riders with written notices instead of reading silence as peace. Orla Saye checks the nearest fuel store; Prince Lucien Vaelorian asks petitioners to remain in the city until news from the outer posts is verified.\n\nThe riders return with no attack to report, and the fires are relit after dry fuel is brought in. The chain failed because covered stores at two posts leaked. The capital must treat a silent watchfire as missing information, not a reassuring answer.',
    'crownspire', [
      ['lady-rowena-thornwall', 'Sent written riders', 'The fires were out. I would not translate silence into a safe road without sending people to check.', 'Did the watchfire failure signal an attack?'],
      ['orla-saye', 'Checked the fuel stores', 'Two covered stores were wet inside. The roofs looked sound from a distance and were not.', 'Why did so many fires go out?'],
      ['prince-lucien-vaelorian', 'Held petitioners in the city', 'We delayed departures until outer-post news returned. I told people what we lacked, not what I hoped.', 'Why were travelers asked to wait?'],
    ], 'There was no attack. What should silence in a signal chain mean?'),
  event('motherleaf-root-wash', 'The Motherleaf Roots Wash Free',
    'A flood exposes the roots protecting Motherleaf Sanctuary. Healers and forest scouts move visitors away while they divert water without cutting the living support.',
    'Motherleaf Sanctuary is held together by living roots as much as by stone. Heavy rain sends a new channel beneath its lowest path and exposes a broad root mat. Thalia Moss moves patients and visitors to dry rooms. Lord Rowan Edevane brings forest workers to divert the run without chopping through the roots; Nerys Rowanleaf records older channel marks that suggest the water once used a different course.\n\nThe sanctuary remains open in its upper rooms. The low path closes for repair. Water diversion works for this storm, but the older marks raise a planning question: should the path be rebuilt in the same place, or should the sanctuary let the water reclaim its former way?',
    'motherleaf-sanctuary', [
      ['thalia-moss', 'Moved visitors upstairs', 'The roots and people both needed room. I kept care going in dry rooms rather than waiting for the water to reach them.', 'Was the sanctuary evacuated?'],
      ['lord-rowan-edevane', 'Diverted the run', 'We moved water without cutting the root mat. That is a temporary defense, not a license to rebuild blindly.', 'How did workers protect the roots?'],
      ['nerys-rowanleaf', 'Read the older marks', 'The marks show an older channel. They do not prove exactly when it moved, but a repair should take them seriously.', 'Did water once flow beneath that path?'],
    ], 'The upper rooms remain open. Where should the low path go next?'),
];
