// Public incidents never expose private bloodlines, covert loyalties, or protected story answers.
const B = (title, place, observed, unresolved, type, ...actions) => [title, place, observed, unresolved, type, actions];
const S = (lead, others, title, place, observed, unresolved, type, ...actions) => [lead, others, title, place, observed, unresolved, type, actions];
export const modeOffsets = [[], [1,2], [3,4,5]];
export const groups = [
  ['queen-maerra-vaelorian','prince-lucien-vaelorian','princess-maris-vaelorian','king-edric-thornwall','lady-rowena-thornwall','lord-halric-thornwall','princess-elara-thornwall','queen-selene-ravaryn','prince-aurel-ravaryn','admiral-nyra-greymere','dame-ysabet-rooke','lady-isolde-morcant','lord-cassian-greymere'],
  ['duchess-mirelle-greymere','bastian-crow','captain-seraphine-vale','kael-dravos','idris-salt','orla-saye','rorik-pell','delphine-lantern','sabine-silk-veyl','sable-wren','celessa-vane','vespera-saan','liora-saintless'],
  ['asha-ren','duchess-aveline-edevane','lord-rowan-edevane','joren-ash','brina-forgehand','nia-chainbreaker','sera-blackvein','torren-bale','lyssa-bramble','freya-hart','malrec-vale','maeve-redreed','catrin-brann'],
  ['brother-aldren','high-flame-elowen-orison','sister-mercy-voss','ilyra-ashscale','rhevan-crownsbane','petra-glass','nerys-rowanleaf','tamsin-quill','thalia-moss','mara-sable','garrick-holt','celia-thatch','nessa-honeybell-marrow'],
];
export const residentBriefs = {
  'queen-maerra-vaelorian': [
    B('The petition seal over an unread page','crownspire','Maerra discovers a petition packet sealed for reply while its final page remains unread.','She has the page entered into the record before issuing an answer.','governance'),
    B('A grain petition counted as a military request','crownspire','Maerra sees a village grain petition filed under military supply, where its households will not receive an answer.','She sends it to the right hearing with its original date intact.','governance','checks which petitions his office has already promised to hear','finds the junior petition docket with the village name'),
    B('The council chamber opened without a fire route','crownspire','Maerra finds a crowded audience scheduled in a chamber whose side fire route is blocked by stored banners.','She clears the route before making anyone wait for an audience.','safety','checks the northern delegation’s arrival count','asks the road keeper which entrance is usable','sets a guard line without sealing the exit'),
  ],
  'prince-lucien-vaelorian': [
    B('The petition copied in a different hand','crownspire','Lucien finds a copy of a citizen petition with one sentence changed after the signer left.','He preserves both versions before asking which one should be heard.','records'),
    B('A hearing notice delivered to the wrong family','crownspire','Lucien sees a hearing notice sent to a household sharing a name with the actual petitioner.','He corrects the notice without exposing the petitioner’s grievance.','privacy','checks the younger princess’s dispatch list','finds the queen’s original hearing order'),
    B('The bridge levy written in a victory speech','ember-throne-hall','Lucien hears a speech promise a bridge levy before the roads office has costed it.','He asks for real figures before the promise becomes policy.','governance','checks the northern road account','asks the military commander what supply route is at stake','separates the envoy’s treaty claim from the levy'),
  ],
  'princess-maris-vaelorian': [
    B('The crown petition with a missing witness','crownspire','Maris finds a signed petition lacking the witness named on its cover.','She asks the signer privately rather than assuming the petition is false.','records'),
    B('An answer drafted before the question arrives','crownspire','Maris sees a stock reply prepared for a petition that has not yet been read.','She returns it to the desk until the actual grievance is known.','governance','compares his office’s older petition draft with the signed letter','confirms whether she had promised this petitioner a hearing'),
    B('The supply list treated as a petition','crownspire','Maris notices a northern supply list filed among appeals for clemency.','She restores it to the quartermaster record before the wrong office answers.','records','checks the road keeper’s delivery mark','asks the commander which supplies were actually requested','finds the envoy’s intended recipient'),
  ],
  'king-edric-thornwall': [
    B('The winter stores counted twice','thornwall-keep','Edric finds a winter stores tally count one granary twice after two clerks report the same shipment.','He orders a physical count before claiming the keep can spare grain.','resources'),
    B('A road order issued without a weather window','thornwall-keep','Edric sees an order send wagons across a northern pass without the roads office’s latest condition report.','He holds departure for a real route check.','safety','checks the road keeper’s current pass report','asks the commander which cargo is truly urgent'),
    B('The treaty table set above the working map','thornwall-keep','Edric finds a ceremonial treaty table placed over the only full northern road map needed by quartermasters.','He moves it before the meeting hides practical needs.','governance','checks the envoy’s actual delegation size','asks the regent’s representative what route they propose','has the admiral’s sea-route note kept separate'),
  ],
  'lady-rowena-thornwall': [
    B('The north road milestone placed too soon','black-march','Rowena finds a newly set milestone shorter of the actual distance to the next safe water stop.','She corrects it before travelers ration by a false measure.','roads'),
    B('A legion wagon given the wrong bridge weight','black-march','Rowena sees a wagon order list a bridge weight limit copied from an older structure.','She checks the present span before sending soldiers over it.','safety','identifies the commander’s actual wagon load','asks the envoy whether the journey can wait'),
    B('The treaty escort without food stops','black-march','Rowena gets an escort route whose ceremonial pace leaves no practical meal stop for horses or people.','She adds stops before the party leaves.','care','checks the regent’s expected travel time','asks the admiral whether a sea leg is possible','confirms the guard captain’s escort roster'),
  ],
  'lord-halric-thornwall': [
    B('The legion shield fitted with a loose strap','wolfgate-barracks','Halric finds an armory shield marked ready with its carrying strap nearly detached.','He holds the issue until the batch is inspected.','safety'),
    B('A road patrol planned beyond its rations','wolfgate-barracks','Halric sees a patrol roster run longer than its issued food and water.','He changes the route or provisions before anyone marches.','care','checks the road keeper’s nearest supply stop','asks the envoy whether the escort must travel that far'),
    B('The inspection that blocks an envoy’s crossing','wolfgate-barracks','Halric discovers a barracks inspection would close the only level crossing used by a visiting delegation.','He changes the inspection plan before the guests arrive.','access','checks the regent’s carriage route','asks the admiral about disembarkation timing','arranges a guard passage with the captain'),
  ],
  'princess-elara-thornwall': [
    B('The quartermaster’s blanket list missing children','thornwall-keep','Elara finds a relief blanket list count adults but omit children staying in the same houses.','She corrects the quantities before the carts leave.','care'),
    B('A treaty gift booked as winter stores','thornwall-keep','Elara sees ceremonial gifts counted among supplies promised to cold villages.','She separates the inventories before either promise fails.','resources','checks which gift the regent’s envoy actually expects','asks the admiral what can arrive by sea'),
    B('The relief route laid through a troop review','thornwall-keep','Elara finds a relief cart due to pass through a troop review at its busiest hour.','She moves the departure to keep food moving.','logistics','checks the admiral’s harbor arrival','asks the guard captain for a safe crossing','finds the intelligence courier’s actual notice date'),
  ],
  'queen-selene-ravaryn': [
    B('The island granary opened for a ceremony','drowned-crown-palace','Selene sees a ceremonial tour planned through a granary still sorting incoming grain.','She moves the tour rather than disrupt the food record.','resources'),
    B('A sea treaty copied without its harbor clause','drowned-crown-palace','Selene receives a treaty summary that omits the practical harbor-access clause.','She asks for the full text before discussing terms.','diplomacy','checks the prince’s public reading of the treaty','asks the admiral which harbor rule affects ships'),
    B('The harbor delegation counted without its crews','drowned-crown-palace','Selene finds a reception plan list captains but not the sailors who brought them.','She orders meals and rest space for the crews too.','care','checks the admiral’s crew count','asks the guard captain about safe lodging','asks the diplomat where the visiting crew can stay'),
  ],
  'prince-aurel-ravaryn': [
    B('The training blade sharpened for a ceremony','ember-isles','Aurel finds a demonstration blade sharpened after the practice plan called for a blunt edge.','He replaces it before the public exercise.','safety'),
    B('An island ship named on a treaty it never saw','drowned-crown-palace','Aurel sees a ship listed as committed to a treaty mission before its captain was consulted.','He checks the actual sailing agreement.','diplomacy','asks the admiral whether the vessel can travel','checks the guard escort tied to the mission'),
    B('The harbor watch reading a false tide table','ashen-docks','Aurel notices a harbor watch board show yesterday’s tide numbers under today’s heading.','He corrects it before cargo moves.','safety','checks the admiral’s sailing window','asks the guard captain which ferry is due','finds the diplomat’s written arrival estimate'),
  ],
  'admiral-nyra-greymere': [
    B('The ship’s lifeboat listed aboard twice','greymere-shipyard','Nyra sees one lifeboat entered on two ships’ equipment lists.','She counts actual boats before either vessel departs.','safety'),
    B('A harbor signal heard as an attack warning','ashen-docks','Nyra hears a routine harbor signal repeated as an attack warning by a new watch.','She corrects the code publicly before panic directs ships into danger.','communications','checks the guard captain’s receiving watch','finds which intelligence notice used the wrong phrase'),
    B('The treaty berth without enough depth','ashen-docks','Nyra finds a visiting ship assigned to a berth too shallow at the promised arrival tide.','She offers a feasible berth rather than a ceremonial welcome that strands them.','navigation','checks the guard’s quay clearance','asks the coastal diplomat what the visiting captain was told','confirms the queen’s reception time'),
  ],
  'dame-ysabet-rooke': [
    B('The guard post with no relief named','crownspire','Ysabet sees a guard post assigned through dawn without a replacement on the roster.','She names relief before the current guard’s attention fails.','safety'),
    B('A prince’s route printed on a public program','crownspire','Ysabet finds a royal procession route printed in public detail before security has reviewed it.','She changes only what protection requires, leaving public access clear.','security','checks the intelligence broker’s actual risk note','asks the diplomat which public stops are essential'),
    B('The council chamber key found outside its box','crownspire','Ysabet finds a chamber key in a corridor after a contentious hearing.','She logs it and changes access rather than treating the nearest servant as guilty.','fairness','checks the broker’s authorized access list','asks the diplomat when the chamber was last used','checks the queen’s meeting schedule'),
  ],
  'lady-isolde-morcant': [
    B('The report that names a witness twice','red-ledger-exchange','Isolde finds two reports cite the same witness under different aliases, making a rumor look corroborated.','She marks it as one source before anyone acts.','evidence'),
    B('A guard briefing built from an old route','red-ledger-exchange','Isolde sees a guard briefing treat last month’s envoy route as tomorrow’s confirmed route.','She separates stale intelligence from current travel plans.','accuracy','checks the captain’s actual escort notice','asks the diplomat what route was agreed'),
    B('The harbor manifest with a copied seal','red-ledger-exchange','Isolde receives a manifest bearing a copied seal but no signed cargo count.','She asks for the physical tally before naming a smuggler.','evidence','checks the diplomat’s authorized cargo','asks the queen’s clerk for the intended recipient','compares the admiral’s boarding record'),
  ],
  'lord-cassian-greymere': [
    B('The treaty page without its sea chart','greymere-shipyard','Cassian sees a treaty page refer to an attached sea chart that never reached the table.','He asks for the chart before either side signs.','diplomacy'),
    B('A petition addressed to the wrong court','crownspire','Cassian finds a coastal petition directed to a court with no power over the disputed berth.','He helps redirect it without losing the filing date.','governance','checks the queen’s petition process','asks the junior clerk for the original receipt'),
    B('The northern road clause added to a sea accord','greymere-shipyard','Cassian sees a northern road clause inserted into a sea accord after the delegations exchanged drafts.','He asks each side to acknowledge it openly.','diplomacy','checks the road keeper’s actual route','asks the commander which cargo it affects','confirms the envoy’s authority to discuss it'),
  ],
  'duchess-mirelle-greymere': [
    B('The shipyard wage ledger with a missing crew','greymere-shipyard','Mirelle finds a shipyard wage ledger omit a crew that worked through the last storm.','She asks for the actual hours before any payment is marked settled.','labor'),
    B('A launch named before the hull is watertight','greymere-shipyard','Mirelle sees a public launch invitation sent while the hull still awaits a water test.','She changes the date rather than make workers rush a seam.','safety','checks the shipwright’s test schedule','asks the courier captain what berth is needed'),
    B('The harbor lodging list excluding deckhands','shattered-coast','Mirelle sees a port reception provide beds for officers but none for the crews working their vessels.','She opens another lodging house before the ships arrive.','care','checks the privateer’s crew count','asks the prison warden about available public berths','asks the lighthouse keeper about the weather window'),
  ],
  'bastian-crow': [
    B('The keel timber with a hidden knot','greymere-shipyard','Bastian finds a keel timber whose painted face conceals a deep knot.','He rejects it before shaping the hull around a weak beam.','craft'),
    B('The duchess’s launch date over the seal test','greymere-shipyard','Bastian sees a proposed launch date before the new hull’s seal test.','He shows the actual work remaining rather than promising a miracle.','safety','checks the patron’s published invitation','asks the captain when a test crew can attend'),
    B('A ship part delivered as prison iron','greymere-shipyard','Bastian receives a crate of ship fittings marked as prison iron under a mixed freight tally.','He separates the orders before either installation.','accuracy','checks the courier’s handoff receipt','asks the warden whether any prison repair is delayed','traces the lighthouse freight route'),
  ],
  'captain-seraphine-vale': [
    B('The cargo seal torn at the wrong end','ashen-docks','Seraphine finds a cargo seal torn after a boat handoff while the manifest says it arrived intact.','She records the discrepancy before moving the crate.','logistics'),
    B('A shipyard test boat used for a courier run','greymere-shipyard','Seraphine sees a courier asked to use a hull still undergoing shipyard trials.','She refuses the departure until the craft is certified.','safety','asks the shipwright when the water test finishes','finds a licensed captain with another boat'),
    B('The prison delivery missing its food count','tidevault-prison','Seraphine arrives with a prison delivery note that lists crates but not actual meals inside.','She asks for a witnessed count before signing away the cargo.','care','checks the warden’s order','asks the lighthouse keeper when the next tide allows return','checks the harbor porter’s load sheet'),
  ],
  'kael-dravos': [
    B('The harbor rope tied to a rotten bollard','ashen-docks','Kael finds his vessel tied to a bollard whose lower timber has split.','He moves the line before the next tide puts strain on it.','safety'),
    B('A duchess’s charter written as unrestricted passage','shattered-coast','Kael sees a charter imply unrestricted passage through a closed sea lane.','He negotiates an honest route before taking payment.','navigation','checks which lane the shipyard actually cleared','asks the courier captain about the recent marker'),
    B('The prison ferry counted as a merchant sail','ashen-docks','Kael finds a ferry carrying prison supplies counted against merchant space rather than protected service capacity.','He asks the port to show its priority rule.','fairness','checks the warden’s needed delivery window','asks the signal keeper which crossing is safe','finds the harbor runner’s current tide note'),
  ],
  'idris-salt': [
    B('The prison meal count without evening names','tidevault-prison','Idris finds a prison meal tally count cells but not people transferred in that afternoon.','He corrects the meal order before service.','care'),
    B('A shipyard bolt sent as a cell repair','tidevault-prison','Idris receives metal fittings labeled for prison repair though the sizes match shipyard stock.','He asks for a correct work order before using them.','records','checks the shipwright’s missing shipment','asks the captain who delivered the crate'),
    B('The lantern signal posted in the wrong window','tidevault-prison','Idris sees a prison transport signal set for a tide window the lighthouse board has already changed.','He delays the transfer until safe passage is confirmed.','safety','checks the lighthouse reading','asks the harbor runner which crew is ready','tells the safehouse keeper only the publicly needed arrival time'),
  ],
  'orla-saye': [
    B('The lighthouse glass with a salt crack','saint-orlas-lighthouse','Orla finds a hairline crack in a lighthouse glass panel after a hard salt storm.','She logs its effect on the beam before nightfall.','navigation'),
    B('A shipyard launch listed under the wrong tide','saint-orlas-lighthouse','Orla sees a launch notice cite a tide window copied from the previous day.','She sends the current table before crews commit.','safety','checks the shipwright’s actual launch time','warns the courier captain which channel is shallow'),
    B('The prison ferry following an old signal code','saint-orlas-lighthouse','Orla hears a prison ferry request the old light code after a recent change.','She repeats the valid signal before the vessel enters the narrows.','communications','checks the warden’s transport list','asks the harbor runner what signal he received','keeps the safehouse’s own lamps distinct'),
  ],
  'rorik-pell': [
    B('The harbor runner’s map missing a pier','lantern-rooms','Rorik sees a visitor map omit a working pier behind the lodging house.','He adds the public route without marking residents’ private doors.','access'),
    B('A launch crew brought to a closed gate','greymere-shipyard','Rorik is asked to bring a launch crew through a yard gate locked for repairs.','He confirms another entrance before anyone travels.','logistics','checks the shipwright’s gate schedule','asks the captain which dock they must reach'),
    B('The prison ferry guest list left in a tavern','lantern-rooms','Rorik finds a transport guest list forgotten on a public tavern table.','He returns it sealed rather than reading names aloud.','privacy','checks the warden’s receiving clerk','asks the lighthouse keeper for the ferry’s public arrival time','finds the lodging keeper who can pass the envelope safely'),
  ],
  'delphine-lantern': [
    B('The lantern room rented without a fire check','lantern-rooms','Delphine finds a guest room rented while its lamp chimney is still cracked.','She moves the guest and repairs the lamp before reuse.','safety'),
    B('The shipyard crew expected but not fed','lantern-rooms','Delphine sees a lodging booking count shipyard workers but omit their meals after a late shift.','She asks the yard for a true headcount.','care','checks which workers the foreman actually sent','offers the captain a separate tide-time meal'),
    B('The prison visitor sent to the wrong shore','lantern-rooms','Delphine receives a visitor whose directions point to an old prison ferry dock.','She gives the active route without discussing private prisoners.','access','checks the warden’s public visiting hour','asks the signal keeper about the safe crossing','finds the harbor runner’s current map'),
  ],
  'sabine-silk-veyl': [
    B('The guest contract copied without its refusal line','house-of-velvet-oaths','Sabine finds a guest contract copied from an old form without the worker’s right to refuse a booking.','She voids the bad forms before any appointment proceeds.','consent'),
    B('A ship captain offered a worker’s private time','house-of-velvet-oaths','Sabine hears a broker promise a guest a worker’s private time without asking the worker.','She makes clear only the worker can accept.','consent','checks the shipwright’s actual social booking','asks the courier captain what was promised'),
    B('A lodging guide calling a private house public','house-of-velvet-oaths','Sabine sees a visitor guide list the house as an unbooked public attraction.','She removes the listing and protects both guests and workers.','privacy','checks the ferry schedule that brought visitors','asks the signal keeper where the guide was posted','asks the harbor runner to carry the correction, not names'),
  ],
  'sable-wren': [
    B('The performance ribbon tied for another act','house-of-velvet-oaths','Sable finds a performance ribbon assigned to an act she never agreed to do.','She corrects the program before anyone treats a prop as consent.','consent'),
    B('A patron’s sketch offered for sale','house-of-velvet-oaths','Sable sees a patron’s private sketch of a performance offered for sale without anyone’s release.','She asks the house to keep the drawing private.','privacy','checks which booking terms the proprietor promised','asks the courier captain if the sketch left by ship'),
    B('The floor cue hidden by a new curtain','house-of-velvet-oaths','Sable finds a new curtain hide the floor mark she needs for a safe performance.','She resets the mark and rehearses before opening.','safety','checks the signal light reflected from the curtain','asks the harbor runner to keep the exit clear','checks the host’s actual staging plan'),
  ],
  'celessa-vane': [
    B('The diplomatic toast translated too strongly','crimson-veil','Celessa hears a polite toast translated as a binding promise during a rehearsal.','She corrects the language before guests arrive.','diplomacy'),
    B('A patron’s guest list containing private names','crimson-veil','Celessa finds a guest list prepared for public display that includes people who requested discretion.','She produces a public list with only agreed names.','privacy','checks what the proprietor has permission to announce','asks the floor performer which name appears on the program'),
    B('The seating order that blocks a guest’s exit','crimson-veil','Celessa sees a diplomatic seating plan trap one guest behind a ceremonial screen.','She adjusts it so everyone can leave without asking permission.','access','checks the performer’s stage route','asks the signal runner how the outer door opens','coordinates the tutor’s public entrance cue'),
  ],
  'vespera-saan': [
    B('The lesson prop mistaken for a contract','crimson-veil','Vespera sees a ceremonial ribbon used in a lesson interpreted by a visitor as a signed agreement.','She explains the ritual and offers a real written choice.','consent'),
    B('A worker’s demonstration booked by someone else','crimson-veil','Vespera finds a demonstration listed under another worker’s name without that person agreeing.','She removes the booking until the worker chooses.','labor','checks her house’s event sheet and who accepted the deposit','states what performance, if any, she was personally offered'),
    B('The visiting envoy rushed through a gesture','crimson-veil','Vespera sees an envoy pushed to repeat a ritual gesture they do not understand for a photograph.','She pauses the lesson and explains what the gesture means.','diplomacy','checks the private room release','asks the signal keeper to hold the light for a slower demonstration','asks the floor host about the proper translation'),
  ],
  'liora-saintless': [
    B('The chosen name crossed out on the guest board','saintless-house','Liora finds a guest board use an old name someone explicitly asked not to use.','She changes it and speaks to staff privately.','respect'),
    B('A shipyard traveler promised an unbooked bed','saintless-house','Liora receives a shipyard traveler whose bed was promised by a broker without a reservation.','She finds a real place to sleep without hiding the mistake.','hospitality','checks what the yard actually paid for','asks the courier captain about another safe lodging'),
    B('A prison visitor’s story written as gossip','saintless-house','Liora sees an inn flyer turn a visitor’s private reason for travel into a curiosity.','She removes the line and explains why it was never public.','privacy','checks the warden’s public visiting rules','asks the lighthouse keeper for the current ferry time','asks the harbor runner to remove copied flyers'),
  ],
  'asha-ren': [
    B('The camp ration card without household sizes','cinder-camp','Asha finds a camp ration card count shelters but not the people sharing each one.','She orders a household count before reallocating food.','resources'),
    B('A forest donation promised before collection','cinder-camp','Asha sees a relief notice promise forest supplies that have not been gathered or delivered.','She corrects the notice rather than spend another community’s food on paper.','honesty','checks what the duchess actually offered','asks the border marshal which route is open'),
    B('The courier route over a damaged bridge','cinder-camp','Asha hears a messenger route planned over a bridge with no current load check.','She sends only essential traffic by a verified path.','safety','asks the courier what can be delayed','checks the smith’s spare bridge fittings','asks the quartermaster about transport capacity'),
  ],
  'duchess-aveline-edevane': [
    B('The forest harvest counted as free labor','verdant-reach','Aveline sees a forest relief shipment budget timber but no pay for the cutters.','She changes the account before asking anyone to work.','labor'),
    B('A camp request written without a delivery path','verdant-reach','Aveline receives a camp request for herbs but no safe path or receiver.','She asks for both before dispatching supplies.','logistics','checks the camp’s actual stock','asks the marshal which border route is safe'),
    B('The forge order that would clear a young grove','verdant-reach','Aveline learns a forge charcoal order could strip a young grove protecting a stream.','She offers a smaller, documented cut and another fuel source.','stewardship','asks the courier when fuel is needed','checks the smith’s real furnace load','asks the quartermaster how long stores will last'),
  ],
  'lord-rowan-edevane': [
    B('The border trail marked after a tree fall','green-hart-lodge','Rowan finds a trail sign still point through a fallen tree and unstable roots.','He marks a safe detour before sending scouts.','safety'),
    B('A camp supply convoy assigned a hunting path','verdant-reach','Rowan sees a heavy supply convoy planned through a narrow hunting path that cannot bear carts.','He provides a real wagon route.','logistics','checks the camp’s delivery deadline','asks the duchess for the road-use terms'),
    B('The courier’s note sent by the wrong pass','green-hart-lodge','Rowan finds a courier’s note routed through a pass closed after rain.','He sends an updated route without opening protected forest ground.','roads','checks the courier’s arrival promise','asks the smith whether a damaged gate can be repaired','checks the quartermaster’s receiving time'),
  ],
  'joren-ash': [
    B('The courier bag with a broken buckle','cinder-camp','Joren finds a courier bag whose buckle opens under a light load.','He changes the bag before moving anyone’s letters.','care'),
    B('A forest message with no named receiver','verdant-reach','Joren receives a forest message addressed only to the camp.','He asks which officer should accept it rather than leave it in public.','privacy','checks the duchess’s intended handoff','asks the marshal where the receiver is stationed'),
    B('The forge part packed beside food','cinder-camp','Joren sees a dirty forge fitting packed against meal sacks in a transport crate.','He repacks it and notes the delay.','safety','asks the smith for a clean wrap','checks the quartermaster’s food count','asks the mine teacher whether the crate came from her route'),
  ],
  'brina-forgehand': [
    B('The forge tongs split at their hinge','ironwake-foundry','Brina finds a tong hinge split after the last heat cycle.','She pulls the tool before anyone lifts molten metal.','craft'),
    B('A camp repair order without a metal grade','ironwake-foundry','Brina receives a camp repair order naming a shape but not the load it must carry.','She asks for measurements before forging.','safety','checks the quartermaster’s intended use','asks the mine runner where the metal came from'),
    B('A forest gate ordered as a prison door','ironwake-foundry','Brina sees a forest gate order copied onto a prison-door specification with a much heavier lock.','She holds the order until the owner clarifies the purpose.','fairness','checks the camp courier’s original request','asks the border marshal which gate is actually damaged','asks the innkeeper where delivery was promised'),
  ],
  'nia-chainbreaker': [
    B('The quartermaster sacks without a bottom seam','cinder-camp','Nia finds grain sacks issued for a long march with weak bottom seams.','She reworks them before grain is lost on the road.','resources'),
    B('A forest load entered as camp property','cinder-camp','Nia sees a forest shipment entered as a gift when its workers were promised payment.','She keeps the debt visible in her ledger.','fairness','asks the duchess what the forest crew agreed','checks the border marshal’s transport tally'),
    B('The forge bolts counted before cooling','cinder-camp','Nia finds newly forged bolts marked available before the metal finished cooling and testing.','She changes the readiness board.','safety','asks the courier which repair is urgent','checks the smith’s test count','asks the mine runner which materials were supplied'),
  ],
  'sera-blackvein': [
    B('The mine lesson held beside an open shaft','deepnail-mines','Sera finds a clandestine reading lesson arranged beside an open mine shaft after a room change.','She moves the children before the lesson begins.','teaching'),
    B('The forest map with a blocked air passage','deepnail-mines','Sera sees a forest travel map show a mine air passage as a public shortcut.','She corrects it before travelers enter active workings.','safety','asks the border marshal which public route is open','checks the camp’s copy of the map'),
    B('The courier packet marked as ore weight','deepnail-mines','Sera finds a teaching packet entered into the ore weight ledger after a mixed delivery.','She separates the records without exposing private students.','privacy','asks the courier for the actual handoff time','checks the smith’s ore receipt','asks the innkeeper to keep the package private'),
  ],
  'torren-bale': [
    B('The inn’s last bed promised twice','broken-spur-tavern','Torren sees the last inn bed promised on two travel slips after a rainy pass closure.','He tells both travelers and finds a safe alternative.','hospitality'),
    B('A forest patrol counted as paying guests','broken-spur-tavern','Torren finds a patrol’s emergency rest stop billed as an ordinary guest stay.','He fixes the account before asking the crew to pay.','fairness','checks the marshal’s actual stop order','asks the camp whether the meal was supplied'),
    B('The forge delivery put through a guest hall','broken-spur-tavern','Torren discovers a hot forge delivery routed through the guest sleeping hall.','He directs it around the building before anyone is burned.','safety','asks the smith when it can be handled','checks the quartermaster’s receiver','asks the mine runner which cargo must stay sealed'),
  ],
  'lyssa-bramble': [
    B('The tavern song with a private name in its chorus','briar-and-cup','Lyssa hears a new tavern chorus include a private name someone gave her in confidence.','She changes the lyric before singing it publicly.','privacy'),
    B('A forest festival set without fair pay','briar-and-cup','Lyssa receives a forest festival invitation offering exposure but no musician fee.','She asks for a fair offer before assembling a band.','labor','checks who funds the festival','asks the border marshal whether travel is safe'),
    B('The camp song used as a marching order','briar-and-cup','Lyssa hears a playful camp song repeated as if it were a real route instruction.','She tells listeners it is music, not a safe travel map.','honesty','asks the courier which route is current','checks the innkeeper’s public road board','asks the scout what trail is actually open'),
  ],
  'freya-hart': [
    B('The hunter’s snare left near a footpath','green-hart-lodge','Freya finds a snare set too near a public footpath after a map change.','She removes it and tells her hunters what changed.','safety'),
    B('A forest grant that assumes hunters guide free','green-hart-lodge','Freya sees a forest grant count on hunters as free guides for visitors.','She asks for paid hours or a smaller route.','labor','checks the duchess’s grant terms','asks the marshal about patrol availability'),
    B('The courier bearing an unverified trail token','green-hart-lodge','Freya receives a courier with an old trail token that no longer proves a route is safe.','She verifies the current pass before sending them onward.','safety','asks the courier what cannot wait','checks the smith’s gate repair','asks the innkeeper which travelers already followed the old token'),
  ],
  'malrec-vale': [
    B('The camp ledger with a copied signature','cinder-camp','Malrec sees a camp supply receipt carry a copied signature from a prior delivery.','He preserves both receipts and asks who actually accepted the goods.','records'),
    B('A forest pardon dated before the hearing','cinder-camp','Malrec finds a public pardon draft dated before the hearing that was meant to decide it.','He corrects the date and marks the decision still open.','accuracy','checks the duchess’s hearing notice','asks the marshal whether anyone already received the draft'),
    B('The forge requisition missing a witness','cinder-camp','Malrec receives a forge requisition with a blank witness line but a full load promised.','He asks for a witnessed count before entering it as delivered.','records','checks the courier’s cargo note','asks the smith what was produced','asks the quartermaster what was received'),
  ],
  'maeve-redreed': [
    B('The Red Reeds performer paid in promises','house-red-reeds','Maeve finds a performer’s agreement marked paid though the promised money has not arrived.','She settles the fee before booking another night.','labor'),
    B('A forest song booked without its players','house-red-reeds','Maeve sees a forest song advertised for a show before asking the musicians who made it.','She offers a proper paid invitation.','rights','checks the duchess’s festival terms','asks the border marshal when the musicians can travel'),
    B('The camp gathering without a private exit','house-red-reeds','Maeve finds a camp gathering booked in a room where guests must pass the public stage to leave.','She arranges a separate exit before doors open.','privacy','checks the courier’s guest count','asks the smith about a temporary gate','asks the quartermaster whether the room is large enough'),
  ],
  'catrin-brann': [
    B('The fiddle bow with a cracked tip','house-red-reeds','Catrin feels a crack at the tip of her fiddle bow before an evening set.','She repairs or changes it before it breaks onstage.','music'),
    B('A forest tune credited to the wrong village','house-red-reeds','Catrin sees a songbook credit a forest tune to a village that learned it from another community.','She asks singers how they know it before printing a claim.','culture','checks the duchess’s festival song list','asks the border marshal where the tune traveled'),
    B('A courier’s letter hidden in the music case','house-red-reeds','Catrin finds a sealed letter in her music case after a crowded performance.','She returns it without making the message part of the show.','privacy','checks the courier’s delivery mark','asks the smith if the case was borrowed','asks the innkeeper where the owner can be reached'),
  ],
  'brother-aldren': [
    B('The sanctuary cot counted as a prison bed','basilica-seven-flames','Aldren sees a sanctuary cot entered into a prison overflow tally without the guest’s knowledge.','He separates the records before someone is moved against their will.','sanctuary'),
    B('A sermon excerpt printed without its plea','basilica-seven-flames','Aldren finds a sermon excerpt printed without the part asking listeners to shelter displaced people.','He asks for the whole meaning to be restored.','faith','checks which official edition was sent to print','asks the infirmary which shelter needs exist'),
    B('The relief procession blocking an infirmary door','basilica-seven-flames','Aldren sees a relief procession gather across the infirmary’s main door.','He moves the assembly so patients can enter.','care','checks the High Flame’s ceremony route','asks the healer about urgent access','asks the hatchery keeper to keep animals off the path'),
  ],
  'high-flame-elowen-orison': [
    B('The basilica reading with a page left sealed','basilica-seven-flames','Elowen finds a public reading planned from a copy with one page sealed by an old repair.','She tells listeners the text is incomplete instead of inventing the missing passage.','history'),
    B('A sanctuary list read as a guest register','basilica-seven-flames','Elowen sees a sanctuary list copied into an ordinary visitor register.','She protects the names and changes the record practice.','privacy','checks which people the traveling priest is sheltering','asks the infirmary which names are clinically necessary'),
    B('The infirmary candle shipment counted twice','basilica-seven-flames','Elowen discovers candles promised to the infirmary also counted for the basilica’s festival.','She allocates the real stock before either service begins.','resources','checks the healer’s needed amount','asks the hatchery keeper whether the festival requires lanterns nearby','checks the relic guide’s existing lantern stock before ordering more'),
  ],
  'sister-mercy-voss': [
    B('The infirmary tonic with a missing date','ash-mother-infirmary','Mercy finds a prepared tonic with no date after a crowded night shift.','She discards it rather than guessing its age.','care'),
    B('A prayer card mistaken for a treatment order','ash-mother-infirmary','Mercy sees a patient’s prayer card attached to a medical instruction board.','She keeps personal wishes separate from clinical orders.','privacy','asks the traveling priest where the card belongs','checks the High Flame’s public wording'),
    B('The hatchery worker brought in without rest','ash-mother-infirmary','Mercy receives an exhausted hatchery worker ordered straight back to duty after basic care.','She asks the worker what they can manage before signing any release.','labor','checks the hatchery’s coverage roster','asks the dragon interpreter about the safe replacement shift','asks the relic guide how far the return trip is'),
  ],
  'ilyra-ashscale': [
    B('The hatchling’s feeding log with a blank night','caldera-hatchery','Ilyra finds a hatchling feeding log missing a whole night after a change of keeper.','She checks the animal and the shift before calling it neglect.','animal-care'),
    B('A basilica blessing booked beside a restless brood','caldera-hatchery','Ilyra learns a loud public blessing is booked beside a brood already unsettled by heat.','She moves the visit instead of forcing the animals to tolerate it.','care','checks which parts of the ritual can be quiet','asks the infirmary whether any visitors need access'),
    B('The dragon chart treating rest as illness','caldera-hatchery','Ilyra sees a keeper chart mark normal rest as a symptom to be treated.','She asks for a second observation before anyone intervenes.','animal-care','checks the interpreter’s account of the animal’s behavior','asks the relic guide whether the heat reading was accurate','finds the archivist’s older husbandry note'),
  ],
  'rhevan-crownsbane': [
    B('The dragon call translated as an order','ashlands','Rhevan hears a dragon call repeated as an attack order though the sound could mean several things.','He marks his translation as uncertain before soldiers act.','interpretation'),
    B('A shrine mural used as a living dragon guide','ashlands','Rhevan sees an old mural treated as proof of how living dragons will move today.','He separates art from observation.','accuracy','asks the priest what the mural was meant to depict','checks the healer’s first-hand report'),
    B('The glass-field echo mistaken for a dragon reply','glass-battlefield','Rhevan hears a glass-field echo described as a dragon response.','He records its timing without promising an answer.','evidence','asks the hatchery keeper about recent calls','checks the relic guide’s mapped echo point','asks the archivist if earlier field notes mention it'),
  ],
  'petra-glass': [
    B('The glass relic with a fresh tool mark','glass-battlefield','Petra finds a glass relic advertised as ancient with a fresh tool mark on its base.','She documents the mark before setting a price.','artifacts'),
    B('A basilica fragment sold as a healing charm','glass-battlefield','Petra hears a seller call an unverified fragment a healing charm.','She refuses the claim and directs buyers toward real care.','ethics','asks the priest which symbols are actually used','checks the healer’s public guidance'),
    B('The dragon scale filed with battlefield glass','glass-battlefield','Petra sees a supposed dragon scale filed among glass fragments without a collection note.','She keeps the identification open and secures the object.','evidence','asks the hatchery keeper to examine it','asks the interpreter what can be known from appearance','checks the leaf archivist’s old site map'),
  ],
  'nerys-rowanleaf': [
    B('The leaf archive index without family names','weeping-archive','Nerys finds an archive index replace family names with numbers in only one decade of records.','She documents the pattern before claiming why it happened.','archive'),
    B('A basilica copy dated after the source burned','weeping-archive','Nerys notices a copied doctrine sheet dated after the source collection was recorded as lost.','She checks provenance before treating the date as a revelation.','history','asks the High Flame which copies survived','checks the infirmary’s old storage list'),
    B('The hatchery record credited to a missing keeper','weeping-archive','Nerys sees a hatchery record attributed to a keeper not on that season’s roster.','She looks for a copying error before rewriting biography.','evidence','checks the keeper’s known shifts','asks the dragon interpreter whether the observation fits','asks the relic guide where the source page came from'),
  ],
  'tamsin-quill': [
    B('The family tree written over an earlier hand','weeping-archive','Tamsin finds a family tree leaf with newer ink drawn over an older line.','She preserves both readings rather than choosing the more dramatic one.','genealogy'),
    B('A basilica name copied from a damaged stone','weeping-archive','Tamsin sees a name entered into a family index from a stone whose last letters are broken.','She marks the letters uncertain.','accuracy','asks the priest for the stone’s location','checks the High Flame’s older transcription'),
    B('The hatchery birth record with two dates','weeping-archive','Tamsin finds a hatchery birth record give one date in the ledger and another on its attached ribbon.','She asks what each date meant before changing either.','records','checks the keeper’s handover log','asks the relic guide how the ribbon was catalogued','compares the archivist’s index'),
  ],
  'thalia-moss': [
    B('The root remedy gathered from a protected bed','motherleaf-sanctuary','Thalia notices a medicinal root pulled from a protected bed after a visitor asked for a sample.','She explains the limits and restores the planting.','stewardship'),
    B('A basilica leaflet calling herbs a cure','motherleaf-sanctuary','Thalia sees a basilica leaflet describe one herb as a guaranteed cure.','She asks for language that respects both tradition and uncertainty.','care','checks which tradition the traveling priest intended','asks the High Flame who approved the text'),
    B('The infirmary order without patient consent','motherleaf-sanctuary','Thalia receives an infirmary request for a patient’s herbal history with no sign the patient agreed to share it.','She asks for consent before sending private notes.','privacy','asks the healer what information is clinically needed','checks the hatchery worker’s exposure only if relevant','asks the archivist for an anonymized plant source'),
  ],
  'mara-sable': [
    B('The arena treatment kit with a broken seal','wyrmglass-arena','Mara finds an arena treatment kit with its seal broken and no restock note.','She replaces supplies before the next bout.','care'),
    B('A basilica blessing advertised as medical clearance','wyrmglass-arena','Mara sees a fighter’s ceremony described as clearance to return to the arena.','She explains that a blessing does not replace examination.','health','asks the priest to correct the public wording','checks the healer’s actual recovery note'),
    B('The hatchery worker entered as a fighter','wyrmglass-arena','Mara discovers a hatchery worker’s injury recorded under an arena fighter with a similar name.','She separates the records before treatment or pay is affected.','privacy','checks the keeper’s identity privately','asks the dragon interpreter who reported the injury','asks the relic guide for the delivery docket'),
  ],
  'garrick-holt': [
    B('The condemned ledger with a blank appeal line','lantern-gallows','Garrick finds a condemned record with its appeal line blank though a petition is known to be pending.','He checks the court before acting on an incomplete page.','law'),
    B('A sanctuary name copied into a prison order','lantern-gallows','Garrick sees a sanctuary guest’s name appear on a prison transfer order without a matching warrant.','He asks for legal authority before any movement.','fairness','checks where the priest received the guest','asks the High Flame for the sanctuary record'),
    B('The infirmary discharge treated as a sentence','lantern-gallows','Garrick hears an infirmary discharge date cited as the date a sentence may proceed.','He requires the court’s actual order and the person’s condition.','law','asks the healer what the discharge means medically','checks whether the hatchery report belongs to the same person','finds the archive’s appeal receipt'),
  ],
  'celia-thatch': [
    B('The market bread counted after the stall closed','gilded-steps-market','Celia finds a market bread tally include loaves sold after the stall had closed.','She checks the next-day carryover before paying the baker.','trade'),
    B('A basilica food collection without a receiver','gilded-steps-market','Celia sees a basilica food collection advertised with no named person to accept perishables.','She asks for a handoff before baking extra bread.','resources','checks the priest’s collection plan','asks the High Flame when the kitchen opens'),
    B('The infirmary soup labeled for the wrong ward','gilded-steps-market','Celia notices a soup delivery labeled for a ward that moved last week.','She takes it to the correct desk while it is still safe to serve.','care','asks the healer for the current receiving point','checks the hatchery worker’s separate meal order','asks the archive clerk for a fresh route map'),
  ],
  'nessa-honeybell-marrow': [
    B('The performance ribbon carrying another name','house-of-velvet-oaths','Nessa finds her performance ribbon tagged with another worker’s name after a costume handoff.','She corrects it before the show and keeps each person’s choices separate.','consent'),
    B('A basilica donor demanding a private performance','house-of-velvet-oaths','Nessa hears a donor claim a charitable gift entitles them to her private time.','She refuses the claim and asks the house to state the boundary clearly.','consent','checks what the priest actually promised','asks the High Flame for the donation terms'),
    B('The healer’s visit turned into a stage story','house-of-velvet-oaths','Nessa sees a show note use a worker’s private infirmary visit as a dramatic backstory.','She removes it before the worker must explain personal care in public.','privacy','checks what the healer can disclose','asks the hatchery keeper whether a similarly named person caused confusion','asks the archivist to remove a copied handout'),
  ],
};
export const participantOverrides = {
  'An answer drafted before the question arrives': ['prince-lucien-vaelorian','queen-maerra-vaelorian'],
  'A worker’s demonstration booked by someone else': ['sabine-silk-veyl','sable-wren'],
};

export const sharedBriefs = [
  S('queen-maerra-vaelorian',['prince-lucien-vaelorian'],'The crown petition with two hearing dates','crownspire','Maerra finds a petition assigned two hearing dates in separate royal notices.','She asks the petitioners which notice they received before choosing a time.','governance','retrieves his office’s original dispatch and the signed change'),
  S('prince-lucien-vaelorian',['princess-maris-vaelorian'],'The petition answer never delivered','crownspire','Lucien finds a completed answer in the petition office but no delivery mark.','He sends it with a reliable receipt rather than calling the petitioner unresponsive.','records','checks the household address and messenger book'),
  S('princess-maris-vaelorian',['queen-maerra-vaelorian'],'A household petition read as a state appeal','crownspire','Maris sees a household repair request placed on the queen’s state appeal agenda.','She redirects it without losing the request’s place in line.','governance','checks whether the hearing agenda has already been announced'),
  S('king-edric-thornwall',['lady-rowena-thornwall'],'The winter bridge opened before inspection','black-march','Edric receives a report calling a winter bridge open while the road keeper’s inspection is still underway.','He waits for the signed condition report before sending wagons.','safety','records which planks still need testing'),
  S('lady-rowena-thornwall',['lord-halric-thornwall'],'The marching order without a return road','black-march','Rowena finds a marching order show an outbound route but no safe return after rain.','She asks for a complete plan before troops leave.','roads','checks which units must return before dark'),
  S('lord-halric-thornwall',['princess-elara-thornwall'],'The relief escort missing the relief cart','thornwall-keep','Halric sees an escort roster prepared for a relief run whose food cart never reached the yard.','He checks the cargo before moving soldiers.','logistics','traces the cart’s delayed household supplies'),
  S('princess-elara-thornwall',['lady-rowena-thornwall'],'Blankets sent to a closed pass','thornwall-keep','Elara finds a relief cart directed through a pass closed since the night before.','She changes the route and warns waiting households of the delay.','care','finds an open road that can bear the cart'),
  S('queen-selene-ravaryn',['prince-aurel-ravaryn'],'The harbor welcome with no sailors invited','drowned-crown-palace','Selene sees a public welcome name visiting captains but omit the crews who sailed them in.','She changes the meal count and invitation wording.','care','checks how many sailors are actually ashore'),
  S('prince-aurel-ravaryn',['admiral-nyra-greymere'],'The patrol chart copied from last tide','ashen-docks','Aurel finds a patrol chart show yesterday’s tide window beneath today’s date.','He asks for a fresh reading before ships move.','navigation','marks the deep-water channel on the current chart'),
  S('admiral-nyra-greymere',['lord-cassian-greymere'],'The treaty berth that cannot hold its ship','greymere-shipyard','Nyra sees a treaty welcome assign a deep-draft ship to a shallow berth.','She proposes a usable arrival point before the delegation sails.','navigation','checks the treaty’s berth clause and visiting notice'),
  S('dame-ysabet-rooke',['lady-isolde-morcant'],'The guard alert with one unnamed witness','crownspire','Ysabet receives a guard alert described as corroborated though only one unnamed witness appears in its source chain.','She limits action to verification, not punishment.','evidence','traces the repeated report to its first source'),
  S('lady-isolde-morcant',['dame-ysabet-rooke'],'A chamber key blamed on the nearest servant','red-ledger-exchange','Isolde sees a missing chamber key blamed on the servant last seen in the corridor.','She asks for an access log before the rumor becomes a charge.','fairness','checks who signed out the spare key'),
  S('lord-cassian-greymere',['duchess-mirelle-greymere'],'The shipyard clause with an unpaid crew','greymere-shipyard','Cassian reads a coastal agreement fund a new berth while omitting wages for the crew building it.','He adds the cost before the duchess signs.','labor','checks the yard’s actual crew hours and payment terms'),
  S('duchess-mirelle-greymere',['bastian-crow'],'The launch plank taken from a repair','greymere-shipyard','Mirelle finds a launch platform built with planks reserved to repair a working ship.','She orders proper materials rather than leaving the repair short.','resources','lists the ship’s actual repair deadline'),
  S('bastian-crow',['captain-seraphine-vale'],'The trial sail listed as courier service','greymere-shipyard','Bastian finds a hull trial entered on a courier schedule as ordinary paid passage.','He marks the boat test-only until it earns clearance.','safety','checks which courier cargo needs another vessel'),
  S('captain-seraphine-vale',['kael-dravos'],'The sealed cargo without a receiver','ashen-docks','Seraphine reaches the docks with sealed cargo whose manifest names no receiving person.','She holds it aboard until a legal handoff is named.','logistics','checks whether his vessel’s freight mark was copied'),
  S('kael-dravos',['orla-saye'],'The privateer sail after the light changes','saint-orlas-lighthouse','Kael plans a departure around a familiar lighthouse pattern and learns the signal changed that morning.','He waits for the valid code before leaving the channel.','navigation','repeats the safe signal and its meaning'),
  S('idris-salt',['captain-seraphine-vale'],'The prison food crate without a count','tidevault-prison','Idris receives a food crate whose manifest lists a full load but feels much lighter.','He opens it with a witness before signing delivery.','care','checks what left the captain’s hold'),
  S('orla-saye',['rorik-pell'],'A storm signal mistaken for a meeting light','saint-orlas-lighthouse','Orla sees a storm warning repeated by a harbor runner as if it were a routine meeting signal.','She corrects the meaning before vessels enter rough water.','communications','changes the runner board at the docks'),
  S('rorik-pell',['delphine-lantern'],'The harbor guest led to the locked door','lantern-rooms','Rorik finds the lodging guide point arriving guests to a locked service door after dark.','He posts the open entrance before the ferry lands.','access','checks which guest rooms are actually ready'),
  S('delphine-lantern',['liora-saintless'],'The two inns holding one bed','lantern-rooms','Delphine discovers two inns each hold a bed for the same traveler while another person sleeps outside.','She confirms the traveler’s plan and releases one bed fairly.','hospitality','checks whether the traveler requested privacy or a late arrival'),
  S('sabine-silk-veyl',['sable-wren'],'The private booking without a worker’s yes','house-of-velvet-oaths','Sabine finds a private booking listed as confirmed before the worker was asked.','She cancels the promise until the worker chooses.','consent','states whether she wants the booking at all'),
  S('sable-wren',['nessa-honeybell-marrow'],'The costume case with mixed ribbons','house-of-velvet-oaths','Sable opens a costume case and finds the ribbons for two different performances mixed together.','She checks each performer’s chosen act before stage setup.','consent','sorts her own agreed ribbons and leaves the rest untouched'),
  S('celessa-vane',['vespera-saan'],'The diplomatic gesture printed as an obligation','crimson-veil','Celessa sees a visitor guide describe an optional ritual gesture as an obligation.','She rewrites it before guests feel compelled to perform.','diplomacy','explains how the ritual can be declined gracefully'),
  S('vespera-saan',['celessa-vane'],'The tutor lesson without a translator','crimson-veil','Vespera finds an advanced ritual lesson booked for visitors who have not received its language explanation.','She postpones the demonstration until choice is informed.','consent','offers a clear translation of the lesson terms'),
  S('liora-saintless',['delphine-lantern'],'A chosen name lost between lodging ledgers','saintless-house','Liora sees a lodging transfer use an old name a traveler asked staff to stop using.','She corrects the transfer and limits who can see the older record.','privacy','checks her receiving ledger and the traveler’s current choice'),
  S('asha-ren',['nia-chainbreaker'],'The relief cart whose axle is not ready','cinder-camp','Asha sees a relief cart loaded while its axle repair remains untested.','She holds departure and tells waiting households the real reason.','safety','tests the axle and lists what parts still need fitting'),
  S('duchess-aveline-edevane',['lord-rowan-edevane'],'The forest harvest path through a young grove','verdant-reach','Aveline receives a harvest plan whose shortest cart path crosses young trees planted for stream protection.','She asks for a slower route that preserves the grove.','stewardship','maps the viable wagon track'),
  S('lord-rowan-edevane',['freya-hart'],'The scout path that became a tourist trail','green-hart-lodge','Rowan finds a scout path copied into a public travel map without any safety check.','He removes it from the public route list.','safety','marks the dangerous crossing and a real alternative'),
  S('joren-ash',['torren-bale'],'The courier letter at an empty inn','broken-spur-tavern','Joren reaches an inn with a letter for someone who has already left the district.','He keeps it sealed and asks for a lawful forwarding route.','privacy','checks what forwarding address the traveler consented to leave'),
  S('brina-forgehand',['nia-chainbreaker'],'The forge batch issued before its test','ironwake-foundry','Brina sees newly forged bolts marked available to the camp before their stress test.','She stops delivery until the batch passes.','craft','updates the quartermaster board so nobody relies on them'),
  S('nia-chainbreaker',['malrec-vale'],'The ration receipt signed without a count','cinder-camp','Nia finds a ration receipt signed complete though the sacks remain stacked unopened.','She calls for a witnessed count.','records','checks the signed copy against the actual delivery note'),
  S('sera-blackvein',['brina-forgehand'],'The mine air shaft used as an ore chute','deepnail-mines','Sera finds ore diverted through a shaft that workers still need for air.','She stops the shortcut and asks for another route.','safety','calculates a workable forge delivery schedule'),
  S('torren-bale',['lyssa-bramble'],'The tavern set promised past closing','broken-spur-tavern','Torren sees a music set advertised beyond the inn’s closing shift.','He offers a paid earlier hour rather than assume the musician will work free.','labor','checks when the band can travel from the forest'),
  S('lyssa-bramble',['catrin-brann'],'The melody copied into a soldiers’ march','briar-and-cup','Lyssa hears a tune she and Catrin arranged together advertised as a traditional army march.','She asks for correct credit before another public performance.','music','shows the dated second-fiddle arrangement'),
  S('freya-hart',['lord-rowan-edevane'],'The hunter’s gate marked as a public exit','green-hart-lodge','Freya finds a gate used for hunters’ work labeled as a safe public exit though it opens into active training ground.','She changes the sign and route.','safety','checks the border map for a public exit'),
  S('malrec-vale',['joren-ash'],'The message copied with one word changed','cinder-camp','Malrec compares a courier’s original message with a copied notice and finds one word changes the delivery date.','He corrects the notice before accusing the courier.','records','shows the sealed original and the handoff time'),
  S('maeve-redreed',['catrin-brann'],'The evening set without the second fiddle','house-red-reeds','Maeve notices a show poster credit a lead performer but omit Catrin’s second fiddle and fee.','She corrects both before the doors open.','labor','checks the rehearsal and agreed payment'),
  S('catrin-brann',['lyssa-bramble'],'The tavern reel played under the wrong title','house-red-reeds','Catrin hears a tavern reel she learned from Lyssa introduced under an unrelated family’s name.','She asks where the title came from before repeating it.','culture','checks her own songbook and the earliest singer she knows'),
  S('brother-aldren',['sister-mercy-voss'],'The sanctuary guest needing care, not a sermon','ash-mother-infirmary','Aldren brings an exhausted sanctuary guest to the infirmary after others urged the person to rest in prayer alone.','He leaves the medical decisions with the patient and healer.','care','checks the guest’s immediate needs and consent'),
  S('high-flame-elowen-orison',['nerys-rowanleaf'],'The doctrine page in two different copies','basilica-seven-flames','Elowen finds two public copies of one doctrine page with a sentence placed differently.','She records both versions before declaring either authoritative.','history','traces the archive’s copy dates and damage'),
  S('sister-mercy-voss',['mara-sable'],'The healer’s kit borrowed for arena night','ash-mother-infirmary','Mercy discovers an infirmary kit loaned to the arena without a replacement ready for patients.','She asks for a return or stocked substitute before the next shift.','resources','checks which arena items were used and must be replenished'),
  S('ilyra-ashscale',['rhevan-crownsbane'],'The hatchling noise heard as a threat','caldera-hatchery','Ilyra hears a keeper call a hatchling’s new noise a threat after one unfamiliar feeding.','She observes the animal before changing its care.','animal-care','explains which similar calls he has heard and what remains uncertain'),
  S('rhevan-crownsbane',['petra-glass'],'The glass echo labeled dragon speech','glass-battlefield','Rhevan hears a battlefield echo displayed as a translation of dragon speech.','He asks for the audio and its context before endorsing words.','evidence','maps the surface that produced the echo'),
];
