import{Pressable,StyleSheet,Text,View}from'react-native';
import{router,useLocalSearchParams}from'expo-router';
import{Image}from'expo-image';
import{ArrowLeft,CalendarDays,MapPin,Sparkles}from'lucide-react-native';
import{cityLifeAsset}from'../../src/assets';
import{Body,EmptyState,GlassCard,GradientButton,LoadingSkeleton,MediaGallery,Screen,SectionHeader}from'../../src/components';
import{colors,radius}from'../../src/theme';
import{useTogether}from'../../src/store/useTogether';

export default function LocationDetail(){
  const{slug}=useLocalSearchParams<{slug:string}>();const snapshot=useTogether((state)=>state.snapshot);if(!snapshot)return <LoadingSkeleton/>;
  const location=snapshot.locations.find((item)=>item.slug===slug);if(!location)return <EmptyState title="Place unavailable" body="This corner of Juniper City is not available right now." action="Back to World" onAction={()=>router.replace('/(tabs)/worlds')}/>;
  const people=snapshot.characters.filter((item)=>item.current_location_id===location.id),active=snapshot.characters.find((item)=>item.id===snapshot.profile?.active_companion_instance_id),dates=snapshot.dates.filter((item)=>item.together_date_templates.location_id===location.id),events=snapshot.lifeEvents.filter((item)=>item.location_id===location.id).slice(0,3),moments=snapshot.moments.filter((item)=>item.location_id===location.id).slice(0,3),photos=(snapshot.generatedMedia??[]).filter((item)=>item.location_id===location.id),hero=photos.find((item)=>item.status==='ready'&&item.signed_url),upcoming=(snapshot.sharedPlans??[]).filter((plan)=>plan.location_id===location.id&&plan.status==='scheduled'&&new Date(plan.starts_at)>new Date()).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime())[0];
  return <Screen><View style={styles.header}><Pressable accessibilityLabel="Back to World" onPress={()=>router.canGoBack()?router.back():router.replace('/(tabs)/worlds')} style={styles.back}><ArrowLeft size={19} color={colors.text}/></Pressable><Text style={styles.kicker}>{location.category.toUpperCase()}</Text></View><Image source={hero?.signed_url?{uri:hero.signed_url}:cityLifeAsset} style={styles.hero} contentFit="cover"/><Text style={styles.title}>{location.name}</Text><Body muted>{location.description}</Body>
    {upcoming?<Pressable onPress={()=>router.push(`/plan/${upcoming.id}` as never)} style={styles.upcoming}><CalendarDays size={18} color={colors.rose}/><View style={{flex:1}}><Text style={styles.upcomingKicker}>COMING UP</Text><Text style={styles.rowTitle}>{upcoming.title}</Text><Text style={styles.rowCopy}>{new Date(upcoming.starts_at).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</Text></View></Pressable>:null}
    <View style={styles.actions}><GradientButton label={`Plan something here${active?` with ${active.together_character_templates.name}`:''}`} onPress={()=>router.push(`/(tabs)/chat-tab?plan=1&location=${location.slug}` as never)}/><Pressable style={styles.ask} onPress={()=>router.push(`/(tabs)/chat-tab?draft=${encodeURIComponent(`What do you think about ${location.name}?`)}` as never)}><Text style={styles.askText}>Ask about this place</Text></Pressable></View>
    {photos.length?<><SectionHeader title={`From ${location.name}`}/><MediaGallery media={photos}/></>:null}{people.length?<><SectionHeader title="Who’s here"/><GlassCard style={styles.list}>{people.map((person)=><Pressable key={person.id} onPress={()=>router.push(`/character/${person.together_character_templates.slug}` as never)} style={styles.row}><MapPin size={17} color={colors.rose}/><View style={{flex:1}}><Text style={styles.rowTitle}>{person.together_character_templates.name}</Text><Text style={styles.rowCopy}>{person.current_activity}</Text></View></Pressable>)}</GlassCard></>:null}
    <SectionHeader title="Things to do"/><GlassCard style={styles.list}>{location.possible_activities.slice(0,8).map((activity)=><Pressable key={activity} onPress={()=>router.push(`/(tabs)/chat-tab?draft=${encodeURIComponent(`Want to ${activity} at ${location.name}?`)}` as never)} style={styles.row}><Sparkles size={16} color={colors.violet}/><Text style={styles.rowTitle}>{activity}</Text></Pressable>)}</GlassCard>
    {dates.length?<><SectionHeader title="Dates here"/><GlassCard style={styles.list}>{dates.map((date)=>{const locked=date.status==='locked';return <Pressable key={date.id} disabled={locked} onPress={()=>router.push(`/date/${date.id}` as never)} style={[styles.row,locked&&{opacity:.55}]}><CalendarDays size={16} color={colors.warm}/><View><Text style={styles.rowTitle}>{date.together_date_templates.name}</Text><Text style={styles.rowCopy}>{locked?'Grow closer to unlock':'Available now'}</Text></View></Pressable>})}</GlassCard></>:null}
    {events.length?<><SectionHeader title="Recent activity"/><GlassCard style={styles.list}>{events.map((event)=><View key={event.id} style={styles.row}><Text style={styles.rowTitle}>{event.title}</Text></View>)}</GlassCard></>:null}{moments.length?<><SectionHeader title="Shared moments"/><GlassCard style={styles.list}>{moments.map((moment)=><Pressable key={moment.id} onPress={()=>router.push(`/moment/${moment.id}` as never)} style={styles.row}><Text style={styles.rowTitle}>{moment.title}</Text></Pressable>)}</GlassCard></>:null}
  </Screen>;
}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:40,height:40,borderRadius:20,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border},kicker:{color:colors.rose,fontWeight:'900',fontSize:10,letterSpacing:1.2},hero:{height:270,width:'100%',borderRadius:radius.xl},title:{color:colors.text,fontFamily:'Georgia',fontSize:36},actions:{gap:9},ask:{minHeight:50,alignItems:'center',justifyContent:'center',borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},askText:{color:colors.text,fontWeight:'800'},upcoming:{flexDirection:'row',alignItems:'center',gap:11,padding:14,borderRadius:radius.lg,backgroundColor:'rgba(241,103,154,.08)',borderWidth:1,borderColor:'rgba(241,103,154,.22)'},upcomingKicker:{color:colors.rose,fontSize:9,fontWeight:'900',letterSpacing:1.1},list:{paddingVertical:4},row:{minHeight:48,flexDirection:'row',alignItems:'center',gap:10,padding:10},rowTitle:{color:colors.text,fontWeight:'800',fontSize:13,textTransform:'capitalize'},rowCopy:{color:colors.muted,fontSize:11,marginTop:2}});
