import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Image } from 'expo-image';
import { ArrowLeft, CalendarDays, MapPin, Sparkles } from 'lucide-react-native';
import { cityLifeAsset } from '../../src/assets';
import { Body, EmptyState, GlassCard, LoadingSkeleton, MediaGallery, Screen, SectionHeader } from '../../src/components';
import { colors, radius } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';

export default function LocationDetail(){
  const{slug}=useLocalSearchParams<{slug:string}>();const snapshot=useTogether((state)=>state.snapshot);
  if(!snapshot)return <LoadingSkeleton/>;
  const location=snapshot.locations.find((item)=>item.slug===slug);
  if(!location)return <EmptyState title="Place unavailable" body="This corner of the city is not available right now." action="Back to World" onAction={()=>router.replace('/(tabs)/worlds')}/>;
  const people=snapshot.characters.filter((character)=>character.current_location_id===location.id);const dates=snapshot.dates.filter((date)=>date.together_date_templates.location_id===location.id);const events=snapshot.lifeEvents.filter((event)=>event.location_id===location.id).slice(0,3);const moments=snapshot.moments.filter((moment)=>moment.location_id===location.id).slice(0,3);const photos=(snapshot.generatedMedia??[]).filter((item)=>item.location_id===location.id);
  return <Screen><View style={styles.header}><Pressable accessibilityLabel="Back to World" onPress={()=>router.back()} style={styles.back}><ArrowLeft size={19} color={colors.text}/></Pressable><Text style={styles.kicker}>{location.category.toUpperCase()}</Text></View><Image source={cityLifeAsset} style={styles.hero} contentFit="cover" contentPosition="center"/><Text style={styles.title}>{location.name}</Text><SectionHeader title="About"/><Body muted>{location.description}</Body>{photos.length?<><SectionHeader title={`From ${location.name}`}/><MediaGallery media={photos}/></>:null}{people.length?<><SectionHeader title="Right now"/><GlassCard style={styles.list}>{people.map((person)=><Pressable key={person.id} onPress={()=>router.push(`/character/${person.together_character_templates.slug}` as never)} style={styles.row}><MapPin size={17} color={colors.rose}/><View style={{flex:1}}><Text style={styles.rowTitle}>{person.together_character_templates.name} is here</Text><Text style={styles.rowCopy}>{person.current_activity}</Text></View></Pressable>)}</GlassCard></>:null}<SectionHeader title="Things that happen here"/><GlassCard style={styles.list}>{location.possible_activities.slice(0,4).map((activity)=><View key={activity} style={styles.row}><Sparkles size={16} color={colors.violet}/><Text style={styles.rowTitle}>{activity}</Text></View>)}</GlassCard>{dates.length?<><SectionHeader title="Dates here"/><GlassCard style={styles.list}>{dates.map((date)=><Pressable key={date.id} onPress={()=>router.push(`/date/${date.id}` as never)} style={styles.row}><CalendarDays size={16} color={colors.warm}/><Text style={styles.rowTitle}>{date.together_date_templates.name}</Text></Pressable>)}</GlassCard></>:null}{events.length?<><SectionHeader title="Recent activity"/><GlassCard style={styles.list}>{events.map((event)=><View key={event.id} style={styles.row}><Text style={styles.rowTitle}>{event.title}</Text></View>)}</GlassCard></>:null}{moments.length?<><SectionHeader title="Recent Moments"/><GlassCard style={styles.list}>{moments.map((moment)=><Pressable key={moment.id} onPress={()=>router.push(`/moment/${moment.id}` as never)} style={styles.row}><Text style={styles.rowTitle}>{moment.title}</Text></Pressable>)}</GlassCard></>:null}</Screen>;
}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:40,height:40,borderRadius:20,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border},kicker:{color:colors.rose,fontWeight:'900',fontSize:10,letterSpacing:1.2},hero:{height:250,width:'100%',borderRadius:radius.xl},title:{color:colors.text,fontFamily:'Georgia',fontSize:34},list:{paddingVertical:4},row:{minHeight:46,flexDirection:'row',alignItems:'center',gap:10,padding:10},rowTitle:{color:colors.text,fontWeight:'800',fontSize:13},rowCopy:{color:colors.muted,fontSize:11,marginTop:2}});
