import { defineNewcomerPack } from './define.mjs';
const C = [
  [
    ['annalise-chen','Portraitist','compares the image permission on the plate with the promise given to its subject'],
    ['belle-sutter','Red Sash performer','checks whether a named worker actually accepted the booking being advertised'],
    ['honey-vale','Baths attendant','protects the changing-room register from being used as a list of private guests'],
    ['wren-keene','Printmaker','shows which copies can still be stopped before a plate reaches the market'],
  ],
  [
    ['faye-mercer','Saloon worker','asks whose shift and wages will be affected by the proposed change'],
    ['josie-duarte','Lantern Row worker','checks whether a claimed appointment came from the person named on it'],
    ['ruby-fenwick','Ribbon Room dancer','checks the performer’s terms against the ticket printed for customers'],
    ['trixie-kincaid','Dance-hall performer','compares the manager’s promise with the hours posted for the floor'],
  ],
  [
    ['birdie-quade','Card-room lookout','identifies who was actually in the room when the disputed account was heard'],
    ['burke-halden','Court clerk','checks whether the paper carries the required signature and date'],
    ['deacon-crowell','Chapel deacon','asks the affected family before a private possession is treated as public property'],
    ['jed-quade','Card-room worker','keeps the original account separate from rumor passed between tables'],
  ],
  [
    ['finn-booker','Rail worker','compares the company order with the names on the shift roster'],
    ['minnie-whitcomb','Rancher','marks the route or boundary that a distant decision has overlooked'],
    ['rhett-avery','Card player','tests whether the proposed game rule gives one player a hidden advantage'],
    ['wes-archer','Ferryman','checks the crossing log against what could really fit on the boat'],
  ],
  [
    ['etta-soto','Forge owner','checks whose name is on the tool order before the iron is worked'],
    ['hank-soto','Forge hand','tests the material and records which part of a repair is actually safe'],
    ['marigold-vale','House worker','asks who consented before a private booking becomes a public promise'],
    ['violet-wynn','Night-kitchen cook','checks the ingredient and meal account before anyone serves it'],
  ],
];
const B = [
  ['annalise-chen','A portrait ordered by a stranger','calder-portrait-studio','Annalise receives payment for a portrait of a dance-hall worker who has never sat for her or agreed to a print.','She returns the deposit and asks the buyer how the worker’s likeness was obtained before the image travels farther.','art'],
  ['annalise-chen','The plate with two signatures','keenes-print-shop','Annalise finds her portrait plate signed by a printer who prepared it but never photographed its subject.','She and the printer must decide how to credit both kinds of work without implying the subject approved publication.','rights'],
  ['belle-sutter','The lesson that booked her nights','red-sash-brothel','Belle sees a regular’s receipt for private lessons that would claim every night she has already agreed to work.','She asks the house to void the invented schedule and tell the customer what Belle actually offers.','work'],
  ['belle-sutter','A sash left at the laundry','public-washhouse','Belle’s unmistakable red sash is hung where any customer can claim it after a washhouse ticket is smudged.','She retrieves it with the attendant and asks for a safer handoff that does not announce her day off to everyone.','privacy'],
  ['honey-vale','The bathhouse camera request','blue-glass-baths','Honey receives a guest’s request to photograph other bathers as if admission included their permission.','She keeps the camera outside the bathing rooms and offers a scheduled portrait hour with explicit consent instead.','privacy'],
  ['honey-vale','A towel count after closing','blue-glass-baths','Honey finds the bathhouse towel count short by six although every guest ticket was returned before closing.','She checks the laundry exchange before accusing a bather of taking supplies that may never have reached the room.','work'],
  ['wren-keene','A face pasted onto the wrong plate','keenes-print-shop','Wren catches a customer trying to pair a living dancer’s face with a print she did not sit for.','He stops the press and asks who supplied the image before deciding whether the original negative must also be returned.','rights'],
  ['wren-keene','The wanted notice with an old scar','keenes-print-shop','Wren receives a wanted notice drawn from a years-old description whose distinctive scar has since healed.','He asks the marshal for a corrected likeness rather than printing a clue that could identify the wrong traveler.','civic'],
  ['faye-mercer','A favor hidden in the saloon rota','copper-mare-saloon','Faye notices a manager has assigned a colleague to escort a drunk guest after closing without asking her.','She changes the rota only after the colleague chooses whether to take that shift and how to get home safely.','work'],
  ['faye-mercer','The tab charged to the wrong saddle','copper-mare-saloon','Faye finds a late-night saloon tab posted to a ranch hand who left before the drinks were ordered.','She keeps the original ticket and asks the server on duty to identify the actual party before collecting.','records'],
  ['josie-duarte','A civic account in her name','marigold-house','Josie learns that a town official opened a standing entertainment account listing her without her consent.','She asks the clerk to cancel it while preserving the entry long enough to show how the false charge was approved.','boundaries'],
  ['josie-duarte','The lantern ticket with no room','marigold-house','Josie receives a numbered appointment ticket for a room that has been closed for repairs all week.','She traces the ticket before anyone can claim she missed a meeting she never could have attended.','work'],
  ['ruby-fenwick','An overnight pass sold at the show','ribbon-room','Ruby sees a show ticket promising an overnight visit to an address she never shared with the venue.','She has the ticket withdrawn and asks whether the address came from a staff record or a customer.','privacy'],
  ['ruby-fenwick','The bow that covered another dancer','bellflower-theater','Ruby watches applause for a duet credited only to her because the printed program lost her partner’s name.','She asks the theater to correct the next program and introduces her partner before the second performance.','performance'],
  ['trixie-kincaid','The hall account that named a person','junebug-dance-hall','Trixie finds a business account that lists her as a standing benefit rather than an employee paid for booked hours.','She demands a revised invoice that sells the hall’s services without promising her personal time.','work'],
  ['trixie-kincaid','A lost shoe before the first set','junebug-dance-hall','Trixie finds one performance shoe missing and a replacement pair that would catch on the hall’s rough floor.','She delays the opening set and gives the crowd an honest start time while the floor and shoe are checked.','performance'],
  ['birdie-quade','The card player omitted from the table','argosy-cardroom','Birdie sees a payoff story repeated with one player’s name missing from the card-room seating sheet.','She saves the original seating book and asks the player what they actually witnessed before the rumor hardens.','evidence'],
  ['birdie-quade','A lookout shift recorded twice','argosy-cardroom','Birdie discovers two lookout payments written for the same hour and the same doorway, though only one person stood there.','She asks who authorized the second payment before the book is used to accuse an absent worker.','records'],
  ['burke-halden','The sentence with no hearing date','county-courthouse','Burke is handed a sentence form dated earlier than the hearing scheduled on the court board.','He refuses to file it and requests the hearing record that would justify any order under his seal.','civic'],
  ['burke-halden','A copy stamped as an original','county-courthouse','Burke catches an unsigned copy of a land petition wearing the court’s original-file stamp.','He separates the papers and asks the petitioners which version they actually submitted before the property vote.','records'],
  ['deacon-crowell','A grave opened for a borrowed plate','canyon-rest-cemetery','Deacon receives a request to open a family grave for a portrait plate the requester cannot prove belongs to them.','He delays the work until the living family and the cemetery register agree on who may reclaim the object.','family'],
  ['deacon-crowell','The chapel box without a donor','riverside-chapel','Deacon finds a small cash box left for funeral costs with no note identifying the intended household.','He asks the chapel trustees to record the gift without guessing which grieving family should accept it.','community'],
  ['jed-quade','The wager read from a torn ticket','argosy-cardroom','Jed sees a disputed card wager argued from half a ticket while the other half is still under the dealer’s tray.','He preserves both pieces and asks the table to replay the rule before paying either side.','game'],
  ['jed-quade','A quiet warning at the cardroom door','argosy-cardroom','Jed hears that a card player has been barred, but the notice carries another player’s description.','He asks for a corrected notice before the wrong traveler is turned away by a night lookout.','fairness'],
  ['finn-booker','The rail removal order without a name','railroad-freight-office','Finn receives an order to remove a striker from the rail yard without a name or any stated safety reason.','He asks the company to put its actual instruction in writing before shifting a crew into a confrontation.','labor'],
  ['finn-booker','The caboose booked for two crews','temporary-passenger-depot','Finn finds a rail car assigned to two maintenance crews who start from opposite ends of the line.','He stops the departure board until dispatch can show which crew has the car and where the other will sleep.','work'],
  ['minnie-whitcomb','A ranch boundary drawn at dusk','whitcomb-ranch','Minnie spots a new fence stake set inside the pasture she agreed to share for the autumn drive.','She calls the neighboring household to walk the boundary in daylight before anyone moves cattle across it.','land'],
  ['minnie-whitcomb','The rustler notice that named a child','river-market','Minnie sees a market notice naming a young stable hand as a rustler on the strength of an unverified brand mark.','She asks the seller to take it down until the brand book and the hand’s account can be checked.','fairness'],
  ['rhett-avery','A charity deck with two backs','argosy-cardroom','Rhett notices a charity-night card deck has two slightly different back patterns mixed together.','He calls for a fresh deck and asks who packed the cards rather than letting the fundraiser end in accusations.','game'],
  ['rhett-avery','The prize written in pencil','argosy-cardroom','Rhett sees a tournament prize changed in pencil after players have already paid their entry fees.','He asks the organizer to post the original terms and offer refunds before another hand is dealt.','fairness'],
  ['wes-archer','A ferry manifest with no passenger','pikes-ferry','Wes receives a crossing manifest listing a passenger who never boarded his ferry that morning.','He checks both banks and keeps the passenger’s place unclaimed until the ticket office corrects its count.','travel'],
  ['wes-archer','The crate left on the wrong bank','pikes-ferry','Wes finds a medicine crate marked delivered although it is still waiting beside the ferry rope.','He alerts the clinic and records the delay before anyone assumes its contents reached a patient.','work'],
  ['etta-soto','A blade ordered under a dead name','soto-forge','Etta receives a tool order signed with her late husband’s shop mark although the customer never met him.','She asks who issued the mark and refuses to let a memorial signature become standing permission for new work.','craft'],
  ['etta-soto','The knife whose handle split','soto-forge','Etta discovers a demonstration knife’s handle has a hairline split hidden beneath a decorative wrap.','She pulls the knife from sale and teaches an apprentice how to test the repaired handle before returning it.','safety'],
  ['hank-soto','The iron order with no maker','soto-forge','Hank finds an off-book iron order that omits the craftsperson who would actually forge the piece.','He refuses to promise a finished tool until the workshop can price the labor and identify its intended use.','work'],
  ['hank-soto','A hinge for the bathhouse gate','blue-glass-baths','Hank delivers a replacement hinge that fits the bathhouse gate but leaves the privacy latch too easy to lift.','He takes it back for adjustment before calling the repair complete on the invoice.','repair'],
  ['marigold-vale','A calendar sold by the room','marigold-house','Marigold finds a guest has been promised every opening on her calendar without asking her which nights she works.','She has the house return the deposit and draw a booking rule that belongs to workers as well as customers.','boundaries'],
  ['marigold-vale','The flower note with no sender','marigold-house','Marigold receives a bouquet with an invitation attached but no sender named on the delivery book.','She keeps the flowers in the shared room and asks for an identified answer path before accepting any appointment.','privacy'],
  ['violet-wynn','The supper ingredient no one named','night-kitchen','Violet is asked to add an unlabelled powder to a worker’s supper after the kitchen has already prepared the meal.','She sets the packet aside and asks the requester to identify it before any plate leaves the counter.','food'],
  ['violet-wynn','A recipe returned without the margin','night-kitchen','Violet borrows a cook’s handwritten recipe and receives it back with the temperature note torn away.','She tests a small batch and asks the lender for the missing instruction instead of serving a guessed version to guests.','craft'],
];
export const { worldIntroduction, groups, leadRoles, supportRoles, contributions, incidents } = defineNewcomerPack(
  "Calder's Run is a frontier town where rail, ranch, river, and entertainment work share a small civic ledger.", C, B);
