import{describe,expect,it}from'vitest';
import{advanceDate,applyRelationshipProposal,automaticPhotoAllowed,characterKnows,chooseDailyContent,classifyPhotoIntent,composeProactiveMessage,contentConditionsPass,datePhases,defaultRelationship,extractMemoryCandidates,extractOpenThreads,firstDateEligibility,isQuietHours,mediaCapabilityAllowed,mergeMemory,nextRelationshipMilestone,nextStoryArcChapter,relationshipCue,resolveAnsweredThreads,resolveCharacterState,shouldInitiateMessage,shouldMaterializeLifeEvents,simulateContentMonth,simulateSince,startDate,summarizeConversation,transferKnowledge,transitionStage,trustedImagePrompt,updateThreadEligibility,validateContentPack,type RichLifeEventTemplate,type StoryArcTemplate}from'../src';

describe('Together domain',()=>{
  it('clamps relationship changes and prevents skipped stages',()=>{const next=applyRelationshipProposal(defaultRelationship,{trust:99,conflict:-99},'ordinary_chat');expect(next.trust).toBe(10);expect(next.conflict).toBe(0);expect(()=>transitionStage(defaultRelationship,'friend')).toThrow();expect(transitionStage(defaultRelationship,'acquaintance').stage).toBe('acquaintance');});
  it('unlocks the first date only after controlled progression',()=>{expect(firstDateEligibility(defaultRelationship).eligible).toBe(false);expect(firstDateEligibility({...defaultRelationship,stage:'flirting',familiarity:35,trust:34,attraction:32,conversationCount:6}).eligible).toBe(true);});
  it('proposes narrative milestones instead of silently skipping relationship stages',()=>{expect(nextRelationshipMilestone({...defaultRelationship,conversationCount:1})?.kind).toBe('keep_in_touch');expect(nextRelationshipMilestone({...defaultRelationship,stage:'friend',conversationCount:8,attraction:20,comfort:20})?.kind).toBe('romantic_spark');expect(nextRelationshipMilestone({...defaultRelationship,stage:'flirting',conversationCount:8,familiarity:35,trust:34,attraction:32})?.kind).toBe('first_date_invitation');});
  it('prioritizes repair over romantic progression and exposes qualitative cues',()=>{const tense={...defaultRelationship,stage:'flirting' as const,conversationCount:12,familiarity:40,trust:35,attraction:40,conflict:52};expect(nextRelationshipMilestone(tense)?.kind).toBe('repair');expect(relationshipCue(tense).tone).toBe('tense');expect(relationshipCue({...defaultRelationship,stage:'flirting'}).label).toContain('spark');});
  it('extracts and reinforces Cooper without duplicates',()=>{const candidate=extractMemoryCandidates("My dog's name is Cooper.")[0]!;expect(candidate.canonicalText).toBe("User's dog is named Cooper.");const first=mergeMemory(undefined,candidate,'2026-08-10T00:00:00Z');const reinforced=mergeMemory(first,candidate,'2026-08-11T00:00:00Z');expect(reinforced.id).toBe(first.id);expect(reinforced.confidence).toBeGreaterThan(first.confidence);});
  it('corrects a stable fact without keeping two active versions',()=>{const cooper=extractMemoryCandidates("My dog's name is Cooper.")[0]!;const luna=extractMemoryCandidates("Actually, my dog's name is Luna.")[0]!;expect(luna.subjectKey).toBe(cooper.subjectKey);const corrected=mergeMemory(mergeMemory(undefined,cooper),luna,'2026-08-12T00:00:00Z');expect(corrected.canonicalText).toBe("User's dog is named Luna.");expect(corrected.metadata?.['previousText']).toBe("User's dog is named Cooper.");});
  it('stores olives as a preference without making it a random life event',()=>{const [candidate]=extractMemoryCandidates('I hate olives.');expect(candidate?.type).toBe('preference');expect(candidate?.canonicalText).toBe('User dislikes olives.');});
  it('updates a preference when the user changes their mind',()=>{const before=extractMemoryCandidates('I hate olives.')[0]!;const after=extractMemoryCandidates("I don't hate olives anymore.")[0]!;expect(after.subjectKey).toBe(before.subjectKey);expect(after.canonicalText).toBe('User no longer dislikes olives.');});
  it('creates, deduplicates, and resolves the Friday presentation thread by topic',()=>{const [thread]=extractOpenThreads('I have a huge presentation Friday.',new Date('2026-08-10T12:00:00Z'));expect(thread?.expectedAt).toContain('2026-08-14');const eligible=updateThreadEligibility(thread!,new Date('2026-08-14T12:01:00Z'));expect(eligible.followUpEligible).toBe(true);expect(resolveAnsweredThreads([eligible],'My presentation went really well!')[0]?.resolvedAt).toBeTruthy();expect(resolveAnsweredThreads([eligible],'Dinner was great.')[0]?.resolvedAt).toBeFalsy();});
  it('builds a compact rolling conversation summary',()=>{const summary=summarizeConversation([{role:'user',content:'My dog is Cooper.'},{role:'assistant',content:'Cooper is a great name.'},{role:'user',content:'I have a presentation Friday.'}]);expect(summary).toContain('My dog is Cooper.');expect(summary).toContain('presentation Friday');expect(summary.length).toBeLessThanOrEqual(900);});
  it('resolves deterministic life state and caps lazy simulation',()=>{const state=resolveCharacterState([{dayOfWeek:1,startMinute:540,endMinute:1020,location:'Photography Studio',activity:'client shoot',availability:'busy',energyDelta:1}],new Date('2026-08-10T14:00:00'), 'maya-user-1');expect(state.location).toBe('Photography Studio');const events=simulateSince(new Date('2026-08-10T12:00:00Z'),new Date('2026-08-14T12:00:00Z'),[{id:'coffee',title:'Coffee with Chloe',type:'social',significance:.7,location:'Juniper Café',participants:['maya','chloe'],proactiveEligible:true,summary:'Maya caught up with Chloe.'}]);expect(events.length).toBeLessThanOrEqual(2);});
  it('honors quiet hours and proactive cooldowns',()=>{expect(isQuietHours(new Date('2026-08-14T03:00:00Z'),'23:00','08:00','UTC')).toBe(true);expect(isQuietHours(new Date('2026-08-14T16:00:00Z'),'23:00','08:00','UTC')).toBe(false);const event={id:'shoot',title:'Successful photo shoot',type:'work',significance:.76,location:'Studio',participants:['maya'],proactiveEligible:true,summary:'Maya finished a great shoot.'};expect(shouldInitiateMessage({event,hoursSinceConversation:24,hoursSinceProactive:3,quietHours:false,relationshipStage:'friend',seed:'yes'})).toBe(false);});
  it('materializes narrative events only when a conversation continues',()=>{expect(shouldMaterializeLifeEvents('conversation_continued')).toBe(true);expect(shouldMaterializeLifeEvents('home_opened')).toBe(false);expect(shouldMaterializeLifeEvents('scheduled_dispatch')).toBe(false);});
  it('writes natural event and open-thread messages without guilt',()=>{expect(composeProactiveMessage({eventTitle:'Successful photo shoot',relationshipStage:'friend'})).toContain('shoot');const followup=composeProactiveMessage({threadSubject:'presentation',relationshipStage:'friend'});expect(followup).toBe('Hey—how did your presentation go? You mentioned it was important.');expect(followup).not.toMatch(/ignore|lonely|miss me/i);});
  it('requires explicit knowledge transfer before Chloe knows',()=>{const fact={id:'fear',ownerInstanceId:'maya-instance',canonicalText:'User fears flying.',sensitivity:'personal' as const};expect(characterKnows(fact,'chloe-instance',[])).toBe(false);const transfer=transferKnowledge(fact,{fromInstanceId:'maya-instance',toInstanceId:'chloe-instance',eventId:'coffee',reason:'Maya shared it',allowSensitive:true,now:new Date('2026-08-12T10:00:00Z')});expect(characterKnows(fact,'chloe-instance',[transfer!])).toBe(true);});
  it('progresses the dinner date through every phase',()=>{let session=startDate('date-1');for(let index=1;index<datePhases.length;index++)session=advanceDate(session,`choice-${index}`);expect(session.phase).toBe('resolution');expect(session.status).toBe('completed');});
  it('scores content with relationship gates and repetition penalties',()=>{const events:RichLifeEventTemplate[]=[{id:'ordinary',title:'Laundry',type:'ordinary',category:'ordinary',tone:'mundane',scale:'micro',contentLevel:'standard',significance:.25,location:'Home',participants:['maya'],proactiveEligible:false,summary:'Laundry.'},{id:'gallery',title:'Gallery invitation',type:'opportunity',category:'opportunity',tone:'exciting',scale:'meaningful',contentLevel:'romance',significance:.72,location:'Gallery',participants:['maya'],proactiveEligible:true,summary:'Gallery.',conditions:{minRelationshipStage:'friend'}}];const context={now:new Date('2026-08-10T18:00:00Z'),relationship:{...defaultRelationship,stage:'friend' as const},characterSlug:'maya',locationTags:['city'],contentMode:'romance' as const,recentTemplateIds:['gallery'],recentCategories:[],activeArcIds:[],seed:'content'};expect(contentConditionsPass(events[1]?.conditions,context).eligible).toBe(true);expect(chooseDailyContent(events,context)[0]?.template.id).toBe('ordinary');});
  it('validates story graphs and respects chapter pacing',()=>{const arc:StoryArcTemplate={id:'gallery',slug:'gallery-opportunity',title:'Gallery Opportunity',category:'career',eligibleCharacters:['maya'],priority:'major',repeatable:false,chapters:[{id:'invite',title:'Invitation',userVisibility:'contextual',mayTriggerProactiveMessage:true,mayCreateMoment:false,narrativeSeed:'invite',possibleNextChapterIds:['submit']},{id:'submit',title:'Submission',userVisibility:'visible',mayTriggerProactiveMessage:true,mayCreateMoment:true,narrativeSeed:'submit'}]};expect(validateContentPack({events:[],arcs:[arc]})).toEqual([]);expect(nextStoryArcChapter(arc,{id:'active',templateId:'gallery',currentChapterId:'invite',status:'active',startedAt:'2026-08-01'},new Date()).chapterId).toBe('submit');expect(nextStoryArcChapter(arc,{id:'active',templateId:'gallery',currentChapterId:'submit',status:'active',startedAt:'2026-08-01'},new Date()).completed).toBe(true);});
  it('simulates a varied deterministic content month without template spam',()=>{const events:RichLifeEventTemplate[]=Array.from({length:8},(_,index)=>({id:`event-${index}`,title:`Event ${index}`,type:'ordinary',category:index%2?'social':'work',tone:'positive',scale:index===0?'meaningful':'normal',contentLevel:'standard',significance:.5,location:'City',participants:['maya'],proactiveEligible:index===0,summary:'A meaningful day.'}));const arcs:StoryArcTemplate[]=Array.from({length:3},(_,index)=>({id:`arc-${index}`,slug:`arc-${index}`,title:`Arc ${index}`,category:'personal',eligibleCharacters:['maya'],priority:'minor',repeatable:false,chapters:[{id:'start',title:'Start',userVisibility:'contextual',mayTriggerProactiveMessage:false,mayCreateMoment:false,narrativeSeed:'Start'}]}));const month=simulateContentMonth(events,arcs);expect(month.events.length).toBeGreaterThan(4);expect(month.repeatedTemplateRate).toBeLessThan(.55);expect(month.arcSteps).toHaveLength(3);});
  it('classifies natural photo requests without turning chat into a prompt box',()=>{expect(classifyPhotoIntent('selfie?')).toMatchObject({requested:true,subject:'companion',shotPreference:'selfie'});expect(classifyPhotoIntent('show me where you are')).toMatchObject({requested:true,subject:'location',shotPreference:'scene'});expect(classifyPhotoIntent('how was your day?').requested).toBe(false);});
  it('keeps canonical identity stable while scene context changes',()=>{const identity={name:'Maya',age:26,canonicalDescription:'Warm expressive face, dark hair.',doNotChange:['face','hair','eyes']};const cafe=trustedImagePrompt({identity,scene:{location:'Juniper Café',activity:'coffee with Chloe',mood:'playful'},shot:'selfie',contentLevel:'standard'});const studio=trustedImagePrompt({identity,scene:{location:'Photography Studio',activity:'editing photos',mood:'tired'},shot:'candid',contentLevel:'standard'});expect(cafe).toContain(identity.canonicalDescription);expect(studio).toContain(identity.canonicalDescription);expect(cafe).not.toContain('Photography Studio');expect(studio).not.toContain('Juniper Café');});
  it('does not forward real-person prompt injection into a trusted request',()=>{const prompt=trustedImagePrompt({identity:{name:'Maya',age:26,canonicalDescription:'Canonical Maya identity.',doNotChange:['face']},scene:{location:'Studio',activity:'editing',mood:'focused'},shot:'selfie',contentLevel:'standard'});expect(prompt).not.toContain('celebrity');expect(prompt).toContain('Do not redesign');});
  it('separates automatic cooldown from user requested photos',()=>{const now=new Date('2026-08-14T18:00:00Z');expect(automaticPhotoAllowed([{source:'life_event',createdAt:'2026-08-14T17:00:00Z'}],now)).toBe(false);expect(automaticPhotoAllowed([{source:'user_request',createdAt:'2026-08-14T17:00:00Z'}],now)).toBe(true);});
  it('never routes unsupported mature content to a conservative provider',()=>{const capabilities={standard:true,romance:true,suggestive:false,mature:false,explicit:false};expect(mediaCapabilityAllowed('romance',capabilities,true)).toBe(true);expect(mediaCapabilityAllowed('mature',capabilities,true)).toBe(false);expect(mediaCapabilityAllowed('romance',capabilities,false)).toBe(false);});
});
