import{describe,expect,it}from'vitest';
import{capabilitiesForAccount,capabilitiesForTier,creditCost,effectiveChatDailyLimit,entitlementsForTier,normalizeSubscriptionTier,subscriptionCatalog}from'../src';

describe('Kivelle subscriptions',()=>{
  it('maps legacy tiers without breaking existing accounts',()=>{expect(normalizeSubscriptionTier('together_plus')).toBe('kivelle_plus');expect(normalizeSubscriptionTier('unlimited')).toBe('kivelle_max');expect(normalizeSubscriptionTier('unexpected')).toBe('free');});
  it('keeps core relationship quality in free while scaling context depth',()=>{const free=capabilitiesForTier('free'),plus=capabilitiesForTier('kivelle_plus'),max=capabilitiesForTier('kivelle_max');expect(entitlementsForTier('free').has('relationship_core')).toBe(true);expect(entitlementsForTier('free').has('plans_dates_moments')).toBe(true);expect(plus.memoryRetrievalBudget).toBeGreaterThan(free.memoryRetrievalBudget);expect(max.historyRetrievalBudget).toBeGreaterThan(plus.historyRetrievalBudget);expect(max.directorPolicy).toBe('normal_and_up');});
  it('defines the intended three-tier pricing, annual savings, and sustainable credit grants',()=>{expect(subscriptionCatalog.free.monthlyPriceUsd).toBe(0);expect(subscriptionCatalog.kivelle_plus.monthlyPriceUsd).toBe(14.99);expect(subscriptionCatalog.kivelle_plus.annualPriceUsd).toBe(149.99);expect(subscriptionCatalog.kivelle_max.monthlyPriceUsd).toBe(34.99);expect(subscriptionCatalog.kivelle_max.annualPriceUsd).toBe(349.99);expect(subscriptionCatalog.kivelle_plus.monthlyCreditGrant).toBe(300);expect(subscriptionCatalog.kivelle_max.monthlyCreditGrant).toBe(1000);});
  it('keeps the free launch week generous before applying the sustainable daily limit',()=>{const free=subscriptionCatalog.free;expect(effectiveChatDailyLimit(free,'2026-08-15T12:00:00Z',new Date('2026-08-19T12:00:00Z'))).toBe(40);expect(effectiveChatDailyLimit(free,'2026-08-01T12:00:00Z',new Date('2026-08-19T12:00:00Z'))).toBe(20);expect(effectiveChatDailyLimit(subscriptionCatalog.kivelle_plus,'2026-08-01T12:00:00Z')).toBeNull();});
  it('bounds the expensive provider-backed benefits by tier',()=>{expect(subscriptionCatalog.free.explicitDialogueMonthlyLimit).toBe(25);expect(subscriptionCatalog.kivelle_plus.includedDatePhotoMonthlyLimit).toBe(1);expect(subscriptionCatalog.kivelle_max.includedDatePhotoMonthlyLimit).toBe(3);});
  it('meters expensive media instead of relationship actions',()=>{expect(creditCost('companion_photo')).toBe(10);expect(creditCost('creator_appearance_set')).toBe(40);expect(creditCost('short_video')).toBeGreaterThan(creditCost('premium_photo'));});
  it('supports a narrow server-controlled unlimited-chat grant without upgrading unrelated capabilities',()=>{const account=capabilitiesForAccount('free',{entitlementOverrides:{grants:['chat_unlimited']}});expect(account.tier).toBe('free');expect(account.chatDailyLimit).toBeNull();expect(account.entitlements).toContain('chat_unlimited');expect(account.worldAccess).toBe('free');expect(account.memoryRetrievalBudget).toBe(subscriptionCatalog.free.memoryRetrievalBudget);});
  it('ignores invalid account capability grants',()=>{const account=capabilitiesForAccount('free',{entitlementOverrides:{grants:['make_everything_free',42]}});expect(account).toBe(subscriptionCatalog.free);expect(account.chatDailyLimit).toBe(20);});
});
