import{describe,expect,it}from'vitest';
import{capabilitiesForAccount,capabilitiesForTier,creditCost,entitlementsForTier,normalizeSubscriptionTier,subscriptionCatalog,voiceNotePricing}from'../src';

describe('Kivelle subscriptions',()=>{
  it('maps legacy tiers without breaking existing accounts',()=>{expect(normalizeSubscriptionTier('together_plus')).toBe('kivelle_plus');expect(normalizeSubscriptionTier('unlimited')).toBe('kivelle_max');expect(normalizeSubscriptionTier('unexpected')).toBe('free');});
  it('keeps core relationship quality in free while scaling context depth',()=>{const free=capabilitiesForTier('free'),plus=capabilitiesForTier('kivelle_plus'),max=capabilitiesForTier('kivelle_max');expect(entitlementsForTier('free').has('relationship_core')).toBe(true);expect(entitlementsForTier('free').has('plans_dates_moments')).toBe(true);expect(plus.memoryRetrievalBudget).toBeGreaterThan(free.memoryRetrievalBudget);expect(max.historyRetrievalBudget).toBeGreaterThan(plus.historyRetrievalBudget);expect(max.directorPolicy).toBe('normal_and_up');});
  it('keeps the product memory recall budgets at 6, 12, and 20',()=>{expect([capabilitiesForTier('free').memoryRetrievalBudget,capabilitiesForTier('kivelle_plus').memoryRetrievalBudget,capabilitiesForTier('kivelle_max').memoryRetrievalBudget]).toEqual([6,12,20]);});
  it('caps main-dialogue reasoning independently by plan',()=>{expect(capabilitiesForTier('free').reasoningEffortMax).toBe('low');expect(capabilitiesForTier('kivelle_plus').reasoningEffortMax).toBe('medium');expect(capabilitiesForTier('kivelle_max').reasoningEffortMax).toBe('high');});
  it('defines the intended three-tier pricing, annual savings, and credit grants',()=>{expect(subscriptionCatalog.free.monthlyPriceUsd).toBe(0);expect(subscriptionCatalog.kivelle_plus.monthlyPriceUsd).toBe(19.99);expect(subscriptionCatalog.kivelle_plus.annualPriceUsd).toBe(199.99);expect(subscriptionCatalog.kivelle_max.monthlyPriceUsd).toBe(39.99);expect(subscriptionCatalog.kivelle_max.annualPriceUsd).toBe(399.99);expect(subscriptionCatalog.kivelle_plus.monthlyCreditGrant).toBe(500);expect(subscriptionCatalog.kivelle_plus.subscriptionCreditRolloverCap).toBe(1000);expect(subscriptionCatalog.kivelle_max.monthlyCreditGrant).toBe(1200);expect(subscriptionCatalog.kivelle_max.subscriptionCreditRolloverCap).toBe(2400);expect(Math.round((1-subscriptionCatalog.kivelle_plus.annualPriceUsd!/(subscriptionCatalog.kivelle_plus.monthlyPriceUsd*12))*100)).toBe(17);expect(Math.round((1-subscriptionCatalog.kivelle_max.annualPriceUsd!/(subscriptionCatalog.kivelle_max.monthlyPriceUsd*12))*100)).toBe(17);});
  it('treats conversation slots and daily messages as separate plan limits',()=>{expect(subscriptionCatalog.free.maxActiveConversations).toBe(5);expect(subscriptionCatalog.kivelle_plus.maxActiveConversations).toBe(20);expect(subscriptionCatalog.kivelle_max.maxActiveConversations).toBe(50);expect(subscriptionCatalog.free.dailyMessageLimit).toBe(40);expect(subscriptionCatalog.kivelle_plus.dailyMessageLimit).toBeNull();expect(subscriptionCatalog.kivelle_max.dailyMessageLimit).toBeNull();});
  it('contains no adult-dialogue allowance or entitlement in any tier',()=>{for(const plan of Object.values(subscriptionCatalog)){expect('explicitDialogueMonthlyLimit' in plan).toBe(false);expect(plan.entitlements.some((key)=>/adult|explicit|nsfw/i.test(key))).toBe(false);}expect(subscriptionCatalog.free.dailyMessageLimit).toBe(40);});
  it('bounds the remaining expensive provider-backed benefits by tier',()=>{expect(subscriptionCatalog.free.includedCompanionPhotoDailyLimit).toBe(0);expect(subscriptionCatalog.kivelle_plus.includedCompanionPhotoDailyLimit).toBe(1);expect(subscriptionCatalog.kivelle_max.includedCompanionPhotoDailyLimit).toBe(3);expect(subscriptionCatalog.kivelle_plus.includedDatePhotoMonthlyLimit).toBe(1);expect(subscriptionCatalog.kivelle_max.includedDatePhotoMonthlyLimit).toBe(3);});
  it('meters expensive media and both voice routes from the shared credit balance',()=>{expect(creditCost('companion_photo')).toBe(10);expect(creditCost('voice_note')).toBe(2);expect(creditCost('voice_standard_minute')).toBe(3);expect(creditCost('voice_minute')).toBe(8);expect(creditCost('creator_appearance_set')).toBe(40);expect(creditCost('short_video')).toBeGreaterThan(creditCost('premium_photo'));});
  it('prices voice notes by canonical message length',()=>{expect(voiceNotePricing(600)).toEqual({characterCount:600,creditCost:2,shortened:false});expect(voiceNotePricing(601).creditCost).toBe(3);expect(voiceNotePricing(1_200).creditCost).toBe(3);expect(voiceNotePricing(1_201).creditCost).toBe(4);expect(voiceNotePricing(2_000)).toEqual({characterCount:2_000,creditCost:4,shortened:false});expect(voiceNotePricing(2_001)).toEqual({characterCount:2_001,creditCost:4,shortened:true});});
  it('supports a narrow server-controlled unlimited-message grant without upgrading conversation slots',()=>{const account=capabilitiesForAccount('free',{entitlementOverrides:{grants:['chat_unlimited']}});expect(account.tier).toBe('free');expect(account.dailyMessageLimit).toBeNull();expect(account.maxActiveConversations).toBe(5);expect(account.entitlements).toContain('chat_unlimited');expect(account.worldAccess).toBe('free');expect(account.memoryRetrievalBudget).toBe(subscriptionCatalog.free.memoryRetrievalBudget);});
  it('gives standard paid plans unlimited messages while retaining finite active-chat limits',()=>{expect(subscriptionCatalog.kivelle_plus.entitlements).not.toContain('chat_unlimited');expect(subscriptionCatalog.kivelle_max.entitlements).not.toContain('chat_unlimited');expect(subscriptionCatalog.kivelle_plus.dailyMessageLimit).toBeNull();expect(subscriptionCatalog.kivelle_max.dailyMessageLimit).toBeNull();expect(subscriptionCatalog.kivelle_plus.maxActiveConversations).toBe(20);expect(subscriptionCatalog.kivelle_max.maxActiveConversations).toBe(50);});
  it('supports a narrow media-testing grant without changing credits or the subscription tier',()=>{const account=capabilitiesForAccount('free',{entitlementOverrides:{grants:['media_generation_unlimited']}});expect(account.tier).toBe('free');expect(account.userRequestedPhotoDailyLimit).toBeNull();expect(account.monthlyCreditGrant).toBe(0);expect(account.entitlements).toContain('media_generation_unlimited');});
  it('ignores legacy adult-dialogue testing grants',()=>{const account=capabilitiesForAccount('free',{entitlementOverrides:{grants:['explicit_dialogue_unlimited']}});expect(account).toBe(subscriptionCatalog.free);expect(account.entitlements).not.toContain('explicit_dialogue_unlimited');});
  it('gates group chat to paid tiers while permitting a narrow test-account grant',()=>{expect(capabilitiesForTier('free').entitlements).not.toContain('group_chat');expect(capabilitiesForTier('kivelle_plus').entitlements).toContain('group_chat');expect(capabilitiesForTier('kivelle_max').entitlements).toContain('group_chat');const testAccount=capabilitiesForAccount('free',{entitlementOverrides:{grants:['group_chat']}});expect(testAccount.tier).toBe('free');expect(testAccount.entitlements).toContain('group_chat');expect(testAccount.memoryRetrievalBudget).toBe(subscriptionCatalog.free.memoryRetrievalBudget);});
  it('gates the memory inspector and manual memory controls without disabling free continuity',()=>{const free=capabilitiesForTier('free'),plus=capabilitiesForTier('kivelle_plus'),max=capabilitiesForTier('kivelle_max');expect(free.entitlements).not.toContain('memory_inspector');expect(free.entitlements).not.toContain('memory_manual_control');expect(free.entitlements).toContain('memory_core');expect(free.memoryRetrievalBudget).toBeGreaterThan(0);expect(plus.entitlements).toContain('memory_inspector');expect(plus.entitlements).toContain('memory_manual_control');expect(max.entitlements).toContain('memory_inspector');expect(max.entitlements).toContain('memory_manual_control');});
  it('ignores invalid account capability grants',()=>{const account=capabilitiesForAccount('free',{entitlementOverrides:{grants:['make_everything_free',42]}});expect(account).toBe(subscriptionCatalog.free);expect(account.maxActiveConversations).toBe(5);expect(account.dailyMessageLimit).toBe(40);});
});
