import{describe,expect,it}from'vitest';
import{buildCompanionPrompt,responseLength,responseTokenBudget,stripGeneratedMediaMarkup}from'../../../supabase/functions/_shared/kivelle-intelligence.ts';

const baseContext={
  character:{name:'Maya',occupation:'Photographer'},
  persona:{display_name:'Tim'},
  relationship:{relationship_stage:'friend',conflict:0},
  currentScene:{location:'Studio',activity:'editing photos',mood:'content',energy:'medium',availability:'available',source:'schedule'},
  clock:{localDate:'2026-08-15',localTime:'21:30',timezone:'America/New_York',daypart:'evening'},
  sharedPlans:[{id:'plan-1',title:'Drinks at Velvet Hour',activityKey:'drinks',status:'scheduled',startsAtLabel:'Saturday 8:00 PM',endsAtLabel:'Saturday 9:30 PM',location:'Velvet Hour'}],
  commitments:[{id:'plan-1',title:'Drinks at Velvet Hour',status:'scheduled',temporalState:'future',relevance:.5,timePrecision:'exact',startsAt:'2026-08-22T00:00:00Z',endsAt:'2026-08-22T01:30:00Z',windowStartsAt:null,windowEndsAt:null,worldTimezone:'America/New_York',userTimezone:'America/New_York',location:'Velvet Hour',userJoinedAt:null,characterJoinedAt:null,companionState:'expected',companionEtaAt:null,companionReason:null,missReason:null,missResolutionStatus:null,missExplanation:null}],
  dates:{active:null,upcoming:[],unlocked:[],recentCompleted:[]},
  memories:[],openThreads:[],social:[],knownLifeEvents:[],sharedHistory:[],recentMedia:[],recent:[],upcomingSchedule:[],
  subscription:{intelligenceProfile:'core'},director:{used:false},responseBrief:{mode:'casual',initiative:'medium',emotionalPosture:'Natural.',selfDisclosure:'none',shouldAskQuestion:false,actionCandidate:'none',avoid:[],autonomy:'Independent.'},
};

describe('Kivelle continuity prompt salience',()=>{
  it('adds explicit texting guidance without replacing character identity',()=>{const prompt=buildCompanionPrompt({...baseContext,conversationStyle:'texting',interactionQuality:'normal',userMessage:'Where should we go tonight?'});expect(prompt).toContain('<CONVERSATION_STYLE>');expect(prompt).toContain('Selected expression style: texting');expect(prompt).toContain('Do not force slang');expect(prompt).toContain('<CHARACTER_CORE>');});
  it('adds compact paragraph guidance and keeps short replies available',()=>{const prompt=buildCompanionPrompt({...baseContext,conversationStyle:'paragraph',interactionQuality:'meaningful',userMessage:'Today was awful.'});expect(prompt).toContain('Selected expression style: paragraph');expect(prompt).toContain('one or two compact paragraphs');expect(prompt).toContain('Short replies are still appropriate');});
  it('lets interaction quality override texting brevity and lowers its token budget',()=>{expect(responseLength('casual','lol','texting','trivial')).toBe('micro');expect(responseLength('supportive','I do not think this relationship is working anymore.','texting','major_relationship_event')).toBe('medium');expect(responseTokenBudget({...baseContext,conversationStyle:'texting',interactionQuality:'normal',userMessage:'What do you think?'})).toBeLessThan(responseTokenBudget({...baseContext,conversationStyle:'paragraph',interactionQuality:'normal',userMessage:'What do you think?'}));});
  it('keeps a future plan out of an unrelated reply prompt',()=>{const prompt=buildCompanionPrompt({...baseContext,userMessage:'My boss was being ridiculous today.',queryIntent:'general',conversationFocus:{type:'plan',planId:'plan-1',title:'Drinks at Velvet Hour',location:'Velvet Hour'}});expect(prompt).toContain('<UPCOMING_PLANS>None.</UPCOMING_PLANS>');expect(prompt).toContain('<COMMITMENTS>None.</COMMITMENTS>');expect(prompt).toContain('<CONVERSATION_FOCUS>None.</CONVERSATION_FOCUS>');expect(prompt).toContain('Callback candidate: None.');});
  it('surfaces plan context when the user reopens the plan',()=>{const prompt=buildCompanionPrompt({...baseContext,userMessage:'Are we still on for Saturday?',queryIntent:'schedule',conversationFocus:{type:'plan',planId:'plan-1',title:'Drinks at Velvet Hour',location:'Velvet Hour'},responseBrief:{...baseContext.responseBrief,mode:'practical',callbackCandidate:'Drinks at Velvet Hour'}});expect(prompt).toContain('Drinks at Velvet Hour');expect(prompt).not.toContain('<CONVERSATION_FOCUS>None.</CONVERSATION_FOCUS>');expect(prompt).toContain('Callback candidate: Drinks at Velvet Hour');});
  it('keeps an active story as background on unrelated messages',()=>{const prompt=buildCompanionPrompt({...baseContext,userMessage:'I am wiped out after work.',queryIntent:'general',activeStory:{title:'Gallery Opportunity',chapterTitle:'Submission',knownSummary:'A deadline is approaching.'}});expect(prompt).toContain('Gallery Opportunity');expect(prompt).toContain('Response intent: casual');expect(prompt).toContain('This is background unless the current message or callback candidate reopens it.');});
  it('marks memories as background rather than required callbacks',()=>{const prompt=buildCompanionPrompt({...baseContext,userMessage:'What a weird day.',queryIntent:'general',memories:[{type:'semantic',text:'User has a dog named Winston.'}]});expect(prompt).toContain('Background knowledge. Use silently unless the current message clearly benefits from a specific callback.');expect(prompt).toContain('A natural reply often contains no explicit continuity reference at all.');});
  it('supplies rich current-place lore without requiring the companion to recite it',()=>{const prompt=buildCompanionPrompt({...baseContext,userMessage:'What is this place like?',queryIntent:'location',place:{path:'Juniper City → Alder District → Velvet Hour',world:{name:'Juniper City',description:'A creative city.'},clock:{weekday:'Saturday',localTime:'20:30',timezone:'America/New_York',daypart:'evening'},location:{name:'Velvet Hour',description:'An intimate cocktail lounge.',type:'venue',possibleActivities:['cocktails','music'],hours:{open:'17:00',close:'01:00'},lore:{atmosphere:['quietly romantic'],sensoryDetails:['low piano notes'],signatureDetails:['black upright piano'],crowdRhythm:{evening:'Conversation-focused tables fill gradually.'},stableFacts:['The pianist plays on Thursdays.']}},ancestry:[{name:'Alder District',type:'district',description:'A walkable creative district.'}],nearby:[{name:'Paper Trail',category:'bookstore',possibleActivities:['books','coffee']}]}});expect(prompt).toContain('Signature details: black upright piano');expect(prompt).toContain('Crowd right now: Conversation-focused tables fill gradually.');expect(prompt).toContain('Nearby: Paper Trail (books, coffee)');expect(prompt).toContain('Treat these details as canonical reality. Do not contradict or repeatedly narrate them');});
  it('supplies lore for another place only when context resolved that named place',()=>{const referenced={path:'Juniper City → Alder District → Paper Trail',world:{name:'Juniper City'},clock:{daypart:'afternoon'},location:{name:'Paper Trail',description:'A quiet bookshop.',type:'venue',possibleActivities:['books'],lore:{signatureDetails:['handwritten staff recommendation cards']}},ancestry:[],nearby:[]};const prompt=buildCompanionPrompt({...baseContext,userMessage:'What is Paper Trail like?',queryIntent:'location',referencedPlaces:[referenced]});expect(prompt).toContain('<REFERENCED_PLACES>');expect(prompt).toContain('handwritten staff recommendation cards');expect(prompt).toContain('do not invent venue details');});
  it('separates personal place perspective from objective lore',()=>{const prompt=buildCompanionPrompt({...baseContext,userMessage:'Do you like it here?',placePerspectives:[{locationName:'Velvet Hour',source:'combined',visitCount:2,opinionSummary:'Likes the piano-side booths, but not the late crowd.',favoriteDetails:['piano-side booths'],dislikedDetails:['late crowd'],preferredActivities:['conversation']}]});expect(prompt).toContain('<CHARACTER_PLACE_PERSPECTIVES>');expect(prompt).toContain('Likes the piano-side booths');expect(prompt).toContain('distinct from objective location facts');expect(prompt).toContain('only Kivelle');});
  it('places present reality after stale recent dialogue for current-location questions',()=>{const prompt=buildCompanionPrompt({...baseContext,currentScene:{...baseContext.currentScene,location:'Riverwalk',activity:'walking along the river',interactionMode:'remote',source:'schedule'},recent:[{role:'assistant',content:"I'm sitting at Juniper Café finishing my coffee."}],userMessage:'Where are you right now?',queryIntent:'location'});expect(prompt).toContain('Current canonical location: Riverwalk');expect(prompt).toContain('Never answer a present-tense question using an older location or activity');expect(prompt).toContain('Do not infer current location from RECENT_CONVERSATION');expect(prompt.indexOf('<PRESENT_REALITY>')).toBeGreaterThan(prompt.indexOf('</RECENT_CONVERSATION>'));expect(prompt.indexOf('<PRESENT_REALITY>')).toBeLessThan(prompt.indexOf('<RESPONSE_DIRECTION>'));});
  it('does not force current location into a historical location answer',()=>{const prompt=buildCompanionPrompt({...baseContext,currentScene:{...baseContext.currentScene,location:'Riverwalk',activity:'walking'},userMessage:'Where were you yesterday afternoon?',queryIntent:'history'});expect(prompt).toContain('Historical-location request');expect(prompt).toContain('must not be presented as the historical answer');});
  it('keeps generated-photo plumbing out of the companion reply',()=>{const prompt=buildCompanionPrompt({...baseContext,userMessage:'Show me where you are',photoRequest:true});expect(prompt).toContain('<PHOTO_DELIVERY>');expect(prompt).toContain('Do not include an image-generation prompt');expect(prompt.indexOf('<PHOTO_DELIVERY>')).toBeGreaterThan(prompt.indexOf('</PRESENT_REALITY>'));expect(stripGeneratedMediaMarkup('Here.\n\n[Attached: A generated portrait prompt.]')).toBe('Here.');expect(stripGeneratedMediaMarkup('This [actually] works.')).toBe('This [actually] works.');});
});
