import{describe,expect,it}from'vitest';
import{antiRepetitionGuidance,compileCharacterGoals,compileRelationshipStance,compileResponseBrief,shouldUseDirector}from'../src';

describe('Kivelle prompt compiler',()=>{
  it('turns metrics into stage-appropriate qualitative stance',()=>{const stance=compileRelationshipStance({relationship_stage:'flirting',trust:48,comfort:52,attraction:67,commitment:12,conflict:4});expect(stance.summary).toContain('chemistry');expect(stance.affectionBoundary).toContain('exclusivity');expect(stance.autonomyRule).toContain('disagree');});
  it('keeps friendship-only stance platonic even when closeness is high',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:80,comfort:80,familiarity:80,attraction:80,romance_enabled:false});expect(stance.affectionBoundary).toContain('platonic');expect(stance.summary).toContain('platonic');});
  it('uses canonical story or bible goals instead of inventing plot facts',()=>{const story=compileCharacterGoals({occupation:'photographer',activeStory:{title:'Gallery Opportunity',chapterTitle:'Submission',knownSummary:'A deadline is approaching.'},bible:{ambitions:['Build a respected body of work.']}});expect(story.currentGoal).toContain('Gallery Opportunity');expect(story.currentConcern).toBe('A deadline is approaching.');expect(story.mediumTermAmbition).toContain('respected body of work');});
  it('builds an autonomous response brief without mandatory questions',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:55,comfort:60,familiarity:60});const brief=compileResponseBrief({message:'lol',interactionQuality:'trivial',relationshipStance:stance,recentAssistantMessages:['What do you think?','How was that?','What happened next?']});expect(brief.initiative).toBe('low');expect(brief.shouldAskQuestion).toBe(false);expect(brief.autonomy).toContain('Agreement is optional');});
  it('detects repetitive question endings and common openings',()=>{const avoid=antiRepetitionGuidance(['Okay, that is fair. What do you think?','Okay, that is fair. How was it?','Okay, that is fair. What happened?']);expect(avoid.join(' ')).toContain('opening pattern');expect(avoid.join(' ')).toContain('question');});
  it('uses Director by tier policy rather than making free characters inaccurate',()=>{expect(shouldUseDirector('major_only','normal')).toBe(false);expect(shouldUseDirector('major_only','major_relationship_event')).toBe(true);expect(shouldUseDirector('meaningful','meaningful')).toBe(true);expect(shouldUseDirector('normal_and_up','normal')).toBe(true);expect(shouldUseDirector('normal_and_up','trivial')).toBe(false);});
});
