import{describe,expect,it}from'vitest';
import{antiRepetitionGuidance,compileCharacterGoals,compileRelationshipStance,compileResponseBrief,shouldUseDirector}from'../src';

describe('Kivelle prompt compiler',()=>{
  it('turns metrics into stage-appropriate qualitative stance',()=>{const stance=compileRelationshipStance({relationship_stage:'flirting',trust:48,comfort:52,attraction:67,commitment:12,conflict:4});expect(stance.summary).toContain('chemistry');expect(stance.affectionBoundary).toContain('exclusivity');expect(stance.autonomyRule).toContain('disagree');});
  it('keeps friendship-only stance platonic even when closeness is high',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:80,comfort:80,familiarity:80,attraction:80,romance_enabled:false});expect(stance.affectionBoundary).toContain('platonic');expect(stance.summary).toContain('platonic');});
  it('uses canonical story or bible goals instead of inventing plot facts',()=>{const story=compileCharacterGoals({occupation:'photographer',activeStory:{title:'Gallery Opportunity',chapterTitle:'Submission',knownSummary:'A deadline is approaching.'},bible:{ambitions:['Build a respected body of work.']}});expect(story.currentGoal).toContain('Gallery Opportunity');expect(story.currentConcern).toBe('A deadline is approaching.');expect(story.mediumTermAmbition).toContain('respected body of work');});
  it('builds an autonomous response brief without mandatory questions',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:55,comfort:60,familiarity:60});const brief=compileResponseBrief({message:'lol',interactionQuality:'trivial',relationshipStance:stance,recentAssistantMessages:['What do you think?','How was that?','What happened next?']});expect(brief.initiative).toBe('low');expect(brief.shouldAskQuestion).toBe(false);expect(brief.autonomy).toContain('Agreement is optional');});
  it('detects repetitive question endings and common openings',()=>{const avoid=antiRepetitionGuidance(['Okay, that is fair. What do you think?','Okay, that is fair. How was it?','Okay, that is fair. What happened?']);expect(avoid.join(' ')).toContain('opening pattern');expect(avoid.join(' ')).toContain('question');});
  it('keeps an unrelated upcoming plan out of the callback slot',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:55,comfort:60,familiarity:60});const brief=compileResponseBrief({message:'My boss was being ridiculous today.',interactionQuality:'normal',relationshipStance:stance,nextCommitment:'Drinks at Velvet Hour',recentAssistantMessages:['I am looking forward to Velvet Hour.']});expect(brief.callbackCandidate).toBeUndefined();expect(brief.avoid.join(' ')).toContain('unless the user reopens that plan');});
  it('recalls a plan when the user actually reopens it',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:55,comfort:60,familiarity:60});const brief=compileResponseBrief({message:'Are we still on for Saturday?',interactionQuality:'normal',relationshipStance:stance,nextCommitment:'Drinks at Velvet Hour',recentAssistantMessages:['I am looking forward to Velvet Hour.']});expect(brief.callbackCandidate).toBe('Drinks at Velvet Hour');expect(brief.mode).toBe('practical');expect(brief.avoid.join(' ')).not.toContain('unless the user reopens that plan');});
  it('does not let an active story dominate an unrelated reply',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:55,comfort:60,familiarity:60});const brief=compileResponseBrief({message:'Work was chaos today.',interactionQuality:'normal',relationshipStance:stance,activeStory:'Gallery Opportunity'});expect(brief.callbackCandidate).toBeUndefined();expect(brief.mode).toBe('casual');expect(brief.actionCandidate).toBe('none');});
  it('reopens an active story when the user asks for it',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:55,comfort:60,familiarity:60});const brief=compileResponseBrief({message:'What happens next in the Gallery Opportunity?',interactionQuality:'normal',relationshipStance:stance,activeStory:'Gallery Opportunity'});expect(brief.callbackCandidate).toBe('Gallery Opportunity');expect(brief.mode).toBe('storytelling');expect(brief.actionCandidate).toBe('story');});
  it('only follows an open thread when the user references that subject',()=>{const stance=compileRelationshipStance({relationship_stage:'friend',trust:55,comfort:60,familiarity:60});const unrelated=compileResponseBrief({message:'I am exhausted.',interactionQuality:'normal',relationshipStance:stance,openThread:'Presentation'});const reopened=compileResponseBrief({message:'My presentation is finally over.',interactionQuality:'meaningful',relationshipStance:stance,openThread:'Presentation'});expect(unrelated.callbackCandidate).toBeUndefined();expect(reopened.callbackCandidate).toBe('Presentation');expect(reopened.actionCandidate).toBe('memory_followup');});
  it('uses Director by tier policy rather than making free characters inaccurate',()=>{expect(shouldUseDirector('major_only','normal')).toBe(false);expect(shouldUseDirector('major_only','major_relationship_event')).toBe(true);expect(shouldUseDirector('meaningful','meaningful')).toBe(true);expect(shouldUseDirector('normal_and_up','normal')).toBe(true);expect(shouldUseDirector('normal_and_up','trivial')).toBe(false);});
});
