import { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ChevronDown, ChevronRight, X } from 'lucide-react-native';
import type { CharacterBlueprint } from '@together/domain/src/character-blueprint';
import { invoke } from '../../lib/api';
import { colors } from '../../theme';

export function CharacterBlueprintSheet({instanceId,onClose}:{instanceId:string|null;onClose:()=>void}){
 const insets=useSafeAreaInsets();
 const [result,setResult]=useState<CharacterBlueprint|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[retry,setRetry]=useState(0),[expanded,setExpanded]=useState<string[]>([]);
 useEffect(()=>{setResult(null);setError('');setQuery('');setExpanded([]);if(!instanceId)return;const controller=new AbortController();
 void invoke<CharacterBlueprint>('together-memory',{action:'character_blueprint',characterInstanceId:instanceId},'POST',{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setResult(value);}).catch(caught=>{if(!controller.signal.aborted)setError(caught instanceof Error?caught.message:'Could not load the character blueprint.');});return()=>controller.abort();
 },[instanceId,retry]);
 const sections=(result?.sections??[]).filter(s=>!query.trim()||(s.title+' '+JSON.stringify(s.data)).toLowerCase().includes(query.trim().toLowerCase()));
 return <Modal visible={Boolean(instanceId)} animationType="slide" onRequestClose={onClose}><View style={[styles.page,{paddingTop:insets.top+16,paddingBottom:insets.bottom}]}><View style={styles.header}><View style={{flex:1}}><Text accessibilityRole="header" style={styles.title}>Character blueprint</Text><Text style={styles.muted}>{result?result.name+' · Version '+result.version:'Authored character data'}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close character blueprint" onPress={onClose} style={styles.close}><X color={colors.text}/></Pressable></View><Text style={styles.note}>Your private preview · Read only. Includes authored secrets and story details. These are the character’s starting instructions, not memories from your chats.</Text>{result?<TextInput accessibilityLabel="Search character blueprint" placeholder="Search authored data" placeholderTextColor={colors.textSecondary} value={query} onChangeText={setQuery} style={styles.search}/>:null}<ScrollView contentContainerStyle={styles.content}>{error?<View><Text style={styles.muted}>{error}</Text><Pressable accessibilityRole="button" onPress={()=>setRetry(x=>x+1)} style={styles.close}><Text style={styles.link}>Try again</Text></Pressable></View>:!result?<ActivityIndicator color={colors.rose}/>:sections.length?sections.map(section=>{const open=Boolean(query.trim())||expanded.includes(section.title);return <View key={section.title} style={styles.section}><Pressable accessibilityRole="button" accessibilityState={{expanded:open}} onPress={()=>setExpanded(items=>items.includes(section.title)?items.filter(x=>x!==section.title):[...items,section.title])} style={styles.sectionHeader}><Text style={styles.sectionTitle}>{section.title}</Text>{open?<ChevronDown color={colors.textSecondary}/>:<ChevronRight color={colors.textSecondary}/>}</Pressable>{open?<DataValue value={section.data}/>:null}</View>}):<Text style={styles.muted}>No matching authored data.</Text>}</ScrollView></View></Modal>;
}
function DataValue({value,depth=0}:{value:unknown;depth?:number}){
 if(value==null||value===''||(Array.isArray(value)&&!value.length))return <Text style={styles.muted}>Not authored</Text>;
 if(typeof value!=='object')return <Text selectable style={styles.value}>{String(value)}</Text>;
 if(depth>5)return <Text selectable style={styles.value}>{JSON.stringify(value,null,2)}</Text>;
 return <View style={depth?styles.nested:undefined}>{Object.entries(value).map(([key,item])=><View key={key} style={styles.field}><Text style={styles.label}>{Array.isArray(value)?'Entry '+(Number(key)+1):key.replace(/_/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2')}</Text><DataValue value={item} depth={depth+1}/></View>)}</View>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background,paddingHorizontal:20},header:{flexDirection:'row',alignItems:'center',gap:12},title:{fontSize:25,fontWeight:'700',color:colors.text},muted:{color:colors.textSecondary,fontSize:14,lineHeight:21},note:{color:colors.textSecondary,fontSize:13,lineHeight:20,marginVertical:18},close:{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'},search:{color:colors.text,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:12,marginBottom:16},content:{paddingBottom:40,gap:12,maxWidth:1000,width:'100%',alignSelf:'center'},section:{borderBottomWidth:1,borderColor:colors.border,paddingBottom:16},sectionHeader:{flexDirection:'row',alignItems:'center',paddingVertical:14,gap:12},sectionTitle:{flex:1,color:colors.text,fontSize:18,fontWeight:'600'},field:{marginTop:12,gap:5},label:{color:colors.rose,fontSize:13,fontWeight:'600'},value:{color:colors.text,fontSize:15,lineHeight:23},nested:{borderLeftWidth:1,borderColor:colors.border,paddingLeft:12},link:{color:colors.rose}});
