import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View, useWindowDimensions, type GestureResponderEvent } from 'react-native';
import { ArrowUpRight, BellRing, Brain, Check, ChevronDown, ChevronRight, Clock3, Heart, History, MapPin, Pin, Search, ShieldCheck, Sparkles, Trash2, UserRound, X } from 'lucide-react-native';
import type { CharacterInstance, MemoryCenterInsights, MemoryCenterItem } from '../../types';
import { colors, radius, spacing, typography } from '../../theme';
import { presentMemoryText } from '../../lib/memoryPresentation';
import { presentInsightText } from '../../lib/memoryCenter';
import { CharacterAvatar } from '../ui';
import { FrostedSurface } from '../FrostedGlass';

export function MemoryCompanionRail({companions,activeId,counts,onChoose}:{companions:CharacterInstance[];activeId?:string;counts:Record<string,number>;onChoose:(companion:CharacterInstance)=>void}){
  const[query,setQuery]=useState('');
  const filtered=useMemo(()=>companions.filter((item)=>item.together_character_templates.name.toLowerCase().includes(query.trim().toLowerCase())),[companions,query]);
  return <FrostedSurface intensity={76} style={styles.companionRail}>
    <Text style={styles.railKicker}>COMPANIONS</Text>
    <View style={styles.railSearch}><Search size={15} color={colors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Find someone" placeholderTextColor={colors.dimmed} style={styles.railSearchInput}/></View>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.railList}>{filtered.map((item)=><Pressable key={item.id} onPress={()=>onChoose(item)} style={[styles.companionRow,item.id===activeId&&styles.companionRowActive]}><CharacterAvatar slug={item.together_character_templates.slug} name={item.together_character_templates.name} template={item.together_character_templates} version={item.together_character_versions} size={38}/><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={[styles.companionName,item.id===activeId&&styles.companionNameActive]}>{item.together_character_templates.name}</Text><Text style={styles.companionCount}>{counts[item.id]??0} remembered</Text></View><ChevronRight size={15} color={item.id===activeId?colors.rose:colors.dimmed}/></Pressable>)}</ScrollView>
  </FrostedSurface>;
}

export function MemoryCompanionStrip({companions,activeId,counts,onChoose}:{companions:CharacterInstance[];activeId?:string;counts:Record<string,number>;onChoose:(companion:CharacterInstance)=>void}){return <ScrollView horizontal style={styles.companionStripScroll} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.companionStrip}>{companions.map((item)=><Pressable key={item.id} accessibilityRole="button" accessibilityState={{selected:item.id===activeId}} accessibilityLabel={`${item.together_character_templates.name}, ${counts[item.id]??0} remembered`} onPress={()=>onChoose(item)} style={[styles.companionChip,item.id===activeId&&styles.companionChipActive]}><CharacterAvatar slug={item.together_character_templates.slug} name={item.together_character_templates.name} template={item.together_character_templates} version={item.together_character_versions} size={32}/><View style={styles.chipCopy}><Text numberOfLines={1} style={[styles.chipName,item.id===activeId&&styles.companionNameActive]}>{item.together_character_templates.name.split(' ')[0]}</Text><Text style={styles.chipCount}>{counts[item.id]??0}</Text></View></Pressable>)}</ScrollView>;}

export function MemoryJournalRow({memory,name,privacyMode,selectionMode,selected,busy,onOpen,onToggle,onForget,onSource}:{memory:MemoryCenterItem;name:string;privacyMode:boolean;selectionMode:boolean;selected:boolean;busy:boolean;onOpen:()=>void;onToggle:()=>void;onForget:()=>void;onSource?:()=>void}){
  const sourceAction=(event:GestureResponderEvent)=>{event.stopPropagation();onSource?.();};
  const due=memory.memory_type==='open_thread'&&memory.expectedAt?new Date(memory.expectedAt):null;
  return <Pressable disabled={busy} onLongPress={onToggle} onPress={selectionMode?onToggle:privacyMode?undefined:onOpen} style={({pressed})=>[styles.memoryRow,selected&&styles.memoryRowSelected,pressed&&(!privacyMode||selectionMode)&&styles.memoryRowPressed]}>
    {selectionMode?<View style={[styles.selectionBox,selected&&styles.selectionBoxActive]}>{selected?<Check size={13} strokeWidth={3} color="#fff"/>:null}</View>:<View style={styles.memoryIcon}><MemoryIcon type={memory.memory_type}/></View>}
    <View style={styles.memoryBody}>
      <View style={styles.memoryMetaLine}><Text style={styles.memoryCategory}>{categoryLabel(memory.memory_type)}</Text><View style={memory.knowledgeKind==='inferred'?styles.inferredBadge:styles.directBadge}>{memory.knowledgeKind==='inferred'?<Sparkles size={11} color={colors.warm}/>:<Check size={11} color={colors.rose}/>}<Text style={memory.knowledgeKind==='inferred'?styles.inferredText:styles.directText}>{memory.knowledgeKind==='inferred'?`${name.split(' ')[0]} noticed`:`You told ${name.split(' ')[0]}`}</Text></View>{memory.pinned?<Pin size={14} color={colors.rose} fill={colors.rose}/>:null}</View>
      <Text style={styles.memoryText}>{presentMemoryText(memory.canonical_text,name)}</Text>
      <View style={styles.memoryFoot}>{due?<View style={styles.sourceButton}><Clock3 size={12} color={colors.warm}/><Text style={styles.dueText}>{relativeDue(due)}</Text></View>:memory.sourceContext?<Pressable disabled={!onSource} onPress={sourceAction} style={styles.sourceButton}>{memory.locationName?<MapPin size={12} color={colors.violet}/>:<History size={12} color={colors.violet}/>}<Text numberOfLines={1} style={[styles.sourceText,onSource&&styles.sourceLink]}>{memory.sourceContext}</Text>{onSource?<ArrowUpRight size={12} color={colors.violet}/>:null}</Pressable>:null}<Text style={styles.memoryDate}>{new Date(memory.updated_at).toLocaleDateString(undefined,{month:'short',day:'numeric',year:new Date(memory.updated_at).getFullYear()===new Date().getFullYear()?undefined:'numeric'})}</Text></View>
    </View>
    {privacyMode?<Pressable accessibilityLabel="Forget this memory" disabled={busy} onPress={onForget} style={styles.rowAction}>{busy?<ActivityIndicator size="small" color={colors.danger}/>:<Trash2 size={18} color={colors.danger}/>}</Pressable>:null}
  </Pressable>;
}

export function MemoryInsightsPanel({name,insights,expandedByDefault=false}:{name:string;insights:MemoryCenterInsights|null;expandedByDefault?:boolean}){
  const[expanded,setExpanded]=useState(expandedByDefault);
  if(!insights||(!insights.relationshipSummary&&!insights.sharedReferences.length&&!insights.learnedPatterns.length&&!insights.recalledReferences.length))return null;
  return <FrostedSurface intensity={76} style={styles.insights}>
    <Pressable onPress={()=>setExpanded((value)=>!value)} style={styles.insightsHeader}><View style={styles.insightIcon}><Sparkles size={18} color={colors.warm}/></View><View style={{flex:1}}><Text style={styles.insightsKicker}>KIVELLE MAX</Text><Text style={styles.insightsTitle}>How {name.split(' ')[0]} understands you</Text></View><ChevronDown size={18} color={colors.muted} style={{transform:[{rotate:expanded?'180deg':'0deg'}]}}/></Pressable>
    {expanded?<View style={styles.insightsContent}>{insights.relationshipSummary?<InsightSection title="YOUR RELATIONSHIP" values={[insights.relationshipSummary]} name={name}/>:null}{insights.learnedPatterns.length?<InsightSection title="PATTERNS NOTICED" values={insights.learnedPatterns.map((item)=>item.summary)} name={name}/>:null}{insights.sharedReferences.length?<InsightSection title="SHARED REFERENCES" values={insights.sharedReferences} name={name}/>:null}{insights.recalledReferences.length?<InsightSection title="RECALLED NATURALLY" values={insights.recalledReferences} name={name}/>:null}</View>:null}
  </FrostedSurface>;
}
function InsightSection({title,values,name}:{title:string;values:string[];name:string}){return <View style={styles.insightSection}><Text style={styles.insightLabel}>{title}</Text>{values.slice(0,5).map((value,index)=><View key={`${title}:${index}`} style={styles.insightRow}><View style={styles.insightDot}/><Text style={styles.insightText}>{presentInsightText(value,name)}</Text></View>)}</View>;}

export function MemoryDetailSheet({memory,name,revisions,historyLoading,busy,manualControl,onClose,onEdit,onPin,onForget,onRestore,onSource}:{memory:MemoryCenterItem|null;name:string;revisions:MemoryCenterItem[];historyLoading:boolean;busy:boolean;manualControl:boolean;onClose:()=>void;onEdit:(memory:MemoryCenterItem)=>void;onPin:(memory:MemoryCenterItem)=>void;onForget:(memory:MemoryCenterItem)=>void;onRestore:(memory:MemoryCenterItem,revision:MemoryCenterItem)=>void;onSource?:(memory:MemoryCenterItem)=>void}){
  const{width}=useWindowDimensions(),desktop=width>=900;
  return <Modal visible={Boolean(memory)} transparent animationType="fade" onRequestClose={onClose}><View style={[styles.modalRoot,desktop?styles.modalDesktop:styles.modalMobile]}><Pressable accessibilityLabel="Close memory details" onPress={onClose} style={StyleSheet.absoluteFill}/>{memory?<FrostedSurface intensity={96} style={[styles.detailSheet,desktop?styles.detailDesktop:styles.detailMobile]}><View style={styles.sheetHandle}/><View style={styles.detailHeader}><View style={styles.detailIcon}><MemoryIcon type={memory.memory_type}/></View><View style={{flex:1}}><Text style={styles.detailKicker}>{categoryLabel(memory.memory_type).toUpperCase()}</Text><Text style={styles.detailTitle}>Memory details</Text></View><Pressable accessibilityLabel="Close" onPress={onClose} style={styles.close}><X size={20} color={colors.muted}/></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.detailScroll}><Text style={styles.detailMemory}>{presentMemoryText(memory.canonical_text,name)}</Text><View style={styles.detailMeta}><View style={memory.knowledgeKind==='inferred'?styles.inferredBadge:styles.directBadge}>{memory.knowledgeKind==='inferred'?<Sparkles size={12} color={colors.warm}/>:<Check size={12} color={colors.rose}/>}<Text style={memory.knowledgeKind==='inferred'?styles.inferredText:styles.directText}>{memory.knowledgeKind==='inferred'?'Learned pattern':'Directly shared'}</Text></View><Text style={styles.detailDate}>Updated {new Date(memory.updated_at).toLocaleDateString()}</Text></View>{memory.sourceContext?<Pressable disabled={!onSource} onPress={()=>onSource?.(memory)} style={styles.sourceCard}><Text style={styles.sourceLabel}>SOURCE</Text><Text style={styles.sourceCardText}>{memory.sourceContext}</Text>{onSource?<ArrowUpRight size={16} color={colors.violet}/>:null}</Pressable>:null}{memory.corrected?<Text style={styles.corrected}>This replaced an earlier version.</Text>:null}
      <View style={styles.detailActions}>{manualControl?<><Pressable disabled={busy} onPress={()=>onPin(memory)} style={styles.detailAction}><Pin size={17} color={colors.rose}/><Text style={styles.detailActionText}>{memory.pinned?'Unpin':'Pin'}</Text></Pressable><Pressable disabled={busy} onPress={()=>onEdit(memory)} style={styles.detailAction}><Sparkles size={17} color={colors.violet}/><Text style={styles.detailActionText}>Correct</Text></Pressable></>:null}<Pressable disabled={busy} onPress={()=>onForget(memory)} style={[styles.detailAction,styles.detailDanger]}><Trash2 size={17} color={colors.danger}/><Text style={[styles.detailActionText,{color:colors.danger}]}>Forget</Text></Pressable></View>
      <View style={styles.historyBlock}><View style={styles.historyHeader}><History size={16} color={colors.violet}/><Text style={styles.historyTitle}>Correction history</Text></View>{historyLoading?<ActivityIndicator color={colors.rose}/>:revisions.length>1?revisions.map((revision,index)=><View key={revision.id} style={styles.revision}><View style={{flex:1}}><Text style={styles.revisionLabel}>{index===0?'CURRENT':`EARLIER · ${new Date(revision.updated_at).toLocaleDateString()}`}</Text><Text style={styles.revisionText}>{presentMemoryText(revision.canonical_text,name)}</Text></View>{index>0&&manualControl?<Pressable disabled={busy} onPress={()=>onRestore(memory,revision)} style={styles.restore}><Text style={styles.restoreText}>Restore</Text></Pressable>:null}</View>):<Text style={styles.historyEmpty}>No earlier corrections.</Text>}</View>
    </ScrollView></FrostedSurface>:null}</View></Modal>;
}

export function MemoryEditorSheet({visible,name,memory,busy,onClose,onSave}:{visible:boolean;name:string;memory?:MemoryCenterItem|null;busy:boolean;onClose:()=>void;onSave:(input:{text:string;memoryType:'semantic'|'preference'|'episodic'|'relationship'|'emotional';pinned:boolean})=>void}){
  const[text,setText]=useState(''),[type,setType]=useState<'semantic'|'preference'|'episodic'|'relationship'|'emotional'>('semantic'),[pinned,setPinned]=useState(false);
  useEffect(()=>{if(visible){setText(memory?presentMemoryText(memory.canonical_text,name):'');setType(memory&&memory.memory_type!=='open_thread'?memory.memory_type:'semantic');setPinned(Boolean(memory?.pinned));}},[memory,name,visible]);
  const types:Array<[typeof type,string]>=[['semantic','About you'],['preference','Preference'],['episodic','Shared moment'],['relationship','Relationship'],['emotional','Emotional context']];
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.editorRoot}><Pressable onPress={onClose} style={StyleSheet.absoluteFill}/><FrostedSurface intensity={96} style={styles.editor}><View style={styles.detailHeader}><View style={styles.detailIcon}><Brain size={19} color={colors.rose}/></View><View style={{flex:1}}><Text style={styles.detailKicker}>{memory?'CORRECT MEMORY':'REMEMBER SOMETHING'}</Text><Text style={styles.detailTitle}>{memory?`Update what ${name.split(' ')[0]} knows`:`Add a memory for ${name.split(' ')[0]}`}</Text></View><Pressable onPress={onClose} style={styles.close}><X size={20} color={colors.muted}/></Pressable></View><Text style={styles.editorHint}>{memory?'Write the accurate version. The earlier wording stays in correction history.':'Use natural wording, such as “I prefer quiet restaurants.”'}</Text>{!memory?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.typeRow}>{types.map(([key,label])=><Pressable key={key} onPress={()=>setType(key)} style={[styles.typeChip,type===key&&styles.typeChipActive]}><Text style={[styles.typeText,type===key&&styles.typeTextActive]}>{label}</Text></Pressable>)}</ScrollView>:null}<TextInput multiline autoFocus value={text} onChangeText={setText} maxLength={2000} placeholder="What should be remembered?" placeholderTextColor={colors.dimmed} style={styles.editorInput}/><View style={styles.editorBottom}><View style={styles.pinToggle}><Pin size={16} color={colors.rose}/><Text style={styles.pinToggleText}>Keep this easy to recall</Text><Switch value={pinned} onValueChange={setPinned} trackColor={{false:colors.elevated,true:colors.rose}}/></View><Pressable disabled={busy||!text.trim()} onPress={()=>onSave({text:text.trim(),memoryType:type,pinned})} style={[styles.save,busy||!text.trim()?styles.disabled:null]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.saveText}>{memory?'Save correction':'Remember this'}</Text>}</Pressable></View></FrostedSurface></View></Modal>;
}

export function MemoryPrivacySheet({visible,categories,busy,globalErase=false,onClose,onToggle,onForgetAll}:{visible:boolean;categories:Record<string,boolean>;busy:string;globalErase?:boolean;onClose:()=>void;onToggle:(key:string,value:boolean)=>void;onForgetAll:()=>void}){
  const controls:Array<[string,string,string]>=[['semantic','About you','Facts and personal details'],['preference','Preferences','Likes, dislikes, and tastes'],['episodic','Shared experiences','Things you experienced together'],['relationship','Relationship','Meaningful relationship context'],['emotional','Emotional context','Durable emotional patterns'],['open_thread','Upcoming things','Questions and follow-ups']];
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.editorRoot}><Pressable onPress={onClose} style={StyleSheet.absoluteFill}/><FrostedSurface intensity={96} style={styles.privacySheet}><View style={styles.detailHeader}><View style={styles.detailIcon}><ShieldCheck size={20} color={colors.violet}/></View><View style={{flex:1}}><Text style={styles.detailKicker}>MEMORY CONTROLS</Text><Text style={styles.detailTitle}>Your privacy, your choice</Text></View><Pressable onPress={onClose} style={styles.close}><X size={20} color={colors.muted}/></Pressable></View><Text style={styles.editorHint}>These controls are available on every plan and change what companions may retain and recall.</Text><ScrollView contentContainerStyle={styles.controlList}>{controls.map(([key,label,description])=><View key={key} style={styles.control}><View style={{flex:1}}><Text style={styles.controlTitle}>{label}</Text><Text style={styles.controlCopy}>{description}</Text></View>{busy===key?<ActivityIndicator color={colors.rose}/>:<Switch disabled={Boolean(busy)} value={categories[key]!==false} onValueChange={(value)=>onToggle(key,value)} trackColor={{false:colors.elevated,true:colors.rose}}/>}</View>)}<Pressable disabled={Boolean(busy)} onPress={onForgetAll} style={styles.erase}><Trash2 size={18} color={colors.danger}/><View style={{flex:1}}><Text style={styles.eraseTitle}>{globalErase?'Erase everything remembered in this Life':'Forget everything for this companion'}</Text><Text style={styles.eraseCopy}>Conversation history and relationship progress remain.</Text></View></Pressable></ScrollView></FrostedSurface></View></Modal>;
}

export function MemoryBulkBar({count,busy,onCancel,onPin,onUnpin,onForget}:{count:number;busy:boolean;onCancel:()=>void;onPin:()=>void;onUnpin:()=>void;onForget:()=>void}){return <FrostedSurface intensity={92} style={styles.bulkBar}><Text style={styles.bulkCount}>{count} selected</Text><Pressable disabled={busy} onPress={onPin} style={styles.bulkAction}><Pin size={15} color={colors.rose}/><Text style={styles.bulkText}>Pin</Text></Pressable><Pressable disabled={busy} onPress={onUnpin} style={styles.bulkAction}><Pin size={15} color={colors.muted}/><Text style={styles.bulkText}>Unpin</Text></Pressable><Pressable disabled={busy} onPress={onForget} style={styles.bulkAction}><Trash2 size={15} color={colors.danger}/><Text style={[styles.bulkText,{color:colors.danger}]}>Forget</Text></Pressable><Pressable onPress={onCancel} style={styles.close}><X size={18} color={colors.muted}/></Pressable></FrostedSurface>;}
export function MemoryActionToast({message,onDismiss}:{message:string;onDismiss:()=>void}){useEffect(()=>{const timer=setTimeout(onDismiss,2600);return()=>clearTimeout(timer);},[onDismiss]);return <View pointerEvents="box-none" style={styles.toastPosition}><FrostedSurface intensity={92} style={styles.toast}><View style={styles.toastIcon}><Check size={14} strokeWidth={3} color="#fff"/></View><Text style={styles.toastText}>{message}</Text></FrostedSurface></View>;}

function MemoryIcon({type}:{type:string}){const props={size:18,color:colors.warm};if(type==='preference')return <Heart {...props}/>;if(type==='episodic')return <Sparkles {...props}/>;if(type==='open_thread')return <BellRing {...props}/>;if(type==='relationship')return <Brain {...props}/>;return <UserRound {...props}/>;}
function categoryLabel(type:string){return({semantic:'About you',emotional:'Emotional context',preference:'Preference',episodic:'Shared moment',relationship:'Relationship',open_thread:'Upcoming'}as Record<string,string>)[type]??'Memory';}
function relativeDue(value:Date){const days=Math.ceil((value.getTime()-Date.now())/86400000);if(days<0)return'Follow-up overdue';if(days===0)return'Due today';if(days===1)return'Due tomorrow';return`Due ${value.toLocaleDateString(undefined,{month:'short',day:'numeric'})}`;}

const styles=StyleSheet.create({
  companionRail:{width:230,minWidth:230,borderRadius:radius.lg,padding:12,gap:10,backgroundColor:'rgba(16,14,24,.72)'},railKicker:{color:colors.dimmed,fontSize:11,fontWeight:'900',letterSpacing:1.2,paddingHorizontal:4},railSearch:{minHeight:42,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:11,borderRadius:radius.md,backgroundColor:'rgba(255,255,255,.035)',borderWidth:1,borderColor:colors.border},railSearchInput:{flex:1,color:colors.text,fontSize:14},railList:{gap:5,paddingBottom:12},companionRow:{minHeight:60,flexDirection:'row',alignItems:'center',gap:9,padding:8,borderRadius:radius.md},companionRowActive:{backgroundColor:'rgba(216,62,234,.11)',borderWidth:1,borderColor:'rgba(216,62,234,.22)'},companionName:{color:colors.textSecondary,fontSize:14,fontWeight:'800'},companionNameActive:{color:colors.text},companionCount:{color:colors.muted,fontSize:11,marginTop:2},companionStripScroll:{height:56,maxHeight:56,flexGrow:0,flexShrink:0},companionStrip:{height:56,alignItems:'center',gap:7,paddingRight:12},companionChip:{height:44,maxHeight:44,flexShrink:0,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:8,borderRadius:radius.pill,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},companionChipActive:{backgroundColor:'rgba(216,62,234,.12)',borderColor:colors.rose},chipCopy:{minWidth:0,maxWidth:76},chipName:{color:colors.muted,fontSize:12,fontWeight:'800'},chipCount:{color:colors.dimmed,fontSize:10},
  memoryRow:{minHeight:108,flexDirection:'row',alignItems:'flex-start',gap:12,paddingHorizontal:15,paddingVertical:15,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,.065)',backgroundColor:'transparent'},memoryRowPressed:{backgroundColor:'rgba(216,62,234,.045)'},memoryRowSelected:{backgroundColor:'rgba(216,62,234,.085)'},memoryIcon:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(242,162,127,.08)'},selectionBox:{width:24,height:24,borderRadius:7,borderWidth:1,borderColor:colors.borderBright,alignItems:'center',justifyContent:'center',marginTop:4},selectionBoxActive:{backgroundColor:colors.rose,borderColor:colors.rose},memoryBody:{flex:1,minWidth:0},memoryMetaLine:{minHeight:22,flexDirection:'row',alignItems:'center',gap:7},memoryCategory:{color:colors.rose,fontSize:11,fontWeight:'900',letterSpacing:.65,textTransform:'uppercase'},directBadge:{flexDirection:'row',alignItems:'center',gap:4,paddingHorizontal:7,paddingVertical:3,borderRadius:radius.pill,backgroundColor:'rgba(216,62,234,.08)'},inferredBadge:{flexDirection:'row',alignItems:'center',gap:4,paddingHorizontal:7,paddingVertical:3,borderRadius:radius.pill,backgroundColor:'rgba(242,162,127,.08)'},directText:{color:colors.textSecondary,fontSize:11,fontWeight:'700'},inferredText:{color:colors.warm,fontSize:11,fontWeight:'700'},memoryText:{color:colors.text,fontSize:16,lineHeight:24,marginTop:6},memoryFoot:{minHeight:22,flexDirection:'row',alignItems:'center',gap:9,marginTop:8},sourceButton:{minWidth:0,flex:1,flexDirection:'row',alignItems:'center',gap:5},sourceText:{flexShrink:1,color:colors.muted,fontSize:12,lineHeight:17},sourceLink:{color:colors.textSecondary},dueText:{color:colors.warm,fontSize:12,fontWeight:'700'},memoryDate:{color:colors.dimmed,fontSize:11},rowAction:{width:44,height:44,alignItems:'center',justifyContent:'center'},
  insights:{borderRadius:radius.lg,padding:14,backgroundColor:'rgba(32,25,42,.78)',borderColor:'rgba(242,162,127,.18)'},insightsHeader:{flexDirection:'row',alignItems:'center',gap:10},insightIcon:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(242,162,127,.08)'},insightsKicker:{color:colors.warm,fontSize:9,fontWeight:'900',letterSpacing:1},insightsTitle:{color:colors.text,fontFamily:typography.display,fontSize:18,fontWeight:'700',marginTop:1},insightsContent:{gap:14,marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:colors.border},insightSection:{gap:7},insightLabel:{color:colors.dimmed,fontSize:9,fontWeight:'900',letterSpacing:1},insightRow:{flexDirection:'row',alignItems:'flex-start',gap:7},insightDot:{width:5,height:5,borderRadius:3,backgroundColor:colors.warm,marginTop:7},insightText:{flex:1,color:colors.textSecondary,fontSize:12,lineHeight:18},
  modalRoot:{flex:1,backgroundColor:'rgba(3,2,7,.70)'},modalDesktop:{alignItems:'flex-end',justifyContent:'flex-start'},modalMobile:{justifyContent:'flex-end'},detailSheet:{overflow:'hidden',backgroundColor:'rgba(25,20,35,.96)'},detailDesktop:{width:460,height:'100%',borderRadius:0,borderTopLeftRadius:radius.xl,borderBottomLeftRadius:radius.xl,padding:20},detailMobile:{width:'100%',maxHeight:'88%',borderTopLeftRadius:radius.xl,borderTopRightRadius:radius.xl,padding:18},sheetHandle:{display:'none',alignSelf:'center',width:42,height:4,borderRadius:2,backgroundColor:colors.borderBright,marginBottom:10},detailHeader:{flexDirection:'row',alignItems:'center',gap:11},detailIcon:{width:40,height:40,alignItems:'center',justifyContent:'center',borderRadius:20,backgroundColor:'rgba(255,255,255,.05)'},detailKicker:{color:colors.rose,fontSize:9,fontWeight:'900',letterSpacing:1},detailTitle:{color:colors.text,fontFamily:typography.display,fontSize:22,fontWeight:'700',marginTop:1},close:{width:40,height:40,alignItems:'center',justifyContent:'center',borderRadius:20,backgroundColor:'rgba(255,255,255,.045)'},detailScroll:{paddingBottom:32},detailMemory:{color:colors.text,fontSize:17,lineHeight:26,marginTop:22},detailMeta:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,marginTop:15},detailDate:{color:colors.muted,fontSize:11},sourceCard:{flexDirection:'row',alignItems:'center',gap:8,padding:13,borderRadius:radius.md,backgroundColor:colors.surface,marginTop:14},sourceLabel:{color:colors.dimmed,fontSize:9,fontWeight:'900',letterSpacing:1},sourceCardText:{flex:1,color:colors.textSecondary,fontSize:12,lineHeight:17},corrected:{color:colors.warm,fontSize:11,fontWeight:'700',marginTop:11},detailActions:{flexDirection:'row',gap:8,marginTop:19},detailAction:{flex:1,minHeight:46,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,borderRadius:radius.md,backgroundColor:colors.surface},detailDanger:{borderWidth:1,borderColor:'rgba(255,107,121,.24)'},detailActionText:{color:colors.text,fontSize:12,fontWeight:'900'},historyBlock:{gap:9,marginTop:24,paddingTop:17,borderTopWidth:1,borderTopColor:colors.border},historyHeader:{flexDirection:'row',alignItems:'center',gap:7},historyTitle:{color:colors.text,fontSize:13,fontWeight:'900'},revision:{flexDirection:'row',alignItems:'center',gap:9,padding:11,borderRadius:radius.md,backgroundColor:'rgba(255,255,255,.025)'},revisionLabel:{color:colors.dimmed,fontSize:8,fontWeight:'900',letterSpacing:.8},revisionText:{color:colors.textSecondary,fontSize:12,lineHeight:17,marginTop:3},restore:{paddingHorizontal:10,paddingVertical:8,borderRadius:radius.sm,backgroundColor:'rgba(216,62,234,.10)'},restoreText:{color:colors.rose,fontSize:10,fontWeight:'900'},historyEmpty:{color:colors.muted,fontSize:11},
  editorRoot:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.lg,backgroundColor:'rgba(3,2,7,.72)'},editor:{width:'100%',maxWidth:600,maxHeight:'90%',padding:20,borderRadius:radius.xl,backgroundColor:'rgba(26,20,37,.97)',borderColor:'rgba(216,62,234,.26)'},editorHint:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:13},typeRow:{gap:7,paddingVertical:14},typeChip:{paddingHorizontal:11,paddingVertical:8,borderRadius:radius.pill,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},typeChipActive:{backgroundColor:'rgba(216,62,234,.13)',borderColor:colors.rose},typeText:{color:colors.muted,fontSize:11,fontWeight:'800'},typeTextActive:{color:colors.text},editorInput:{minHeight:130,maxHeight:260,color:colors.text,fontSize:15,lineHeight:22,textAlignVertical:'top',padding:14,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},editorBottom:{gap:13,marginTop:14},pinToggle:{minHeight:46,flexDirection:'row',alignItems:'center',gap:8},pinToggleText:{flex:1,color:colors.textSecondary,fontSize:12},save:{minHeight:48,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.rose},saveText:{color:'#fff',fontSize:13,fontWeight:'900'},disabled:{opacity:.45},privacySheet:{width:'100%',maxWidth:620,maxHeight:'90%',padding:20,borderRadius:radius.xl,backgroundColor:'rgba(26,20,37,.97)'},controlList:{gap:8,paddingTop:16},control:{minHeight:62,flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:13,borderRadius:radius.md,backgroundColor:colors.surface},controlTitle:{color:colors.text,fontSize:13,fontWeight:'800'},controlCopy:{color:colors.muted,fontSize:10,marginTop:3},erase:{minHeight:64,flexDirection:'row',alignItems:'center',gap:11,padding:13,borderRadius:radius.md,borderWidth:1,borderColor:'rgba(255,107,121,.28)',marginTop:5},eraseTitle:{color:colors.danger,fontWeight:'800',fontSize:12},eraseCopy:{color:colors.muted,fontSize:10,lineHeight:14,marginTop:2},
  bulkBar:{position:'absolute',left:14,right:14,bottom:14,zIndex:20,minHeight:58,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:12,borderRadius:radius.lg,backgroundColor:'rgba(25,19,35,.94)',borderColor:'rgba(216,62,234,.27)'},bulkCount:{color:colors.text,fontSize:12,fontWeight:'900',marginRight:'auto'},bulkAction:{minHeight:38,flexDirection:'row',alignItems:'center',gap:5,paddingHorizontal:9,borderRadius:radius.sm,backgroundColor:'rgba(255,255,255,.04)'},bulkText:{color:colors.textSecondary,fontSize:10,fontWeight:'800'},toastPosition:{position:'absolute',left:16,right:16,bottom:22,zIndex:100,alignItems:'center'},toast:{minHeight:48,maxWidth:420,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:15,paddingVertical:10,borderRadius:radius.lg,backgroundColor:'rgba(26,17,37,.92)',borderColor:'rgba(216,62,234,.30)'},toastIcon:{width:25,height:25,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:colors.rose},toastText:{color:colors.text,fontSize:13,fontWeight:'800'},
});
