import { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { ArrowUpRight, BellRing, Brain, Check, Heart, History, Pin, Scale, ShieldCheck, Sparkles, Trash2, UserRound, X } from 'lucide-react-native';
import type { MemoryCenterAuthorKind, MemoryCenterItem, UserPersona } from '../../types';
import { colors } from '../../theme';
import { presentMemoryText } from '../../lib/memoryPresentation';
import { MEMORY_AUTHOR_KINDS, memoryJournalLabel } from '../../lib/memoryCenter';
import { FrostedSurface } from '../FrostedGlass';
import { styles } from './memoryStyles';

export function MemoryDetailSheet({memory,name,revisions,historyLoading,busy,manualControl,onClose,onEdit,onPin,onForget,onRestore,onSource}:{memory:MemoryCenterItem|null;name:string;revisions:MemoryCenterItem[];historyLoading:boolean;busy:boolean;manualControl:boolean;onClose:()=>void;onEdit:(memory:MemoryCenterItem)=>void;onPin:(memory:MemoryCenterItem)=>void;onForget:(memory:MemoryCenterItem)=>void;onRestore:(memory:MemoryCenterItem,revision:MemoryCenterItem)=>void;onSource?:(memory:MemoryCenterItem)=>void}){
  const{width}=useWindowDimensions(),desktop=width>=900;
  return <Modal visible={Boolean(memory)} transparent animationType="fade" onRequestClose={onClose}><View style={[styles.modalRoot,desktop?styles.modalDesktop:styles.modalMobile]}><Pressable accessibilityLabel="Close memory details" onPress={onClose} style={StyleSheet.absoluteFill}/>{memory?<FrostedSurface intensity={96} style={[styles.detailSheet,desktop?styles.detailDesktop:styles.detailMobile]}><View style={styles.sheetHandle}/><View style={styles.detailHeader}><View style={styles.detailIcon}><MemoryIcon memory={memory}/></View><View style={{flex:1}}><Text style={styles.detailKicker}>{memoryJournalLabel(memory).toUpperCase()}</Text><Text style={styles.detailTitle}>Memory details</Text></View><Pressable accessibilityLabel="Close" onPress={onClose} style={styles.close}><X size={20} color={colors.muted}/></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.detailScroll}><Text style={styles.detailMemory}>{presentMemoryText(memory.canonical_text,name)}</Text><View style={styles.detailMeta}><View style={memory.knowledgeKind==='inferred'?styles.inferredBadge:styles.directBadge}>{memory.knowledgeKind==='inferred'?<Sparkles size={12} color={colors.warm}/>:<Check size={12} color={colors.rose}/>}<Text style={memory.knowledgeKind==='inferred'?styles.inferredText:styles.directText}>{memory.knowledgeKind==='inferred'?'Learned pattern':'Directly shared'}</Text></View><Text style={styles.detailDate}>Updated {new Date(memory.updated_at).toLocaleDateString()}</Text></View>{memory.sourceContext?<Pressable disabled={!onSource} onPress={()=>onSource?.(memory)} style={styles.sourceCard}><Text style={styles.sourceLabel}>SOURCE</Text><Text style={styles.sourceCardText}>{memory.sourceContext}</Text>{onSource?<ArrowUpRight size={16} color={colors.violet}/>:null}</Pressable>:null}{memory.corrected?<Text style={styles.corrected}>This replaced an earlier version.</Text>:null}
      <View style={styles.detailActions}>{manualControl?<><Pressable disabled={busy} onPress={()=>onPin(memory)} style={styles.detailAction}><Pin size={17} color={colors.rose}/><Text style={styles.detailActionText}>{memory.pinned?'Unpin':'Pin'}</Text></Pressable><Pressable disabled={busy} onPress={()=>onEdit(memory)} style={styles.detailAction}><Sparkles size={17} color={colors.violet}/><Text style={styles.detailActionText}>Correct</Text></Pressable></>:null}<Pressable disabled={busy} onPress={()=>onForget(memory)} style={[styles.detailAction,styles.detailDanger]}><Trash2 size={17} color={colors.danger}/><Text style={[styles.detailActionText,{color:colors.danger}]}>Forget</Text></Pressable></View>
      <View style={styles.historyBlock}><View style={styles.historyHeader}><History size={16} color={colors.violet}/><Text style={styles.historyTitle}>Correction history</Text></View>{historyLoading?<ActivityIndicator color={colors.rose}/>:revisions.length>1?revisions.map((revision,index)=><View key={revision.id} style={styles.revision}><View style={{flex:1}}><Text style={styles.revisionLabel}>{index===0?'CURRENT':`EARLIER · ${new Date(revision.updated_at).toLocaleDateString()}`}</Text><Text style={styles.revisionText}>{presentMemoryText(revision.canonical_text,name)}</Text></View>{index>0&&manualControl?<Pressable disabled={busy} onPress={()=>onRestore(memory,revision)} style={styles.restore}><Text style={styles.restoreText}>Restore</Text></Pressable>:null}</View>):<Text style={styles.historyEmpty}>No earlier corrections.</Text>}</View>
    </ScrollView></FrostedSurface>:null}</View></Modal>;
}

export function MemoryEditorSheet({visible,name,memory,busy,personas=[],activePersonaId,onClose,onSave}:{visible:boolean;name:string;memory?:MemoryCenterItem|null;busy:boolean;personas?:UserPersona[];activePersonaId?:string;onClose:()=>void;onSave:(input:{text:string;kind:MemoryCenterAuthorKind;personaId?:string;pinned:boolean})=>void}){
  const[text,setText]=useState('');
  const[kind,setKind]=useState<MemoryCenterAuthorKind>('about');
  const[personaId,setPersonaId]=useState('');
  const[pinned,setPinned]=useState(false);
  useEffect(()=>{
    if(!visible)return;
    setText(memory?presentMemoryText(memory.canonical_text,name):'');
    setKind(memory?.kind==='core_rule'||memory?.coreRule?'core_rule':memory?.kind==='additional'?'additional':'about');
    setPinned(Boolean(memory?.pinned));
    setPersonaId(memory?.personaId||activePersonaId||personas[0]?.id||'');
  },[activePersonaId,memory,name,visible]);
  const selectedKind=MEMORY_AUTHOR_KINDS.find((item)=>item.key===kind)??MEMORY_AUTHOR_KINDS[1];
  const showPersonaPicker=!memory&&kind==='about'&&personas.length>1;
  const chooseKind=(next:MemoryCenterAuthorKind)=>{
    setKind(next);
    if(next==='core_rule')setPinned(true);
  };
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.editorRoot}><Pressable onPress={onClose} style={StyleSheet.absoluteFill}/><FrostedSurface intensity={96} style={styles.editor}>
    <View style={styles.detailHeader}><View style={styles.detailIcon}><Brain size={19} color={colors.rose}/></View><View style={{flex:1}}><Text style={styles.detailKicker}>{memory?'CORRECT MEMORY':'REMEMBER SOMETHING'}</Text><Text style={styles.detailTitle}>{memory?`Update what ${name.split(' ')[0]} knows`:`Add a memory for ${name.split(' ')[0]}`}</Text></View><Pressable onPress={onClose} style={styles.close}><X size={20} color={colors.muted}/></Pressable></View>
    <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
      <Text style={styles.editorHint}>{memory?'Write the accurate version. The earlier wording stays in correction history.':selectedKind?.hint}</Text>
      {!memory?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.typeRow}>{MEMORY_AUTHOR_KINDS.map((option)=><Pressable key={option.key} onPress={()=>chooseKind(option.key)} style={[styles.typeChip,kind===option.key&&styles.typeChipActive]}><Text style={[styles.typeText,kind===option.key&&styles.typeTextActive]}>{option.label}</Text></Pressable>)}</ScrollView>:null}
      {showPersonaPicker?<View style={styles.personaBlock}><Text style={styles.personaLabel}>PERSONA</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.personaRow}>
        <Pressable onPress={()=>setPersonaId('')} style={[styles.typeChip,!personaId&&styles.typeChipActive]}><Text style={[styles.typeText,!personaId&&styles.typeTextActive]}>Any persona</Text></Pressable>
        {personas.map((persona)=><Pressable key={persona.id} onPress={()=>setPersonaId(persona.id)} style={[styles.typeChip,personaId===persona.id&&styles.typeChipActive]}><Text style={[styles.typeText,personaId===persona.id&&styles.typeTextActive]}>{persona.display_name||persona.name}</Text></Pressable>)}
      </ScrollView></View>:null}
      <TextInput multiline autoFocus value={text} onChangeText={setText} maxLength={2000} placeholder={kind==='core_rule'?'What should always be true between you?':'What should be remembered?'} placeholderTextColor={colors.dimmed} style={styles.editorInput}/>
      <View style={styles.editorBottom}><View style={styles.pinToggle}><Pin size={16} color={colors.rose}/><Text style={styles.pinToggleText}>{kind==='core_rule'?'Keep this in effect every turn':'Keep this easy to recall'}</Text><Switch value={kind==='core_rule'?true:pinned} onValueChange={setPinned} disabled={kind==='core_rule'} trackColor={{false:colors.elevated,true:colors.rose}}/></View>
        <Pressable disabled={busy||!text.trim()} onPress={()=>onSave({text:text.trim(),kind,pinned:kind==='core_rule'?true:pinned,...(kind==='about'&&personaId?{personaId}:{})})} style={[styles.save,busy||!text.trim()?styles.disabled:null]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.saveText}>{memory?'Save correction':'Remember this'}</Text>}</Pressable>
      </View>
    </ScrollView>
  </FrostedSurface></View></Modal>;
}

export function MemoryPrivacySheet({visible,categories,busy,globalErase=false,onClose,onToggle,onForgetAll}:{visible:boolean;categories:Record<string,boolean>;busy:string;globalErase?:boolean;onClose:()=>void;onToggle:(key:string,value:boolean)=>void;onForgetAll:()=>void}){
  const controls:Array<[string,string,string]>=[['semantic','About you','Facts and personal details'],['preference','Preferences','Likes, dislikes, and tastes'],['episodic','Shared experiences','Things you experienced together'],['relationship','Relationship','Meaningful relationship context'],['emotional','Emotional context','Durable emotional patterns'],['open_thread','Upcoming things','Questions and follow-ups']];
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.editorRoot}><Pressable onPress={onClose} style={StyleSheet.absoluteFill}/><FrostedSurface intensity={96} style={styles.privacySheet}><View style={styles.detailHeader}><View style={styles.detailIcon}><ShieldCheck size={20} color={colors.violet}/></View><View style={{flex:1}}><Text style={styles.detailKicker}>MEMORY CONTROLS</Text><Text style={styles.detailTitle}>Your privacy, your choice</Text></View><Pressable onPress={onClose} style={styles.close}><X size={20} color={colors.muted}/></Pressable></View><Text style={styles.editorHint}>These controls are available on every plan and change what companions may retain and recall.</Text><ScrollView contentContainerStyle={styles.controlList}>{controls.map(([key,label,description])=><View key={key} style={styles.control}><View style={{flex:1}}><Text style={styles.controlTitle}>{label}</Text><Text style={styles.controlCopy}>{description}</Text></View>{busy===key?<ActivityIndicator color={colors.rose}/>:<Switch disabled={Boolean(busy)} value={categories[key]!==false} onValueChange={(value)=>onToggle(key,value)} trackColor={{false:colors.elevated,true:colors.rose}}/>}</View>)}<Pressable disabled={Boolean(busy)} onPress={onForgetAll} style={styles.erase}><Trash2 size={18} color={colors.danger}/><View style={{flex:1}}><Text style={styles.eraseTitle}>{globalErase?'Erase everything remembered in this Life':'Forget everything for this companion'}</Text><Text style={styles.eraseCopy}>Conversation history and relationship progress remain.</Text></View></Pressable></ScrollView></FrostedSurface></View></Modal>;
}

function MemoryIcon({memory}:{memory:Pick<MemoryCenterItem,'memory_type'|'kind'|'coreRule'>}){const props={size:18,color:colors.warm};if(memory.coreRule||memory.kind==='core_rule')return <Scale {...props}/>;if(memory.memory_type==='preference')return <Heart {...props}/>;if(memory.memory_type==='episodic')return <Sparkles {...props}/>;if(memory.memory_type==='open_thread')return <BellRing {...props}/>;if(memory.memory_type==='relationship'||memory.kind==='additional')return <Brain {...props}/>;return <UserRound {...props}/>;}
