import { useEffect, useMemo, useState } from 'react';
import { Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { router, useLocalSearchParams } from 'expo-router';
import { AlertTriangle, ArrowLeft, CalendarDays, Check, Clock3, MapPin, RotateCcw, Trash2, UserCheck } from 'lucide-react-native';
import { DateTimeFields, EmptyState, GlassCard, GradientButton, LoadingSkeleton, Screen } from '../../src/components';
import { colors, radius, spacing } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';
import { managePlan } from '../../src/lib/api';
import { commitmentStatusLabel, commitmentTemporalState, commitmentTimeLabel, explainMissedCommitment, getCommitment, joinCommitment, type Commitment } from '../../src/lib/commitments';
import { confirmAction } from '../../src/lib/dialogs';
import { parseCustomPlanTime, recommendPlanOptions } from '../../src/lib/plans';

export default function PlanDetail(){
  const{id}=useLocalSearchParams<{id:string}>(),{snapshot,refresh}=useTogether();
  const[detail,setDetail]=useState<Commitment|null>(null),[editingTime,setEditingTime]=useState(false),[editingPlace,setEditingPlace]=useState(false),[dateValue,setDateValue]=useState(''),[timeValue,setTimeValue]=useState('19:30'),[note,setNote]=useState<string|null>(null),[explanation,setExplanation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const snapshotPlan=snapshot?.sharedPlans?.find((item)=>item.id===id),plan=(detail??snapshotPlan)as Commitment|undefined,character=snapshot?.characters.find((item)=>item.id===plan?.character_instance_id),location=snapshot?.locations.find((item)=>item.id===plan?.location_id);
  useEffect(()=>{if(!id)return;let active=true;void getCommitment(id).then((value)=>{if(active)setDetail(value);}).catch(()=>undefined);return()=>{active=false;};},[id]);
  const locations=useMemo(()=>snapshot&&character&&plan?recommendPlanOptions({activity:character.current_activity,mood:character.current_mood,locationId:character.current_location_id,interests:[...(snapshot.activePersona?.interests??[]),...character.together_character_versions.interests],relationshipStage:character.relationship_stage,locations:snapshot.locations.filter((item)=>!plan.world_id||item.world_id===plan.world_id),chooseElsewhere:true,previousPlans:snapshot.sharedPlans}).filter((item)=>item.activityKey===plan.activity_key||item.tags.some((tag)=>plan.activity_key.includes(tag))).slice(0,8):[],[snapshot,character,plan]);
  if(!snapshot)return <LoadingSkeleton label="Loading plan…"/>;if(!plan||!character)return <EmptyState title="Plan unavailable" body="It may have been removed or belongs to another companion."/>;
  const temporal=plan.temporalState??commitmentTemporalState(plan),viewerTimezone=Intl.DateTimeFormat().resolvedOptions().timeZone,stateLabel=commitmentStatusLabel({...plan,temporalState:temporal}),canEdit=['proposed','scheduled'].includes(plan.status),canJoin=plan.participation_mode!=='ambient'&&!plan.attendance?.user&&['en_route','imminent','active','grace'].includes(temporal)&&!['missed','cancelled','completed'].includes(plan.status);
  const exactStart=plan.starts_at?new Date(plan.starts_at):null,exactEnd=plan.ends_at?new Date(plan.ends_at):null;
  const schedule=exactStart?snapshot.schedules.filter((item)=>item.character_version_id===character.character_version_id&&item.day_of_week===exactStart.getDay()&&item.availability==='busy'&&item.end_minute<=exactStart.getHours()*60+exactStart.getMinutes()).sort((a,b)=>b.end_minute-a.end_minute)[0]:undefined;
  const currentNote=note===null?(plan.note??''):note;
  const mutate=async(input:Record<string,unknown>)=>{setBusy(true);setError('');try{await managePlan({planId:plan.id,...input});const fresh=await getCommitment(plan.id);setDetail(fresh);await refresh();if(Platform.OS!=='web')void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);setEditingTime(false);setEditingPlace(false);}catch(caught){setError(caught instanceof Error?caught.message:'The plan could not be changed.');}finally{setBusy(false);}};
  const openTimeEditor=()=>{if(exactStart){setDateValue(exactStart.toISOString().slice(0,10));setTimeValue(`${String(exactStart.getHours()).padStart(2,'0')}:${String(exactStart.getMinutes()).padStart(2,'0')}`);}else if(plan.window_starts_at){const value=new Date(plan.window_starts_at);setDateValue(value.toISOString().slice(0,10));setTimeValue(`${String(value.getHours()).padStart(2,'0')}:${String(value.getMinutes()).padStart(2,'0')}`);}setEditingTime((value)=>!value);};
  const saveTime=()=>{const value=parseCustomPlanTime(dateValue,timeValue);if(!value){setError('Use a date like 2026-08-16 and a time like 19:30.');return;}void mutate({action:'reschedule',startsAt:value.toISOString(),timePrecision:'exact',conversationId:(snapshotPlan as unknown as {source_conversation_id?:string|null})?.source_conversation_id});};
  const cancel=()=>confirmAction({title:'Cancel this plan?',message:`Cancel ${plan.title}? ${character.together_character_templates.name} will know it changed.`,confirmLabel:'Cancel plan',onConfirm:async()=>{await mutate({action:'cancel',conversationId:(snapshotPlan as unknown as {source_conversation_id?:string|null})?.source_conversation_id});}});
  const join=async()=>{setBusy(true);setError('');try{const value=await joinCommitment(plan.id,character.id);setDetail(value);await refresh();if(Platform.OS!=='web')void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);}catch(caught){setError(caught instanceof Error?caught.message:'Could not join this plan.');}finally{setBusy(false);}};
  const explain=async()=>{if(!explanation.trim()){setError('Tell them what happened first.');return;}setBusy(true);setError('');try{const value=await explainMissedCommitment(plan.id,character.id,explanation.trim(),(snapshotPlan as unknown as {source_conversation_id?:string|null})?.source_conversation_id??undefined);setDetail(value);setExplanation('');await refresh();}catch(caught){setError(caught instanceof Error?caught.message:'Could not save that explanation.');}finally{setBusy(false);}};
  const missed=plan.status==='missed',resolution=plan.missResolution;
  const headerKicker=missed?'MISSED COMMITMENT':plan.status==='active'?'TOGETHER NOW':plan.status==='completed'?'SHARED HISTORY':plan.status==='cancelled'?'CANCELLED':plan.status==='proposed'?'TIME TO SET':'UPCOMING TOGETHER';
  return <Screen contentStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={()=>router.canGoBack()?router.back():router.replace('/(tabs)/dates')} style={styles.icon}><ArrowLeft color={colors.text}/></Pressable><View style={{flex:1}}><Text style={[styles.kicker,missed&&styles.kickerMissed]}>{headerKicker}</Text><Text style={styles.title}>{plan.title}</Text></View><View style={[styles.status,['cancelled','missed'].includes(plan.status)&&styles.cancelled]}><Text style={styles.statusText}>{stateLabel}</Text></View></View>
    <GlassCard style={styles.card}>
      <Detail icon={<CalendarDays color={colors.rose}/>} label="WHEN" value={plan.time_precision==='exact'&&exactStart?exactStart.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'}):(plan.original_time_expression??'Time window')}/>
      <Detail icon={<Clock3 color={colors.warm}/>} label="TIME" value={commitmentTimeLabel(plan,viewerTimezone)}/>
      <Detail icon={<MapPin color={colors.violet}/>} label="PLACE" value={location?.name??plan.together_locations?.name??'Place not set'}/>
      {exactEnd&&plan.time_precision==='exact'?<Text style={styles.small}>Expected through {exactEnd.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} · {plan.world_timezone??'world local time'}</Text>:null}
    </GlassCard>
    {plan.companion_state==='late'?<GlassCard style={styles.notice}><Clock3 color={colors.warm}/><View style={{flex:1}}><Text style={styles.noticeTitle}>{character.together_character_templates.name} is running late.</Text><Text style={styles.noticeCopy}>{plan.companion_reason??'Their arrival changed.'}{plan.companion_eta_at?` New ETA: ${new Date(plan.companion_eta_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}.`:''}</Text></View></GlassCard>:null}
    {plan.companion_state==='absent'?<GlassCard style={styles.notice}><AlertTriangle color={colors.warm}/><View style={{flex:1}}><Text style={styles.noticeTitle}>{character.together_character_templates.name} couldn't make it.</Text><Text style={styles.noticeCopy}>{plan.companion_reason??'The plan changed on their side.'} This does not count as you missing the plan.</Text></View></GlassCard>:null}
    {temporal==='grace'&&!plan.attendance?.user?<GlassCard style={styles.waiting}><Clock3 color={colors.rose}/><View style={{flex:1}}><Text style={styles.noticeTitle}>{character.together_character_templates.name} is waiting.</Text><Text style={styles.noticeCopy}>Join before the grace period ends so Kivelle records that you made it.</Text></View></GlassCard>:null}
    {canJoin?<GradientButton label={busy?'Joining…':`Join ${character.together_character_templates.name}`} onPress={()=>void join()}/>:null}
    {plan.attendance?.user&&plan.status==='active'?<View style={styles.attended}><UserCheck size={17} color={colors.success}/><Text style={styles.attendedText}>You're here. This shared time counts as attended.</Text></View>:null}
    {missed?<GlassCard style={styles.missed}><View style={styles.missedTop}><AlertTriangle color={colors.danger}/><View style={{flex:1}}><Text style={styles.missedTitle}>{plan.miss_reason==='user_absent'?`${character.together_character_templates.name} waited for you.`:'This plan did not happen.'}</Text><Text style={styles.missedCopy}>{plan.miss_reason==='user_absent'?`Kivelle recorded the missed commitment. ${resolution?.status==='repaired'?'You talked about what happened.':'What happens next depends on the conversation, not an automatic punishment.'}`:'A technical or companion-caused miss does not penalize your relationship.'}</Text></View></View>{plan.miss_reason==='user_absent'&&!['repaired','resolved'].includes(resolution?.status??'')?<><TextInput value={explanation} onChangeText={setExplanation} placeholder="Tell them what happened…" placeholderTextColor={colors.dimmed} multiline style={styles.explanation}/><GradientButton label={busy?'Saving…':'Explain what happened'} onPress={()=>void explain()}/><Pressable onPress={()=>router.push(`/chat?character=${character.together_character_templates.public_handle??character.together_character_templates.slug}&planId=${plan.id}&draft=${encodeURIComponent(`I'm sorry I missed ${plan.title}.`)}` as never)} style={styles.secondary}><Text style={styles.secondaryText}>Talk about it in Chat</Text></Pressable></>:resolution?.status==='repaired'?<View style={styles.repaired}><Check size={16} color={colors.success}/><Text style={styles.attendedText}>Repair recorded. Future conversation can remember how you handled it.</Text></View>:null}</GlassCard>:null}
    {schedule&&!missed?<Text style={styles.companionContext}>{character.together_character_templates.name} finishes {schedule.activity} at {formatMinute(schedule.end_minute)}.</Text>:null}
    {!missed?<View style={styles.noteBlock}><Text style={styles.label}>NOTE · OPTIONAL</Text><TextInput value={currentNote} onChangeText={setNote} placeholder="Outdoor table if the weather is good." placeholderTextColor={colors.dimmed} multiline style={styles.note}/><Pressable disabled={busy||currentNote===(plan.note??'')} onPress={()=>void mutate({action:'update',note:currentNote})} style={[styles.secondary,busy&&styles.disabled]}><Text style={styles.secondaryText}>Save note</Text></Pressable></View>:null}
    {editingTime?<GlassCard style={styles.editor}><Text style={styles.editorTitle}>{plan.starts_at?'Change date & time':'Set exact date & time'}</Text><DateTimeFields date={dateValue} time={timeValue} onDateChange={setDateValue} onTimeChange={setTimeValue}/><GradientButton label={busy?'Checking…':'Save exact time'} onPress={saveTime}/></GlassCard>:null}
    {editingPlace?<GlassCard style={styles.editor}><Text style={styles.editorTitle}>Change place</Text>{locations.map((option)=><Pressable key={option.id} onPress={()=>void mutate({action:'update',locationId:option.locationId,conversationId:(snapshotPlan as unknown as {source_conversation_id?:string|null})?.source_conversation_id})} style={styles.place}><View style={{flex:1}}><Text style={styles.placeTitle}>{option.locationName}</Text><Text style={styles.placeReason}>{option.reason}</Text></View><MapPin size={16} color={colors.rose}/></Pressable>)}</GlassCard>:null}
    {error?<Text style={styles.error}>{error}</Text>:null}
    {!missed?<GradientButton label={plan.status==='completed'?'Talk about it':`Message ${character.together_character_templates.name}`} onPress={()=>router.push(`/chat?character=${character.together_character_templates.public_handle??character.together_character_templates.slug}&planId=${plan.id}&draft=${encodeURIComponent(plan.status==='completed'?'Last time was fun.':plan.status==='proposed'?'What time should we make our plan?':'Still good for our plan?')}` as never)}/>:null}
    {plan.status==='completed'?<Pressable onPress={()=>router.push(`/chat?character=${character.together_character_templates.public_handle??character.together_character_templates.slug}&plan=1&repeatPlanId=${plan.id}` as never)} style={styles.secondary}><RotateCcw size={17} color={colors.rose}/><Text style={styles.secondaryText}>Go again</Text></Pressable>:null}
    {canEdit?<View style={styles.actions}><Pressable onPress={openTimeEditor} style={styles.secondary}><Clock3 size={17} color={colors.rose}/><Text style={styles.secondaryText}>{plan.starts_at?'Change time':'Set exact time'}</Text></Pressable><Pressable onPress={()=>setEditingPlace((value)=>!value)} style={styles.secondary}><MapPin size={17} color={colors.violet}/><Text style={styles.secondaryText}>Change place</Text></Pressable><Pressable onPress={cancel} style={[styles.secondary,styles.danger]}><Trash2 size={17} color={colors.danger}/><Text style={[styles.secondaryText,{color:colors.danger}]}>Cancel plan</Text></Pressable></View>:null}
  </Screen>;
}
function Detail({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <View style={styles.detail}>{icon}<View style={{flex:1}}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View></View>}
function formatMinute(value:number){const hour=Math.floor(value/60),minute=value%60;return new Date(2000,0,1,hour,minute).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
const styles=StyleSheet.create({content:{gap:spacing.lg,maxWidth:720},header:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface},kicker:{color:colors.rose,fontSize:9,fontWeight:'900',letterSpacing:1.2},kickerMissed:{color:colors.danger},title:{fontFamily:'Georgia',fontSize:28,color:colors.text,marginTop:3},status:{paddingHorizontal:10,paddingVertical:7,borderRadius:radius.pill,backgroundColor:'rgba(241,103,154,.12)'},cancelled:{backgroundColor:colors.surface},statusText:{color:colors.text,fontSize:9,fontWeight:'900'},card:{gap:16},detail:{flexDirection:'row',alignItems:'center',gap:12},label:{color:colors.dimmed,fontSize:9,fontWeight:'900',letterSpacing:1},value:{color:colors.text,fontSize:14,fontWeight:'800',marginTop:3},small:{color:colors.muted,fontSize:10,marginLeft:36},companionContext:{color:colors.warm,fontSize:11,fontWeight:'700',marginTop:-8},notice:{flexDirection:'row',gap:11,alignItems:'flex-start'},waiting:{flexDirection:'row',gap:11,alignItems:'flex-start',borderColor:'rgba(241,103,154,.3)'},noticeTitle:{color:colors.text,fontSize:13,fontWeight:'900'},noticeCopy:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:3},attended:{flexDirection:'row',alignItems:'center',gap:8,padding:12,borderRadius:radius.md,backgroundColor:'rgba(78,203,141,.08)'},attendedText:{color:colors.text,fontSize:11,fontWeight:'700',flex:1},missed:{gap:12,borderColor:'rgba(255,93,121,.26)'},missedTop:{flexDirection:'row',gap:11,alignItems:'flex-start'},missedTitle:{fontFamily:'Georgia',fontSize:20,color:colors.text},missedCopy:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:4},explanation:{minHeight:92,borderRadius:radius.md,backgroundColor:colors.background,borderWidth:1,borderColor:colors.border,color:colors.text,padding:12,textAlignVertical:'top'},repaired:{flexDirection:'row',gap:8,alignItems:'center'},noteBlock:{gap:8},note:{minHeight:82,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,color:colors.text,padding:13,textAlignVertical:'top'},editor:{gap:12},editorTitle:{color:colors.text,fontFamily:'Georgia',fontSize:20},place:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10,borderTopWidth:1,borderTopColor:colors.border},placeTitle:{color:colors.text,fontSize:13,fontWeight:'800'},placeReason:{color:colors.muted,fontSize:10,marginTop:3},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},secondary:{minHeight:42,paddingHorizontal:13,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.text,fontSize:11,fontWeight:'800'},danger:{borderColor:'rgba(255,93,121,.25)'},disabled:{opacity:.4},error:{color:colors.danger,fontSize:12,textAlign:'center'}});
