import { useEffect, useMemo, useState } from 'react';
import { Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, CalendarDays, Clock3, MapPin, RotateCcw, Trash2 } from 'lucide-react-native';
import { DateTimeFields, EmptyState, GlassCard, GradientButton, LoadingSkeleton, Screen } from '../../src/components';
import { colors, radius, spacing } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';
import { managePlan } from '../../src/lib/api';
import { confirmAction } from '../../src/lib/dialogs';
import { parseCustomPlanTime, recommendPlanOptions } from '../../src/lib/plans';
import { locationsForWorld, worldForLocation } from '../../src/lib/place';

export default function PlanDetail(){
  const{id}=useLocalSearchParams<{id:string}>(),{snapshot,refresh}=useTogether();
  const[editingTime,setEditingTime]=useState(false),[editingPlace,setEditingPlace]=useState(false),[dateValue,setDateValue]=useState(''),[timeValue,setTimeValue]=useState('19:30'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const plan=snapshot?.sharedPlans?.find((item)=>item.id===id),character=snapshot?.characters.find((item)=>item.id===plan?.character_instance_id),location=snapshot?.locations.find((item)=>item.id===plan?.location_id),planWorld=snapshot&&location?worldForLocation(snapshot,location.id):undefined;
  useEffect(()=>{if(plan)setNote(plan.note??'');},[plan?.id,plan?.note]);
  const locations=useMemo(()=>{
    if(!snapshot||!character||!plan)return[];
    const personaInterests=snapshot.activePersona?.interests??[];
    const worldLocations=planWorld?locationsForWorld(snapshot,planWorld.id):snapshot.locations;
    return recommendPlanOptions({activity:character.current_activity,mood:character.current_mood,locationId:character.current_location_id,interests:[...personaInterests,...character.together_character_versions.interests],relationshipStage:character.relationship_stage,locations:worldLocations,chooseElsewhere:true,previousPlans:snapshot.sharedPlans}).filter((item)=>item.activityKey===plan.activity_key||item.tags.some((tag)=>plan.activity_key.includes(tag))).slice(0,8);
  },[snapshot,character,plan,planWorld]);
  if(!snapshot)return <LoadingSkeleton label="Loading plan…"/>;if(!plan||!character)return <EmptyState title="Plan unavailable" body="It may have been removed or belongs to another companion."/>;
  const mutate=async(input:Record<string,unknown>)=>{setBusy(true);setError('');try{await managePlan({planId:plan.id,...input});await refresh();if(Platform.OS!=='web')void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);setEditingTime(false);setEditingPlace(false);}catch(caught){setError(caught instanceof Error?caught.message:'The plan could not be changed.');}finally{setBusy(false);}};
  const openTime=()=>{const current=new Date(plan.starts_at);setDateValue(`${current.getFullYear()}-${String(current.getMonth()+1).padStart(2,'0')}-${String(current.getDate()).padStart(2,'0')}`);setTimeValue(`${String(current.getHours()).padStart(2,'0')}:${String(current.getMinutes()).padStart(2,'0')}`);setEditingTime(true);setEditingPlace(false);setError('');};
  const saveTime=()=>{const value=parseCustomPlanTime(dateValue,timeValue);if(!value){setError('Choose a valid date and time.');return;}void mutate({action:'reschedule',startsAt:value.toISOString(),conversationId:plan.source_conversation_id});};
  const cancel=()=>confirmAction({title:'Cancel this plan?',message:`Cancel ${plan.title}? ${character.together_character_templates.name} will know it changed.`,confirmLabel:'Cancel plan',onConfirm:async()=>{await mutate({action:'cancel',conversationId:plan.source_conversation_id});}});
  const canEdit=['proposed','scheduled'].includes(plan.status);
  const schedule=snapshot.schedules.filter((item)=>item.character_version_id===character.character_version_id&&item.day_of_week===new Date(plan.starts_at).getDay()&&item.availability==='busy'&&item.end_minute<=new Date(plan.starts_at).getHours()*60+new Date(plan.starts_at).getMinutes()).sort((a,b)=>b.end_minute-a.end_minute)[0];
  const stateLabel=plan.status==='proposed'?'Proposed':plan.status==='scheduled'?'Coming up':plan.status==='active'?'Together now':plan.status==='completed'?'Shared':'Cancelled';
  const headerLabel=plan.status==='active'?'TOGETHER NOW':plan.status==='completed'?'SHARED HISTORY':plan.status==='cancelled'?'CANCELLED':plan.status==='proposed'?'PLAN PROPOSAL':'UPCOMING TOGETHER';
  const handle=character.together_character_templates.public_handle??character.together_character_templates.slug;
  return <Screen contentStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={()=>router.canGoBack()?router.back():router.replace('/(tabs)/dates')} style={styles.icon}><ArrowLeft color={colors.text}/></Pressable><View style={{flex:1}}><Text style={styles.kicker}>{headerLabel}</Text><Text style={styles.title}>{plan.title}</Text></View><View style={[styles.status,plan.status==='cancelled'&&styles.cancelled]}><Text style={styles.statusText}>{stateLabel.toUpperCase()}</Text></View></View>
    <GlassCard style={styles.card}><Detail icon={<CalendarDays color={colors.rose}/>} label="DATE" value={new Date(plan.starts_at).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}/><Detail icon={<Clock3 color={colors.warm}/>} label="TIME" value={`${new Date(plan.starts_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}–${new Date(plan.ends_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`}/><Detail icon={<MapPin color={colors.violet}/>} label="PLACE" value={location?.name??planWorld?.name??'Current place'}/></GlassCard>
    {schedule?<Text style={styles.companionContext}>{character.together_character_templates.name} finishes {schedule.activity} at {formatMinute(schedule.end_minute)}.</Text>:null}
    {plan.status!=='cancelled'?<View style={styles.noteBlock}><Text style={styles.label}>NOTE · OPTIONAL</Text><TextInput value={note} onChangeText={setNote} placeholder="Add anything worth remembering about the plan." placeholderTextColor={colors.dimmed} multiline style={styles.note}/><Pressable disabled={busy||note===(plan.note??'')} onPress={()=>void mutate({action:'update',note})} style={[styles.secondary,(busy||note===(plan.note??''))&&styles.disabled]}><Text style={styles.secondaryText}>Save note</Text></Pressable></View>:null}
    {editingTime?<GlassCard style={styles.editor}><Text style={styles.editorTitle}>Change date & time</Text><DateTimeFields date={dateValue} time={timeValue} onDateChange={setDateValue} onTimeChange={setTimeValue}/><GradientButton label={busy?'Checking…':'Save new time'} disabled={busy} onPress={saveTime}/></GlassCard>:null}
    {editingPlace?<GlassCard style={styles.editor}><Text style={styles.editorTitle}>Change place</Text>{locations.length?locations.map((option)=><Pressable key={option.id} onPress={()=>void mutate({action:'update',locationId:option.locationId,conversationId:plan.source_conversation_id})} style={styles.place}><View style={{flex:1}}><Text style={styles.placeTitle}>{option.locationName}</Text><Text style={styles.placeReason}>{option.reason}</Text></View><MapPin size={16} color={colors.rose}/></Pressable>):<Text style={styles.placeReason}>No similar places are available in {planWorld?.name??'this world'} right now.</Text>}</GlassCard>:null}
    {error?<Text style={styles.error}>{error}</Text>:null}
    {plan.status!=='cancelled'?<GradientButton label={plan.status==='completed'?'Talk about it':`Message ${character.together_character_templates.name}`} onPress={()=>router.push(`/chat?character=${handle}&planId=${plan.id}&draft=${encodeURIComponent(plan.status==='completed'?'Last time was fun.':'Still good for our plan?')}` as never)}/>:null}
    {plan.status==='completed'?<Pressable onPress={()=>router.push(`/chat?character=${handle}&plan=1&repeatPlanId=${plan.id}` as never)} style={styles.secondary}><RotateCcw size={17} color={colors.rose}/><Text style={styles.secondaryText}>Go again</Text></Pressable>:null}
    {canEdit?<View style={styles.actions}><Pressable onPress={()=>editingTime?setEditingTime(false):openTime()} style={styles.secondary}><Clock3 size={17} color={colors.rose}/><Text style={styles.secondaryText}>{editingTime?'Close time editor':'Change time'}</Text></Pressable><Pressable onPress={()=>{setEditingPlace((value)=>!value);setEditingTime(false);setError('');}} style={styles.secondary}><MapPin size={17} color={colors.violet}/><Text style={styles.secondaryText}>{editingPlace?'Close place editor':'Change place'}</Text></Pressable><Pressable onPress={cancel} style={[styles.secondary,styles.danger]}><Trash2 size={17} color={colors.danger}/><Text style={[styles.secondaryText,{color:colors.danger}]}>Cancel plan</Text></Pressable></View>:null}
  </Screen>;
}
function Detail({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <View style={styles.detail}>{icon}<View><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View></View>}
function formatMinute(value:number){const hour=Math.floor(value/60),minute=value%60;return new Date(2000,0,1,hour,minute).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
const styles=StyleSheet.create({content:{gap:spacing.lg,maxWidth:720},header:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface},kicker:{color:colors.rose,fontSize:9,fontWeight:'900',letterSpacing:1.2},title:{fontFamily:'Georgia',fontSize:28,color:colors.text,marginTop:3},status:{paddingHorizontal:10,paddingVertical:7,borderRadius:radius.pill,backgroundColor:'rgba(241,103,154,.12)'},cancelled:{backgroundColor:colors.surface},statusText:{color:colors.text,fontSize:9,fontWeight:'900'},card:{gap:16},detail:{flexDirection:'row',alignItems:'center',gap:12},label:{color:colors.dimmed,fontSize:9,fontWeight:'900',letterSpacing:1},value:{color:colors.text,fontSize:14,fontWeight:'800',marginTop:3},companionContext:{color:colors.warm,fontSize:11,fontWeight:'700',marginTop:-8},noteBlock:{gap:8},note:{minHeight:82,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,color:colors.text,padding:13,textAlignVertical:'top'},editor:{gap:12},editorTitle:{color:colors.text,fontFamily:'Georgia',fontSize:20},place:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10,borderTopWidth:1,borderTopColor:colors.border},placeTitle:{color:colors.text,fontSize:13,fontWeight:'800'},placeReason:{color:colors.muted,fontSize:10,marginTop:3},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},secondary:{minHeight:42,paddingHorizontal:13,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.text,fontSize:11,fontWeight:'800'},danger:{borderColor:'rgba(255,93,121,.25)'},disabled:{opacity:.4},error:{color:colors.danger,fontSize:12,textAlign:'center'}});
