import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ArrowLeft } from 'lucide-react-native';
import { GradientButton, PageTitle, Screen, SectionHeader } from '../src/components';
import { colors, radius } from '../src/theme';
import { useTogether } from '../src/store/useTogether';
import { invoke } from '../src/lib/api';

export default function Debug(){const{snapshot,refresh}=useTogether();const maya=snapshot?.characters.find((item)=>item.together_character_templates.slug==='maya');const relation=snapshot?.relationships.find((item)=>item.character_instance_id===maya?.id);const advance=async(hours:number)=>{if(!maya)return;const now=new Date(Date.now()+hours*3600000).toISOString();try{await invoke('together-simulate',{characterInstanceId:maya.id,now,evaluateProactive:true});await refresh();}catch(error){Alert.alert('Simulation failed',error instanceof Error?error.message:'Unknown error');}};return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()}><ArrowLeft color={colors.text}/></Pressable><PageTitle>Internal Tools</PageTitle></View><Text style={styles.warning}>DEVELOPMENT / INTERNAL BUILDS ONLY</Text><SectionHeader title="Maya State"/><Data label="Location" value={snapshot?.locations.find((item)=>item.id===maya?.current_location_id)?.name}/><Data label="Activity" value={maya?.current_activity}/><Data label="Mood" value={maya?.current_mood}/><Data label="Energy" value={maya?.current_energy}/><SectionHeader title="Relationship"/>{relation?Object.entries(relation).filter(([,value])=>typeof value==='number').map(([key,value])=><Data key={key} label={key} value={String(value)}/>):null}<SectionHeader title="Simulation"/><View style={styles.buttons}><GradientButton label="Advance one hour" onPress={()=>void advance(1)}/><GradientButton label="Advance one day" onPress={()=>void advance(24)}/><GradientButton label="Advance one week" onPress={()=>void advance(168)}/></View><SectionHeader title="Open Threads"/>{snapshot?.openThreads.map((thread)=><Data key={thread.id} label={thread.follow_up_eligible?'Eligible':'Waiting'} value={thread.topic}/>)}</Screen>;}
function Data({label,value}:{label:string;value?:string}){return <View style={styles.data}><Text style={styles.label}>{label.replaceAll('_',' ')}</Text><Text style={styles.value}>{value??'—'}</Text></View>;}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:14},warning:{color:colors.warm,fontSize:10,fontWeight:'800',letterSpacing:1.2},data:{flexDirection:'row',justifyContent:'space-between',gap:10,backgroundColor:colors.surface,borderRadius:radius.sm,padding:12},label:{color:colors.muted,textTransform:'capitalize'},value:{color:colors.text,maxWidth:'65%',textAlign:'right'},buttons:{gap:10}});
