import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Image } from 'expo-image';
import { X } from 'lucide-react-native';
import { characterAssets } from '../src/assets';
import { Body, DateChoice, GradientButton, Screen } from '../src/components';
import { colors, radius, spacing } from '../src/theme';
import { introduction } from '../src/lib/api';
import { useTogether } from '../src/store/useTogether';

export default function Introduction(){const[phase,setPhase]=useState(0);const[busy,setBusy]=useState(false);const refresh=useTogether((state)=>state.refresh);const next=async(choice?:string)=>{if(phase===0)await introduction('accept',choice);if(phase<5){setPhase(phase+1);return;}setBusy(true);try{await introduction('complete',choice);await refresh();Alert.alert('Chloe is now in your world','You can talk with Chloe independently—and she only knows what was actually shared.',[{text:'Say hi',onPress:()=>router.replace('/chat?character=chloe')}]);}finally{setBusy(false);}};return <Screen contentStyle={{padding:0}}><View style={styles.top}><Pressable onPress={()=>router.back()}><X color="#fff"/></Pressable><Text style={styles.title}>Introduction</Text><Text style={styles.count}>{phase+1} of 6</Text></View><View style={styles.images}><Image source={characterAssets.maya} style={styles.image} contentFit="cover" contentPosition="top"/><Image source={characterAssets.chloe} style={styles.image} contentFit="cover" contentPosition="top"/></View><View style={styles.panel}><Text style={styles.speaker}>{phase<3?'Maya':'Chloe'}</Text><Body>{lines[phase]}</Body><View style={{gap:10,marginTop:spacing.md}}>{phase===0?<><DateChoice label="Nice to meet you, Chloe!" primary onPress={()=>void next('warm')}/><DateChoice label="Hey Chloe, great to meet you." onPress={()=>void next('friendly')}/><DateChoice label="*waves* Hi!" onPress={()=>void next('shy')}/></>:<GradientButton label={phase===5?(busy?'Adding Chloe…':'Keep in touch with Chloe'):'Continue'} disabled={busy} onPress={()=>void next()}/>}</View><View style={styles.progress}>{Array.from({length:6},(_,index)=><View key={index} style={[styles.dot,index<=phase&&styles.dotActive]}/>)}</View></View></Screen>;}
const lines=['“Chloe, you have to meet them. They’re the reason I finally tried the spicy ramen challenge.”','Chloe glances at Maya. “The challenge you claimed was completely under control?”','Maya narrows her eyes. “We agreed not to lead with that detail.”','“Okay,” Chloe says, turning to you. “Now I need your version, because hers is clearly compromised.”','The conversation bounces easily between the three of you. Chloe is quick, observant, and not remotely intimidated by Maya.','By the time you leave, Chloe feels like someone you met—not an extension of Maya.'];
const styles=StyleSheet.create({top:{position:'absolute',top:0,left:0,right:0,zIndex:2,paddingTop:52,paddingHorizontal:16,flexDirection:'row',alignItems:'center'},title:{flex:1,textAlign:'center',color:'#fff',fontWeight:'800'},count:{color:'#fff',fontSize:11},images:{height:460,flexDirection:'row'},image:{width:'50%',height:'100%'},panel:{marginTop:-25,borderTopLeftRadius:radius.xl,borderTopRightRadius:radius.xl,backgroundColor:colors.background,padding:spacing.lg,gap:9},speaker:{color:colors.rose,fontWeight:'800'},progress:{flexDirection:'row',gap:6,marginTop:spacing.lg},dot:{height:3,flex:1,backgroundColor:colors.border,borderRadius:2},dotActive:{backgroundColor:colors.rose}});
