import{useState}from'react';
import{Alert,Pressable,StyleSheet,Switch,Text,View}from'react-native';
import{router}from'expo-router';
import{ArrowLeft,Flame,ShieldCheck}from'lucide-react-native';
import{Body,GradientButton,PageTitle,Screen,SectionHeader}from'../src/components';
import{saveMediaContentPreferences}from'../src/lib/api';
import{useTogether}from'../src/store/useTogether';
import{colors,radius}from'../src/theme';

type Key='suggestiveMediaEnabled'|'matureMediaEnabled'|'explicitMediaEnabled'|'adultVideoEnabled';
const definitions:Array<{key:Key;title:string;body:string}>=[
  {key:'suggestiveMediaEnabled',title:'Suggestive photos',body:'Allow adult-only flirtier imagery when the relationship and character boundaries support it.'},
  {key:'matureMediaEnabled',title:'Mature photos',body:'Allow stronger adult sensuality. This never enables real-person or non-consensual content.'},
  {key:'explicitMediaEnabled',title:'Explicit photos',body:'Allow explicit fictional-adult imagery only through separately validated server routes.'},
  {key:'adultVideoEnabled',title:'Adult short videos',body:'Allow approved higher-intensity photos to be animated when a validated video route is available.'},
];
// @ts-expect-error age_verified_at is returned by the profile row before the legacy Snapshot inline type exposes it.
export default function MediaContentSettings(){const{snapshot,refresh}=useTogether(),stored=snapshot?.profile?.content_preferences??{},ageVerified=Boolean(snapshot?.profile?.age_verified_at),[values,setValues]=useState<Record<Key,boolean>>({suggestiveMediaEnabled:stored.suggestiveMediaEnabled===true,matureMediaEnabled:stored.matureMediaEnabled===true,explicitMediaEnabled:stored.explicitMediaEnabled===true,adultVideoEnabled:stored.adultVideoEnabled===true}),[busy,setBusy]=useState(false);const save=async()=>{setBusy(true);try{await saveMediaContentPreferences(values);await refresh();Alert.alert('Media preferences saved');}catch(error){Alert.alert('Could not save',error instanceof Error?error.message:'Try again.');}finally{setBusy(false);}};return <Screen><View style={styles.header}><Pressable accessibilityLabel="Back" onPress={()=>router.back()}><ArrowLeft color={colors.text}/></Pressable><PageTitle>Media boundaries</PageTitle></View><Body muted>These preferences only permit eligible media. They never override age rules, fictional-character limits, consent, relationship state, or a companion’s boundaries.</Body>{ageVerified?<><SectionHeader title="Adult media"/>{definitions.map((item)=><View key={item.key} style={styles.row}><View style={styles.icon}><Flame size={18} color={colors.rose}/></View><View style={{flex:1}}><Text style={styles.title}>{item.title}</Text><Text style={styles.body}>{item.body}</Text></View><Switch value={values[item.key]} onValueChange={(value)=>setValues((current)=>({...current,[item.key]:value}))} trackColor={{false:colors.elevated,true:colors.rose}}/></View>)}<GradientButton label={busy?'Saving…':'Save media boundaries'} disabled={busy} onPress={()=>void save()}/></>:<View style={styles.notice}><ShieldCheck color={colors.violet}/><View style={{flex:1}}><Text style={styles.title}>Age verification required</Text><Text style={styles.body}>Higher-intensity media controls appear only for verified adult accounts. Standard and romantic companion photos remain governed by your existing relationship preferences.</Text></View></View>}<Text style={styles.foot}>Higher-intensity media is never generated automatically. Provider availability is separate from permission.</Text></Screen>}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:14},row:{minHeight:92,flexDirection:'row',alignItems:'center',gap:12,padding:14,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},icon:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(216,62,234,.10)'},title:{color:colors.text,fontWeight:'900'},body:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:4},notice:{flexDirection:'row',gap:12,padding:16,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},foot:{color:colors.muted,fontSize:11,lineHeight:17,textAlign:'center'}});
