import{useMemo,useState}from'react';
import{KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{router}from'expo-router';
import{Check,Eye,EyeOff}from'lucide-react-native';
import{Body,GradientButton,PageTitle,Screen}from'../src/components';
import{colors,radius,spacing}from'../src/theme';
import{useAuth}from'../src/hooks/useAuth';
import{bootstrap}from'../src/lib/api';
import{clearPendingOnboarding,savePendingOnboarding,type PendingOnboarding}from'../src/lib/pendingOnboarding';
import{companionChoices,rankCompanions}from'../src/lib/companionDiscovery';
import{useTogether}from'../src/store/useTogether';

const interests=['Sports','Gaming','Movies','Music','Food','Travel','Photography','Outdoors','Technology','Books'];
const goals=['Dating','Friendship','Stories','Social worlds']as const;
export default function Onboarding(){
 const[step,setStep]=useState(0),[selectedGoals,setGoals]=useState<string[]>([]),[selectedInterests,setInterests]=useState<string[]>([]),[displayName,setDisplayName]=useState(''),[selectedId,setSelectedId]=useState(companionChoices[0]!.id),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[awaitingConfirmation,setAwaitingConfirmation]=useState(false);
 const{session,signUp,resendSignUpConfirmation}=useAuth();const setSnapshot=useTogether((state)=>state.setSnapshot);const ranked=useMemo(()=>rankCompanions(selectedGoals,selectedInterests),[selectedGoals,selectedInterests]);const chosen=companionChoices.find((item)=>item.id===selectedId)??companionChoices[0]!;
 const toggle=(value:string,current:string[],setter:(value:string[])=>void)=>setter(current.includes(value)?current.filter((item)=>item!==value):[...current,value]);
 const finish=async()=>{setBusy(true);setError('');try{const pending:PendingOnboarding={ageConfirmed:true,displayName:displayName.trim()||undefined,characterTemplateId:chosen.id,interests:selectedInterests,goals:selectedGoals as PendingOnboarding['goals']};if(!session){await savePendingOnboarding(pending);const result=await signUp(email.trim(),password);if(result.needsEmailConfirmation){setAwaitingConfirmation(true);return;}}const snapshot=await bootstrap(pending);await clearPendingOnboarding();setSnapshot(snapshot);router.replace(`/character/${chosen.slug}?intro=1`);}catch(caught){setError(caught instanceof Error?caught.message:'Could not begin your story.');}finally{setBusy(false);}};
 const resend=async()=>{setBusy(true);setError('');try{await resendSignUpConfirmation(email.trim());}catch(caught){setError(caught instanceof Error?caught.message:'Could not resend the confirmation.');}finally{setBusy(false);}};
 if(awaitingConfirmation)return <Screen contentStyle={styles.center}><Text style={styles.brand}>Kivelle.AI</Text><PageTitle>Check your email.</PageTitle><Body muted>We sent a confirmation link to {email.trim()}. Open it on this device to meet {chosen.name} in Juniper City.</Body>{error?<Text style={styles.error}>{error}</Text>:null}<GradientButton label={busy?'Sending…':'Resend confirmation'} disabled={busy} onPress={()=>void resend()}/><Pressable onPress={()=>router.replace('/auth')}><Text style={styles.link}>Back to sign in</Text></Pressable></Screen>;
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><Screen scroll={false} contentStyle={styles.content}><View style={styles.progress}>{Array.from({length:7},(_,index)=><View key={index} style={[styles.progressDot,index<=step&&styles.progressActive]}/>)}</View><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
  {step===0?<><Text style={styles.brand}>Kivelle.AI</Text><PageTitle>Choose who your story begins with.</PageTitle><Body muted>Build a relationship with someone who remembers, changes, and shares a living world with you.</Body></>:null}
  {step===1?<><Text style={styles.kicker}>BEFORE WE BEGIN</Text><PageTitle>Kivelle is for adults.</PageTitle><Body muted>Confirm that you are 18 or older. Every character is a fictional AI personality. Kivelle is designed for romantic, social, and narrative experiences—not dependency or impersonation.</Body><View style={styles.notice}><Check color={colors.rose}/><Text style={styles.noticeText}>I confirm I am 18 or older.</Text></View></>:null}
  {step===2?<><Text style={styles.kicker}>YOUR STORY</Text><PageTitle>What are you looking for?</PageTitle><View style={styles.wrap}>{goals.map((item)=><Chip key={item} label={item} selected={selectedGoals.includes(item)} onPress={()=>toggle(item,selectedGoals,setGoals)}/>)}</View></>:null}
  {step===3?<><Text style={styles.kicker}>COMMON GROUND</Text><PageTitle>What are you into?</PageTitle><Body muted>We’ll use this to recommend people—not to script your conversations.</Body><View style={styles.wrap}>{interests.map((item)=><Chip key={item} label={item} selected={selectedInterests.includes(item)} onPress={()=>toggle(item,selectedInterests,setInterests)}/>)}</View></>:null}
  {step===4?<><Text style={styles.kicker}>ABOUT YOU</Text><PageTitle>What should they call you?</PageTitle><TextInput value={displayName} onChangeText={setDisplayName} placeholder="Your first name or nickname" placeholderTextColor={colors.muted} maxLength={50} autoFocus style={styles.input}/><Body muted>You can change this in Account settings anytime.</Body></>:null}
  {step===5?<><Text style={styles.kicker}>RECOMMENDED FOR YOU</Text><PageTitle>Who do you want to meet?</PageTitle><Body muted>You’re choosing a person, not a personality setting. You can meet others later.</Body><View style={styles.cards}>{ranked.map((item,index)=><Pressable key={item.id} onPress={()=>setSelectedId(item.id)} style={[styles.personCard,selectedId===item.id&&styles.personSelected]}><View style={[styles.initial,{backgroundColor:index%2?colors.elevated:'#37203f'}]}><Text style={styles.initialText}>{item.name[0]}</Text></View><View style={{flex:1,gap:5}}><View style={styles.cardTitle}><Text style={styles.personName}>{item.name}</Text>{selectedId===item.id?<Check size={18} color={colors.rose}/>:null}</View><Text style={styles.occupation}>{item.occupation}</Text><Text style={styles.summary}>{item.summary}</Text><View style={styles.traits}>{item.traits.map((trait)=><Text key={trait} style={styles.trait}>{trait}</Text>)}</View></View></Pressable>)}</View></>:null}
  {step===6?<><Text style={styles.kicker}>JUNIPER CITY · FRIDAY, 5:38 PM</Text><PageTitle>Meet {chosen.name}.</PageTitle><View style={styles.scene}><Text style={styles.sceneName}>{chosen.name}</Text><Text style={styles.sceneText}>You’re waiting for your coffee at Juniper Café when {chosen.name} approaches the empty chair across from you.</Text><Text style={styles.quote}>“Is anyone sitting here?”</Text></View>{!session?<View style={{gap:12}}><TextInput value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor={colors.muted} autoCapitalize="none" keyboardType="email-address" style={styles.input}/><View style={styles.password}><TextInput value={password} onChangeText={setPassword} placeholder="Create a password" placeholderTextColor={colors.muted} secureTextEntry={!showPassword} autoCapitalize="none" style={[styles.input,{flex:1,borderWidth:0}]}/><Pressable accessibilityLabel={showPassword?'Hide password':'Show password'} onPress={()=>setShowPassword(!showPassword)} style={styles.eye}>{showPassword?<EyeOff color={colors.text}/>:<Eye color={colors.text}/>}</Pressable></View></View>:<Body muted>You’re signed in. Your story will be saved to this account.</Body>}{error?<Text style={styles.error}>{error}</Text>:null}</>:null}
 </ScrollView><View style={styles.actions}><GradientButton label={step===6?(busy?`Meeting ${chosen.name}…`:`Meet ${chosen.name}`):'Continue'} disabled={busy||(step===4&&!displayName.trim())||(step===6&&!session&&(!email.includes('@')||password.length<8))} onPress={()=>step<6?setStep(step+1):void finish()}/>{step===0?<Pressable onPress={()=>router.push('/auth')}><Text style={styles.link}>Already have an account? Sign in</Text></Pressable>:<Pressable disabled={busy} onPress={()=>setStep(step-1)}><Text style={styles.link}>Back</Text></Pressable>}</View></Screen></KeyboardAvoidingView>;
}
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,selected&&styles.chipSelected]}><Text style={[styles.chipText,selected&&{color:'#fff'}]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({content:{minHeight:'100%',paddingBottom:spacing.lg},center:{minHeight:'100%',justifyContent:'center',gap:spacing.lg},scroll:{flexGrow:1,justifyContent:'center',gap:spacing.xl,paddingVertical:spacing.xl},progress:{flexDirection:'row',gap:6,paddingTop:spacing.sm},progressDot:{height:3,flex:1,borderRadius:4,backgroundColor:colors.border},progressActive:{backgroundColor:colors.rose},brand:{fontFamily:'Georgia',fontSize:46,color:colors.text},kicker:{color:colors.rose,fontSize:12,fontWeight:'800',letterSpacing:1.5},notice:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:colors.elevated,borderRadius:radius.md,padding:spacing.lg,borderWidth:1,borderColor:'rgba(241,103,154,.3)'},noticeText:{color:colors.text,fontSize:16,fontWeight:'700'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:10},chip:{paddingHorizontal:16,paddingVertical:12,borderRadius:radius.pill,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},chipSelected:{backgroundColor:colors.violet,borderColor:colors.violet},chipText:{color:colors.muted,fontWeight:'700'},input:{minHeight:54,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:16,fontSize:16},password:{flexDirection:'row',alignItems:'center',borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},eye:{padding:14},error:{color:colors.danger},link:{textAlign:'center',color:colors.muted,fontWeight:'700'},actions:{gap:12,paddingTop:12},cards:{gap:12},personCard:{flexDirection:'row',gap:14,padding:14,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},personSelected:{borderColor:colors.rose,backgroundColor:'rgba(241,103,154,.08)'},initial:{width:60,height:76,borderRadius:16,alignItems:'center',justifyContent:'center'},initialText:{fontFamily:'Georgia',fontSize:30,color:colors.text},cardTitle:{flexDirection:'row',justifyContent:'space-between'},personName:{fontFamily:'Georgia',fontSize:22,color:colors.text},occupation:{color:colors.rose,fontWeight:'700'},summary:{color:colors.muted,lineHeight:19},traits:{flexDirection:'row',gap:6,flexWrap:'wrap'},trait:{fontSize:11,color:colors.text,backgroundColor:colors.elevated,paddingHorizontal:8,paddingVertical:4,borderRadius:20},scene:{gap:12,padding:22,borderRadius:radius.xl,backgroundColor:colors.elevated,borderWidth:1,borderColor:'rgba(154,104,255,.25)'},sceneName:{fontFamily:'Georgia',fontSize:30,color:colors.text},sceneText:{color:colors.muted,fontSize:16,lineHeight:24},quote:{color:colors.text,fontFamily:'Georgia',fontSize:23,lineHeight:31}});
