import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Eye, EyeOff } from 'lucide-react-native';
import { Body, GradientButton, PageTitle, Screen } from '../src/components';
import { colors, radius, spacing } from '../src/theme';
import { useAuth } from '../src/hooks/useAuth';
import { bootstrap } from '../src/lib/api';
import { clearPendingOnboarding, savePendingOnboarding, type PendingOnboarding } from '../src/lib/pendingOnboarding';
import { useTogether } from '../src/store/useTogether';

const interests=['Sports','Gaming','Movies','Music','Food','Travel','Photography','Outdoors','Technology','Books'];
const goals=['Dating','Friendship','Stories','Social worlds'] as const;
export default function Onboarding(){const[step,setStep]=useState(0);const[selectedGoals,setGoals]=useState<string[]>([]);const[selectedInterests,setInterests]=useState<string[]>([]);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[awaitingConfirmation,setAwaitingConfirmation]=useState(false);const{session,signUp,resendSignUpConfirmation}=useAuth();const setSnapshot=useTogether((state)=>state.setSnapshot);
  const toggle=(value:string,current:string[],setter:(value:string[])=>void)=>setter(current.includes(value)?current.filter((item)=>item!==value):[...current,value]);
  const finish=async()=>{setBusy(true);setError('');try{const pending:PendingOnboarding={ageConfirmed:true,interests:selectedInterests,goals:selectedGoals as PendingOnboarding['goals']};if(!session){await savePendingOnboarding(pending);const result=await signUp(email.trim(),password);if(result.needsEmailConfirmation){setAwaitingConfirmation(true);return;}}const snapshot=await bootstrap(pending);await clearPendingOnboarding();setSnapshot(snapshot);router.replace('/meet-maya');}catch(caught){setError(caught instanceof Error?caught.message:'Could not begin your story.');}finally{setBusy(false);}};
  const resend=async()=>{setBusy(true);setError('');try{await resendSignUpConfirmation(email.trim());}catch(caught){setError(caught instanceof Error?caught.message:'Could not resend the confirmation.');}finally{setBusy(false);}};
  if(awaitingConfirmation)return <Screen contentStyle={styles.confirmation}><Text style={styles.brand}>Together</Text><PageTitle>Check your email.</PageTitle><Body muted>We sent a confirmation link to {email.trim()}. Open it on this device to finish creating your account and enter City Life.</Body>{error?<Text style={styles.error}>{error}</Text>:null}<GradientButton label={busy?'Sending…':'Resend confirmation'} disabled={busy} onPress={()=>void resend()}/><Pressable onPress={()=>router.replace('/auth')}><Text style={styles.signIn}>Back to sign in</Text></Pressable></Screen>;
  return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><Screen contentStyle={styles.content}>
    <View style={{flex:1,justifyContent:'center',gap:spacing.xl}}>
      {step===0?<><Text style={styles.brand}>Together</Text><PageTitle>Meet characters who remember you, change with you, and share a world with you.</PageTitle><Body muted>Maya is not a prompt or a disposable chat. She has a life, a history, and a place in City Life.</Body></>:null}
      {step===1?<><Text style={styles.kicker}>BEFORE WE BEGIN</Text><PageTitle>Together is for adults.</PageTitle><Body muted>Confirm that you are 18 or older. Characters are fictional AI personalities, and Together is designed for romantic, social, and narrative experiences—not dependency or impersonation.</Body><View style={styles.notice}><Text style={styles.noticeText}>By continuing, I confirm I am 18+.</Text></View></>:null}
      {step===2?<><Text style={styles.kicker}>YOUR STORY</Text><PageTitle>What sounds interesting?</PageTitle><View style={styles.wrap}>{goals.map((item)=><Chip key={item} label={item} selected={selectedGoals.includes(item)} onPress={()=>toggle(item,selectedGoals,setGoals)}/>)}</View></>:null}
      {step===3?<><Text style={styles.kicker}>A LITTLE CONTEXT</Text><PageTitle>What are you into?</PageTitle><Body muted>These shape natural conversation. You can change them later.</Body><View style={styles.wrap}>{interests.map((item)=><Chip key={item} label={item} selected={selectedInterests.includes(item)} onPress={()=>toggle(item,selectedInterests,setInterests)}/>)}</View></>:null}
      {step===4?<><Text style={styles.kicker}>CITY LIFE</Text><PageTitle>A city full of people, places, and stories.</PageTitle><Body muted>Friday · 5:38 PM{`\n\n`}You’re waiting for your coffee at Juniper when someone approaches the empty chair across from you.</Body><View style={{gap:12}}><TextInput value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor={colors.muted} autoCapitalize="none" keyboardType="email-address" style={styles.input}/><View style={styles.password}><TextInput value={password} onChangeText={setPassword} placeholder="Create a password" placeholderTextColor={colors.muted} secureTextEntry={!showPassword} autoCapitalize="none" style={[styles.input,{flex:1,borderWidth:0}]}/><Pressable accessibilityLabel={showPassword?'Hide password':'Show password'} onPress={()=>setShowPassword(!showPassword)} style={styles.eye}>{showPassword?<EyeOff color={colors.text}/>:<Eye color={colors.text}/>}</Pressable></View>{error?<Text style={styles.error}>{error}</Text>:null}</View></>:null}
    </View>
    <View style={{gap:12}}><GradientButton label={step===4?(busy?'Entering City Life…':'Enter City Life'):'Continue'} disabled={busy||(step===4&&(!email.includes('@')||password.length<8))} onPress={()=>step<4?setStep(step+1):void finish()}/>{step===0?<Pressable onPress={()=>router.push('/auth')}><Text style={styles.signIn}>Already have an account? Sign in</Text></Pressable>:step>0?<Pressable onPress={()=>setStep(step-1)}><Text style={styles.signIn}>Back</Text></Pressable>:null}</View>
  </Screen></KeyboardAvoidingView>;
}
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,selected&&styles.chipSelected]}><Text style={[styles.chipText,selected&&{color:'#fff'}]}>{label}</Text></Pressable>;}
const styles=StyleSheet.create({content:{minHeight:'100%',justifyContent:'space-between'},confirmation:{minHeight:'100%',justifyContent:'center',gap:spacing.lg},brand:{fontFamily:'Georgia',fontSize:46,color:colors.text},kicker:{color:colors.rose,fontSize:12,fontWeight:'800',letterSpacing:1.5},notice:{backgroundColor:colors.elevated,borderRadius:radius.md,padding:spacing.lg,borderWidth:1,borderColor:'rgba(241,103,154,.3)'},noticeText:{color:colors.text,fontSize:16,fontWeight:'700'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:10},chip:{paddingHorizontal:16,paddingVertical:12,borderRadius:radius.pill,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},chipSelected:{backgroundColor:colors.violet,borderColor:colors.violet},chipText:{color:colors.muted,fontWeight:'700'},input:{minHeight:54,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:16,fontSize:16},password:{flexDirection:'row',alignItems:'center',borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},eye:{padding:14},error:{color:colors.danger},signIn:{textAlign:'center',color:colors.muted,fontWeight:'700'}});
