import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ArrowLeft, Camera, Coins } from 'lucide-react-native';
import { PageTitle, Screen, SectionHeader } from '../src/components';
import { colors, radius } from '../src/theme';
import { useTogether } from '../src/store/useTogether';
import { manageMedia } from '../src/lib/api';

export default function PhotoSettings(){const{snapshot,refresh}=useTogether();const preferences=snapshot?.profile?.photo_preferences??{companionPhotos:true,automaticPhotos:true};const save=async(next:{companionPhotos:boolean;automaticPhotos:boolean})=>{await manageMedia({action:'preferences',...next});await refresh();};return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()}><ArrowLeft color={colors.text}/></Pressable><PageTitle>Photos</PageTitle></View><View style={styles.intro}><Camera color={colors.rose}/><Text style={styles.lead}>Companions can share occasional photos that match where they are and what is happening in your story.</Text></View><View style={styles.creditInfo}><Coins size={18} color={colors.warm}/><View style={{flex:1}}><Text style={styles.creditTitle}>Direct photo requests use 10 Kivelle Credits</Text><Text style={styles.creditCopy}>Automatic life, Date, Story, and Moment photos do not spend credits. Failed paid generations are refunded automatically.</Text></View><Pressable onPress={()=>router.push('/subscription')}><Text style={styles.creditLink}>Credits</Text></Pressable></View><SectionHeader title="Photos from companions"/><Toggle title="Companion photos" body="Allow photos in Chat, Dates, Moments, and Galleries." value={preferences.companionPhotos!==false} onChange={(companionPhotos)=>void save({companionPhotos,automaticPhotos:companionPhotos&&preferences.automaticPhotos!==false})}/><Toggle title="Automatic photos" body="Allow rare, meaningful life-event photos. You can still ask directly when this is off." value={preferences.companionPhotos!==false&&preferences.automaticPhotos!==false} disabled={preferences.companionPhotos===false} onChange={(automaticPhotos)=>void save({companionPhotos:true,automaticPhotos})}/><Text style={styles.note}>Photos are private to your account. Kivelle uses canonical fictional character identity and current world state; your message never becomes a raw image prompt.</Text></Screen>}
function Toggle({title,body,value,onChange,disabled=false}:{title:string;body:string;value:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <View style={[styles.row,disabled&&{opacity:.5}]}><View style={{flex:1}}><Text style={styles.title}>{title}</Text><Text style={styles.body}>{body}</Text></View><Switch disabled={disabled} value={value} onValueChange={onChange} trackColor={{false:colors.elevated,true:colors.rose}}/></View>}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:14},intro:{padding:16,borderRadius:radius.lg,backgroundColor:'rgba(241,103,154,.07)',borderWidth:1,borderColor:'rgba(241,103,154,.18)',gap:10},lead:{color:colors.text,fontSize:13,lineHeight:19},creditInfo:{flexDirection:'row',alignItems:'center',gap:10,padding:13,borderRadius:radius.md,backgroundColor:'rgba(242,162,127,.07)',borderWidth:1,borderColor:'rgba(242,162,127,.20)'},creditTitle:{color:colors.text,fontWeight:'900',fontSize:12},creditCopy:{color:colors.muted,fontSize:10,lineHeight:15,marginTop:3},creditLink:{color:colors.warm,fontWeight:'900',fontSize:11},row:{minHeight:76,flexDirection:'row',alignItems:'center',gap:12,padding:14,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},title:{color:colors.text,fontWeight:'800'},body:{color:colors.muted,fontSize:12,lineHeight:17,marginTop:3},note:{color:colors.muted,fontSize:11,lineHeight:17}});
