import { Alert, Modal, Pressable, Share, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { ArrowLeft, Download, ShieldAlert, Trash2, X } from 'lucide-react-native';
import { FrostedSurface, PageTitle, Screen, SectionHeader } from '../src/components';
import { colors, radius, spacing } from '../src/theme';
import { useTogether } from '../src/store/useTogether';
import { manageAccount } from '../src/lib/api';
import { useAuth } from '../src/hooks/useAuth';
import { useState } from 'react';

export default function Privacy(){
  const{snapshot,refresh,clear}=useTogether(),{signOut}=useAuth(),settings=snapshot?.profile?.privacy_settings??{personalization:true,analytics:true};
  const[deleteOpen,setDeleteOpen]=useState(false),[confirmation,setConfirmation]=useState(''),[deleting,setDeleting]=useState(false);
  const toggle=async(key:string,value:boolean)=>{try{await manageAccount({action:'privacy',settings:{...settings,[key]:value}});await refresh();}catch(error){Alert.alert('Could not update privacy',error instanceof Error?error.message:'Please try again.');}};
  const exportData=async()=>{try{const data=await manageAccount<unknown>({action:'export'});await Share.share({title:'Kivelle data export',message:JSON.stringify(data,null,2)});}catch(error){Alert.alert('Export unavailable',error instanceof Error?error.message:'Please try again.');}};
  const remove=async()=>{if(confirmation!=='DELETE')return;setDeleting(true);try{await manageAccount({action:'delete',confirmation:'DELETE'});await signOut();clear();setDeleteOpen(false);router.replace('/auth');}catch(error){Alert.alert('Could not delete account',error instanceof Error?error.message:'Please try again.');}finally{setDeleting(false);}};
  return <Screen><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={()=>router.back()}><ArrowLeft color={colors.text}/></Pressable><PageTitle>Privacy</PageTitle></View><Text style={styles.lead}>You control what Kivelle keeps and how the experience is personalized.</Text><SectionHeader title="Experience controls"/><Toggle title="Personalized experience" body="Use your profile and memories to tailor your experience. Turning this off removes personal memory and reflection context from new replies." value={settings.personalization!==false} onChange={value=>void toggle('personalization',value)}/><Toggle title="Product analytics" body="Help us understand what works without exposing your conversations. Turning this off is enforced before analytics are stored." value={settings.analytics!==false} onChange={value=>void toggle('analytics',value)}/><Pressable onPress={()=>router.push('/memories?privacy=1')} style={styles.row}><ShieldAlert color={colors.violet}/><View style={{flex:1}}><Text style={styles.rowTitle}>Manage remembered information</Text><Text style={styles.rowBody}>Review, forget, or disable remembered information on any plan.</Text></View></Pressable><SectionHeader title="Your data"/><Pressable onPress={()=>void exportData()} style={styles.row}><Download color={colors.rose}/><View style={{flex:1}}><Text style={styles.rowTitle}>Export your Kivelle data</Text><Text style={styles.rowBody}>Create a portable copy of your profile, relationships, conversations, and history.</Text></View></Pressable><Pressable onPress={()=>{setConfirmation('');setDeleteOpen(true);}} style={[styles.row,styles.dangerRow]}><Trash2 color={colors.danger}/><View style={{flex:1}}><Text style={[styles.rowTitle,{color:colors.danger}]}>Delete Kivelle account</Text><Text style={styles.rowBody}>Permanently removes your account, messages, memories, and stored media.</Text></View></Pressable><Text style={styles.note}>Kivelle companions are fictional AI characters. Kivelle never uses guilt or dependency to pressure you to return.</Text>
    <Modal visible={deleteOpen} transparent animationType="fade" onRequestClose={()=>!deleting&&setDeleteOpen(false)}><View style={styles.modalBackdrop}><Pressable style={StyleSheet.absoluteFill} onPress={()=>!deleting&&setDeleteOpen(false)}/><FrostedSurface intensity={85} style={styles.modalCard}><View style={styles.modalHeader}><Text accessibilityRole="header" style={styles.modalTitle}>Delete your account?</Text><Pressable accessibilityLabel="Close" disabled={deleting} onPress={()=>setDeleteOpen(false)}><X color={colors.muted}/></Pressable></View><Text style={styles.modalBody}>This permanently removes your Kivelle account, conversations, memories, relationships, and stored media. This cannot be undone.</Text><Text style={styles.confirmLabel}>Type DELETE to confirm</Text><TextInput autoCapitalize="characters" autoCorrect={false} value={confirmation} onChangeText={setConfirmation} placeholder="DELETE" placeholderTextColor={colors.dimmed} style={styles.confirmInput}/><View style={styles.modalActions}><Pressable disabled={deleting} onPress={()=>setDeleteOpen(false)} style={styles.cancelButton}><Text style={styles.cancelText}>Cancel</Text></Pressable><Pressable accessibilityState={{disabled:deleting||confirmation!=='DELETE'}} disabled={deleting||confirmation!=='DELETE'} onPress={()=>void remove()} style={[styles.deleteButton,(deleting||confirmation!=='DELETE')&&styles.disabled]}><Text style={styles.deleteText}>{deleting?'Deleting…':'Delete permanently'}</Text></Pressable></View></FrostedSurface></View></Modal>
  </Screen>;
}
function Toggle({title,body,value,onChange}:{title:string;body:string;value:boolean;onChange:(value:boolean)=>void}){return <View style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowBody}>{body}</Text></View><Switch accessibilityLabel={title} value={value} onValueChange={onChange} trackColor={{false:colors.elevated,true:colors.rose}}/></View>}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:14},lead:{color:colors.muted,lineHeight:20},row:{minHeight:70,flexDirection:'row',alignItems:'center',gap:12,padding:13,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},rowTitle:{color:colors.text,fontWeight:'800'},rowBody:{color:colors.muted,fontSize:12,lineHeight:17,marginTop:3},dangerRow:{borderColor:'rgba(255,107,121,.35)'},note:{color:colors.muted,fontSize:12,lineHeight:18,padding:spacing.md,borderRadius:radius.md,backgroundColor:'rgba(154,104,255,.07)'},modalBackdrop:{flex:1,backgroundColor:'rgba(4,5,12,.82)',alignItems:'center',justifyContent:'center',padding:20},modalCard:{width:'100%',maxWidth:520,padding:22,borderRadius:24,borderWidth:1,borderColor:'rgba(255,255,255,.14)',backgroundColor:'rgba(26,20,40,.96)'},modalHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},modalTitle:{fontSize:24,fontWeight:'900',color:colors.text},modalBody:{color:colors.muted,lineHeight:21,marginTop:12},confirmLabel:{color:colors.text,fontWeight:'800',fontSize:13,marginTop:20,marginBottom:8},confirmInput:{color:colors.text,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:14,paddingVertical:12,backgroundColor:'rgba(255,255,255,.05)',fontWeight:'900',letterSpacing:1.5},modalActions:{flexDirection:'row',justifyContent:'flex-end',gap:10,marginTop:20},cancelButton:{paddingHorizontal:18,paddingVertical:12},cancelText:{color:colors.text,fontWeight:'800'},deleteButton:{paddingHorizontal:18,paddingVertical:12,borderRadius:radius.md,backgroundColor:colors.danger},deleteText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.35}});
