import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ArrowLeft, Bell, Brain, Camera, ChevronRight, FileText, LogOut, MessageCircle, Shield, Sparkles, UserRound } from 'lucide-react-native';
import { Body, PageTitle, Screen, SectionHeader } from '../src/components';
import { colors, radius } from '../src/theme';
import { useTogether } from '../src/store/useTogether';
import { useAuth } from '../src/hooks/useAuth';
import { activeCompanion } from '../src/lib/companionLife';

export default function Settings(){const{snapshot,clear}=useTogether();const{signOut,session}=useAuth();const companion=snapshot?activeCompanion(snapshot):undefined;const name=companion?.together_character_templates.name??'your companion';const logout=()=>Alert.alert('Sign out?','Your world and memories will still be here when you return.',[{text:'Cancel',style:'cancel'},{text:'Sign out',onPress:()=>void signOut().then(()=>{clear();router.replace('/auth');})}]);return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()}><ArrowLeft color={colors.text}/></Pressable><PageTitle>Settings</PageTitle></View><View style={styles.identity}><View style={styles.initial}><Text style={styles.initialText}>{(snapshot?.profile?.display_name??'Y')[0]}</Text></View><View><Text style={styles.name}>{snapshot?.profile?.display_name??'You'}</Text><Text style={styles.email}>{session?.user.email}</Text></View></View><SectionHeader title="Account"/><Link icon={<UserRound/>} title="Profile & security" value="Personalize Kivelle" onPress={()=>router.push('/account')}/><Link icon={<Sparkles/>} title="Subscription" value={snapshot?.entitlements?.tier==='free'?'Free plan':'Kivelle+'}/><SectionHeader title="Experience"/><Link icon={<Bell/>} title="Notifications" value={snapshot?.notificationPreferences?.push_enabled?'On':'Off'} onPress={()=>router.push('/notifications')}/><Link icon={<Camera/>} title="Photos from companions" value={snapshot?.profile?.photo_preferences?.companionPhotos===false?'Off':'On'} onPress={()=>router.push('/photo-settings' as never)}/><SectionHeader title="Your relationships"/><Link icon={<MessageCircle/>} title="Conversations & resets" value="History and fresh starts" onPress={()=>router.push('/conversation-controls' as never)}/><Link icon={<Brain/>} title={`What ${name} remembers`} value={`${snapshot?.memories.filter((memory)=>memory.character_instance_id===companion?.id).length??0} memories`} onPress={()=>router.push(`/memories?character=${companion?.together_character_templates.slug??''}` as never)}/><SectionHeader title="Privacy & data"/><Link icon={<Shield/>} title="Privacy controls" value="You’re in control" onPress={()=>router.push('/privacy')}/><Link icon={<FileText/>} title="AI disclosure" value="Fictional AI characters"/><Pressable onPress={logout}><Link icon={<LogOut color={colors.danger}/>} title="Sign out" danger/></Pressable><View style={styles.disclosure}><Body muted>Kivelle keeps memories visible and editable. Characters are fictional, and the app never uses guilt or dependency to bring you back.</Body></View><Text style={styles.version}>Kivelle.AI 1.0.0</Text></Screen>}
function Link({icon,title,value,onPress,danger=false}:{icon:React.ReactElement;title:string;value?:string;onPress?:()=>void;danger?:boolean}){return <Pressable onPress={onPress} disabled={!onPress&&title!=='AI disclosure'&&title!=='Subscription'} style={({pressed})=>[styles.row,pressed&&{opacity:.8}]}><View style={styles.rowIcon}>{icon}</View><Text style={[styles.rowTitle,danger&&{color:colors.danger}]}>{title}</Text>{value?<Text style={styles.value}>{value}</Text>:null}{onPress?<ChevronRight color={colors.muted} size={17}/>:null}</Pressable>}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:14},identity:{flexDirection:'row',alignItems:'center',gap:12,padding:14,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},initial:{width:46,height:46,borderRadius:23,alignItems:'center',justifyContent:'center',backgroundColor:colors.elevated,borderWidth:1,borderColor:'rgba(241,103,154,.4)'},initialText:{color:colors.text,fontSize:23,fontFamily:'Georgia'},name:{color:colors.text,fontSize:16,fontWeight:'800'},email:{color:colors.muted,fontSize:12,marginTop:3},row:{minHeight:60,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:colors.surface,borderRadius:radius.md,paddingHorizontal:13,borderWidth:1,borderColor:colors.border},rowIcon:{width:28,alignItems:'center'},rowTitle:{flex:1,color:colors.text,fontWeight:'700'},value:{color:colors.muted,fontSize:11},disclosure:{padding:14,borderRadius:radius.md,borderWidth:1,borderColor:colors.border},version:{color:colors.muted,textAlign:'center',fontSize:11}});
