import { z } from 'zod';
import { authenticated, enforceRateLimit } from '../_shared/context.ts';
import { parseBody } from '../_shared/body.ts';
import { json, serve } from '../_shared/http.ts';
import { AppError } from '../_shared/types.ts';
import { ConfiguredModerationProvider } from '../_shared/together-ai.ts';
import { ConfiguredCharacterCreationProvider, appearanceCandidates } from '../_shared/together-creator.ts';
import { resolvePlaceContext, resolveWorldAccess } from '../_shared/together-place.ts';
import { routeImageProvider, type CanonicalImageGenerationRequest } from '../_shared/together-media.ts';
import { track } from '../_shared/together.ts';
import { enforceCustomCompanionLimit, refundCredits, resolveSubscriptionState, spendCredits } from '../_shared/kivelle-subscription.ts';
import { handleCreatorStudioAction, isCreatorStudioAction } from '../_shared/kivelle-creator-studio.ts';

const schema=z.discriminatedUnion('action',[
  z.object({action:z.literal('create_draft'),concept:z.string().trim().min(20).max(1200),worldId:z.string().uuid(),relationshipGoal:z.enum(['friendship','romance','either']),requestId:z.string().uuid()}),
  z.object({action:z.literal('get_draft'),draftId:z.string().uuid()}),
  z.object({action:z.literal('list_drafts')}),
  z.object({action:z.literal('update_draft_section'),draftId:z.string().uuid(),section:z.enum(['identity','appearance','personality','communication','connection','life','routine']),config:z.record(z.string(),z.unknown()),relationshipGoal:z.enum(['friendship','romance','either']).optional(),currentStep:z.enum(['identity','appearance','personality','life','connection','meeting','review']).optional(),expectedRevision:z.number().int().positive()}),
  z.object({action:z.literal('regenerate_draft_section'),draftId:z.string().uuid(),section:z.enum(['routine','first_meetings'])}),
  z.object({action:z.literal('generate_draft_appearance'),draftId:z.string().uuid(),requestId:z.string().uuid()}),
  z.object({action:z.literal('select_draft_appearance'),draftId:z.string().uuid(),assetId:z.string().uuid()}),
  z.object({action:z.literal('select_first_meeting'),draftId:z.string().uuid(),meetingId:z.string().uuid()}),
  z.object({action:z.literal('finalize_draft'),draftId:z.string().uuid(),requestId:z.string().uuid()}),
  z.object({action:z.literal('archive_draft'),draftId:z.string().uuid()}),
  z.object({action:z.literal('quick_create'),concept:z.string().trim().min(20).max(1200),worldId:z.string().uuid(),relationshipGoal:z.enum(['friendship','romance','either'])}),
  z.object({action:z.literal('generate_appearance'),characterTemplateId:z.string().uuid(),requestId:z.string().uuid().optional()}),
  z.object({action:z.literal('select_appearance'),characterTemplateId:z.string().uuid(),candidateId:z.string().uuid(),confirmVersionChange:z.boolean().default(false)}),
  z.object({action:z.literal('update'),characterTemplateId:z.string().uuid(),name:z.string().trim().min(1).max(50).optional(),age:z.number().int().min(18).max(99).optional(),pronouns:z.string().trim().max(40).optional(),occupation:z.string().trim().min(1).max(100).optional(),biography:z.string().trim().min(20).max(1000).optional(),interests:z.array(z.string().trim().min(1).max(40)).max(12).optional(),personality:z.record(z.string(),z.number().min(0).max(1)).optional(),relationshipConfig:z.record(z.string(),z.unknown()).optional(),lifeConfig:z.record(z.string(),z.unknown()).optional()}),
  z.object({action:z.literal('generate_routine'),characterTemplateId:z.string().uuid()}),
  z.object({action:z.literal('finalize'),characterTemplateId:z.string().uuid()}),
  z.object({action:z.literal('archive'),characterTemplateId:z.string().uuid()}),
]);
const provider=new ConfiguredCharacterCreationProvider(),moderation=new ConfiguredModerationProvider();

serve(async(request,correlationId)=>{
  const{user,db}=await authenticated(request);const input=await parseBody(request,schema);await enforceRateLimit(db,user.id,`together_creator_${input.action}`,['generate_appearance','generate_draft_appearance'].includes(input.action)?8:30,3600);const now=new Date().toISOString();
  if(isCreatorStudioAction(input.action)){
    const data=await handleCreatorStudioAction({db,userId:user.id,action:input,now});
    return json({data,correlationId},input.action==='create_draft'?201:200,correlationId);
  }
  if(input.action==='quick_create'){
    const subscription=await resolveSubscriptionState(db,user.id);await enforceCustomCompanionLimit(db,user.id,subscription.capabilities);
    if(/\b(exactly like|identical to|clone of|look like)\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+)+/i.test(input.concept))throw new AppError('VALIDATION_ERROR','Create an original fictional person rather than copying a real person.',400);
    const safety=await moderation.check(input.concept);if(!safety.allowed)throw new AppError('VALIDATION_ERROR','That companion concept cannot be created. Try an original fictional adult.',400);
    const access=await resolveWorldAccess({db,userId:user.id,worldId:input.worldId});if(access==='locked')throw new AppError('FORBIDDEN','That world is not available for character creation.',403);
    const{data:world}=await db.from('together_worlds').select('id,name,default_arrival_location_id').eq('id',input.worldId).eq('published',true).maybeSingle();if(!world)throw new AppError('NOT_FOUND','Choose an available world.',404);
    const proposal=await provider.propose(input.concept);const locations=await worldLocations(db,input.worldId);const home=pickHome(locations,world.default_arrival_location_id),meeting=pickMeeting(locations,world.default_arrival_location_id,proposal.interests);if(!home||!meeting)throw new AppError('CONFLICT','That world needs a home and meeting place before someone can live there.',409);
    const suffix=crypto.randomUUID().replace(/-/g,'').slice(0,7),base=slugify(proposal.displayName)||'companion',handle=`${base}-${suffix}`;
    const firstMeeting={world_id:world.id,location_id:meeting.id,title:`First meeting at ${meeting.name}`,setup:`You notice ${proposal.displayName} at ${meeting.name}, focused on something connected to ${proposal.interests[0]??proposal.occupation}.`,companion_activity:`spending time at ${meeting.name}`,mood:proposal.personality.warmth>.65?'warmly curious':'observant',opening_line:openingLine(proposal.displayName,proposal.occupation,meeting.name,proposal.personality.directness),suggested_prompts:['What caught your attention?','Do you come here often?']};
    const templateInsert=await db.from('together_character_templates').insert({name:proposal.displayName,slug:handle,public_handle:handle,age:proposal.age,occupation:proposal.occupation,biography:proposal.biography,creator_id:user.id,current_published_version:1,published:false,lifecycle_status:'draft',visibility:'private',relationship_goal:input.relationshipGoal,connection_config:proposal.relationshipStyle,character_role:'romanceable_companion',can_be_selected:false,can_be_romanced:input.relationshipGoal!=='friendship',discovery_metadata:{summary:proposal.biography,traits:proposal.traits,goals:input.relationshipGoal==='friendship'?['Friendship','Stories']:['Dating','Friendship','Stories'],custom:true},first_meeting:firstMeeting}).select('*').single();if(templateInsert.error||!templateInsert.data)throw new AppError('INTERNAL_ERROR','Your character draft could not be saved.',500,true);
    const characterBible={promptVersion:2,values:{autonomy:.9,mutualRespect:.9},traits:proposal.traits,contradictions:[],ambitions:[`Grow meaningfully as ${article(proposal.occupation)} ${proposal.occupation.toLowerCase()}.`],communicationStyle:proposal.communicationStyle,relationshipStyle:proposal.relationshipStyle,affectionStyle:proposal.relationshipStyle,conflictStyle:{independentPointOfView:true,neverForcedAgreement:true},selfDisclosure:{startsGuarded:true,deepensWithTrust:true},initiative:{independentLife:true},boundaries:['fictional adult','mutual consent','independent point of view']};
    const template=templateInsert.data;const versionInsert=await db.from('together_character_versions').insert({character_template_id:template.id,version:1,pronouns:proposal.pronouns??null,personality_config:proposal.personality,values_config:{autonomy:.9,mutualRespect:.9},interests:proposal.interests,communication_style:proposal.communicationStyle,appearance_config:{description:proposal.appearanceDescription},voice_config:{},boundaries:['fictional adult','mutual consent','independent point of view'],default_social_graph:[],portrait_asset_key:null,relationship_config:proposal.relationshipStyle,life_config:{...proposal.lifestyleHints,homeWorldId:world.id,homeLocationId:home.id},character_bible:characterBible,appearance_candidates:[],published_at:null}).select('*').single();if(versionInsert.error||!versionInsert.data){await db.from('together_character_templates').delete().eq('id',template.id).eq('creator_id',user.id);throw new AppError('INTERNAL_ERROR','Your character identity could not be saved.',500,true);}
    const presenceInsert=await db.from('together_character_world_presence').insert({character_version_id:versionInsert.data.id,world_id:world.id,presence_type:'resident',home_location_id:home.id,familiarity:.8,visited_count:0,metadata:{custom:true,creator_id:user.id}});if(presenceInsert.error){await db.from('together_character_templates').delete().eq('id',template.id).eq('creator_id',user.id);throw new AppError('INTERNAL_ERROR','Your character could not be placed in that world.',500,true);}
    await track(db,user.id,'custom_companion_draft_created',{character_template_id:template.id,world_id:world.id,tier:subscription.tier});return json({data:{template:{...template,together_character_versions:versionInsert.data},proposal,homeLocation:home,meetingLocation:meeting},correlationId},201,correlationId);
  }

  if(!('characterTemplateId' in input))throw new AppError('VALIDATION_ERROR','A character is required for this legacy creator action.',400);
  const{template,version}=await ownedCharacter(db,user.id,input.characterTemplateId);
  if(input.action==='generate_appearance'){
    const subscription=await resolveSubscriptionState(db,user.id),requestId=input.requestId??crypto.randomUUID();
    const existing=(Array.isArray(version.appearance_candidates)?version.appearance_candidates:[]).filter((candidate:Record<string,unknown>)=>candidate.creditRequestId===requestId&&typeof candidate.storagePath==='string');
    if(existing.length){const signed=await db.storage.from('kivelle-character-reference').createSignedUrls(existing.map((item:Record<string,unknown>)=>String(item.storagePath)),3600);const candidates=existing.map((item:Record<string,unknown>,index:number)=>({...item,signedUrl:signed.data?.[index]?.signedUrl??null}));return json({data:{candidates,creditCost:40,creditBalance:subscription.creditBalance,idempotent:true},correlationId},200,correlationId);}
    const charged=await spendCredits(db,{userId:user.id,action:'creator_appearance_set',idempotencyKey:`creator-appearance:${template.id}:${requestId}`,referenceType:'custom_companion',referenceId:template.id,metadata:{requestId,tier:subscription.tier}});
    const uploaded:Array<Record<string,unknown>>=[];
    try{
      const proposal={displayName:template.name,age:template.age,pronouns:version.pronouns??undefined,occupation:template.occupation,biography:template.biography,interests:version.interests??[],traits:Object.keys(version.personality_config??{}),personality:version.personality_config,communicationStyle:version.communication_style??{},relationshipStyle:version.relationship_config??{},appearanceDescription:String(version.appearance_config?.description??`An original fictional adult identity for ${template.name}.`),lifestyleHints:version.life_config??{}} as any;
      const candidates=appearanceCandidates(proposal);const meeting=template.first_meeting as Record<string,unknown>,locationId=String(meeting?.location_id??version.life_config?.homeLocationId??'');if(!locationId)throw new AppError('CONFLICT','Choose a canonical home or meeting place before generating an appearance.',409);const place=await resolvePlaceContext({db,locationId,userId:user.id});const imageProvider=routeImageProvider('standard');
      const generated=await Promise.all(candidates.map(async(candidate)=>{const request:CanonicalImageGenerationRequest={mediaId:candidate.id,companion:{templateId:template.id,versionId:version.id,name:template.name,age:Number(template.age)},visualIdentity:{canonicalDescription:candidate.description,age:Number(template.age),referenceStoragePaths:[],identifyingFeatures:[],fashionStyle:candidate.label,visualDoNotChange:candidate.visualDoNotChange??[]},referenceImages:[],context:{place,activity:'a neutral canonical identity portrait',mood:'natural, self-possessed, approachable',timeOfDay:place.clock.daypart},composition:{shotType:'portrait',framing:'waist-up character portrait with face clearly visible and natural posture',aspectRatio:'4:5'},contentLevel:'standard',qualityTier:'standard'};return{candidate,image:await imageProvider.generate(request)}}));
      for(const item of generated){const extension=item.image.contentType==='image/webp'?'webp':item.image.contentType==='image/jpeg'?'jpg':'png',storagePath=`${user.id}/${template.id}/appearance-${item.candidate.id}.${extension}`;const upload=await db.storage.from('kivelle-character-reference').upload(storagePath,item.image.bytes,{contentType:item.image.contentType,upsert:true,cacheControl:'31536000'});if(upload.error)throw new AppError('INTERNAL_ERROR','Appearance options could not be stored.',500,true);uploaded.push({...item.candidate,storagePath,width:item.image.width,height:item.image.height,provider:imageProvider.id,model:item.image.model,creditRequestId:requestId,creditTransactionId:charged.transactionId});}
      const signed=await db.storage.from('kivelle-character-reference').createSignedUrls(uploaded.map((item)=>String(item.storagePath)),3600);const persisted=uploaded.map((item,index)=>({...item,signedUrl:signed.data?.[index]?.signedUrl??null}));const{error}=await db.from('together_character_versions').update({appearance_candidates:uploaded,updated_at:now}).eq('id',version.id);if(error)throw new AppError('INTERNAL_ERROR','Appearance options could not be prepared.',500,true);await track(db,user.id,'custom_companion_appearance_candidates_created',{character_template_id:template.id,count:candidates.length,provider:imageProvider.id,creditCost:charged.cost,tier:subscription.tier});return json({data:{candidates:persisted,creditCost:charged.cost,creditBalance:charged.balance},correlationId},200,correlationId);
    }catch(error){if(uploaded.length)await db.storage.from('kivelle-character-reference').remove(uploaded.map((item)=>String(item.storagePath)));await refundCredits(db,{userId:user.id,transactionId:charged.transactionId,idempotencyKey:`refund:${charged.transactionId}`,metadata:{reason:'creator_appearance_failed',requestId}});throw error;}
  }
  if(input.action==='select_appearance'){
    const candidates=Array.isArray(version.appearance_candidates)?version.appearance_candidates:[];const candidate=candidates.find((item:Record<string,unknown>)=>item.id===input.candidateId);if(!candidate)throw new AppError('NOT_FOUND','That appearance option is no longer available.',404);
    const identity={canonicalDescription:candidate.description,referenceStoragePaths:typeof candidate.storagePath==='string'?[candidate.storagePath]:[],hair:null,eyes:null,skinTone:null,build:null,identifyingFeatures:[],fashionStyle:candidate.label,visualDoNotChange:candidate.visualDoNotChange??[],identityVersion:Number(version.visual_identity?.identityVersion??0)+1,fictional:true};
    const hasInstance=await instanceCount(db,user.id,template.id);if(hasInstance>0&&!input.confirmVersionChange)throw new AppError('CONFLICT',`Your relationship with ${template.name} has already started. Choosing a different face creates a new CharacterVersion for future scenes while preserving existing history.`,409);const changes={visual_identity:identity,appearance_config:{...(version.appearance_config??{}),selectedCandidateId:input.candidateId}};
    if(hasInstance>0)await createReplacementVersion(db,user.id,template,version,changes,now);else{const{error}=await db.from('together_character_versions').update({...changes,updated_at:now}).eq('id',version.id);if(error)throw new AppError('INTERNAL_ERROR','That visual identity could not be selected.',500,true);}
    return json({data:{visualIdentity:identity,createdNewVersion:hasInstance>0},correlationId},200,correlationId);
  }
  if(input.action==='update'){
    const hasInstance=await instanceCount(db,user.id,template.id);const bible={...(version.character_bible??{}),promptVersion:2,...(input.personality?{personality:input.personality}:{}),...(input.relationshipConfig?{relationshipStyle:input.relationshipConfig}:{}),...(input.lifeConfig?{life:input.lifeConfig}:{})};const versionChanges={pronouns:input.pronouns??version.pronouns,personality_config:input.personality??version.personality_config,interests:input.interests??version.interests,relationship_config:input.relationshipConfig??version.relationship_config,life_config:input.lifeConfig??version.life_config,character_bible:bible};
    let nextVersion=version;if(hasInstance>0)nextVersion=await createReplacementVersion(db,user.id,template,version,versionChanges,now);else{const updated=await db.from('together_character_versions').update({...versionChanges,updated_at:now}).eq('id',version.id).select('*').single();if(updated.error||!updated.data)throw new AppError('INTERNAL_ERROR','Your character changes could not be saved.',500,true);nextVersion=updated.data;}
    const templateChanges={...(input.name?{name:input.name}:{}),...(input.age?{age:input.age}:{}),...(input.occupation?{occupation:input.occupation}:{}),...(input.biography?{biography:input.biography}:{})};if(Object.keys(templateChanges).length)await db.from('together_character_templates').update({...templateChanges,updated_at:now}).eq('id',template.id).eq('creator_id',user.id);return json({data:{version:nextVersion,createdNewVersion:hasInstance>0},correlationId},200,correlationId);
  }
  if(input.action==='generate_routine'){
    const worldId=String(version.life_config?.homeWorldId??'');const locations=await worldLocations(db,worldId);const homeId=String(version.life_config?.homeLocationId??pickHome(locations,null)?.id??''),work=locations.find((item)=>['work','studio','culture'].includes(String(item.category)))??locations.find((item)=>item.id!==homeId),social=locations.find((item)=>['cafe','food','nightlife','outdoor'].includes(String(item.category)))??work;if(!homeId||!work||!social)throw new AppError('CONFLICT','This world needs more authored places before a routine can be generated.',409);
    const rows=[];for(let day=1;day<=5;day++)rows.push({character_version_id:version.id,day_of_week:day,start_minute:540,end_minute:1020,location_id:work.id,activity:`working as ${article(template.occupation)} ${template.occupation.toLowerCase()}`,availability:'busy',energy_delta:-1,mood_influence:'focused',metadata:{source:'creator_generated'}},{character_version_id:version.id,day_of_week:day,start_minute:1110,end_minute:1260,location_id:social.id,activity:'unwinding after work',availability:'available',energy_delta:0,mood_influence:'relaxed',metadata:{source:'creator_generated'}});rows.push({character_version_id:version.id,day_of_week:6,start_minute:660,end_minute:900,location_id:social.id,activity:'taking a flexible Saturday',availability:'available',energy_delta:1,mood_influence:'open',metadata:{source:'creator_generated'}},{character_version_id:version.id,day_of_week:0,start_minute:600,end_minute:900,location_id:homeId,activity:'having a slow Sunday at home',availability:'limited',energy_delta:1,mood_influence:'rested',metadata:{source:'creator_generated'}});
    await db.from('together_schedule_templates').delete().eq('character_version_id',version.id);const created=await db.from('together_schedule_templates').insert(rows).select('*');if(created.error)throw new AppError('INTERNAL_ERROR','The routine could not be generated.',500,true);await db.from('together_character_versions').update({life_config:{...(version.life_config??{}),routineGeneratedAt:now},updated_at:now}).eq('id',version.id);return json({data:{schedule:created.data??[]},correlationId},200,correlationId);
  }
  if(input.action==='finalize'){
    const meeting=template.first_meeting as Record<string,unknown>;if(!meeting?.world_id||!meeting?.location_id)throw new AppError('CONFLICT','Generate a valid first meeting before meeting this companion.',409);const{error}=await db.from('together_character_templates').update({lifecycle_status:'ready',can_be_selected:true,updated_at:now}).eq('id',template.id).eq('creator_id',user.id);if(error)throw new AppError('INTERNAL_ERROR','This companion could not be made ready.',500,true);await track(db,user.id,'custom_companion_ready',{character_template_id:template.id});return json({data:{ready:true,characterTemplateId:template.id,publicHandle:template.public_handle},correlationId},200,correlationId);
  }
  const{error}=await db.from('together_character_templates').update({lifecycle_status:'archived',can_be_selected:false,updated_at:now}).eq('id',template.id).eq('creator_id',user.id);if(error)throw new AppError('INTERNAL_ERROR','This creation could not be archived.',500,true);return json({data:{archived:true},correlationId},200,correlationId);
});

async function ownedCharacter(db:any,userId:string,id:string){const{data:template}=await db.from('together_character_templates').select('*,together_character_versions(*)').eq('id',id).eq('creator_id',userId).maybeSingle();if(!template)throw new AppError('NOT_FOUND','That private creation is unavailable.',404);const versions=template.together_character_versions??[];const version=versions.find((item:Record<string,unknown>)=>Number(item.version)===Number(template.current_published_version))??versions.sort((a:any,b:any)=>b.version-a.version)[0];if(!version)throw new AppError('CONFLICT','That creation has no identity version.',409);return{template,version};}
async function instanceCount(db:any,userId:string,templateId:string){const result=await db.from('together_character_instances').select('id',{count:'exact',head:true}).eq('user_id',userId).eq('character_template_id',templateId);if(result.error)throw new AppError('INTERNAL_ERROR','Kivelle could not verify this character history.',500,true);return result.count??0;}
async function createReplacementVersion(db:any,userId:string,template:Record<string,any>,version:Record<string,any>,changes:Record<string,unknown>,now:string){
  const created=await db.from('together_character_versions').insert({...stripVersion(version),...changes,id:undefined,character_template_id:template.id,version:Number(version.version)+1,published_at:null,created_at:undefined,updated_at:undefined}).select('*').single();if(created.error||!created.data)throw new AppError('INTERNAL_ERROR','A new character version could not be created.',500,true);
  const[presence,schedules]=await Promise.all([db.from('together_character_world_presence').select('*').eq('character_version_id',version.id),db.from('together_schedule_templates').select('*').eq('character_version_id',version.id)]);if(presence.error||schedules.error){await db.from('together_character_versions').delete().eq('id',created.data.id);throw new AppError('INTERNAL_ERROR','The character life configuration could not be preserved.',500,true);}
  const presenceRows=(presence.data??[]).map((row:Record<string,unknown>)=>copyVersionChild(row,created.data.id));const scheduleRows=(schedules.data??[]).map((row:Record<string,unknown>)=>copyVersionChild(row,created.data.id));
  const[presenceCopy,scheduleCopy]=await Promise.all([presenceRows.length?db.from('together_character_world_presence').insert(presenceRows):Promise.resolve({error:null}),scheduleRows.length?db.from('together_schedule_templates').insert(scheduleRows):Promise.resolve({error:null})]);if(presenceCopy.error||scheduleCopy.error){await db.from('together_character_versions').delete().eq('id',created.data.id);throw new AppError('INTERNAL_ERROR','The character routine could not be preserved.',500,true);}
  const templateUpdate=await db.from('together_character_templates').update({current_published_version:created.data.version,updated_at:now}).eq('id',template.id).eq('creator_id',userId);if(templateUpdate.error){await db.from('together_character_versions').delete().eq('id',created.data.id);throw new AppError('INTERNAL_ERROR','The new identity could not be activated.',500,true);}
  const instances=await db.from('together_character_instances').update({character_version_id:created.data.id,updated_at:now}).eq('user_id',userId).eq('character_template_id',template.id);if(instances.error){await db.from('together_character_templates').update({current_published_version:version.version,updated_at:now}).eq('id',template.id).eq('creator_id',userId);throw new AppError('INTERNAL_ERROR','Existing relationships could not move to the new identity version.',500,true);}
  return created.data;
}
async function worldLocations(db:any,worldId:string){const{data}=await db.from('together_locations').select('*').eq('world_id',worldId).order('sort_order');return(data??[])as Array<Record<string,any>>}function pickHome(locations:Array<Record<string,any>>,fallback:string|null){return locations.find((item)=>item.location_type==='residence')??locations.find((item)=>['district','neighborhood'].includes(item.location_type))??locations.find((item)=>item.id===fallback)??locations[0]??null}function pickMeeting(locations:Array<Record<string,any>>,fallback:string|null,interests:string[]){const cultural=interests.some((item)=>/design|architecture|art/i.test(item));return cultural?locations.find((item)=>['culture','gallery'].includes(String(item.category)))??locations.find((item)=>item.slug?.includes('glassline'))??locations.find((item)=>item.id===fallback)??locations[0]:locations.find((item)=>['cafe','culture','food'].includes(String(item.category)))??locations.find((item)=>item.id===fallback)??locations[0]??null}function openingLine(name:string,occupation:string,place:string,directness:number){void name;void occupation;void place;return directness>.7?`I need a second opinion. Does this look as badly designed to you as it does to me?`:`I was starting to think I was the only person actually looking at this. What do you think?`;}function slugify(value:string){return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,30)}function stripVersion(value:Record<string,unknown>){const{id,created_at,updated_at,together_character_templates,...rest}=value;void id;void created_at;void updated_at;void together_character_templates;return rest}function article(value:string){return/^[aeiou]/i.test(value)?'an':'a'}
function copyVersionChild(value:Record<string,unknown>,characterVersionId:string){const{id,created_at,updated_at,...rest}=value;void id;void created_at;void updated_at;return{...rest,character_version_id:characterVersionId};}
