import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, MessageCircle, Sparkles } from 'lucide-react-native';
import { Body, EmptyState, GlassCard, GradientButton, LoadingSkeleton, MediaGallery, Screen, SectionHeader } from '../../src/components';
import { colors } from '../../src/theme';
import { useTogether } from '../../src/store/useTogether';

export default function StoryDetail(){const{id}=useLocalSearchParams<{id:string}>();const snapshot=useTogether((state)=>state.snapshot);if(!snapshot)return <LoadingSkeleton/>;const story=snapshot.storyArcs?.find((item)=>item.id===id);if(!story)return <EmptyState title="Story unavailable" body="This story may have reached its end." action="Back to World" onAction={()=>router.replace('/(tabs)/worlds')}/>;const companion=snapshot.characters.find((item)=>item.id===story.character_instance_id);const template=story.together_story_arc_templates;const current=template?.chapters.find((chapter)=>chapter.id===story.current_chapter_id);const known=snapshot.lifeEvents.filter((event)=>event.character_instance_id===story.character_instance_id&&String(event.metadata?.arc_slug??'')===story.template_slug&&event.user_should_know!==false).slice(0,4);const photos=(snapshot.generatedMedia??[]).filter((item)=>item.story_arc_id===story.id);const name=companion?.together_character_templates.name??'Your companion';return <Screen><View style={styles.header}><Pressable accessibilityLabel="Back to World" onPress={()=>router.back()} style={styles.back}><ArrowLeft color={colors.text}/></Pressable><Text style={styles.kicker}>AN OPEN STORY</Text></View><Text style={styles.title}>{template?.title??'Something is happening'}</Text><Body muted>{known[0]?.narrative_summary??current?.narrativeSeed??`${name}'s life is moving forward.`}</Body>{photos.length?<><SectionHeader title="From this story"/><MediaGallery media={photos}/></>:null}<SectionHeader title="What you know"/><GlassCard style={styles.card}>{known.length?known.map((event)=><View key={event.id} style={styles.beat}><Sparkles size={15} color={colors.rose}/><Text style={styles.beatText}>{event.narrative_summary}</Text></View>):<Text style={styles.beatText}>This story is still taking shape.</Text>}</GlassCard><GradientButton label={`Talk to ${name} about it`} icon={<MessageCircle size={17} color="#fff"/>} onPress={()=>router.push(`/chat?character=${companion?.together_character_templates.slug??''}&story=${story.id}` as never)}/></Screen>}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:40,height:40,borderRadius:20,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},kicker:{color:colors.rose,fontSize:10,fontWeight:'900',letterSpacing:1.1},title:{fontFamily:'Georgia',fontSize:35,color:colors.text},card:{gap:10},beat:{flexDirection:'row',gap:9,alignItems:'flex-start'},beatText:{flex:1,color:colors.muted,fontSize:12,lineHeight:18}});
