import{describe,expect,it}from'vitest';
import{buildClientConversationContext}from'./conversationContext';
import type{CharacterInstance,Snapshot}from'../types';

const character={id:'maya-instance',user_id:'user',character_template_id:'maya',character_version_id:'maya-v1',relationship_stage:'friend',current_mood:'playful',current_activity:'editing photos',current_location_id:'apartment',current_energy:'medium',contact_added_at:'2026-08-01',introduced_at:'2026-08-01',met_at:'2026-08-01',last_simulated_at:'2026-08-14',together_character_templates:{id:'maya',name:'Maya',slug:'maya',age:26,occupation:'Photographer',biography:''},together_character_versions:{id:'maya-v1',portrait_asset_key:'maya',interests:['photography'],personality_config:{}}}satisfies CharacterInstance;
const snapshot={profile:null,discoverableCharacters:[],worlds:[],locations:[{id:'apartment',name:"Maya's Apartment",slug:'apartment',description:'',category:'home',possible_activities:[]},{id:'juniper',name:'Juniper CafÃ©',slug:'juniper',description:'',category:'cafe',possible_activities:[]}],characters:[character],schedules:[],relationships:[],dates:[],moments:[],memories:[],openThreads:[],conversations:[],sharedPlans:[],conversationEvents:[],lifeEvents:[],proactiveMessages:[],entitlements:null,notificationPreferences:null}as unknown as Snapshot;

describe('client conversation context',()=>{
  it('does not render a future event as the current scene',()=>{const context=buildClientConversationContext({...snapshot,lifeEvents:[{id:'future',character_instance_id:character.id,title:'Dinner',narrative_summary:'Dinner at Juniper.',starts_at:'2026-08-14T20:00:00Z',ends_at:'2026-08-14T21:00:00Z',location_id:'juniper'}]},character,new Date('2026-08-14T18:00:00Z'));expect(context.scene.location).toBe("Maya's Apartment");expect(context.scene.summary).toContain('editing photos');expect(context.nextCommitment?.title).toBeUndefined();});
  it('does not treat an undated historical event as the current scene',()=>{const context=buildClientConversationContext({...snapshot,lifeEvents:[{id:'history',character_instance_id:character.id,title:'Old coffee',narrative_summary:'A coffee meeting from last week.',starts_at:'2026-08-07T18:00:00Z',location_id:'juniper'}]},character,new Date('2026-08-14T18:00:00Z'));expect(context.scene.location).toBe("Maya's Apartment");expect(context.scene.summary).toContain('editing photos');});
  it('uses the clean open-thread prompt',()=>{const context=buildClientConversationContext({...snapshot,openThreads:[{id:'thread',character_instance_id:character.id,topic:"Ask how the user's presentation went.",subject:'presentation',display_subject:'Presentation',followup_prompt:'I should tell you how my presentation went.',expected_at:'2026-08-14',follow_up_eligible:true}]},character,new Date('2026-08-14T18:00:00Z'));expect(context.prompts[0]).toBe('I should tell you how my presentation went.');expect(context.prompts[0]).not.toContain('Ask how');});
  it('uses only this companion\'s canonical plan as the next commitment',()=>{const context=buildClientConversationContext({...snapshot,sharedPlans:[{id:'maya-plan',character_instance_id:character.id,title:'Drinks at Velvet Hour',activity_key:'drinks',location_id:'juniper',starts_at:'2026-08-16T00:00:00Z',ends_at:'2026-08-16T01:30:00Z',status:'scheduled',source:'chat',created_at:'2026-08-14T18:00:00Z',updated_at:'2026-08-14T18:00:00Z'},{id:'other-plan',character_instance_id:'sofia',title:'Coffee',activity_key:'coffee',location_id:'juniper',starts_at:'2026-08-15T19:00:00Z',ends_at:'2026-08-15T20:00:00Z',status:'scheduled',source:'chat',created_at:'2026-08-14T18:00:00Z',updated_at:'2026-08-14T18:00:00Z'}]},character,new Date('2026-08-14T18:00:00Z'));expect(context.nextCommitment?.id).toBe('maya-plan');});
  it('uses an active plan as the canonical current scene',()=>{const context=buildClientConversationContext({...snapshot,sharedPlans:[{id:'now',character_instance_id:character.id,title:'Movie at Juniper',activity_key:'movie',location_id:'juniper',starts_at:'2026-08-14T18:00:00Z',ends_at:'2026-08-14T20:30:00Z',status:'active',source:'chat',created_at:'2026-08-14T12:00:00Z',updated_at:'2026-08-14T18:00:00Z'}]},character,new Date('2026-08-14T19:00:00Z'));expect(context.activePlan?.id).toBe('now');expect(context.scene.location).toContain('Juniper');expect(context.prompts[0]).not.toContain('How is your day');});
  it('keeps direct chat remote when the companion has a physical location',()=>{const context=buildClientConversationContext(snapshot,character,new Date('2026-08-14T19:00:00Z'));expect(context.interactionMode).toBe('remote');expect(context.scene.summary).toContain('Maya is');});
  it('renders a persisted drop-in as co-present and only asks for arrival once',()=>{const context=buildClientConversationContext({...snapshot,conversations:[{id:'conversation',character_instance_id:character.id,kind:'direct',title:null,last_message_at:null,metadata:{activeScene:{version:1,characterInstanceId:character.id,locationId:'apartment',worldId:'juniper',interactionMode:'co_present',entryReason:'user_drop_in',enteredAt:'2026-08-14T18:00:00Z',updatedAt:'2026-08-14T18:00:00Z'}}}]},character,new Date('2026-08-14T19:00:00Z'));expect(context.interactionMode).toBe('co_present');expect(context.entryReason).toBe('user_drop_in');expect(context.sceneBehavior.acknowledgeArrival).toBe(true);});
  it('prioritizes a starting-soon plan over a generic open thread',()=>{const context=buildClientConversationContext({...snapshot,sharedPlans:[{id:'soon',character_instance_id:character.id,title:'Coffee at Juniper',activity_key:'coffee',location_id:'juniper',starts_at:'2026-08-14T21:00:00Z',ends_at:'2026-08-14T22:00:00Z',status:'scheduled',source:'chat',created_at:'2026-08-14T12:00:00Z',updated_at:'2026-08-14T12:00:00Z'}],openThreads:[{id:'thread',character_instance_id:character.id,topic:'presentation',expected_at:null,follow_up_eligible:true}]},character,new Date('2026-08-14T18:00:00Z'));expect(context.startingSoon?.id).toBe('soon');expect(context.prompts[0]).toContain('Still good');});
  it('turns a recently completed plan into talk-about-it context',()=>{const context=buildClientConversationContext({...snapshot,sharedPlans:[{id:'past',character_instance_id:character.id,title:'Drinks at Juniper',activity_key:'drinks',location_id:'juniper',starts_at:'2026-08-13T23:00:00Z',ends_at:'2026-08-14T00:30:00Z',status:'completed',source:'chat',completed_at:'2026-08-14T00:30:00Z',created_at:'2026-08-13T12:00:00Z',updated_at:'2026-08-14T00:30:00Z'}]},character,new Date('2026-08-14T18:00:00Z'));expect(context.recentPlan?.id).toBe('past');expect(context.prompts).toContain('We should do that again.');});
});

