import type { CharacterInstance, Location, PlaceContext, Snapshot, World } from '../types';
import { currentScheduleEvent } from './lifePresentation';

export function worldById(snapshot:Snapshot,worldId?:string|null){return worldId?snapshot.worlds.find((world)=>world.id===worldId):undefined;}
export function locationById(snapshot:Snapshot,locationId?:string|null){return locationId?snapshot.locations.find((location)=>location.id===locationId):undefined;}
export function worldForLocation(snapshot:Snapshot,locationId?:string|null){const location=locationById(snapshot,locationId);return worldById(snapshot,location?.world_id);}
export function locationsForWorld(snapshot:Snapshot,worldId:string){return snapshot.locations.filter((location)=>location.world_id===worldId).sort((a,b)=>(a.sort_order??0)-(b.sort_order??0)||a.name.localeCompare(b.name));}
export function childLocations(snapshot:Snapshot,parentId:string){return snapshot.locations.filter((location)=>location.parent_location_id===parentId).sort((a,b)=>(a.sort_order??0)-(b.sort_order??0)||a.name.localeCompare(b.name));}
export function nearbyLocations(snapshot:Snapshot,locationId:string){const location=locationById(snapshot,locationId);if(!location)return[];return snapshot.locations.filter((item)=>item.id!==location.id&&item.world_id===location.world_id&&((location.parent_location_id&&item.parent_location_id===location.parent_location_id)||item.parent_location_id===location.id||location.parent_location_id===item.id)).sort((a,b)=>(a.sort_order??0)-(b.sort_order??0)||a.name.localeCompare(b.name));}
export function locationAncestry(snapshot:Snapshot,locationId:string){const result:Location[]=[];const visited=new Set<string>();let location=locationById(snapshot,locationId);while(location?.parent_location_id){if(visited.has(location.parent_location_id)||visited.size>16)break;visited.add(location.parent_location_id);const parent=locationById(snapshot,location.parent_location_id);if(!parent||parent.world_id!==location.world_id)break;result.unshift(parent);location=parent;}return result;}
export function placePath(snapshot:Snapshot,locationId:string){const location=locationById(snapshot,locationId);if(!location)return'';const world=worldById(snapshot,location.world_id);return[world?.name,...locationAncestry(snapshot,locationId).map((item)=>item.name),location.name].filter(Boolean).join(' → ');}
export function buildClientPlaceContext(snapshot:Snapshot,locationId:string,now=new Date()):PlaceContext|undefined{const location=locationById(snapshot,locationId),world=worldById(snapshot,location?.world_id);if(!location||!world)return undefined;const timezone=world.timezone||'UTC';const parts=new Intl.DateTimeFormat('en-US',{timeZone:timezone,weekday:'long',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now);const part=(key:string)=>parts.find((item)=>item.type===key)?.value??'';const hour=Number(part('hour'));const explicitNearby=location.canonical_lore?.nearbyLocationSlugs??[];const nearby=(explicitNearby.length?explicitNearby.map((slug)=>snapshot.locations.find((item)=>item.world_id===world.id&&item.slug===slug)).filter((item):item is Location=>Boolean(item)):nearbyLocations(snapshot,locationId)).slice(0,8);return{contextVersion:1,world:{id:world.id,slug:world.slug,name:world.name,description:world.description,timezone,accessType:world.access_type,visualContext:world.visual_context??{}},location:{id:location.id,slug:location.slug,name:location.name,type:location.location_type,description:location.description,category:location.category,hours:location.hours??null,possibleActivities:location.possible_activities,visualContext:location.canonical_visual_context??{},lore:location.canonical_lore??{}},ancestry:locationAncestry(snapshot,locationId).map((item)=>({id:item.id,slug:item.slug,name:item.name,type:item.location_type,description:item.description,lore:item.canonical_lore??{}})),nearby:nearby.map((item)=>({id:item.id,slug:item.slug,name:item.name,type:item.location_type,category:item.category,description:item.description,possibleActivities:item.possible_activities})),path:placePath(snapshot,locationId),clock:{timezone,localIso:`${part('year')}-${part('month')}-${part('day')}T${part('hour')}:${part('minute')}`,weekday:part('weekday'),localTime:`${part('hour')}:${part('minute')}`,daypart:hour<5?'overnight':hour<12?'morning':hour<17?'afternoon':hour<22?'evening':'late_night'}};}
export function charactersConnectedToWorld(snapshot:Snapshot,worldId:string){const allowedVersions=new Set((snapshot.characterWorldPresence??[]).filter((presence)=>presence.world_id===worldId&&presence.presence_type!=='unavailable').map((presence)=>presence.character_version_id));return snapshot.characters.filter((character)=>worldForLocation(snapshot,character.current_location_id)?.id===worldId||allowedVersions.has(character.character_version_id));}
export function charactersCurrentlyAtLocation(snapshot:Snapshot,locationId:string,now=new Date()){return snapshot.characters.filter((character)=>{const event=currentScheduleEvent(snapshot.scheduleEvents,character.id,now,character.current_schedule_event_id);const actual=event?.location_id??character.current_location_id;return actual===locationId&&event?.activity_key!=='travel'&&character.current_interruptibility!=='unavailable';});}
export function charactersCurrentlyInWorld(snapshot:Snapshot,worldId:string,now=new Date()){return snapshot.characters.filter((character)=>worldForLocation(snapshot,(currentScheduleEvent(snapshot.scheduleEvents,character.id,now,character.current_schedule_event_id)?.location_id??character.current_location_id))?.id===worldId&&currentScheduleEvent(snapshot.scheduleEvents,character.id,now,character.current_schedule_event_id)?.activity_key!=='travel');}
/** Backwards-compatible connected catalog selector; use charactersCurrently* for physical presence. */
export function charactersForWorld(snapshot:Snapshot,worldId:string){return charactersConnectedToWorld(snapshot,worldId);}
export function plansForWorld(snapshot:Snapshot,worldId:string){return(snapshot.sharedPlans??[]).filter((plan)=>(plan.world_id??worldForLocation(snapshot,plan.location_id)?.id)===worldId);}
export function datesForWorld(snapshot:Snapshot,worldId:string){return snapshot.dates.filter((date)=>date.together_date_templates.world_id===worldId);}
export function mediaForWorld(snapshot:Snapshot,worldId:string){return(snapshot.generatedMedia??[]).filter((media)=>(media.world_id??worldForLocation(snapshot,media.location_id)?.id)===worldId);}
export function worldAccessLabel(snapshot:Snapshot,world:World):'FREE'|'INCLUDED'|'OWNED'|'KIVELLE+'|'PREMIUM'{const row=(snapshot.userWorlds??[]).find((item)=>item.world_id===world.id);if(world.access_type==='free')return'FREE';if(row?.access_status==='unlocked')return'OWNED';if(world.access_type==='subscription')return'KIVELLE+';return'PREMIUM';}
export function characterCurrentWorld(snapshot:Snapshot,character?:CharacterInstance){return character?worldForLocation(snapshot,character.current_location_id):undefined;}
