import { describe, expect, it } from 'vitest';
import { buildClientPlaceContext, charactersForWorld, locationsForWorld, nearbyLocations, placePath, worldAccessLabel } from './place';
import type { Snapshot } from '../types';

const world=(id:string,name:string,access_type:'free'|'premium'='free')=>({id,slug:name.toLowerCase().replaceAll(' ','-'),name,description:`${name} description`,access_type,timezone:id==='tokyo'?'Asia/Tokyo':'America/New_York',sort_order:0,featured:true,published:true,visual_context:{setting:name},metadata:{}} as const);
const snapshot={worlds:[world('juniper','Juniper City'),world('tokyo','Tokyo After Dark','premium')],locations:[{id:'alder',world_id:'juniper',name:'Alder District',slug:'alder',location_type:'district',description:'Alder',category:'district',possible_activities:[]},{id:'velvet',world_id:'juniper',parent_location_id:'alder',name:'Velvet Hour',slug:'velvet-hour',location_type:'venue',description:'Lounge',category:'lounge',possible_activities:['drinks']},{id:'shibuya',world_id:'tokyo',name:'Shibuya',slug:'shibuya',location_type:'district',description:'Shibuya',category:'district',possible_activities:[]},{id:'arcade',world_id:'tokyo',parent_location_id:'shibuya',name:'Neon Arcade',slug:'neon-arcade',location_type:'venue',description:'Arcade',category:'arcade',possible_activities:['games']}],characters:[{id:'maya',character_version_id:'maya-v',current_location_id:'velvet',together_character_templates:{slug:'maya'}}],characterWorldPresence:[{id:'p',character_version_id:'maya-v',world_id:'juniper',presence_type:'resident',familiarity:1,visited_count:1,metadata:{}}],userWorlds:[],sharedPlans:[],generatedMedia:[],dates:[]} as unknown as Snapshot;

describe('canonical place selectors',()=>{
  it('resolves world and ancestry for a location',()=>{expect(placePath(snapshot,'velvet')).toBe('Juniper City → Alder District → Velvet Hour');expect(buildClientPlaceContext(snapshot,'velvet')?.world.name).toBe('Juniper City');});
  it('filters world content without moving the character',()=>{expect(locationsForWorld(snapshot,'tokyo').map((item)=>item.name)).toEqual(['Neon Arcade','Shibuya']);expect(snapshot.characters[0]?.current_location_id).toBe('velvet');expect(charactersForWorld(snapshot,'tokyo')).toHaveLength(0);});
  it('makes every free world available without Juniper hardcoding',()=>{expect(worldAccessLabel(snapshot,world('second-free','Second Free'))).toBe('FREE');expect(worldAccessLabel(snapshot,snapshot.worlds[1]!)).toBe('PREMIUM');});
  it('uses the configured world timezone',()=>{expect(buildClientPlaceContext(snapshot,'arcade',new Date('2026-08-15T12:00:00Z'))?.clock.localTime).toBe('21:00');});
  it('finds nearby places through hierarchy without crossing worlds',()=>{const withSibling={...snapshot,locations:[...snapshot.locations,{...snapshot.locations[1]!,id:'paper',name:'Paper Trail'}]};expect(nearbyLocations(withSibling,'velvet').map((item)=>item.name)).toEqual(['Alder District','Paper Trail']);});
});
