import{describe,expect,it}from'vitest';
import{annualSavingsPercentage,billingStatusPresentation,checkoutBackoffDelay,creditActivityPresentation,membershipBenefits,membershipMetrics,membershipPageMode,membershipPricePresentation,normalizeSubscriptionIntent,preferredPaidTier,safeSubscriptionReturnTo,shouldShowSubscriptionIntentCallout,subscriptionHref}from'./subscriptionPresentation';
import type{SubscriptionPlan,SubscriptionStatus}from'./subscription';

const status=(overrides:Partial<SubscriptionStatus>={}):SubscriptionStatus=>({tier:'kivelle_plus',capabilities:{tier:'kivelle_plus',displayName:'Kivelle+',monthlyPriceUsd:19.99,annualPriceUsd:199.99,chatDailyLimit:20,introductoryChatDailyLimit:null,introductoryChatDays:0,includedCompanionPhotoDailyLimit:1,includedDatePhotoMonthlyLimit:1,intelligenceProfile:'deep',memoryRetrievalBudget:12,historyRetrievalBudget:3,maxLives:3,maxCustomCompanions:5,worldAccess:'all_standard',earlyWorldAccess:false,monthlyCreditGrant:500,subscriptionCreditRolloverCap:1000,mediaQueue:'priority'},creditBalance:{permanentBalance:10,subscriptionBalance:20,total:30},entitlementKeys:[],billing:{provider:'stripe',status:'active',periodEnd:'2026-09-30T00:00:00Z'},management:{mode:'stripe',label:'Stripe',canManageSubscription:true,manageAction:'portal',canPurchaseCredits:true,managementReason:'Stripe',creditPurchaseReason:null},catalog:[],creditCosts:{},creditPacks:[],creditActivity:[],billingConfigured:{kivelle_plus:true,kivelle_max:true,credits:true,portal:true},...overrides});

describe('subscription presentation',()=>{
  it('builds contextual local-only subscription routes',()=>{expect(subscriptionHref({intent:'photo_sharing',returnTo:'/chat?character=bianca'})).toBe('/subscription?intent=photo_sharing&returnTo=%2Fchat%3Fcharacter%3Dbianca');expect(safeSubscriptionReturnTo('https://evil.example')).toBeNull();expect(safeSubscriptionReturnTo('//evil.example')).toBeNull();});
  it('maps the legacy photo-sharing source and defaults unknown intents',()=>{expect(normalizeSubscriptionIntent(undefined,'share-photo')).toBe('photo_sharing');expect(normalizeSubscriptionIntent('unknown')).toBe('plans');});
  it('keeps paid subscribers on their current tier unless a tier was explicitly requested',()=>{expect(preferredPaidTier('kivelle_max')).toBe('kivelle_max');expect(preferredPaidTier('kivelle_plus')).toBe('kivelle_plus');expect(preferredPaidTier('free')).toBe('kivelle_plus');expect(preferredPaidTier('kivelle_max','kivelle_plus')).toBe('kivelle_plus');});
  it('computes savings and bounded progressive checkout delays',()=>{expect(annualSavingsPercentage(19.99,199.99)).toBe(17);expect(checkoutBackoffDelay(0)).toBe(0);expect(checkoutBackoffDelay(99)).toBe(10000);});
  it('presents active, granted, cancellation, and payment states clearly',()=>{expect(billingStatusPresentation(status()).label).toBe('Active');expect(billingStatusPresentation(status({management:{...status().management,mode:'kivelle'}})).detail).toContain('provided directly');expect(billingStatusPresentation(status({billing:{status:'past_due',periodEnd:'2026-09-01T00:00:00Z'}})).tone).toBe('warning');expect(billingStatusPresentation(status({billing:{status:'active',cancelAtPeriodEnd:true,periodEnd:'2026-09-30T00:00:00Z'}})).label).toBe('Cancellation scheduled');});
  it('uses safe user-facing credit activity labels without metadata',()=>{expect(creditActivityPresentation({id:'1',eventType:'refund',permanentDelta:10,subscriptionDelta:0,createdAt:'2026-08-30T00:00:00Z'})).toMatchObject({label:'Automatic refund',amount:10});});
  it('explains plan-change reductions and restorations without calling them charges',()=>{
    expect(creditActivityPresentation({id:'1',eventType:'adjustment',permanentDelta:0,subscriptionDelta:-200,createdAt:'2026-08-31T00:00:00Z',adjustmentReason:'tier_cap_reduced'})).toMatchObject({label:'Plan limit adjustment',amount:-200});
    expect(creditActivityPresentation({id:'2',eventType:'adjustment',permanentDelta:0,subscriptionDelta:200,createdAt:'2026-08-31T00:01:00Z',adjustmentReason:'tier_cap_restored'})).toMatchObject({label:'Plan Credits restored',amount:200});
  });
  it('switches the membership experience from discovery to an active member dashboard',()=>{expect(membershipPageMode('free')).toBe('discovery');expect(membershipPageMode('kivelle_plus')).toBe('member');expect(membershipPageMode('kivelle_max')).toBe('member');});
  it('hides the redundant generic Credits callout for every membership state',()=>{expect(shouldShowSubscriptionIntentCallout('discovery','credits')).toBe(false);expect(shouldShowSubscriptionIntentCallout('member','credits')).toBe(false);expect(shouldShowSubscriptionIntentCallout('discovery','photo_sharing')).toBe(true);});
  it('derives member metrics and benefits from the authoritative plan instead of mockup values',()=>{const plan=status().capabilities as SubscriptionPlan;expect(membershipMetrics(plan)).toEqual([{key:'lives',value:3,label:'Lives',detail:'available'},{key:'companions',value:5,label:'companions',detail:'custom slots'},{key:'photos',value:1,label:'photos daily',detail:'included generation'}]);expect(membershipBenefits(plan)).toContain('20 conversations per day and group chats');expect(membershipBenefits(plan)).toContain('500 monthly Kivelle Credits');expect(membershipBenefits(plan)).toContain('3 Lives and 5 custom companions');});
  it('presents monthly and annual catalog pricing without hard-coded page prices',()=>{const plan=status().capabilities as SubscriptionPlan;expect(membershipPricePresentation(plan,'monthly')).toEqual({primary:'$19.99',period:'/ month',detail:'Billed monthly'});expect(membershipPricePresentation(plan,'annual')).toEqual({primary:'$16.67',period:'/ month',detail:'$199.99 billed yearly'});});
});
