import{describe,expect,it}from'vitest';
import{annualSavingsPercentage,billingStatusPresentation,checkoutBackoffDelay,creditActivityPresentation,normalizeSubscriptionIntent,safeSubscriptionReturnTo,subscriptionHref}from'./subscriptionPresentation';
import type{SubscriptionStatus}from'./subscription';

const status=(overrides:Partial<SubscriptionStatus>={}):SubscriptionStatus=>({tier:'kivelle_plus',capabilities:{tier:'kivelle_plus',displayName:'Kivelle+',monthlyPriceUsd:19.99,annualPriceUsd:199.99,chatDailyLimit:null,introductoryChatDailyLimit:null,introductoryChatDays:0,includedCompanionPhotoDailyLimit:1,includedDatePhotoMonthlyLimit:1,intelligenceProfile:'deep',memoryRetrievalBudget:12,historyRetrievalBudget:3,maxLives:3,maxCustomCompanions:5,worldAccess:'all_standard',earlyWorldAccess:false,monthlyCreditGrant:500,subscriptionCreditRolloverCap:1000,mediaQueue:'priority'},creditBalance:{permanentBalance:10,subscriptionBalance:20,total:30},entitlementKeys:[],billing:{provider:'stripe',status:'active',periodEnd:'2026-09-30T00:00:00Z'},management:{mode:'stripe',label:'Stripe',canManageSubscription:true,manageAction:'portal',canPurchaseCredits:true,managementReason:'Stripe',creditPurchaseReason:null},catalog:[],creditCosts:{},creditPacks:[],creditActivity:[],billingConfigured:{kivelle_plus:true,kivelle_max:true,credits:true,portal:true},...overrides});

describe('subscription presentation',()=>{
  it('builds contextual local-only subscription routes',()=>{expect(subscriptionHref({intent:'photo_sharing',returnTo:'/chat?character=bianca'})).toBe('/subscription?intent=photo_sharing&returnTo=%2Fchat%3Fcharacter%3Dbianca');expect(safeSubscriptionReturnTo('https://evil.example')).toBeNull();expect(safeSubscriptionReturnTo('//evil.example')).toBeNull();});
  it('maps the legacy photo-sharing source and defaults unknown intents',()=>{expect(normalizeSubscriptionIntent(undefined,'share-photo')).toBe('photo_sharing');expect(normalizeSubscriptionIntent('unknown')).toBe('plans');});
  it('computes savings and bounded progressive checkout delays',()=>{expect(annualSavingsPercentage(19.99,199.99)).toBe(17);expect(checkoutBackoffDelay(0)).toBe(0);expect(checkoutBackoffDelay(99)).toBe(10000);});
  it('presents active, granted, cancellation, and payment states clearly',()=>{expect(billingStatusPresentation(status()).label).toBe('Active');expect(billingStatusPresentation(status({management:{...status().management,mode:'kivelle'}})).detail).toContain('provided directly');expect(billingStatusPresentation(status({billing:{status:'past_due',periodEnd:'2026-09-01T00:00:00Z'}})).tone).toBe('warning');expect(billingStatusPresentation(status({billing:{status:'active',cancelAtPeriodEnd:true,periodEnd:'2026-09-30T00:00:00Z'}})).label).toBe('Cancellation scheduled');});
  it('uses safe user-facing credit activity labels without metadata',()=>{expect(creditActivityPresentation({id:'1',eventType:'refund',permanentDelta:10,subscriptionDelta:0,createdAt:'2026-08-30T00:00:00Z'})).toMatchObject({label:'Automatic refund',amount:10});});
});
