import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '../theme';

export const styles = StyleSheet.create({
  pageMobile: { padding: spacing.md, paddingBottom: 120, gap: 0 },
  pageDesktop: { padding: spacing.xl, paddingBottom: 120, gap: 0, maxWidth: 1040 },
  profile: { width: '100%', gap: spacing.md },
  profileDesktop: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.xl },
  portrait: { position: 'relative', overflow: 'hidden', backgroundColor: colors.elevated, borderWidth: 1, borderColor: colors.borderBright, borderRadius: radius.xl },
  portraitMobile: { width: '100%', height: 310 },
  portraitCompact: { height: 292 },
  portraitDesktop: { width: 330, height: 430, flexShrink: 0 },
  portraitFallback: { ...StyleSheet.absoluteFill, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.plum },
  portraitFallbackInitial: { color: 'rgba(255,255,255,.18)', fontFamily: typography.display, fontSize: 112, fontWeight: '600' },
  photoPreload: { position: 'absolute', top: 0, left: 0, width: 1, height: 1, opacity: 0 },
  portraitImageButton: { ...StyleSheet.absoluteFill },
  portraitFrameMobile: { top: 4, right: 4, bottom: 4, left: 4 },
  portraitFrameDesktop: { top: 5, right: 5, bottom: 5, left: 5 },
  portraitShade: { position: 'absolute', right: 0, bottom: 0, left: 0, height: 118, backgroundColor: 'rgba(6,4,9,.72)' },
  back: { position: 'absolute', top: 12, left: 12, zIndex: 5, width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  photoButton: { position: 'absolute', top: '43%', zIndex: 4, width: 44, height: 48, borderRadius: 22, backgroundColor: 'rgba(8,11,19,.68)', borderWidth: 1, borderColor: 'rgba(255,255,255,.22)', alignItems: 'center', justifyContent: 'center' },
  previousPhoto: { left: 12 },
  nextPhoto: { right: 12 },
  photoCounter: { position: 'absolute', top: 14, right: 14, zIndex: 3, minWidth: 50, paddingHorizontal: 10, paddingVertical: 7, borderRadius: radius.pill, backgroundColor: 'rgba(8,11,19,.72)', borderWidth: 1, borderColor: 'rgba(255,255,255,.18)', alignItems: 'center' },
  photoCounterText: { color: '#fff', fontSize: 10, lineHeight: 12, fontWeight: '900', letterSpacing: .6 },
  profileSpiceWithCounter: { top: 58 },
  photoDots: { position: 'absolute', right: 20, bottom: 105, left: 20, zIndex: 3, flexDirection: 'row', justifyContent: 'center', gap: 6 },
  photoDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: 'rgba(255,255,255,.42)' },
  photoDotActive: { width: 18, backgroundColor: '#fff' },
  photoError: { position: 'absolute', zIndex: 3, top: '32%', right: 54, left: 54, alignItems: 'center', gap: 8, padding: 12, borderRadius: radius.md, backgroundColor: 'rgba(8,7,12,.84)' },
  photoErrorText: { color: '#fff', fontSize: 11, textAlign: 'center' },
  photoErrorAction: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 },
  photoErrorActionText: { color: colors.rose, fontSize: 11, fontWeight: '900' },
  portraitTitle: { position: 'absolute', right: 20, bottom: 18, left: 20 },
  name: { flex: 1, minWidth: 0, fontFamily: typography.display, fontSize: 34, lineHeight: 37, color: '#fff', fontWeight: '600', textShadowColor: '#000', textShadowRadius: 14 },
  nameCompact: { fontSize: 29, lineHeight: 32 },
  job: { color: 'rgba(255,255,255,.90)', fontSize: 13, lineHeight: 17, marginTop: 5, fontWeight: '700', textShadowColor: '#000', textShadowRadius: 8 },
  details: { width: '100%', gap: spacing.md, padding: spacing.lg, borderRadius: radius.xl, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border },
  detailsDesktop: { flex: 1, width: 'auto', minHeight: 430, backgroundColor: colors.glass },
  flex: { flex: 1 },
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  relationshipHeading: { gap: 7 },
  relationshipHeadingText: { flex: 1 },
  relationshipSupporting: { maxWidth: 600, color: colors.muted, fontSize: 12, lineHeight: 18 },
  heading: { fontFamily: typography.display, fontSize: 26, lineHeight: 31, color: colors.text, fontWeight: '600' },
  about: { gap: 6 },
  aboutLabel: { color: colors.dimmed, fontSize: 9, fontWeight: '900', letterSpacing: 1.05 },
  history: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  stat: { flexGrow: 1, flexBasis: 92, minWidth: 0, paddingHorizontal: 8, paddingVertical: 12, borderRadius: radius.md, backgroundColor: colors.surface, alignItems: 'center', borderWidth: 1, borderColor: colors.border },
  statValue: { fontFamily: typography.display, fontSize: 23, color: colors.text },
  statLabel: { fontSize: 9, color: colors.muted, fontWeight: '800', marginTop: 2, textAlign: 'center' },
  upcomingStat: { flexBasis: 190, alignItems: 'stretch', paddingHorizontal: 12, paddingVertical: 10 },
  upcomingStatTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
  upcomingStatKicker: { color: colors.rose, fontSize: 8, lineHeight: 11, fontWeight: '900', letterSpacing: .8 },
  upcomingStatDate: { color: colors.text, fontFamily: typography.display, fontSize: 19, lineHeight: 23, marginTop: 4 },
  upcomingStatTitle: { color: colors.textSecondary, fontSize: 10, lineHeight: 14, fontWeight: '900', marginTop: 1 },
  upcomingStatMeta: { color: colors.muted, fontSize: 8.5, lineHeight: 12, marginTop: 2 },
  upcomingModalRoot: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20, backgroundColor: 'rgba(3,2,7,.72)' },
  upcomingModal: { width: '100%', maxWidth: 440, padding: 18, borderRadius: radius.xl, backgroundColor: 'rgba(24,17,34,.99)', borderWidth: 1, borderColor: 'rgba(216,62,234,.34)', gap: 14 },
  upcomingModalHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  upcomingModalIcon: { width: 38, height: 38, flexShrink: 0, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(216,62,234,.12)' },
  upcomingModalKicker: { color: colors.rose, fontSize: 8, lineHeight: 11, fontWeight: '900', letterSpacing: .9 },
  upcomingModalTitle: { color: colors.text, fontFamily: typography.display, fontSize: 22, lineHeight: 26, fontWeight: '700', marginTop: 2 },
  upcomingModalClose: { width: 40, height: 40, flexShrink: 0, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.05)' },
  upcomingModalDescription: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  upcomingModalDetails: { overflow: 'hidden', borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  commitmentDetail: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 12, paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  commitmentDetailIcon: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(154,104,255,.10)' },
  commitmentDetailLabel: { color: colors.dimmed, fontSize: 8, lineHeight: 11, fontWeight: '900', letterSpacing: .7 },
  commitmentDetailValue: { color: colors.text, fontSize: 12, lineHeight: 17, fontWeight: '800', marginTop: 1 },
  upcomingModalCount: { color: colors.muted, fontSize: 10, lineHeight: 15, textAlign: 'center' },
  upcomingModalActions: { gap: 8 },
  upcomingModalPrimary: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 16, borderRadius: radius.md, backgroundColor: colors.rose },
  upcomingModalPrimaryText: { color: '#fff', fontSize: 12, fontWeight: '900' },
  upcomingModalSecondary: { minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border },
  upcomingModalSecondaryText: { color: colors.textSecondary, fontSize: 11, fontWeight: '900' },
  trustSection: { gap: 8, paddingVertical: 2 },
  trustHeader: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, borderRadius: radius.sm },
  trustIdentity: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 9 },
  trustIcon: { width: 24, height: 34, flexShrink: 0, alignItems: 'flex-start', justifyContent: 'center' },
  trustKicker: { color: colors.dimmed, fontSize: 8, fontWeight: '900', letterSpacing: .9 },
  trustLabel: { color: colors.text, fontSize: 14, lineHeight: 18, fontWeight: '900', marginTop: 1 },
  trustTrend: { marginTop: 2, fontSize: 9, lineHeight: 12, fontWeight: '800' },
  trustTrendStrained: { color: colors.danger },
  trustTrendRepairing: { color: colors.success },
  trustValueRow: { flexShrink: 0, flexDirection: 'row', alignItems: 'center', gap: 7 },
  trustValue: { flexShrink: 0, color: colors.text, fontFamily: typography.display, fontSize: 20 },
  trustTotal: { color: colors.muted, fontFamily: typography.interface, fontSize: 9, fontWeight: '800' },
  trustTrack: { height: 6, overflow: 'hidden', borderRadius: 3, backgroundColor: 'rgba(255,255,255,.08)' },
  trustFill: { height: '100%', minWidth: 2, borderRadius: 3, backgroundColor: colors.violet },
  trustTooltipRoot: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20, backgroundColor: 'rgba(3,2,7,.66)' },
  trustTooltip: { width: '100%', maxWidth: 380, padding: 17, borderRadius: radius.lg, backgroundColor: 'rgba(29,21,40,.99)', borderWidth: 1, borderColor: 'rgba(199,120,255,.42)' },
  trustTooltipHeader: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  trustTooltipMark: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(168,69,242,.13)' },
  trustTooltipTitle: { flex: 1, color: colors.text, fontFamily: typography.display, fontSize: 20, fontWeight: '800' },
  trustTooltipClose: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.05)' },
  trustTooltipBody: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 12 },
  detailsLabel: { color: colors.dimmed, fontSize: 9, fontWeight: '900', letterSpacing: 1.05 },
  facts: { borderTopWidth: 1, borderTopColor: colors.border },
  info: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.border },
  infoInteractive: { paddingHorizontal: 4, marginHorizontal: -4, borderRadius: radius.sm },
  infoValue: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 5 },
  label: { color: colors.muted, flexShrink: 0 },
  value: { flexShrink: 1, color: colors.text, textAlign: 'right' },
  connectionsSection: { gap: 10, paddingTop: 2 },
  connectionsHeader: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 10 },
  connectionsIcon: { width: 34, height: 34, flexShrink: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: 'rgba(154,104,255,.12)' },
  connectionsTitle: { color: colors.text, fontFamily: typography.display, fontSize: 20, lineHeight: 24, fontWeight: '700' },
  connectionsCount: { color: colors.muted, fontSize: 9.5, lineHeight: 13, marginTop: 1 },
  connectionsAll: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 2, paddingLeft: 10 },
  connectionsAllText: { color: colors.rose, fontSize: 10, fontWeight: '900' },
  connectionsError: { color: colors.muted, fontSize: 10, lineHeight: 14, marginTop: 2 },
  connectionsRetry: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 8 },
  connectionsRetryText: { color: colors.rose, fontSize: 10, fontWeight: '900' },
  connectionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  connectionCard: { flexGrow: 1, flexBasis: 245, minWidth: 0, minHeight: 88, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 10, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  connectionCardExpanded: { flexBasis: 'auto', width: '100%', minHeight: 96 },
  connectionPortrait: { width: 58, height: 68, flexShrink: 0, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.elevated },
  connectionInitial: { color: colors.textSecondary, fontFamily: typography.display, fontSize: 24, fontWeight: '700' },
  connectionCopy: { flex: 1, minWidth: 0 },
  connectionName: { color: colors.text, fontSize: 12, lineHeight: 16, fontWeight: '900' },
  connectionRelationship: { color: colors.violet, fontSize: 9, lineHeight: 13, fontWeight: '900', marginTop: 1, textTransform: 'capitalize' },
  connectionHistory: { color: colors.muted, fontSize: 9.5, lineHeight: 14, marginTop: 4 },
  connectionDirection: { color: colors.dimmed, fontSize: 8, lineHeight: 11, marginTop: 4 },
  connectionSkeleton: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 10, borderRadius: radius.lg, backgroundColor: colors.surface },
  connectionSkeletonPortrait: { width: 52, height: 62, borderRadius: radius.md, backgroundColor: 'rgba(255,255,255,.07)' },
  connectionSkeletonCopy: { flex: 1, gap: 8 },
  connectionSkeletonName: { width: '42%', height: 10, borderRadius: 5, backgroundColor: 'rgba(255,255,255,.09)' },
  connectionSkeletonLine: { width: '82%', height: 8, borderRadius: 4, backgroundColor: 'rgba(255,255,255,.055)' },
  connectionsModalRoot: { flex: 1, padding: 12, backgroundColor: 'rgba(3,2,7,.72)' },
  connectionsModalCentered: { alignItems: 'center', justifyContent: 'center' },
  connectionsModalBottom: { justifyContent: 'flex-end' },
  connectionsModal: { width: '100%', maxHeight: '88%', overflow: 'hidden', padding: 16, paddingBottom: 24, borderRadius: radius.xl, borderWidth: 1, borderColor: 'rgba(199,120,255,.34)', backgroundColor: 'rgba(24,17,34,.99)' },
  connectionsModalDesktop: { maxWidth: 570, maxHeight: '78%' },
  connectionsModalHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  connectionsModalTitle: { color: colors.text, fontFamily: typography.display, fontSize: 22, lineHeight: 27, fontWeight: '700' },
  connectionsModalClose: { width: 42, height: 42, flexShrink: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 21, backgroundColor: 'rgba(255,255,255,.05)' },
  connectionsModalList: { gap: 8, paddingBottom: 4 },
  interests: { gap: 8 },
  interestChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  interestChip: { minHeight: 32, justifyContent: 'center', paddingHorizontal: 10, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  interestChipText: { color: colors.textSecondary, fontSize: 10, fontWeight: '800' },
  schedule: { gap: 10, padding: 14, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  scheduleHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  scheduleIcon: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(216,62,234,.10)' },
  scheduleTitle: { color: colors.text, fontFamily: typography.display, fontSize: 19, fontWeight: '600' },
  scheduleDate: { color: colors.muted, fontSize: 10, marginTop: 1 },
  scheduleToggle: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 3, paddingLeft: 8 },
  scheduleToggleText: { color: colors.rose, fontSize: 9, fontWeight: '900' },
  scheduleList: { borderTopWidth: 1, borderTopColor: colors.border },
  scheduleRow: { position: 'relative', minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, paddingLeft: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
  scheduleRowCurrent: { backgroundColor: 'rgba(216,62,234,.07)' },
  scheduleRowPast: { opacity: .5 },
  scheduleRail: { position: 'absolute', left: 0, top: 12, bottom: 12, width: 2, borderRadius: 2, backgroundColor: colors.borderBright },
  scheduleRailCurrent: { width: 3, backgroundColor: colors.rose },
  scheduleTimeWrap: { width: 86 },
  scheduleTime: { color: colors.muted, fontSize: 9, lineHeight: 13, fontWeight: '800' },
  scheduleTimeCurrent: { color: colors.rose, letterSpacing: .7 },
  scheduleCurrentRange: { color: colors.muted, fontSize: 8, marginTop: 2 },
  scheduleCopy: { flex: 1, gap: 4 },
  scheduleActivity: { color: colors.text, fontSize: 12, fontWeight: '800' },
  schedulePlace: { minHeight: 24, flexDirection: 'row', alignItems: 'center', gap: 4 },
  scheduleLocation: { color: colors.muted, fontSize: 9 },
  scheduleLocationInteractive: { color: colors.textSecondary, fontWeight: '800' },
  scheduleEmpty: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderTopWidth: 1, borderTopColor: colors.border },
  scheduleEmptyText: { color: colors.muted, fontSize: 11 },
  scheduleLoadingText: { color: colors.rose, fontSize: 11, fontWeight: '800' },
  scheduleRetry: { minHeight: 34, justifyContent: 'center', paddingHorizontal: 9 }, scheduleRetryText: { color: colors.rose, fontSize: 10, fontWeight: '900', textDecorationLine: 'underline' },
  welcome: { flexDirection: 'row', gap: 10, padding: 13, borderRadius: radius.md, backgroundColor: 'rgba(216,62,234,.10)', borderWidth: 1, borderColor: 'rgba(216,62,234,.22)' },
  welcomeTitle: { color: colors.text, fontWeight: '900' },
  welcomeCopy: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 3 },
  notMet: { flexDirection: 'row', gap: 10, padding: 14, borderRadius: radius.md, backgroundColor: colors.surface },
  notMetText: { flex: 1, color: colors.muted, fontSize: 12, lineHeight: 18 },
  sharedHistory: { gap: 10, paddingTop: 3 },
  sharedHistoryTitle: { color: colors.text, fontFamily: typography.display, fontSize: 21, fontWeight: '600' },
  previewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  previewCard: { flexGrow: 1, flexBasis: 245, minWidth: 0, minHeight: 124, flexDirection: 'row', alignItems: 'flex-start', gap: 10, padding: 13, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  previewCardPressed: { opacity: .86, transform: [{ scale: .99 }], borderColor: colors.borderBright },
  previewIcon: { width: 36, height: 36, flexShrink: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 18, backgroundColor: 'rgba(154,104,255,.11)' },
  previewCopy: { flex: 1, minWidth: 0, gap: 3 },
  previewKicker: { color: colors.dimmed, fontSize: 8, fontWeight: '900', letterSpacing: .8 },
  previewTitle: { color: colors.text, fontSize: 13, lineHeight: 17, fontWeight: '900' },
  previewBody: { color: colors.muted, fontSize: 10, lineHeight: 15 },
  previewMeta: { color: colors.rose, fontSize: 9, fontWeight: '800', marginTop: 2 },
  pressed: { opacity: .78 },
  error: { color: colors.danger, fontSize: 12, fontWeight: '700', textAlign: 'center' },
  openingStatus: { color: colors.muted, fontSize: 11, fontWeight: '700', textAlign: 'center', marginBottom: -8 },
});
