import { Platform, StyleSheet } from 'react-native';
import { DESKTOP_CHAT_SHELL_MAX_WIDTH } from '../lib/chatLayout';
import { colors, radius, typography } from '../theme';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  shell: {
    flex: 1,
    width: "100%",
    maxWidth: DESKTOP_CHAT_SHELL_MAX_WIDTH,
    alignSelf: "center",
    flexDirection: "row",
    backgroundColor: colors.background,
  },
  conversation: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: colors.border,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  loadingScreen:{flex:1,backgroundColor:colors.background},
  loadingHeader:{minHeight:82,paddingTop:18,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:colors.border},
  loadingCircle:{width:48,height:48,borderRadius:24,backgroundColor:"rgba(181,111,223,.14)"},
  loadingHeaderCopy:{gap:8},
  loadingLine:{height:12,borderRadius:6,backgroundColor:"rgba(255,255,255,.09)"},
  loadingLineSmall:{height:8,borderRadius:4,backgroundColor:"rgba(255,255,255,.055)"},
  loadingTimeline:{flex:1,paddingHorizontal:18,paddingTop:36,gap:18},
  loadingBubble:{height:58,borderRadius:18,backgroundColor:"rgba(255,255,255,.055)"},
  loadingBubbleUser:{alignSelf:"flex-end",backgroundColor:"rgba(216,62,234,.09)"},
  loadingComposer:{height:58,marginHorizontal:12,marginBottom:14,borderRadius:29,backgroundColor:"rgba(255,255,255,.06)",borderWidth:1,borderColor:colors.border},
  glowLayer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    overflow: "hidden",
  },
  glowOrb: {
    position: "absolute",
    borderRadius: 999,
    backgroundColor: "rgba(156,68,196,.035)",
    ...(Platform.OS === "web" ? ({ filter: "blur(62px)" } as never) : {}),
  },
  glowRose: {
    width: 620,
    height: 620,
    top: "14%",
    right: -250,
    backgroundColor: "rgba(216,62,234,.055)",
    ...(Platform.OS === "web"
      ? ({
        backgroundImage:
          "radial-gradient(circle, rgba(216,62,234,.15) 0%, rgba(164,46,182,.055) 44%, transparent 73%)",
      } as never)
      : {}),
  },
  glowViolet: {
    width: 540,
    height: 540,
    bottom: "5%",
    left: -250,
    backgroundColor: "rgba(120,72,210,.045)",
    ...(Platform.OS === "web"
      ? ({
        backgroundImage:
          "radial-gradient(circle, rgba(130,83,220,.13) 0%, rgba(93,56,166,.045) 48%, transparent 74%)",
      } as never)
      : {}),
  },
  glowCenter: {
    width: 430,
    height: 430,
    top: "44%",
    left: "30%",
    backgroundColor: "rgba(115,42,133,.025)",
    ...(Platform.OS === "web"
      ? ({
        backgroundImage:
          "radial-gradient(circle, rgba(172,65,178,.075) 0%, transparent 70%)",
      } as never)
      : {}),
  },
  glowRoseCompact: {
    width: 420,
    height: 420,
    right: -210,
    top: "18%",
    opacity: .72,
  },
  glowVioletCompact: {
    width: 380,
    height: 380,
    left: -210,
    bottom: "8%",
    opacity: .66,
  },
  glowCenterCompact: {
    width: 300,
    height: 300,
    left: "22%",
    opacity: .55,
  },
  header: {
    paddingTop: Platform.OS === "web" ? 14 : 50,
    paddingHorizontal: 14,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: "rgba(8,11,19,.98)",
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
  },
  headerMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerCopy: { minWidth: 0, flex: 1 },
  headerTitle: { color: colors.text, fontSize: 18, fontWeight: "900" },
  headerSub: { color: colors.muted, fontSize: 12, marginTop: 3 },
  avatarStack: { width: 64, height: 38, position: "relative" },
  avatarStackItem: {
    position: "absolute",
    top: 2,
    borderWidth: 2,
    borderColor: colors.background,
    borderRadius: 20,
  },
  groupMenu:{position:"absolute",zIndex:30,top:Platform.OS==="web"?72:108,right:12,width:270,padding:12,gap:2,borderRadius:radius.lg,backgroundColor:"rgba(24,18,33,.98)",borderWidth:1,borderColor:colors.border,shadowColor:"#000",shadowOpacity:.42,shadowRadius:18,shadowOffset:{width:0,height:10}},
  groupMenuTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8,paddingHorizontal:8,paddingBottom:5},
  groupMenuTitle:{flex:1,color:colors.text,fontFamily:"Georgia",fontSize:19},
  groupMenuClose:{color:colors.muted,fontSize:10,fontWeight:"800"},
  groupMenuSection:{color:colors.dimmed,fontSize:8,fontWeight:"900",letterSpacing:1.2,paddingHorizontal:8,paddingTop:9,paddingBottom:3},
  groupMenuItem:{minHeight:40,justifyContent:"center",paddingHorizontal:9,borderRadius:radius.md},
  groupMenuFavorite:{minHeight:40,paddingHorizontal:9,borderRadius:radius.md,flexDirection:"row",alignItems:"center",gap:8},
  groupMenuItemText:{color:colors.text,fontSize:12,fontWeight:"700"},
  rightRail: {
    width: 310,
    maxWidth: 310,
    flexGrow: 0,
    flexShrink: 0,
    borderRightWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(10,10,17,.78)",
  },
  rightRailContent: { padding: 12, paddingBottom: 26 },
  memberNavigator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  memberCycleButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(255,255,255,.035)",
  },
  memberCounter: {
    color: colors.dimmed,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  memberStrip: {
    flexGrow: 1,
    justifyContent: "center",
    gap: 6,
    paddingVertical: 2,
    marginBottom: 9,
  },
  memberThumb: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "transparent",
  },
  memberThumbActive: { borderColor: colors.violet },
  contextPortrait: {
    width: "100%",
    height: 148,
    borderRadius: radius.lg,
    backgroundColor: colors.elevated,
  },
  contextPortraitFallback: {
    width: "100%",
    height: 148,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.lg,
    backgroundColor: colors.elevated,
  },
  contextName: {
    color: colors.text,
    fontFamily: "Georgia",
    fontSize: 21,
    fontWeight: "800",
    marginTop: 11,
  },
  contextBio: { color: colors.muted, fontSize: 11, lineHeight: 15, marginTop: 3 },
  contextSection: {
    paddingTop: 13,
    marginTop: 13,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 7,
  },
  contextSectionTitle: {
    color: colors.dimmed,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.15,
  },
  contextLine: { flexDirection: "row", alignItems: "flex-start", gap: 7 },
  contextLineIcon: {
    width: 24,
    height: 24,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.04)",
  },
  contextLineTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 3,
  },
  contextCopy: { flex: 1, color: colors.muted, fontSize: 10, lineHeight: 15 },
  contextMuted: { color: colors.dimmed, fontSize: 10, lineHeight: 15 },
  contextMemoryLine: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingVertical: 3,
  },
  contextPlanButton: {
    minHeight: 40,
    marginTop: 15,
    borderRadius: radius.pill,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.rose,
  },
  contextPlanButtonText: { color: "#fff", fontSize: 11, fontWeight: "900" },
  contextSecondaryButton: {
    minHeight: 38,
    marginTop: 7,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  contextSecondaryButtonText: { color: colors.text, fontSize: 11, fontWeight: "800" },
  plannerModalRoot:{flex:1,backgroundColor:"rgba(4,5,10,.76)",paddingTop:Platform.OS==="web"?34:70,paddingHorizontal:Platform.OS==="web"?24:0},
  plannerModalScroll:{width:"100%",maxWidth:860,alignSelf:"center",borderRadius:Platform.OS==="web"?24:0,overflow:"hidden",backgroundColor:colors.background},
  plannerModalContent:{paddingBottom:32},
  timeline: { flex: 1 },
  timelineContent: {
    width: "100%",
    minWidth: 0,
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 24,
    gap: 8,
  },
  timelineLoading: {
    flex: 1,
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  timelineLoadingText: { color: colors.muted, fontSize: 11 },
  timelineFailure:{alignSelf:"center",width:"100%",maxWidth:460,alignItems:"center",gap:9,marginTop:22,paddingHorizontal:22,paddingVertical:24,borderRadius:radius.lg,backgroundColor:"rgba(255,255,255,.035)",borderWidth:1,borderColor:colors.border},
  timelineFailureTitle:{color:colors.text,fontSize:15,fontWeight:"900"},
  timelineFailureBody:{color:colors.muted,fontSize:12,lineHeight:18,textAlign:"center"},
  timelineFailureButton:{minHeight:42,marginTop:4,paddingHorizontal:19,alignItems:"center",justifyContent:"center",borderRadius:radius.pill,backgroundColor:"rgba(216,62,234,.14)",borderWidth:1,borderColor:"rgba(216,62,234,.32)"},
  timelineFailureButtonText:{color:colors.text,fontSize:12,fontWeight:"900"},
  groupWelcome:{alignSelf:"center",width:"100%",maxWidth:520,minHeight:360,alignItems:"center",justifyContent:"center",paddingHorizontal:18,paddingVertical:34},
  groupWelcomeTitle:{color:colors.text,fontFamily:"Georgia",fontSize:25,fontWeight:"800",marginTop:13},
  groupWelcomeBody:{maxWidth:390,color:colors.muted,fontSize:12,lineHeight:18,textAlign:"center",marginTop:7},
  groupWelcomePrompts:{width:"100%",gap:8,marginTop:21},
  groupWelcomePrompt:{minHeight:48,paddingHorizontal:14,borderRadius:radius.md,flexDirection:"row",alignItems:"center",gap:10,backgroundColor:"rgba(255,255,255,.035)",borderWidth:1,borderColor:colors.border},
  groupWelcomePromptText:{flex:1,color:colors.textSecondary,fontSize:11,fontWeight:"700"},
  earlierButton: {
    alignSelf: "center",
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: 16,
    marginBottom: 8,
    borderRadius: radius.pill,
    backgroundColor: "rgba(112,69,145,.16)",
    borderWidth: 1,
    borderColor: "rgba(203,168,255,.18)",
  },
  earlierText: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  pressed: { opacity: .72 },
  day: {
    alignSelf: "center",
    color: colors.dimmed,
    fontSize: 10,
    letterSpacing: 1.1,
    fontWeight: "800",
    marginVertical: 8,
  },
  planLifecycleDivider:{width:"100%",flexDirection:"row",alignItems:"center",gap:10,marginVertical:10},
  planLifecycleLine:{height:1,flex:1,backgroundColor:"rgba(255,255,255,.10)"},
  planLifecycleText:{color:colors.dimmed,fontSize:9,fontWeight:"900",letterSpacing:.8,textTransform:"uppercase"},
  groupPlanEvent:{alignSelf:"center",width:"100%",maxWidth:580,borderRadius:radius.lg,backgroundColor:"rgba(30,22,40,.96)",borderWidth:1,borderColor:"rgba(216,62,234,.24)",overflow:"hidden",marginVertical:4},
  groupPlanSuggestion:{alignSelf:"center",width:"100%",maxWidth:580,borderRadius:radius.lg,backgroundColor:"rgba(22,17,31,.98)",borderWidth:1,borderColor:"rgba(216,62,234,.24)",overflow:"hidden",marginVertical:6},
  groupPlanSuggestionHero:{height:176,overflow:"hidden"},
  groupPlanSuggestionShade:{position:"absolute",top:0,right:0,bottom:0,left:0,backgroundColor:"rgba(8,6,14,.48)"},
  groupPlanSuggestionCopy:{flex:1,justifyContent:"flex-end",padding:16},
  groupPlanSuggestionTop:{position:"absolute",top:12,left:14,right:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},
  groupPlanSuggestionClose:{width:32,height:32,borderRadius:16,backgroundColor:"rgba(5,5,10,.52)",alignItems:"center",justifyContent:"center"},
  groupPlanSuggestionTitle:{color:"#fff",fontFamily:"Georgia",fontSize:22,fontWeight:"800"},
  groupPlanSuggestionBody:{color:"rgba(255,255,255,.78)",fontSize:11,marginTop:5},
  groupPlanInvitationPeople:{minHeight:34,flexDirection:"row",alignItems:"center",gap:8,marginTop:7},
  groupPlanHoursOpen:{color:"#84E6B7"},
  groupPlanHoursClosed:{color:"#F5A0AE"},
  groupPlanSuggestionActions:{padding:12,flexDirection:"row",alignItems:"center",gap:8,flexWrap:"wrap"},
  groupPlanSuggestionSecondaryText:{color:colors.text,fontSize:10,fontWeight:"900"},
  groupPlanSuggestionChange:{minHeight:36,flexDirection:"row",alignItems:"center",gap:6,paddingHorizontal:9},
  groupPlanSuggestionChangeText:{color:colors.rose,fontSize:9,fontWeight:"900"},
  groupPlanEventMain:{flexDirection:"row",alignItems:"center",gap:11,padding:13},
  groupPlanEventKicker:{color:colors.rose,fontSize:9,fontWeight:"900",letterSpacing:1.1},
  groupPlanEventTitle:{color:colors.text,fontSize:14,fontWeight:"900",marginTop:3},
  groupPlanEventMeta:{color:colors.muted,fontSize:10,marginTop:4},
  groupPlanEventActions:{flexDirection:"row",alignItems:"center",gap:8,paddingHorizontal:13,paddingBottom:12},
  groupPlanPrimary:{minHeight:36,paddingHorizontal:13,borderRadius:18,backgroundColor:colors.rose,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},
  groupPlanPrimaryText:{color:"#fff",fontSize:10,fontWeight:"900"},
  groupPlanSecondary:{minHeight:36,paddingHorizontal:12,borderRadius:18,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center"},
  groupPlanDangerText:{color:colors.danger,fontSize:10,fontWeight:"900"},
  groupPlanDisabled:{opacity:.42},
  groupPlanResponses:{alignSelf:"center",width:"100%",maxWidth:580,flexDirection:"row",alignItems:"center",justifyContent:"center",flexWrap:"wrap",gap:10,marginTop:-2,marginBottom:8},
  groupPlanResponse:{minHeight:29,flexDirection:"row",alignItems:"center",gap:5},
  groupPlanResponseDot:{width:7,height:7,borderRadius:4,marginLeft:-10,marginTop:17,borderWidth:1,borderColor:"#17111F"},
  groupPlanResponseReady:{backgroundColor:colors.success},
  groupPlanResponseLate:{backgroundColor:colors.warm},
  groupPlanResponseUnavailable:{backgroundColor:colors.danger},
  groupPlanResponseText:{color:colors.muted,fontSize:9,fontWeight:"800",maxWidth:105},
  messageRow: {
    width: "86%",
    maxWidth: 680,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 7,
  },
  assistantRow: { alignSelf: "flex-start" },
  userRow: { alignSelf: "flex-end", justifyContent: "flex-end" },
  groupedRow: { marginTop: -4 },
  portraitSlot: { width: 28 },
  bubbleWrap: { minWidth: 0, maxWidth: "100%", flexShrink: 1 },
  mediaBubbleWrap: { width: "100%", maxWidth: 430 },
  speakerName: {
    color: colors.rose,
    fontSize: 11,
    fontWeight: "900",
    marginLeft: 10,
    marginBottom: 5,
  },
  handoffLabel:{color:colors.dimmed,fontSize:9,fontWeight:"700",marginLeft:10,marginTop:-3,marginBottom:5},
  quotedReply:{maxWidth:"100%",marginBottom:8,paddingLeft:9,paddingVertical:3,borderLeftWidth:2,borderLeftColor:colors.violet},
  quotedReplyLabel:{color:colors.violet,fontSize:9,fontWeight:"900",marginBottom:2},
  quotedReplyText:{color:colors.muted,fontSize:10,lineHeight:14},
  bubble: {
    minWidth: 0,
    maxWidth: "100%",
    flexShrink: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.md,
  },
  assistantBubble: {
    backgroundColor: colors.surface,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,.06)",
  },
  userBubble: {
    backgroundColor: colors.roseSoft,
    borderBottomRightRadius: 4,
    shadowColor: colors.rose,
    shadowOpacity: .18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  bubbleText: {
    minWidth: 0,
    maxWidth: "100%",
    flexShrink: 1,
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
    ...(Platform.OS === "web"
      ? ({ overflowWrap: "anywhere", wordBreak: "break-word" } as never)
      : {}),
  },
  messageTimeRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 6,
    marginTop: 5,
  },
  timestamp: { color: "rgba(255,255,255,.48)", fontSize: 9 },
  sharedImage: {
    width: "100%",
    height: 390,
    maxWidth: "100%",
    marginTop: 6,
    borderRadius: 14,
    backgroundColor: colors.elevated,
  },
  bubbleMeta: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 4,
  },
  reaction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 7,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,.06)",
    borderWidth: 1,
    borderColor: colors.border,
  },
  reactor: { color: colors.dimmed, fontSize: 9 },
  replyAction: {
    color: colors.dimmed,
    fontSize: 9,
    fontWeight: "800",
    paddingHorizontal: 5,
  },
  typing: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginLeft: 46,
    marginTop: 14,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.violet,
  },
  typingText: { color: colors.muted, fontSize: 11, marginLeft: 5 },
  errorBanner:{marginHorizontal:12,marginVertical:5,minHeight:44,paddingLeft:12,flexDirection:"row",alignItems:"center",gap:8,borderRadius:radius.md,backgroundColor:"rgba(220,72,100,.10)",borderWidth:1,borderColor:"rgba(220,72,100,.25)"},
  error: {
    flex:1,
    color: colors.danger,
    fontSize: 11,
    lineHeight:16,
  },
  errorDismiss:{width:44,height:44,alignItems:"center",justifyContent:"center"},
  mentions: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 78,
    maxWidth: 700,
    alignSelf: "center",
    padding: 8,
    borderRadius: radius.lg,
    backgroundColor: "rgba(29,23,37,.98)",
  },
  mentionRow: {
    height: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 8,
  },
  mentionName: { color: colors.text, fontWeight: "800" },
  recipientWrap:{borderTopWidth:1,borderTopColor:"rgba(255,255,255,.045)",paddingTop:5},
  recipientLabel:{color:colors.dimmed,fontSize:8,fontWeight:"900",letterSpacing:1.05,paddingHorizontal:14,paddingTop:2},
  speakerPicker: { gap: 7, paddingHorizontal: 14, paddingVertical: 7 },
  speakerChip: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 7,
    paddingRight: 11,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,.04)",
    borderWidth: 1,
    borderColor: colors.border,
  },
  speakerChipActive: {
    borderColor: colors.rose,
    backgroundColor: "rgba(104,42,111,.55)",
  },
  speakerChipText: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  speakerChipTextActive:{color:colors.text},
  replyPreview: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderLeftWidth: 3,
    borderLeftColor: colors.violet,
    backgroundColor: "rgba(255,255,255,.04)",
  },
  replyLabel: { color: colors.violet, fontSize: 10, fontWeight: "900" },
  replyText: { color: colors.muted, fontSize: 11, marginTop: 2 },
  attachmentPreview: {
    marginHorizontal: 12,
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 8,
    borderRadius: 14,
    backgroundColor: "rgba(216,62,234,.08)",
    borderWidth: 1,
    borderColor: "rgba(216,62,234,.22)",
  },
  attachmentPreviewImage: { width: 50, height: 50, borderRadius: 10 },
  attachmentPreviewTitle: {
    color: colors.text,
    fontSize: 11,
    fontWeight: "900",
  },
  attachmentPreviewMeta: { color: colors.muted, fontSize: 9, marginTop: 3 },
  attachmentProgressTrack:{height:3,borderRadius:2,overflow:"hidden",backgroundColor:"rgba(255,255,255,.10)",marginTop:7},
  attachmentProgressFill:{height:3,borderRadius:2,backgroundColor:colors.rose},
  attachmentRetry:{color:colors.danger,fontSize:10,fontWeight:"800",marginBottom:4},
  attachmentReplaceButton:{alignSelf:"flex-start",minHeight:44,justifyContent:"center",marginTop:-4},
  attachmentReplaceText:{color:colors.rose,fontSize:10,fontWeight:"800"},
  attachmentRemoveButton:{width:44,height:44,borderRadius:22,alignItems:"center",justifyContent:"center"},
  groupPlanBar:{minHeight:68,marginHorizontal:10,marginTop:7,padding:10,borderRadius:radius.lg,flexDirection:"row",alignItems:"center",gap:9,backgroundColor:"rgba(30,22,40,.98)",borderWidth:1,borderColor:"rgba(216,62,234,.25)"},
  groupPlanBarIcon:{width:36,height:36,borderRadius:18,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(216,62,234,.10)"},
  groupPlanBarContent:{flex:1,minWidth:0},
  groupPlanBarHeading:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:6},
  groupPlanBarKicker:{color:colors.rose,fontSize:8,fontWeight:"900",letterSpacing:1.1},
  groupPlanBarClock:{color:colors.muted,fontSize:8,fontWeight:"800"},
  groupPlanBarTitle:{color:colors.text,fontSize:12,fontWeight:"900",marginTop:2},
  groupPlanBarMeta:{color:colors.muted,fontSize:9,marginTop:2},
  groupPlanBarButtons:{alignItems:"stretch",justifyContent:"center"},
  groupPlanBarAction:{minHeight:28,paddingHorizontal:8,alignItems:"center",justifyContent:"center"},
  groupPlanBarActionText:{color:colors.text,fontSize:10,fontWeight:"900"},
  groupPlanProgressTrack:{height:2,borderRadius:1,overflow:"hidden",backgroundColor:"rgba(255,255,255,.10)",marginTop:6},
  groupPlanProgressFill:{height:2,borderRadius:1,backgroundColor:colors.rose},
  groupPlanJoin:{minHeight:38,paddingHorizontal:13,borderRadius:19,backgroundColor:colors.rose,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},
  composerWrap: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: "rgba(8,11,19,.99)",
    paddingBottom: Platform.OS === "ios" ? 10 : 2,
  },
  composer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  composerInputShell: {
    flex: 1,
    minWidth: 0,
    minHeight: 54,
    maxHeight: 124,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingLeft: 5,
    paddingRight: 5,
    paddingVertical: 4,
    borderRadius: 27,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  composerInputFocused: {
    backgroundColor: "rgba(43,27,56,.98)",
    borderColor: "rgba(188,142,216,.20)",
  },
  mediaButton: {
    position: "relative",
    width: 42,
    height: 42,
    borderRadius: 21,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(70,42,108,.72)",
    borderWidth: 1,
    borderColor: "rgba(203,168,255,.48)",
    shadowColor: "#8F5BFF",
    shadowOpacity: .4,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 3 },
  },
  mediaButtonPressed: {
    transform: [{ scale: .96 }],
    backgroundColor: "rgba(88,48,137,.94)",
  },
  mediaButtonGlow: {
    position: "absolute",
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(139,80,255,.25)",
    borderWidth: 1,
    borderColor: "rgba(220,196,255,.28)",
  },
  composerInput: {
    minWidth: 0,
    flex: 1,
    maxHeight: 116,
    minHeight: 40,
    paddingLeft: 4,
    paddingRight: 7,
    paddingVertical: 10,
    color: colors.text,
    fontSize: 15,
    backgroundColor: "transparent",
    ...(Platform.OS === "web" ? ({ outlineStyle: "none" } as never) : {}),
  },
  send: {
    width: 50,
    height: 50,
    borderRadius: 25,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.rose,
    shadowColor: colors.rose,
    shadowOpacity: .3,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
  },
  continueButton: {
    backgroundColor: colors.violet,
    shadowColor: colors.violet,
  },
  sendDisabled: { opacity: .4 },
  dictationButton: {
    position: "relative",
    flexShrink: 0,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
    backgroundColor: "rgba(100,61,167,.18)",
    borderWidth: 1,
    borderColor: "rgba(203,168,255,.22)",
  },
  dictationRecording: {
    backgroundColor: "rgba(225,65,99,.84)",
    borderColor: "rgba(255,180,200,.82)",
  },
  dictationPulse: {
    position: "absolute",
    top: 2,
    left: 2,
    right: 2,
    bottom: 2,
    borderRadius: 20,
    backgroundColor: "#FF6F91",
  },
  modalRoot: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backgroundColor: "rgba(4,3,7,.72)",
  },
  photoMenu: {
    width: "100%",
    maxWidth: 470,
    padding: 20,
    borderRadius: radius.xl,
    backgroundColor: "rgba(31,23,42,.97)",
    borderWidth: 1,
    borderColor: "rgba(219,169,238,.28)",
    shadowColor: "#000",
    shadowOpacity: .42,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
  },
  photoMenuHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  photoMenuTitle: {
    color: colors.text,
    fontFamily: typography.display,
    fontSize: 24,
    marginTop: 3,
  },
  photoMenuLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
    marginBottom: 10,
  },
  photoSubjectGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  photoSubject: {
    minWidth: 94,
    flex: 1,
    maxWidth: 140,
    minHeight: 82,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 9,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,.045)",
    borderWidth: 1,
    borderColor: colors.border,
  },
  photoSubjectSelected: {
    backgroundColor: "rgba(128,61,151,.36)",
    borderColor: colors.violet,
  },
  photoSubjectName: { color: colors.muted, fontSize: 12, fontWeight: "800" },
  photoSubjectNameSelected: { color: colors.text },
  photoRequestButton: {
    height: 50,
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 16,
    backgroundColor: colors.wine,
  },
  photoRequestButtonText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  photoMenuDivider: {
    height: 1,
    marginVertical: 17,
    backgroundColor: colors.border,
  },
  photoUploadButton: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  photoUploadTitle: { color: colors.text, fontSize: 14, fontWeight: "900" },
  photoUploadCopy: {
    color: colors.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  details: {
    width: "100%",
    maxWidth: 560,
    maxHeight: "90%",
    padding: 20,
    borderRadius: radius.xl,
    backgroundColor: "rgba(27,21,35,.97)",
    borderColor: "rgba(207,162,231,.24)",
  },
  detailsHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  detailsKicker: {
    color: colors.rose,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.4,
  },
  detailsTitle: {
    color: colors.text,
    fontFamily: typography.display,
    fontSize: 26,
    marginTop: 4,
  },
  close: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.05)",
  },
  detailsLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
    marginTop: 20,
    marginBottom: 9,
  },
  renameRow: { flexDirection: "row", gap: 8 },
  renameInput: {
    flex: 1,
    height: 46,
    borderRadius: 14,
    paddingHorizontal: 13,
    color: colors.text,
    backgroundColor: "rgba(255,255,255,.05)",
    borderWidth: 1,
    borderColor: colors.border,
  },
  saveSmall: {
    width: 68,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.wine,
  },
  saveSmallText: { color: colors.text, fontSize: 12, fontWeight: "900" },
  detailPerson: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  detailPersonName: {
    minWidth: 0,
    flex: 1,
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
  },
  detailPersonStatus:{color:colors.muted,fontSize:10,fontWeight:"700",maxWidth:100,textAlign:"right"},
  detailError:{color:colors.danger,fontSize:12,lineHeight:18,marginTop:12,textAlign:"center"},
  iconButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  addButton: { height: 48, flexDirection: "row", alignItems: "center", gap: 9 },
  addText: { flex: 1, color: colors.rose, fontSize: 13, fontWeight: "900" },
  addList: {
    padding: 6,
    borderRadius: radius.md,
    backgroundColor: "rgba(255,255,255,.025)",
  },
  addEmpty: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 10,
    paddingVertical: 14,
    textAlign: "center",
  },
  segment: {
    flexDirection: "row",
    padding: 4,
    borderRadius: radius.pill,
    backgroundColor: "rgba(10,8,15,.62)",
    borderWidth: 1,
    borderColor: colors.border,
  },
  segmentOption: {
    flex: 1,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.pill,
  },
  segmentActive: { backgroundColor: "rgba(92,47,108,.78)" },
  segmentText: { color: colors.muted, fontSize: 12, fontWeight: "800" },
  segmentTextActive: { color: colors.text },
  archive: {
    height: 52,
    marginTop: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    borderRadius: radius.lg,
    backgroundColor: "rgba(255,113,129,.08)",
    borderWidth: 1,
    borderColor: "rgba(255,113,129,.2)",
  },
  archiveDisabled:{opacity:.45},
  archiveText: { color: colors.danger, fontWeight: "900" },
  busyOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.xl,
    backgroundColor: "rgba(10,8,14,.58)",
  },
});
