import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '../theme';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  glow: {
    position: "absolute",
    top: -120,
    left: "15%",
    width: 420,
    height: 420,
    borderRadius: 210,
    backgroundColor: "rgba(123,58,154,.15)",
  },
  header: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    minHeight: 92,
    paddingHorizontal: spacing.lg,
    paddingTop: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  back: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.05)",
  },
  headerCopy: { flex: 1 },
  kicker: {
    color: colors.rose,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.5,
  },
  heading: {
    color: colors.text,
    fontFamily: typography.display,
    fontSize: 28,
    fontWeight: "700",
    marginTop: 2,
  },
  count: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 11,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,.05)",
  },
  countText: { color: colors.muted, fontSize: 12, fontWeight: "800" },
  content: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    padding: spacing.lg,
    paddingBottom: 60,
  },
  label: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.1,
    marginTop: 12,
  },
  optional: { color: colors.dimmed, fontSize: 9 },
  input: {
    height: 54,
    marginTop: 10,
    paddingHorizontal: 16,
    borderRadius: radius.lg,
    color: colors.text,
    fontSize: 16,
    backgroundColor: "rgba(31,24,39,.8)",
    borderWidth: 1,
    borderColor: colors.borderBright,
  },
  sectionLine: { marginTop: 25, marginBottom: 14 },
  help: { color: colors.muted, fontSize: 12, marginTop: 5 },
  worlds: { gap: 9, paddingRight: 12 },
  world: {
    minWidth: 138,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(20,17,27,.72)",
  },
  worldActive: {
    borderColor: "rgba(216,62,234,.62)",
    backgroundColor: "rgba(88,37,100,.38)",
  },
  worldName: { color: colors.textSecondary, fontSize: 13, fontWeight: "900" },
  worldNameActive: { color: colors.text },
  worldCount: { color: colors.muted, fontSize: 10, marginTop: 4 },
  grid: { gap: 9 },
  person: {
    minHeight: 84,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 10,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(20,17,27,.72)",
  },
  personActive: {
    borderColor: "rgba(216,62,234,.62)",
    backgroundColor: "rgba(88,37,100,.38)",
  },
  personCopy: { minWidth: 0, flex: 1 },
  personName: { color: colors.text, fontSize: 16, fontWeight: "900" },
  personMeta: { color: colors.muted, fontSize: 12, marginTop: 5 },
  check: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.borderBright,
    alignItems: "center",
    justifyContent: "center",
  },
  checkActive: { backgroundColor: colors.rose, borderColor: colors.rose },
  primary: {
    height: 54,
    marginTop: 24,
    borderRadius: radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.rose,
    shadowColor: colors.rose,
    shadowOpacity: .25,
    shadowRadius: 16,
  },
  primaryText: { color: "#fff", fontWeight: "900", fontSize: 15 },
  disabled: { opacity: .38 },
  error: {
    color: colors.danger,
    fontSize: 12,
    marginTop: 14,
    textAlign: "center",
  },
  empty: { color: colors.muted, textAlign: "center", paddingVertical: 40 },
  gate: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  gateCard: {
    width: "100%",
    maxWidth: 480,
    alignItems: "center",
    padding: 28,
    borderRadius: radius.xl,
    backgroundColor: "rgba(30,23,39,.9)",
    borderColor: "rgba(216,62,234,.28)",
  },
  gateIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(216,62,234,.12)",
  },
  gateTitle: {
    color: colors.text,
    fontFamily: typography.display,
    fontSize: 25,
    textAlign: "center",
    marginTop: 18,
  },
  gateCopy: {
    color: colors.muted,
    textAlign: "center",
    lineHeight: 20,
    marginTop: 8,
  },
});
