import { StyleSheet } from 'react-native';
import { colors, radius } from '../theme';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#0B1018", overflow: "hidden" },
  glow: {
    position: "absolute",
    width: 760,
    height: 760,
    borderRadius: 380,
    top: -420,
    right: -250,
    backgroundColor: "rgba(112,54,160,.13)",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,.08)",
  },
  headerCopy: { flex: 1, minWidth: 0 },
  iconButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(18,14,25,.72)",
    borderRadius: radius.md,
  },
  eyebrow: {
    color: colors.violet,
    fontWeight: "600",
    fontSize: 12,
    letterSpacing: 1.4,
  },
  title: {
    color: colors.text,
    fontWeight: "600",
    fontSize: 29,
    marginTop: 3,
  },
  subtitle: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 3 },
  tabShell: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,.07)",
    backgroundColor: "rgba(10,8,15,.82)",
  },
  tabs: { paddingHorizontal: 24, paddingVertical: 10, gap: 6 },
  tab: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: radius.sm },
  tabActive: {
    backgroundColor: "rgba(154,104,255,.16)",
    borderWidth: 1,
    borderColor: "rgba(154,104,255,.36)",
  },
  tabText: { color: colors.muted, fontSize: 12, fontWeight: "600" },
  tabTextActive: { color: colors.text },
  content: {
    width: "100%",
    maxWidth: 1480,
    alignSelf: "center",
    padding: 24,
    gap: 18,
    paddingBottom: 70,
  },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 13,
    borderWidth: 1,
    borderColor: "rgba(255,182,95,.35)",
    backgroundColor: "rgba(255,182,95,.08)",
    borderRadius: radius.md,
  },
  errorText: { color: colors.text, flex: 1, fontSize: 12 },
  dismiss: { color: colors.warm, fontSize: 12, fontWeight: "600" },
  health: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    padding: 17,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: "#111A27",
  },
  healthDot: { width: 12, height: 12, borderRadius: 6 },
  good: { backgroundColor: colors.success },
  attention: { backgroundColor: colors.warm },
  healthTitle: { color: colors.text, fontSize: 18, fontWeight: "600" },
  muted: { color: colors.muted, fontSize: 12 },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  metric: {
    width: "19.2%",
    minWidth: 170,
    minHeight: 105,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: "#111A27",
  },
  metricCompact: { width: "47.8%", minWidth: 140 },
  metricIcon: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  metricValue: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "600",
    marginTop: 7,
  },
  metricLabel: { color: colors.muted, fontSize: 12, marginTop: 4 },
  columns: { flexDirection: "row", alignItems: "flex-start", gap: 14 },
  columnsStack: { flexDirection: "column" },
  panel: {
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: 'auto',
    width: "100%",
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: "#111A27",
    gap: 8,
  },
  panelTitle: { color: colors.text, fontSize: 18, fontWeight: "600" },
  panelHint: { color: '#A7B4C7', fontSize: 12, lineHeight: 18, marginBottom: 7 },
  record: {
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,.07)",
  },
  clickRecord: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,.07)",
  },
  recordTitle: { color: colors.text, fontWeight: "600", fontSize: 14 },
  recordBody: { color: "#BBC7D8", fontSize: 13, lineHeight: 20, marginTop: 4 },
  recordMeta: { color: '#98A7BB', fontSize: 12, lineHeight: 18, marginTop: 5 },
  sectionHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  sectionTitle: {
    fontWeight: "600",
    color: colors.text,
    fontSize: 26,
  },
  queueGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  queueCard: {
    flexGrow: 1,
    flexBasis: 330,
    minWidth: 280,
    padding: 17,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#111A27",
    gap: 13,
  },
  queueAttention: { borderColor: "rgba(255,171,105,.4)" },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  queueNumbers: { flexDirection: "row", gap: 10 },
  statValue: { color: colors.text, fontSize: 18, fontWeight: "600" },
  statLabel: {
    color: colors.dimmed,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: .8,
    marginTop: 3,
  },
  statusRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  statusText: { color: colors.muted, fontSize: 12 },
  providerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,.07)",
  },
  providerMetric: {
    color: colors.muted,
    fontSize: 12,
    minWidth: 58,
    textAlign: "right",
  },
  goodValue: { color: colors.success, fontWeight: "600" },
  badValue: { color: colors.rose, fontWeight: "600" },
  incident: {
    paddingVertical: 9,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,.07)",
    gap: 8,
  },
  incidentLine: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  severity: { width: 4, minHeight: 46, borderRadius: 2 },
  severityCritical: { backgroundColor: colors.rose },
  severityWarning: { backgroundColor: colors.warm },
  severityInfo: { backgroundColor: colors.violet },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 7,
  },
  worldControl: {
    gap: 10,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,.07)",
  },
  worldStatusRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  worldStatusChoice: {
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 13,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(255,255,255,.025)",
  },
  worldStatusChoiceActive: { borderColor: "rgba(154,104,255,.55)", backgroundColor: "rgba(154,104,255,.16)" },
  worldStatusChoiceText: { color: colors.muted, fontSize: 12, fontWeight: "600" },
  worldStatusChoiceTextActive: { color: colors.text },
  worldConfirmation: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 16,
    padding: 17,
    borderWidth: 1,
    borderColor: "rgba(255,171,105,.32)",
    borderRadius: 10,
    backgroundColor: "rgba(255,171,105,.06)",
  },
  smallAction: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: "rgba(154,104,255,.34)",
    backgroundColor: "rgba(154,104,255,.12)",
  },
  smallActionText: { color: colors.text, fontSize: 12, fontWeight: "600" },
  disabled: { opacity: .45 },
  ticketMessage: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
    paddingVertical: 12,
  },
  input: {
    minHeight: 44,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(7,6,12,.8)",
    color: colors.text,
    paddingHorizontal: 13,
    fontSize: 13,
  },
  noteInput: { minHeight: 100, textAlignVertical: "top", paddingTop: 12 },
  link: { color: colors.violet, fontSize: 12, fontWeight: "600" },
  searchRow: { flexDirection: "row", gap: 10 },
  primary: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 16,
    borderRadius: radius.md,
    backgroundColor: colors.violet,
  },
  primaryText: { color: "#fff", fontWeight: "600", fontSize: 12 },
  userHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 17,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: "#111A27",
  },
  statCard: {
    flexGrow: 1,
    flexBasis: 210,
    minWidth: 180,
    minHeight: 100,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: "#111A27",
    justifyContent: "center",
  },
  sensitive: {
    gap: 10,
    padding: 17,
    borderWidth: 1,
    borderColor: "rgba(255,171,105,.32)",
    borderRadius: 10,
    backgroundColor: "rgba(255,171,105,.05)",
  },
  confirm: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 11,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
  },
  confirmActive: { borderColor: colors.success },
  check: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  checkActive: { backgroundColor: colors.success, borderColor: colors.success },
  configRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  alertList: { gap: 10 },
  alertRule: {
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: "#111A27",
    gap: 11,
  },
  ruleInputs: { flexDirection: "row", alignItems: "center", gap: 8 },
  ruleInput: { width: 105 },
  channel: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  channelActive: {
    borderColor: colors.violet,
    backgroundColor: "rgba(154,104,255,.14)",
  },
  channelText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  pill: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: radius.sm,
    backgroundColor: "rgba(154,104,255,.12)",
    borderWidth: 1,
    borderColor: "rgba(154,104,255,.27)",
  },
  pillText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: .5,
  },
  note: { color: colors.dimmed, fontSize: 12, lineHeight: 18 },
  loading: {
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    padding: 30,
  },
});
