import { catalogArtwork } from '../catalogArtwork';
import type { ImageSource } from 'expo-image';

export const gildedCoastCharacterAssets: Record<string, ImageSource> = {
  'elara-voss': catalogArtwork('characters/gilded-coast/elara-voss.jpg'),
  'tomas-renn': catalogArtwork('characters/gilded-coast/tomas-renn.jpg'),
  'anika-saye': catalogArtwork('characters/gilded-coast/anika-saye.jpg'),
  'rafiq-nadir': catalogArtwork('characters/gilded-coast/rafiq-nadir.jpg'),
  'mira-cael': catalogArtwork('characters/gilded-coast/mira-cael.jpg'),
  'nico-solari': catalogArtwork('characters/gilded-coast/nico-solari.jpg'),
  'seraphine-vale': catalogArtwork('characters/gilded-coast/seraphine-vale.jpg'),
  'julian-mercer': catalogArtwork('characters/gilded-coast/julian-mercer.jpg'),
  'sabine-quill': catalogArtwork('characters/gilded-coast/sabine-quill.jpg'),
  'lucien-damar': catalogArtwork('characters/gilded-coast/lucien-damar.jpg'),
  'iria-montrose': catalogArtwork('characters/gilded-coast/iria-montrose.jpg'),
  'hugo-fen': catalogArtwork('characters/gilded-coast/hugo-fen.jpg'),
  'bruna-kest': catalogArtwork('characters/gilded-coast/bruna-kest.jpg'),
  'mateo-salt': catalogArtwork('characters/gilded-coast/mateo-salt.jpg'),
  'yara-nouri': catalogArtwork('characters/gilded-coast/yara-nouri.jpg'),
  'dorian-pike': catalogArtwork('characters/gilded-coast/dorian-pike.jpg'),
  'levi-ash': catalogArtwork('characters/gilded-coast/levi-ash.jpg'),
  'celia-mar': catalogArtwork('characters/gilded-coast/celia-mar.jpg'),
  'inez-sol': catalogArtwork('characters/gilded-coast/inez-sol.jpg'),
  'cassia-bloom': catalogArtwork('characters/gilded-coast/cassia-bloom.jpg'),
  'luca-vane': catalogArtwork('characters/gilded-coast/luca-vane.jpg'),
  'fen-moreno': catalogArtwork('characters/gilded-coast/fen-moreno.jpg'),
  'javier-ro': catalogArtwork('characters/gilded-coast/javier-ro.jpg'),
  'maia-bel': catalogArtwork('characters/gilded-coast/maia-bel.jpg'),
  'amara-kade': catalogArtwork('characters/gilded-coast/amara-kade.jpg'),
  'bastien-crow': catalogArtwork('characters/gilded-coast/bastien-crow.jpg'),
  'talia-wren': catalogArtwork('characters/gilded-coast/talia-wren.jpg'),
  'oren-gale': catalogArtwork('characters/gilded-coast/oren-gale.jpg'),
  'nera-tide': catalogArtwork('characters/gilded-coast/nera-tide.jpg'),
  'sami-haddad': catalogArtwork('characters/gilded-coast/sami-haddad.jpg'),
  'mara-blackfin': catalogArtwork('characters/gilded-coast/mara-blackfin.jpg'),
  'idris-vale': catalogArtwork('characters/gilded-coast/idris-vale.jpg'),
  'sora-bay': catalogArtwork('characters/gilded-coast/sora-bay.jpg'),
  'keon-flint': catalogArtwork('characters/gilded-coast/keon-flint.jpg'),
  'nadia-storm': catalogArtwork('characters/gilded-coast/nadia-storm.jpg'),
  'elias-reed': catalogArtwork('characters/gilded-coast/elias-reed.jpg'),
  // New Gilded Coast residents: each has a dedicated canonical portrait.
  'calista-fen': catalogArtwork('characters/gilded-coast/calista-fen.jpg'),
  'cormac-bray': catalogArtwork('characters/gilded-coast/cormac-bray.jpg'),
  'dax-marin': catalogArtwork('characters/gilded-coast/dax-marin.jpg'),
  'gideon-holt': catalogArtwork('characters/gilded-coast/gideon-holt.jpg'),
  'harlan-vex': catalogArtwork('characters/gilded-coast/harlan-vex.jpg'),
  'helene-dusk': catalogArtwork('characters/gilded-coast/helene-dusk.jpg'),
  'isolde-wren': catalogArtwork('characters/gilded-coast/isolde-wren.jpg'),
  'liora-quell': catalogArtwork('characters/gilded-coast/liora-quell.jpg'),
  'maren-hooke': catalogArtwork('characters/gilded-coast/maren-hooke.jpg'),
  'nyxa-marin': catalogArtwork('characters/gilded-coast/nyxa-marin.jpg'),
  'odile-vane': catalogArtwork('characters/gilded-coast/odile-vane.jpg'),
  'osric-kane': catalogArtwork('characters/gilded-coast/osric-kane.jpg'),
  'petra-cinder': catalogArtwork('characters/gilded-coast/petra-cinder.jpg'),
  'quinnie-salt': catalogArtwork('characters/gilded-coast/quinnie-salt.jpg'),
  'roxana-brine': catalogArtwork('characters/gilded-coast/roxana-brine.jpg'),
  'rune-calder': catalogArtwork('characters/gilded-coast/rune-calder.jpg'),
  'sable-rourke': catalogArtwork('characters/gilded-coast/sable-rourke.jpg'),
  'stellan-rook': catalogArtwork('characters/gilded-coast/stellan-rook.jpg'),
  'tessera-pike': catalogArtwork('characters/gilded-coast/tessera-pike.jpg'),
  'vesperine-crowe': catalogArtwork('characters/gilded-coast/vesperine-crowe.jpg'),
};
