import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

test('companion preferences preserve scope; delivery enforces paid access, quiet hours, scenarios and pacing',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table together_notification_preferences(user_id uuid primary key,push_enabled boolean default false,character_initiated_messages boolean default true,initiative_level text default 'natural',companion_initiative_levels jsonb default '{}',quiet_hours_start time default '23:00',quiet_hours_end time default '08:00',timezone text default 'UTC',date_reminders boolean default true,world_event_updates boolean default true,updated_at timestamptz default now());
 create table together_character_instances(id uuid primary key,user_id uuid,continuity_id uuid,scenario_state jsonb);
 create table together_entitlements(user_id uuid primary key,tier text,expires_at timestamptz);
 create table together_proactive_messages(id uuid primary key,user_id uuid,character_instance_id uuid,continuity_id uuid,context jsonb default '{}',dedupe_key text,status text default 'queued',updated_at timestamptz default now());
 create table together_messages(id uuid default gen_random_uuid(),user_id uuid,character_instance_id uuid,role text,provider_metadata jsonb default '{}',created_at timestamptz default now(),delivery_status text default 'complete');`);
 await db.exec(readFileSync('supabase/migrations/20260910115620_proactive_chat_preferences.sql','utf8'));
 const [user,other,life,life2,char,char2,char3,q,q2]=Array.from({length:9},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`);
 await db.query('insert into together_character_instances(id,user_id,continuity_id) values($1,$2,$3),($4,$2,$3),($5,$2,$6)',[char,user,life,char2,char3,life2]);
 await db.query("insert into together_entitlements values($1,'kivelle_plus',null)",[user]);
 await db.query("insert into together_proactive_messages(id,user_id,character_instance_id,continuity_id) values($1,$2,$3,$4),($5,$2,$3,$4)",[q,user,char,life,q2]);
 const patch=async(id,world,data,who=user)=>(await db.query('select kivelle_patch_companion_preferences($1,$2,$3,$4) p',[who,id,world,data])).rows[0].p;
 const quiet={start:'23:00',end:'08:00',timezone:'America/New_York',enabled:true};
 await assert.rejects(()=>patch(char,life,{frequency:'off'},other),/COMPANION_UNAVAILABLE/);
 await assert.rejects(()=>patch(char,life2,{frequency:'off'}),/COMPANION_UNAVAILABLE/);
 await assert.rejects(()=>patch(char,life,{quietHours:{...quiet,start:'26:00'}}),/INVALID_QUIET/);
 await assert.rejects(()=>patch(char,life,{quietHours:{...quiet,end:'23:00'}}),/DIFFERENT_TIMES/);
 await patch(char2,life,{frequency:'occasional',quietHours:quiet});
 await patch(char3,life2,{quietHours:quiet});
 let p=await patch(char,life,{frequency:'frequent',quietHours:{...quiet,start:'22:00'},applyAllQuietHours:true});
 assert.equal(p.companion_initiative_levels[char2],'occasional');assert.equal(p.companion_quiet_hours[char2],undefined);assert.deepEqual(p.companion_quiet_hours[char3],quiet);assert.equal(p.life_quiet_hours[life].start,'22:00');
 await patch(char,life,{quietHours:{...quiet,enabled:false}});
 const policy=async(at='2026-09-10T12:00:00Z',id=q,pace=true)=>(await db.query('select kivelle_proactive_delivery_policy($1,$2,$3,$4) p',[user,id,at,pace])).rows[0].p;
 assert.equal((await policy()).allowed,true);
 await patch(char,life,{quietHours:null});
 assert.equal((await policy('2026-09-10T03:00:00Z')).reason,'quiet_hours');
 assert.equal((await policy('2026-09-10T12:00:00Z')).allowed,true,'End boundary is open');
 await db.query("update together_entitlements set tier='free' where user_id=$1",[user]);
 assert.equal((await policy()).reason,'paid_required');await assert.rejects(()=>patch(char,life,{frequency:'natural'}),/PAID_REQUIRED/);
 await db.query("update together_entitlements set tier='kivelle_plus',expires_at='2026-01-01' where user_id=$1",[user]);assert.equal((await policy()).reason,'paid_required');
 await db.query('update together_entitlements set expires_at=null where user_id=$1',[user]);
 await patch(char,life,{frequency:'off'});assert.equal((await policy()).reason,'initiative_off');
 assert.equal((await db.query('select status from together_proactive_messages where id=$1',[q])).rows[0].status,'cancelled');
 await db.query("update together_proactive_messages set context='{"+'"messageKind":"plan_reminder"'+"}',status='queued' where id=$1",[q]);
 assert.equal((await policy()).allowed,true,'Off permits plan reminders');
 assert.equal((await policy('2026-09-10T03:00:00Z')).reason,'quiet_hours','Reminders observe quiet hours');
 await db.query("update together_entitlements set tier='free' where user_id=$1",[user]);assert.equal((await policy()).allowed,true,'Free still gets requested reminders');
 await db.query("update together_entitlements set tier='kivelle_plus' where user_id=$1",[user]);
 await patch(char,life,{frequency:'frequent',quietHours:{...quiet,enabled:false}});
 await db.query("update together_proactive_messages set context='{}',status='queued'");
 await db.query("update together_character_instances set scenario_state='{}' where id=$1",[char]);assert.equal((await policy()).reason,'scenario_active');
 await db.query('update together_character_instances set scenario_state=null where id=$1',[char]);
 const insert=async(id,role='assistant')=>db.query('insert into together_messages(user_id,character_instance_id,role,provider_metadata) values($1,$2,$3,$4)',[user,char,role,{proactive:role==='assistant',proactive_message_id:id}]);
 await insert(q);await assert.rejects(()=>insert(q2),/frequency_cooldown/);
 assert.equal((await policy(new Date().toISOString(),q2,false)).allowed,true,'Push policy does not count its own delivery cooldown');
 await patch(char,life,{frequency:'off'});await assert.rejects(()=>insert(q2),/initiative_off/);await insert(q2,'user');
 const defaults={pushEnabled:true,initiativeLevel:'natural',dateReminders:true,worldEventUpdates:true,quietHoursStart:'23:00',quietHoursEnd:'08:00',timezone:'UTC'};
 p=(await db.query('select kivelle_patch_notification_defaults($1,$2,$3) p',[user,defaults,{[char]:null}])).rows[0].p;
 assert.equal(p.companion_initiative_levels[char],undefined);assert.equal(p.companion_initiative_levels[char2],'occasional');assert.ok(p.life_quiet_hours[life]);assert.equal(p.push_enabled,true);
 await patch(char,life,{quietHours:null,applyAllQuietHours:true});p=(await db.query('select * from together_notification_preferences')).rows[0];assert.equal(p.life_quiet_hours[life],undefined);assert.ok(p.companion_quiet_hours[char3]);
 assert.equal((await db.query("select has_function_privilege('authenticated','kivelle_patch_companion_preferences(uuid,uuid,uuid,jsonb)','EXECUTE') allowed")).rows[0].allowed,false);
 }finally{await db.close();}
});
