import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const catalogue=JSON.parse(readFileSync('content/scenarios/runtime-catalog.json','utf8'));
const migration=readFileSync('supabase/migrations/20260910001505_scenario_presence_pause.sql','utf8');
test('scenario location, routine hold, movement, lifecycle and atomic event handoff',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create function auth.uid() returns uuid language sql as 'select null::uuid';create table auth.users(id uuid primary key);
 create table together_continuities(id uuid primary key,user_id uuid);
 create table together_character_templates(id uuid primary key);create table together_worlds(id uuid primary key);create table together_locations(id uuid primary key,world_id uuid,name text);
 create table together_character_instances(id uuid primary key,user_id uuid,continuity_id uuid,character_template_id uuid,current_location_id uuid,current_activity text,current_presence_source text default 'fallback',current_schedule_event_id uuid,current_interruptibility text,last_simulated_at timestamptz,last_event_simulated_at timestamptz,updated_at timestamptz);
 create table together_conversations(id uuid primary key,user_id uuid,character_instance_id uuid,continuity_id uuid,user_archived_at timestamptz,archived_at timestamptz,kind text default 'direct',updated_at timestamptz default now());
 create table together_messages(id uuid default gen_random_uuid(),user_id uuid,conversation_id uuid,character_instance_id uuid,role text,content text,delivery_status text,provider_metadata jsonb,content_rating text,visibility_scope text,moderation_version text);
 create table together_shared_plans(id uuid primary key,user_id uuid,continuity_id uuid,character_instance_id uuid,participant_instance_ids uuid[],status text,title text,location_id uuid,starts_at timestamptz,ends_at timestamptz,metadata jsonb default '{}',updated_at timestamptz,companion_state text,companion_eta_at timestamptz,grace_minutes int,grace_ends_at timestamptz);
 create table together_proactive_messages(id uuid,user_id uuid,context jsonb);create table together_life_events(id uuid,user_id uuid,character_instance_id uuid,event_type text,metadata jsonb);
 create table together_plan_attendance(id uuid default gen_random_uuid(),plan_id uuid,user_id uuid,participant_type text,left_at timestamptz);
 create table together_date_templates(id uuid primary key,location_id uuid);create table together_date_sessions(id uuid,user_id uuid,continuity_id uuid,character_instance_id uuid,status text,date_template_id uuid,current_phase text,phase_index int,started_at timestamptz,scheduled_for timestamptz,state jsonb,updated_at timestamptz);
 create table together_scene_sessions(id uuid primary key,user_id uuid,continuity_id uuid,character_instance_id uuid,conversation_id uuid,location_id uuid,shared_plan_id uuid,started_at timestamptz default now(),ended_at timestamptz,updated_at timestamptz,state jsonb default '{}');
 create function kivelle_begin_plan_experience(uuid,uuid,uuid,uuid,text,timestamptz default now(),text default 'app') returns jsonb language plpgsql as $$begin if $7 not in('app','chat','push','date') then raise exception 'attendance source constraint';end if;if $5='fail' then raise exception 'event cannot be joined';end if;update together_shared_plans set status='active' where id=$4;return jsonb_build_object('planId',$4);end $$;
 `);
 for(const id of new Set(catalogue.map(x=>x.characterTemplateId)))await db.query('insert into together_character_templates values($1)',[id]);
 for(const id of new Set(catalogue.map(x=>x.worldId)))await db.query('insert into together_worlds values($1)',[id]);
 for(const s of catalogue)await db.query('insert into together_locations values($1,$2,$3) on conflict do nothing',[s.locationId,s.worldId,s.locationName]);
 await db.exec(readFileSync('supabase/migrations/20260909205155_kivelle_scenarios.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/20260909210553_scenario_context_revision.sql','utf8'));
 await db.exec(migration);
 await db.exec(readFileSync('supabase/migrations/20260910002531_scenario_join_attendance_source.sql','utf8'));
 const ids=Array.from({length:7},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`),[user,other,life,character,conversation,secondChat,plan]=ids;
 const s=catalogue[0],next=catalogue.find(x=>x.worldId===s.worldId&&x.locationId!==s.locationId);
 await db.query('insert into auth.users values($1),($2)',[user,other]);await db.query('insert into together_continuities values($1,$2)',[life,user]);
 await db.query('insert into together_character_instances(id,user_id,continuity_id,character_template_id,current_location_id,current_activity) values($1,$2,$3,$4,$5,$6)',[character,user,life,s.characterTemplateId,next.locationId,'Working']);
 await db.query('insert into together_conversations(id,user_id,character_instance_id,continuity_id) values($1,$2,$3,$4),($5,$2,$3,$4)',[conversation,user,character,life,secondChat]);
 const start=()=>db.query('select (together_start_scenario($1,$2,$3,$4,$5,$6,$7)).*',[user,life,conversation,character,s.characterTemplateId,s.id,'Opening']);
 const session=(await start()).rows[0];await start();
 const actor=async()=>(await db.query('select * from together_character_instances where id=$1',[character])).rows[0];
 assert.equal((await actor()).current_location_id,s.locationId);assert.equal((await actor()).scenario_state.scenarioId,s.id);
 await db.query("update together_character_instances set current_location_id=$1,current_activity='Sleeping',current_presence_source='schedule' where id=$2",[next.locationId,character]);
 assert.equal((await actor()).current_location_id,s.locationId);assert.equal((await actor()).current_presence_source,'scenario');
 await db.query('insert into together_shared_plans(id,user_id,continuity_id,character_instance_id,participant_instance_ids,status,title,location_id,starts_at,ends_at) values($1,$2,$3,$4,array[$4]::uuid[],\'scheduled\',\'Dinner\',$5,now(),now()+interval \'1 hour\')',[plan,user,life,character,next.locationId]);
 assert.equal((await actor()).scenario_state.sessionId,session.id,'Planning does not pause or move');
 await db.query("insert into together_scene_sessions(id,user_id,continuity_id,character_instance_id,conversation_id,location_id) values(gen_random_uuid(),$1,$2,$3,$4,$5)",[user,life,character,conversation,next.locationId]);
 assert.equal((await actor()).current_location_id,next.locationId,'Explicit scene movement persists');
 await db.query("update together_scenario_sessions set status='paused' where id=$1",[session.id]);assert.equal((await actor()).scenario_state,null);
 await start();assert.equal((await actor()).current_location_id,next.locationId,'Resume keeps last scenario location');
 const join=(source='app',request='ok')=>db.query('select kivelle_begin_plan_experience($1,$2,$3,$4,$5,now(),$6)',[user,life,character,plan,request,source]);
 await assert.rejects(()=>join(),/SCENARIO_PAUSE_REQUIRED/);assert.ok((await actor()).scenario_state);
 await assert.rejects(()=>join('scenario_confirmed','fail'),/event cannot be joined/);assert.ok((await actor()).scenario_state,'Failed join rolls back pause');
 await join('scenario_confirmed');assert.equal((await actor()).scenario_state,null);assert.equal((await actor()).current_location_id,next.locationId);
 await db.query("update together_shared_plans set status='cancelled' where id=$1",[plan]);await start();
 await db.query('update together_conversations set user_archived_at=now() where id=$1',[conversation]);assert.equal((await actor()).scenario_state,null,'Archive releases routine');
 await db.query('update together_conversations set user_archived_at=null where id=$1',[conversation]);await start();
 await db.query("update together_shared_plans set status='scheduled',starts_at=now()-interval '1 minute',ends_at=now()+interval '1 minute' where id=$1",[plan]);
 await db.query('select together_defer_scenario_plans($1,$2,now()+interval \'2 minutes\')',[user,character]);
 const deferred=(await db.query('select status,metadata from together_shared_plans where id=$1',[plan])).rows[0];assert.equal(deferred.status,'proposed');assert.equal(deferred.metadata.scenarioNeedsReschedule,true);
 await db.query("insert into together_life_events values(gen_random_uuid(),$1,$2,'schedule_outcome','{}')",[user,character]);assert.equal((await db.query('select count(*)::int n from together_life_events')).rows[0].n,0);
 await db.query("insert into together_messages(user_id,character_instance_id,provider_metadata) values($1,$2,jsonb_build_object('proactive',true))",[user,character]);
 const dateId=crypto.randomUUID(),dateTemplate=crypto.randomUUID();
 await db.query('insert into together_date_templates values($1,$2)',[dateTemplate,next.locationId]);
 await db.query("insert into together_date_sessions(id,user_id,continuity_id,character_instance_id,status,date_template_id) values($1,$2,$3,$4,'unlocked',$5)",[dateId,user,life,character,dateTemplate]);
 const joinDate=pause=>db.query("select together_start_date_with_scenario($1,$2,$3,$4,'{}',false)",[user,life,dateId,pause]);
 await assert.rejects(()=>joinDate(false),/SCENARIO_PAUSE_REQUIRED/);assert.ok((await actor()).scenario_state);
 await joinDate(true);assert.equal((await actor()).scenario_state,null);assert.equal((await actor()).current_location_id,next.locationId);
 await db.query("update together_date_sessions set status='completed' where id=$1",[dateId]);await start();
 await db.query('delete from together_scenario_sessions where id=$1',[session.id]);assert.equal((await actor()).scenario_state,null,'Delete releases routine');
 assert.equal((await db.query('select count(*)::int n from together_messages')).rows[0].n,1);
 for(const item of catalogue){
 const c=crypto.randomUUID(),v=crypto.randomUUID();
 await db.query('insert into together_character_instances(id,user_id,continuity_id,character_template_id) values($1,$2,$3,$4)',[c,user,life,item.characterTemplateId]);
 await db.query('insert into together_conversations(id,user_id,character_instance_id,continuity_id) values($1,$2,$3,$4)',[v,user,c,life]);
 await db.query('select together_start_scenario($1,$2,$3,$4,$5,$6,$7)',[user,life,v,c,item.characterTemplateId,item.id,'Opening']);
 assert.equal((await db.query('select current_location_id from together_character_instances where id=$1',[c])).rows[0].current_location_id,item.locationId,item.id);
 }
 await assert.rejects(()=>db.query('select together_start_scenario($1,$2,$3,$4,$5,$6,$7)',[other,life,conversation,character,catalogue[0].characterTemplateId,catalogue[0].id,'Opening']),/unavailable/);

 // Scoped resets replace just this transcript while retaining relationship state.
 await db.exec(`alter table together_conversations alter column id set default gen_random_uuid();alter table together_conversations add column title text,add column metadata jsonb default '{}',add column last_read_at timestamptz,add column summary text,add column canonical_context jsonb default '{}';
 alter table together_messages add constraint messages_conversation_fk foreign key(conversation_id) references together_conversations(id) on delete cascade;
 alter table together_proactive_messages add column conversation_id uuid,add column status text,add column updated_at timestamptz;
 create table together_conversation_attachments(id uuid,user_id uuid,conversation_id uuid references together_conversations(id) on delete cascade,storage_path text);
 create table together_dialogue_turns(id uuid,conversation_id uuid references together_conversations(id) on delete cascade,state text,lease_expires_at timestamptz);
 create table together_relationship_states(character_instance_id uuid,user_id uuid,conversation_session_count integer default 0,state jsonb);create table together_generated_media(user_id uuid,conversation_id uuid,status text);`);
 await db.exec(readFileSync('supabase/migrations/20260910004000_conversation_scoped_resets.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/20260910004232_chat_reset_preserve_progress.sql','utf8'));
 await db.query('delete from together_scenario_sessions where scenario_id=$1 and user_id=$2',[s.id,user]);
 const resetSession=(await start()).rows[0];
 await db.query("insert into together_relationship_states(character_instance_id,state) values($1,'{\"trust\":85,\"stage\":\"dating\"}')",[character]);
 await db.query("update together_conversations set metadata='{\"chatPreferences\":{\"textSize\":\"large\"},\"focus\":{\"old\":true}}',summary='Old summary',canonical_context='{\"old\":true}' where id=$1",[conversation]);
 await db.query("insert into together_messages(user_id,conversation_id,character_instance_id,content) values($1,$2,$3,'Other chat stays')",[user,secondChat,character]);
 await db.query('update together_relationship_states set user_id=$1 where character_instance_id=$2',[user,character]);
 await db.exec(`create function mock_session_counter() returns trigger language plpgsql as $$begin update together_relationship_states set conversation_session_count=conversation_session_count+1 where character_instance_id=new.character_instance_id;return new;end $$;create trigger mock_session_counter after insert on together_conversations for each row execute function mock_session_counter();`);
 const resetRequest=crypto.randomUUID(),reset=(chat,mode,request=crypto.randomUUID(),sid=resetSession.id)=>db.query('select kivelli_reset_chat($1,$2,$3,$4,$5,$6,$7) result',[user,life,chat,mode,request,sid,'New opening']);
 await assert.rejects(()=>reset(conversation,'scenario',crypto.randomUUID(),crypto.randomUUID()),/Scenario unavailable/);
 assert.ok((await db.query('select id from together_conversations where id=$1',[conversation])).rows.length);
 const resetResult=(await reset(conversation,'scenario',resetRequest)).rows[0].result;
 assert.deepEqual((await reset(conversation,'scenario',resetRequest)).rows[0].result,resetResult,'Retry is idempotent');
 assert.equal((await db.query('select content from together_messages where conversation_id=$1',[resetResult.conversationId])).rows[0].content,'New opening');
 assert.equal((await actor()).scenario_state.conversationId,resetResult.conversationId);
 assert.equal((await actor()).current_location_id,s.locationId);
 const fresh=(await db.query('select * from together_conversations where id=$1',[resetResult.conversationId])).rows[0];assert.equal(fresh.summary,null);assert.deepEqual(fresh.canonical_context,{});assert.deepEqual(fresh.metadata,{chatPreferences:{textSize:'large'}});
 await db.query("insert into together_dialogue_turns values(gen_random_uuid(),$1,'planning',now()+interval '1 minute')",[resetResult.conversationId]);
 await assert.rejects(()=>reset(resetResult.conversationId,'conversation'),/Wait for the current reply/);
 await db.query('delete from together_dialogue_turns where conversation_id=$1',[resetResult.conversationId]);
 const plain=(await reset(resetResult.conversationId,'conversation')).rows[0].result;
 assert.equal((await db.query('select count(*)::int n from together_messages where conversation_id=$1',[plain.conversationId])).rows[0].n,0);
 assert.equal((await actor()).scenario_state.conversationId,plain.conversationId);
 assert.equal((await db.query('select content from together_messages where conversation_id=$1',[secondChat])).rows[0].content,'Other chat stays');
 assert.equal((await db.query('select conversation_session_count from together_relationship_states where character_instance_id=$1',[character])).rows[0].conversation_session_count,0,'Chat resets preserve relationship counters');
 assert.deepEqual((await db.query('select state from together_relationship_states where character_instance_id=$1',[character])).rows[0].state,{trust:85,stage:'dating'});
 await assert.rejects(()=>db.query("select kivelli_reset_chat($1,$2,$3,'conversation',$4,null,null)",[other,life,plain.conversationId,crypto.randomUUID()]),/Conversation unavailable/);
 await db.exec('set role authenticated');await assert.rejects(()=>db.query('select * from together_scenario_definitions'),/permission denied/);
 }finally{await db.close();}
});
