import { generateScheduleWindow, validateSchedule, type ActivityTemplate, type CharacterLifeProfile, type LifeLocation } from '../packages/together-domain/src/life-engine.ts';

const count=Math.max(1,Number(process.argv[2]??30)),runs=Math.max(1,Number(process.argv[3]??1));
const names=['Miranda','Nia','Sophie','Priya','Jade','Camila','Hannah','Amara','Elena','Lena','Zoe','Tessa','Samira','Avery','Mateo','Ethan','Darius','Kenji','Luca','Claire','Becka','Emma','Brooke'];
const locations:LifeLocation[]=[
  {id:'home',worldId:'juniper',name:'Home',category:'home',locationType:'residence',supportedActivities:['sleep','home_evening'],tags:['home']},
  {id:'studio',worldId:'juniper',name:'Professional workplace',category:'work',locationType:'venue',supportedActivities:['work'],tags:['work','studio'],hours:{default:'00:00-23:59'}},
  {id:'cafe',worldId:'juniper',name:'Juniper Cafe',category:'cafe',locationType:'venue',supportedActivities:['coffee'],tags:['coffee'],hours:{default:'07:00-22:00'}},
  {id:'park',worldId:'juniper',name:'Halcyon Park',category:'outdoor',locationType:'outdoor',supportedActivities:['walk','photo_walk'],tags:['outdoors','photography']},
  {id:'gym',worldId:'juniper',name:'Meridian Fitness',category:'fitness',locationType:'venue',supportedActivities:['gym'],tags:['fitness'],hours:{default:'05:00-23:00'}},
  {id:'gallery',worldId:'juniper',name:'Glassline Gallery',category:'venue',locationType:'venue',supportedActivities:['gallery'],tags:['art','gallery','design'],hours:{default:'10:00-22:00'}},
  {id:'night',worldId:'juniper',name:'Velvet Hour',category:'nightlife',locationType:'venue',supportedActivities:['music_night'],tags:['nightlife','social','jazz'],hours:{default:'17:00-02:00'}},
  {id:'arcade',worldId:'juniper',name:'Pixel & Pint',category:'entertainment',locationType:'venue',supportedActivities:['arcade'],tags:['gaming','events'],hours:{default:'11:00-01:00'}},
];
const templates:ActivityTemplate[]=[
  activity('coffee','Having coffee','cafe',['coffee'],.75,[1,3],3,18),activity('photo_walk','Taking photographs','outdoor',['photography'],.72,[0,2],2,30),activity('gym','Getting a workout in','fitness',['fitness'],.58,[1,3],3,30),activity('gallery','Exploring an exhibit','venue',['gallery'],.65,[0,2],2,48),activity('music_night','Listening to live music','nightlife',['social'],.62,[0,1],1,72,true),activity('arcade','Playing arcade games','entertainment',['gaming'],.6,[0,2],2,36),activity('walk','Taking a walk','outdoor',['outdoors'],.65,[1,4],4,18),activity('home_evening','Having a quiet night at home','home',['home'],.8,[1,4],4,12),
];

for(const name of names){
  const profile=profileFor(name),batches=Array.from({length:runs},(_,run)=>generateScheduleWindow({characterInstanceId:name.toLowerCase(),seed:`report:${name}:${run}`,timezone:'America/New_York',fromLocalDate:'2026-08-17',days:count,profile,locations,homeLocationId:'home',activityTemplates:templatesFor(name),generationVersion:'life_engine_v2'}));
  const events=batches.flat(),issues=batches.flatMap((batch,run)=>validateSchedule(batch,locations,'America/New_York').map(issue=>`run-${run+1}:${issue}`));
  const visits=countBy(events.filter(item=>item.locationId).map(item=>locations.find(location=>location.id===item.locationId)?.name??'Unknown'));
  const activities=countBy(events.filter(item=>!['sleep','travel'].includes(item.activityKey)).map(item=>item.activityKey));
  const occupationCount=Object.entries(activities).filter(([key])=>key.startsWith('occupation_')).reduce((sum,[,value])=>sum+value,0);
  const lateNights=events.filter(item=>{const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',hourCycle:'h23'}).format(new Date(item.endsAt)));return hour<4&&item.activityKey!=='sleep';}).length;
  const warnings=batches.flatMap(scheduleWarnings);
  console.log(`\n${name.toUpperCase()} — ${count} DAY × ${runs} RUN SUMMARY\nOccupation blocks: ${occupationCount}\nLate nights: ${lateNights}\nTop locations: ${top(visits)}\nTop activities: ${top(activities)}\nQuality issues: ${issues.length?issues.slice(0,8).join(', '):'none'}\nPotential problem: ${warnings[0]??'none detected'}`);
}

function activity(key:string,title:string,category:string,tags:string[],affinity:number,frequency:[number,number],maximum:number,gap:number,rare=false):ActivityTemplate{return{key,title,category,validTimeWindows:[{startMinute:480,endMinute:key==='music_night'?1410:1320}],durationMinutes:[45,120],locationCategories:[category],tags,affinity,preferredWeeklyFrequency:frequency,maximumWeeklyFrequency:maximum,minimumGapHours:gap,priority:key.includes('night')?'social_event':key==='coffee'||key==='gym'?'recurring_routine':'preferred_activity',visibility:rare?'hint':'hidden',interruptibility:key==='gym'?'limited':'open',activityLabel:title,upcomingHint:`May ${title.toLowerCase()} later`,rare};}
function templatesFor(name:string){const favored:Record<string,string[]>={Sophie:['coffee','home_evening'],Priya:['music_night','home_evening'],Elena:['gym','coffee'],Lena:['photo_walk','coffee'],Zoe:['music_night','gym'],Mateo:['music_night','walk'],Luca:['music_night','home_evening'],Brooke:['walk','gym']};return templates.map(template=>({...template,affinity:favored[name]?.includes(template.key) ? .97 : template.affinity}));}
function profileFor(name:string):CharacterLifeProfile{
  const shifts=new Set(['Nia','Sophie','Priya','Jade','Camila','Elena','Zoe','Avery','Mateo','Luca','Emma']),students=new Set(['Lena','Samira','Becka','Brooke']),freelance=new Set(['Miranda','Ethan','Darius']);
  const pattern=students.has(name)?'student':freelance.has(name)?'freelance':shifts.has(name)?'shifts':'hybrid',overnight=new Set(['Priya','Elena','Mateo']).has(name),early=new Set(['Sophie','Emma','Avery']).has(name),late=name==='Luca',start=overnight?19*60:early?5*60:late?15*60:9*60,days=shifts.has(name)?[0,2,4,6]:[1,2,3,4,5];
  return{version:2,occupation:{title:`${name}'s profession`,workPattern:pattern,flexibility:.5,scheduleBlocks:[{key:'primary',title:`${name}'s profession`,activityKey:'occupation_primary',workDays:days,startRange:{startMinute:start,endMinute:start+45},durationMinutes:overnight?[600,720]:late?[480,600]:[360,510],primaryLocationId:'studio',activityVariants:[`handling a specific ${name.toLowerCase()} work responsibility`,`finishing a scheduled ${name.toLowerCase()} work block`],breakPolicy:overnight||late?'none':'meal',...(overnight?{recoverySleepMinutes:[360,420] as [number,number]}:{})}]},sleep:{preferredBedtime:early?{startMinute:1200,endMinute:1320}:late?{startMinute:90,endMinute:180}:{startMinute:1320,endMinute:1430},preferredWakeTime:early?{startMinute:210,endMinute:285}:late?{startMinute:540,endMinute:660}:{startMinute:360,endMinute:540},variabilityMinutes:25,weekendShiftMinutes:30},lifestyle:{social:.65,adventurous:.62,spontaneous:shifts.has(name)?.7:.45,fitness:new Set(['Avery','Mateo','Zoe','Brooke','Becka','Elena']).has(name)?.85:.45,nightlife:new Set(['Zoe','Luca','Nia']).has(name)?.85:.4,outdoors:new Set(['Brooke','Becka']).has(name)?.9:.5,homebody:new Set(['Sophie','Elena','Lena']).has(name)?.72:.4,creativity:.78},interests:[],scheduling:{repetitionTolerance:.3,spontaneity:.55,preferredDailyActivityCount:[2,3]}};
}
function countBy(values:string[]){return values.reduce<Record<string,number>>((result,value)=>{result[value]=(result[value]??0)+1;return result;},{});}
function top(values:Record<string,number>){return Object.entries(values).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([key,value])=>`${key} ${value}`).join(', ')||'none';}
function scheduleWarnings(events:ReturnType<typeof generateScheduleWindow>){const warnings:string[]=[];const acts=events.filter(item=>!['sleep','travel','meal_break'].includes(item.activityKey)&&!item.activityKey.startsWith('occupation_'));for(let index=2;index<acts.length;index++)if(acts[index]!.activityKey===acts[index-1]!.activityKey&&acts[index]!.activityKey===acts[index-2]!.activityKey)warnings.push(`${acts[index]!.activityKey} selected three consecutive times`);if(events.some(event=>/nearby|Focused on work|In the middle of a project|taking care of a few things/i.test(`${event.title} ${event.metadata?.['activityLabel']??''}`)))warnings.push('vague visible activity');if(new Set(acts.map(event=>event.activityKey)).size<Math.min(4,Math.max(2,Math.floor(count/7))))warnings.push('insufficient activity diversity');for(const event of events.filter(event=>event.metadata?.['rare']===true)){if(events.filter(candidate=>candidate.activityKey===event.activityKey).length>Math.ceil(count/7))warnings.push(`rare activity repeated: ${event.activityKey}`);}return warnings;}
