import { generateScheduleWindow, validateSchedule, type ActivityTemplate, type CharacterLifeProfile, type LifeLocation } from '../packages/together-domain/src/life-engine.ts';

const count=Math.max(1,Number(process.argv[2]??30));
const runs=Math.max(1,Number(process.argv[3]??1));
const names=['Maya','Chloe','Alex','Sofia','Avery','Riley','Elena','Harper'];
const locations:LifeLocation[]=[
  {id:'home',worldId:'juniper',name:'Home',category:'home',locationType:'residence',supportedActivities:['sleep','home_evening','home_creative','home_gaming','reading_home'],tags:['home']},
  {id:'studio',worldId:'juniper',name:'Studio',category:'work',locationType:'venue',supportedActivities:['work'],tags:['work','studio']},
  {id:'cafe',worldId:'juniper',name:'Juniper Cafe',category:'cafe',locationType:'venue',supportedActivities:['coffee'],tags:['coffee'],hours:{default:'07:00-22:00'}},
  {id:'park',worldId:'juniper',name:'Halcyon Park',category:'outdoor',locationType:'outdoor',supportedActivities:['walk','photo_walk','park_patrol'],tags:['outdoors','photography']},
  {id:'gym',worldId:'juniper',name:'Meridian Fitness',category:'fitness',locationType:'venue',supportedActivities:['gym'],tags:['fitness'],hours:{default:'05:00-23:00'}},
  {id:'gallery',worldId:'juniper',name:'Glassline Gallery',category:'venue',locationType:'venue',supportedActivities:['gallery'],tags:['art','gallery','design'],hours:{default:'10:00-22:00'}},
  {id:'night',worldId:'juniper',name:'Velvet Hour',category:'nightlife',locationType:'venue',supportedActivities:['drinks_with_chloe','jazz_evening','rooftop_social'],tags:['nightlife','social','jazz'],hours:{default:'17:00-02:00'}},
  {id:'arcade',worldId:'juniper',name:'Pixel & Pint',category:'entertainment',locationType:'venue',supportedActivities:['arcade','live_event'],tags:['gaming','events'],hours:{default:'11:00-01:00'}},
];
const templates:ActivityTemplate[]=[
  activity('coffee','Coffee and editing','cafe',['coffee'],.75,[2,4],4,12),activity('photo_walk','Taking photographs','outdoor',['photography'],.8,[1,4],4,18),activity('gym','Working out','fitness',['fitness'],.55,[2,4],4,30),activity('gallery','Exploring an exhibit','venue',['gallery'],.7,[1,2],2,48),activity('drinks_with_chloe','Drinks with a friend','nightlife',['social'],.62,[0,2],2,60),activity('arcade','Playing arcade games','entertainment',['gaming'],.65,[0,3],3,30),activity('walk','Taking a walk','outdoor',['outdoors'],.65,[1,5],5,14),activity('home_evening','Quiet night at home','home',['home'],.8,[2,7],7,6),
];
for(const [index,name] of names.entries()){
  const profile=profileFor(index),batches=Array.from({length:runs},(_,run)=>generateScheduleWindow({characterInstanceId:name.toLowerCase(),seed:`report:${name}:${run}`,timezone:'America/New_York',fromLocalDate:'2026-08-17',days:count,profile,locations,homeLocationId:'home',activityTemplates:templatesFor(name),generationVersion:'life_engine_v1'})),events=batches.flat(),issues=batches.flatMap((batch,run)=>validateSchedule(batch,locations,'America/New_York').map(issue=>`run-${run+1}:${issue}`));
  const visits=countBy(events.filter(item=>item.locationId).map(item=>locations.find(location=>location.id===item.locationId)?.name??'Unknown'));
  const activities=countBy(events.filter(item=>!['sleep','travel'].includes(item.activityKey)).map(item=>item.activityKey));
  const nightsHome=events.filter(item=>item.activityKey==='home_evening').length,lateNights=events.filter(item=>{const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',hourCycle:'h23'}).format(new Date(item.endsAt)));return hour<4&&item.activityKey!=='sleep';}).length;
  const warnings=batches.map(repetitionWarning).filter(warning=>warning!=='none detected');
  console.log(`\n${name.toUpperCase()} — ${count} DAY × ${runs} RUN SUMMARY\nWork blocks: ${activities.work??0}\nHome evenings: ${nightsHome}\nLate nights: ${lateNights}\nTop locations: ${top(visits)}\nTop activities: ${top(activities)}\nQuality issues: ${issues.length?issues.slice(0,8).join(', '):'none'}\nPotential problem: ${warnings[0]??'none detected'}`);
}
function activity(key:string,title:string,category:string,tags:string[],affinity:number,frequency:[number,number],maximum:number,gap:number):ActivityTemplate{return{key,title,category,validTimeWindows:[{startMinute:480,endMinute:1320}],durationMinutes:[45,120],locationCategories:[category],tags,affinity,preferredWeeklyFrequency:frequency,maximumWeeklyFrequency:maximum,minimumGapHours:gap,priority:key.includes('drink')?'social_event':key==='coffee'||key==='gym'?'recurring_routine':'preferred_activity',visibility:key.includes('drink')?'hint':'hidden',interruptibility:key==='gym'?'limited':'open'};}
function templatesFor(name:string){const favored:Record<string,string[]>={Maya:['photo_walk','coffee'],Chloe:['drinks_with_chloe','gallery'],Alex:['photo_walk','walk'],Sofia:['gallery','home_evening'],Avery:['drinks_with_chloe','arcade'],Riley:['arcade','home_evening'],Elena:['gym','gallery'],Harper:['walk','photo_walk']};return templates.map(template=>({...template,affinity:favored[name]?.includes(template.key) ? .97 : template.affinity*(name==='Sofia'&&template.key==='drinks_with_chloe' ? .45 : 1)}));}
function profileFor(index:number):CharacterLifeProfile{const social=[.68,.9,.55,.42,.94,.34,.48,.4][index]!,spontaneous=[.68,.82,.36,.28,.8,.61,.2,.55][index]!,homebody=[.42,.23,.55,.76,.18,.85,.58,.44][index]!,outdoors=[.78,.52,.67,.38,.32,.28,.42,.98][index]!,patterns=['freelance','hybrid','hybrid','hybrid','shifts','remote','fixed_weekdays','shifts'] as const;return{version:1,occupation:{title:['photographer','designer','producer','editor','event producer','writer','architect','park ranger'][index]!,primaryLocationId:'studio',workPattern:patterns[index]!,flexibility:.5,workDays:patterns[index]==='shifts'?[0,2,3,5,6]:[1,2,3,4,5],startRange:{startMinute:patterns[index]==='shifts'?420:510,endMinute:patterns[index]==='shifts'?780:630},durationMinutes:patterns[index]==='shifts'?[480,660]:[360,510]},sleep:{preferredBedtime:{startMinute:1320,endMinute:1430},preferredWakeTime:{startMinute:360,endMinute:540},variabilityMinutes:30,weekendShiftMinutes:60},lifestyle:{social,adventurous:spontaneous,spontaneous,fitness:index===7?.88:.45,nightlife:index===4?.92:.4,outdoors,homebody,creativity:index===7?.45:.85},interests:[],scheduling:{repetitionTolerance:.4,spontaneity:spontaneous,preferredDailyActivityCount:[2,4]}};}
function countBy(values:string[]){return values.reduce<Record<string,number>>((result,value)=>{result[value]=(result[value]??0)+1;return result;},{});}
function top(values:Record<string,number>){return Object.entries(values).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([key,value])=>`${key} ${value}`).join(', ')||'none';}
function repetitionWarning(events:ReturnType<typeof generateScheduleWindow>){const acts=events.filter(item=>!['sleep','travel','work','lunch_break'].includes(item.activityKey));for(let index=2;index<acts.length;index++)if(acts[index]!.activityKey===acts[index-1]!.activityKey&&acts[index]!.activityKey===acts[index-2]!.activityKey)return`${acts[index]!.activityKey} selected three consecutive times`;return'none detected';}
