import{createClient,type SupabaseClient}from'@supabase/supabase-js';
import{createHash}from'node:crypto';
import{readFile,readdir}from'node:fs/promises';
import{extname,join,parse}from'node:path';

const root=process.cwd(),apply=process.argv.includes('--apply'),url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY??process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!key)throw new Error('SUPABASE_URL and SUPABASE_SECRET_KEY are required.');
const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),bucket='kivelle-reference-media';

type Asset={sourceKey:string;role:'character_identity'|'location_canonical'|'world_canonical';path:string;worldSlug?:string;locationSlug?:string;characterSlug?:string};

async function main(){const assets=await discoverAssets(),context=await loadContext(db),summary={discovered:assets.length,unchanged:0,uploaded:0,missingCanonicalEntity:0};for(const asset of assets){const scope=resolveScope(asset,context);if(!scope){summary.missingCanonicalEntity+=1;console.warn(`skip missing canonical entity: ${asset.sourceKey}`);continue;}const bytes=await readFile(asset.path),sha256=createHash('sha256').update(bytes).digest('hex'),extension=extname(asset.path).slice(1).toLowerCase(),contentType=extension==='png'?'image/png':extension==='webp'?'image/webp':'image/jpeg';const{data:existing,error}=await db.from('together_media_reference_assets').select('*').eq('source_key',asset.sourceKey).eq('asset_role',asset.role).order('revision',{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(existing?.sha256===sha256){summary.unchanged+=1;continue;}const revision=Number(existing?.revision??0)+1,storagePath=`${asset.role}/${asset.sourceKey}/${sha256.slice(0,20)}.${extension}`;if(!apply){console.log(`[dry-run] ${asset.sourceKey} -> ${storagePath}`);summary.uploaded+=1;continue;}const{error:uploadError}=await db.storage.from(bucket).upload(storagePath,bytes,{contentType,upsert:false,cacheControl:'31536000'});if(uploadError&&!/already exists/i.test(uploadError.message))throw uploadError;if(existing?.id)await db.from('together_media_reference_assets').update({active:false,updated_at:new Date().toISOString()}).eq('id',existing.id);const dimensions=imageDimensions(bytes,contentType);const{error:insertError}=await db.from('together_media_reference_assets').insert({asset_role:asset.role,source_key:asset.sourceKey,storage_bucket:bucket,storage_path:storagePath,content_type:contentType,byte_size:bytes.byteLength,sha256,revision,active:true,...dimensions,...scope,metadata:{syncedBy:'sync-kivelle-reference-media',sourcePath:asset.path.replace(root,'').replaceAll('\\','/')}});if(insertError)throw insertError;summary.uploaded+=1;}console.log(JSON.stringify({...summary,mode:apply?'apply':'dry-run'}));}

async function discoverAssets():Promise<Asset[]>{const output:Asset[]=[];const worlds=['juniper-city'];for(const worldSlug of worlds){const directory=join(root,'apps','together','assets','locations',worldSlug),files=await readdir(directory);for(const name of files.filter((item)=>/\.(jpe?g|png|webp)$/i.test(item))){const slug=parse(name).name;if(slug===worldSlug){output.push({sourceKey:`world:${worldSlug}:canonical`,role:'world_canonical',path:join(directory,name),worldSlug});continue;}if(files.some((candidate)=>parse(candidate).name===slug&&/\.jpe?g$/i.test(candidate))&&!/\.jpe?g$/i.test(name))continue;output.push({sourceKey:`location:${worldSlug}:${slug}:canonical`,role:'location_canonical',path:join(directory,name),worldSlug,locationSlug:slug});}}const characterDirectory=join(root,'apps','together','assets','characters','juniper-city');for(const name of(await readdir(characterDirectory)).filter((item)=>/\.(jpe?g|png|webp)$/i.test(item)))output.push({sourceKey:`character:${parse(name).name}:identity`,role:'character_identity',path:join(characterDirectory,name),characterSlug:parse(name).name});for(const characterSlug of['maya','chloe','alex']){const path=join(root,'apps','together','assets',`${characterSlug}-portrait.png`);output.push({sourceKey:`character:${characterSlug}:identity`,role:'character_identity',path,characterSlug});}return output;}

async function loadContext(client:SupabaseClient){const[{data:worlds,error:worldError},{data:locations,error:locationError},{data:templates,error:templateError}]=await Promise.all([client.from('together_worlds').select('id,slug'),client.from('together_locations').select('id,slug,world_id'),client.from('together_character_templates').select('id,slug,current_published_version,together_character_versions(id,version,published_at)')]);if(worldError)throw worldError;if(locationError)throw locationError;if(templateError)throw templateError;return{worlds:new Map((worlds??[]).map((item)=>[item.slug,item.id])),locations:locations??[],templates:templates??[]};}
function resolveScope(asset:Asset,context:Awaited<ReturnType<typeof loadContext>>){if(asset.worldSlug&&!asset.locationSlug){const id=context.worlds.get(asset.worldSlug);return id?{world_id:id}:null;}if(asset.worldSlug&&asset.locationSlug){const worldId=context.worlds.get(asset.worldSlug),location=context.locations.find((item)=>item.world_id===worldId&&item.slug===asset.locationSlug);return location?{location_id:location.id}:null;}if(asset.characterSlug){const template=context.templates.find((item)=>item.slug===asset.characterSlug);const versions=(template?.together_character_versions??[]) as Array<{id:string;version:number;published_at?:string}>;const version=[...versions].sort((a,b)=>Number(b.version)-Number(a.version))[0];return version?{character_version_id:version.id}:null;}return null;}
function imageDimensions(bytes:Buffer,contentType:string):{width?:number;height?:number}{if(contentType==='image/png'&&bytes.length>=24)return{width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};if(contentType==='image/jpeg'){let offset=2;while(offset+9<bytes.length){if(bytes[offset]!==0xff){offset+=1;continue;}const marker=bytes[offset+1]!,length=bytes.readUInt16BE(offset+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return{height:bytes.readUInt16BE(offset+5),width:bytes.readUInt16BE(offset+7)};offset+=2+length;}}return{};}

await main();
