def L(summary, history, layout, social, private_truth, seeds, activities, anchors, etiquette, regulars):
    return dict(summary=summary, history=history, layout=layout, socialTexture=social,
                privateTruth=private_truth, storySeeds=seeds, activities=activities,
                visualAnchors=anchors, etiquette=etiquette, regulars=regulars)

LOCATION_LORE = {
1:L(
 'A three-story brick hotel with a shaded balcony, dependable meals, and a lobby where visitors learn how quickly an arrival becomes public news.',
 'The hotel absorbed two older boarding buildings after the 1872 flood. Its respectable front conceals mismatched floors and an inexpensive staff wing. The current management rents rooms to railway representatives, traveling performers, and locals between leases.',
 'The front desk faces the street doors. A public dining room opens to a side courtyard; a narrow service stair reaches staff rooms. Guest corridors and the register behind the desk are private.',
 'Breakfast brings departures and account disputes. Afternoons belong to letters and quiet waiting. Evening balconies host conversation, while Rafael controls the practical business of late arrivals.',
 'Rafael has quietly reserved one low-priced room for stranded travelers using gratuities of his own. Management has not authorized a permanent relief arrangement.',
 ['An investor wants a familiar tenant displaced before a private meeting.','A room reservation becomes a choice between a profitable guest and someone with nowhere to go.'],
 ['lodging','supper','balcony conversation','arrival assistance'],['brick balcony','green shutters','worn register','courtyard washstand'],
 'A guest name is not public entertainment. Ask before entering a corridor or joining someone on a balcony. Staff assistance does not purchase private attention.',[45,4,40]),
2:L(
 'A working print shop publishing The Run Ledger, selling stationery, and turning private grievances into carefully chosen public words.',
 'Iris purchased a damaged press with savings and an equipment loan. The shop’s older job-printing business pays for a newspaper whose independence is admired more often than it is financially supported.',
 'A customer counter separates the shopfront from type cases, a hand-fed press, and a drying room. A rear desk holds drafts and correspondence; proofs may be pinned publicly only when marked for release.',
 'Morning customers need notices, menus, and invoices. The press is loud in the afternoon. Just before publication, a casual visitor can become either useful company or an unwelcome distraction.',
 'A local patron offered to clear Iris’s equipment debt in exchange for advance sight of articles. The proposal remains unanswered in her private correspondence.',
 ['A damaging accusation arrives without evidence shortly before printing.','An innocent correction reveals two versions of a land notice.'],
 ['printing','news discussion','notice submission','proofreading by invitation'],['ink-black fingertips','lead type cases','drying sheets','patched press belt'],
 'Do not touch type or lift private proofs. Published assertions can be questioned; unpublished material requires Iris’s permission.',[4,20,19]),
3:L(
 'The county’s modest record office and hearing rooms, where property, inheritance, and public promises acquire forms that outlast the people arguing over them.',
 'A reading room became a courthouse as the town grew. Reconstruction after the flood left an uneven archive: some volumes survived, some were copied, and some entries remain disputed.',
 'A public counter and notice board lead to a hearing room. Copy desks occupy a bright side room. The archive cage, evidence cupboard, and officials’ offices require specific access.',
 'Mornings are procedural and crowded; afternoons slow into document work. Adult evening petition clinics happen only on authored dates, with Esther or a supervising official present.',
 'A copied water-register page combines measurements from different years. Its existence is genuine; whether its use was fraudulent requires comparison with other evidence.',
 ['A claimant needs an accurate copy before a hearing.','A missing page is less revealing than the filing date of the page replacing it.'],
 ['record requests','public hearings','petition assistance','archive research'],['sunlit copy desk','uneven brick addition','locked iron cage','crowded notice board'],
 'Public records and sealed records have different access. Clerks can explain process but cannot promise a ruling or create legal authority.',[20,31,6]),
4:L(
 'A busy livery and training yard where the town hires transport, boards animals, swaps practical news, and learns whether a newcomer can be trusted with a horse.',
 'June’s family built the yard around coach traffic. Growing debt and the railway’s arrival have made its future uncertain, but its repair contacts and sound animals remain indispensable.',
 'The hire counter faces a covered yard. Training pens, tack room, feed loft, and staff cottage sit beyond. Visitors wait at the rail until invited into an animal’s space.',
 'Dawn departures and evening returns are crowded. Midday offers training, grooming, and quieter conversation. A delayed return can disturb several people’s plans.',
 'A recently accepted boarding animal matches a disputed bill of sale. June knows the paperwork is weak but has not established who is telling the truth.',
 ['A borrowed horse is recognized by someone who claims it was stolen.','A novice rider needs help before an important visit.'],
 ['horse hire','riding lessons','grooming','travel planning'],['dusty training rail','labeled tack hooks','hay loft','water trough'],
 'Animal welfare governs access and timing. Borrowing requires a specific agreement; being friendly with June does not make every horse available.',[7,32,27]),
5:L(
 'The mercantile supplies everything from nails and lamp wicks to fabric, with a stockroom whose contents reveal the town’s changing ambitions.',
 'The store began as a freight counter and expanded with the silver trade. Its proprietor relies increasingly on Lottie’s purchasing judgment while continuing to call her an assistant when ownership is discussed.',
 'Public aisles lead past hardware and dry goods to a fabric counter. A scale and invoice desk mark the boundary of the stockroom. The upstairs rooms are private storage and household space.',
 'Working customers arrive early; browsing and household shopping fill the afternoon. Near closing, Lottie rearranges displays and weighs what people asked for against what the owner will buy.',
 'Lottie has designed a buying list for a small independent shop. She is using public catalog prices, not stealing the store’s accounts.',
 ['A scarce delivery is promised to two customers.','A bold display succeeds, and someone else takes the credit.'],
 ['shopping','fabric selection','ordering supplies','parcel collection'],['fabric bolts','brass scale','hanging lanterns','scuffed freight counter'],
 'A store tab is a financial arrangement, not social ownership. Ask before opening stock drawers or reading an invoice.',[13,21,11]),
6:L(
 'A warm bakery serving ordinary bread, occasional elaborate pastries, and a few tables whose regulars know the rhythms of the oven.',
 'The business survived the dry summer by shortening its menu and sharing deliveries. Beatrice learned the practical cost of wasting a batch and now balances affordable staples with higher-margin commissions.',
 'A front counter and two small tables overlook the boardwalk. The oven room, mixing bench, and ingredient store sit behind a half door. Work space is tight and hot.',
 'The first hours are brisk with workers collecting breakfast. Afternoons grow companionable as the last loaves cool. A large special order can change the whole day.',
 'Beatrice keeps a small, openly documented reduced-price shelf after the main rush. She is ashamed that she sometimes resents customers who assume the reduction is endless.',
 ['A celebration order conflicts with supplying the boardinghouse.','Someone anonymously pays for another household’s weekly bread.'],
 ['breakfast','bread buying','pastry orders','kitchen conversation by invitation'],['flour-dusted counter','brick oven','window cooling rack','blue enamel pitcher'],
 'The kitchen requires permission. Help is useful when offered concretely, and a gift should not expose a recipient’s hardship.',[16,18,36]),
7:L(
 'The marshal’s small office combines public service, uncomfortable waiting, local records, and the persistent problem of deciding which trouble cannot wait.',
 'Its cells were added after a violent payday dispute. Elias has spent years making the public room feel ordinary enough that residents report a problem before it becomes a confrontation.',
 'A desk and benches occupy the front. A record cupboard, small interview room, and separate holding area are restricted. The back yard is used for maintenance and authorized transfers.',
 'Morning reports give way to patrols and appointments. Another officer may staff the desk when Elias is away, but background staff do not acquire a new named companion identity.',
 'Elias has tolerated limited fee-evasion deliveries when household necessity was involved. His notes distinguish those cases, but the arrangement was never formally approved.',
 ['An accusation relies on a witness who saw only part of an event.','A formerly harmless exception is invoked to excuse a serious theft.'],
 ['reporting a problem','public notices','lawful appointments','found-property claims'],['scarred desk','repair tools by a window','holding-room door','pinned notices'],
 'A notice is not proof of guilt. Restricted records and holding areas require actual authority; a personal relationship does not provide it.',[31,20,30]),
8:L(
 'A forge and wagon yard where hot metal, measured workmanship, and friendly argument keep the town’s animals and vehicles moving.',
 'Gabriel acquired tools gradually and rents the yard. He has more demand than space, yet a move would mean leaving customers who can walk to the present shop and pay in small installments.',
 'The public yard contains a waiting rail and repair wagons. A forge bay, tool wall, and small office sit under a broad roof. Hot work zones are kept clear.',
 'Morning jobs are organized around animals and departures. Afternoon repairs allow longer talk between noisy stretches. Friends gather after the fires are banked.',
 'Gabriel has priced a new workshop near the railhead but has not told June because she would read the move as a judgment on the livery’s future.',
 ['A repair mark can identify a wagon seen on an old road.','An attractive workshop offer would leave longstanding customers without affordable help.'],
 ['wagon repair','farrier work','tool discussion','after-work meals'],['forge glow','hanging horseshoes','half-repaired wagon','shared outdoor table'],
 'Wait for Gabriel to make work safe before approaching. Repairs create practical records, not automatic knowledge of a customer’s purpose.',[32,7,37]),
9:L(
 'The Copper Mare is a generous, noisy saloon with good music, ordinary food, and a back room where people who dislike one another sometimes manage to talk.',
 'Gin turned an unreliable drinking room into a business through consistent service and staff loyalty. The landlord now values the location partly because her work made it desirable.',
 'The main bar opens to tables and a small music platform. A courtyard catches evening air. The back meeting room and upstairs lodgings require invitation; the office contains private business records.',
 'Afternoon trade is relaxed and conversational. Evenings draw mixed company. Closing is work: counting, cleaning, escorting staff, and settling disagreements without turning them into a spectacle.',
 'Gin can purchase the building only with outside money. Halden’s associate wants approval over private bookings in return for favorable financing.',
 ['A meeting booking forces Gin to choose between money and the room’s reputation.','A musician’s departure threatens a valued nightly routine.'],
 ['supper','music','conversation','private meetings by arrangement'],['copper horse above the bar','worn piano','courtyard lanterns','polished but repaired tables'],
 'Staff can refuse service. A drink buys a drink. Joining a table or entering the back room requires an invitation.',[1,5,31]),
10:L(
 'Marigold House is an adult companionship business with a gracious public parlor, experienced management, and workers whose private lives extend well beyond the building.',
 'Mabel purchased the original house after years of managing other people’s establishments. She has paid for repairs and supported local improvements while still being treated as a temporary convenience by some officials.',
 'A reception parlor and music room are public during service hours. Separate consultation rooms and private suites require a specific booking and the worker’s agreement. Staff rooms have no public access.',
 'Deliveries and household work occupy the day. Evenings vary from sociable company to private appointments. Workers can decline bookings or leave early without the story turning that choice into a mystery.',
 'A redevelopment prospectus omits the cost of relocating current workers. Mabel has kept copies while seeking a long lease that protects their independence.',
 ['A patron publicly supports eviction while privately asking for favors.','A worker’s new opportunity creates a practical disagreement about the house’s future.'],
 ['adult social company','music','private appointments','business negotiation'],['marigold-painted door','upright piano','embroidered lamp shades','well-tended courtyard'],
 'All workers and eligible guests in adult scenes are adults. Services, company, lodging, and personal relationships are separate choices; no payment establishes consent to anything else.',[8,12,11]),
11:L(
 'A small theater where professional ambition and community entertainment share costumes, limited money, and the hope of a full room.',
 'The Bellflower grew from a rented hall into a fixed stage. Touring companies improved its reputation; local performers now want work that lasts beyond the next visiting attraction.',
 'A box office leads into a modest auditorium and stage. Rehearsal space, dressing rooms, and the costume loft are backstage and private unless invited.',
 'Afternoons bring rehearsal and repairs. Evenings alternate performances, amateur nights, and quiet closures. After a show, performers may want food, company, or solitude.',
 'Rosalie has received a touring offer that would take her away just as a local company plan becomes financially possible.',
 ['A good offer tests what support between friends actually means.','A damaged costume reveals an unpaid debt between productions.'],
 ['performances','rehearsal visits','music','community productions'],['painted stage flats','patched velvet curtain','gasless oil footlights','crowded costume loft'],
 'Buying a ticket grants audience access. Dressing rooms and rehearsal interruptions require permission; applause creates no personal obligation.',[5,10,35]),
12:L(
 'The Night Kitchen feeds the town when its evening workers finally have time to sit down, with a long table that becomes a second living room.',
 'Alma took over the late menu after a series of indifferent cooks. Her food made the business dependable, and she is negotiating a real partnership rather than an endless promise of one.',
 'A street counter opens to a compact dining room and shared table. The kitchen and stores are staff areas. A back step provides a brief place to cool down.',
 'Preparation begins while the street is quiet. Performers and bathhouse workers eat before shifts; a second rush follows closing elsewhere. Alma has little patience for an elaborate conversation during service.',
 'Her partnership offer assigns responsibility for debts without matching control over purchasing. She understands the problem and is looking for a workable counteroffer.',
 ['A crowded supper brings two former friends to the same table.','A supply shortage gives a young cook a chance to prove an unpopular idea.'],
 ['late supper','staff meals','recipe discussion','shared-table conversation'],['long communal table','steaming pots','chalkless handwritten menu','open back step'],
 'The table is communal; a person’s attention is not. Offer help without entering a crowded kitchen unasked.',[9,1,45]),
13:L(
 'A music hall where callers, musicians, and dancers negotiate crowded floors, uneven skill, and the pleasure of being seen enjoying themselves.',
 'The Junebug began as a barnlike rental hall. Regular dances made it viable, but the owner still spends more readily on decoration than on reliable wages for performers.',
 'The floor is open beneath a high timber roof. Musicians use a raised corner; benches and a refreshment counter line the walls. A staff room holds personal belongings.',
 'Practice and setup occupy late afternoon. Early evening is easiest for beginners, while later sets draw confident regulars. Sunday closures provide time for cleaning and private rehearsal.',
 'Cora has been promised a permanent caller’s share of takings, yet the agreement exists only in letters she has not shown anyone.',
 ['A beginner’s lesson becomes a friendship outside the hall.','A successful event forces a dispute over who earned its proceeds.'],
 ['dancing','lessons','live music','social evenings'],['scuffed dance floor','bright cloth bunting','fiddle corner','wall benches'],
 'A dance invitation can be declined without explanation. Partners check comfort and space; confidence is not permission to pull someone onto the floor.',[10,5,42]),
14:L(
 'A bathhouse providing washing, quiet recovery, and a rare interval when residents can be comfortable without performing competence for their employers.',
 'Blue Glass replaced a makeshift washing business with plumbing that is useful but temperamental. Edith’s careful accounts and maintenance reports have made her essential without yet giving her a share.',
 'Reception leads to separate bookable washing areas and screened resting spaces. Staff control the boiler, linen store, and maintenance access. Privacy boundaries are physical and explicit.',
 'Late mornings are quiet; afternoon bookings follow field work, and evening demand follows performances and travel. A failed valve can rearrange several people’s plans.',
 'Maintenance money has been diverted to decorative improvements. Edith has receipts establishing the decision, but not proof of the owner’s alleged other misconduct.',
 ['A plumbing failure makes a hidden management disagreement public.','Someone leaves a personal letter in a returned linen bundle.'],
 ['bathing','rest','linen service','private conversation in booked space'],['blue glass transoms','copper pipes','linen shelves','screened resting alcoves'],
 'Ordinary bathing is not an invitation to sexual attention. Private bookings and staff areas require appropriate access; found belongings are returned discreetly.',[11,14,8]),
15:L(
 'A gaming room known for controlled manners, attentive dealers, and the distinction between enjoying a risk and pretending consequences do not exist.',
 'The Argosy separated from a rougher saloon to attract steady customers. Felix’s ability to keep a table sociable is central to its reputation; his personal finances are less orderly.',
 'A public lounge leads to staffed card tables. A cashier’s desk and secure store are restricted. A rear room is used for booked private games under house rules.',
 'Afternoons are slow and conversational. Evening games gather regulars and arrivals. Felix is usually working when others assume he is available to amuse them.',
 'Felix owes a personal debt that he has concealed from his partner. The house accounts do not currently show theft or a rigged game.',
 ['A player tries to use a personal debt to influence a dealer.','A disputed game turns on what witnesses actually observed.'],
 ['social card play','spectating','refreshments','conversation between games'],['green cloth tables','well-used cards','brass cashier grille','low hanging lamps'],
 'House games are fictional story activity; no real-money wagering is supplied. Respect a refusal to play, lend money, or continue a conversation.',[35,1,40]),
16:L(
 'An intimate adult salon where Pearl hosts private company, small dinners, and occasional readings for people who prefer a quieter social room.',
 'Pearl leases the rooms independently and shares referrals with Marigold House. Her growing clientele has made the arrangement viable, but renewal terms could undermine that independence.',
 'A reception room leads to a dining salon and individually private rooms. Pearl’s living quarters and business correspondence remain separate from booked space.',
 'Daytime belongs to errands and preparation. Evening appointments are deliberate and limited; a closed door is a boundary, not an invitation to invent a clandestine scene.',
 'Pearl is saving toward a lease with a purchase option. A prospective guarantor expects to be treated as a permanent personal favorite.',
 ['An attractive guarantee carries an unacceptable private expectation.','A quiet dinner allows two people to correct a public misunderstanding.'],
 ['adult social appointments','small dinners','readings','private conversation'],['ribbon-trimmed curtains','small polished dining table','flower bowl','separate private door'],
 'Every appointment is separately agreed. Pearl’s paid work does not establish her personal romantic availability, and guests may leave or decline without owing affection.',[12,8,19]),
17:L(
 'The working ferry joins the town’s banks and makes a journey into a brief shared experience of waiting, weather, and other people’s business.',
 'Samuel’s crew maintained the service through lean years and helped rebuild it after high water. The crossing compact recognizes their work, but the bridge proposal treats their future as a minor cost.',
 'West and east landings share a scheduled service. Waiting rails, a ticket shed, rope gear, and loading ramps organize access. The boat and working gear require crew direction.',
 'Early commuters are impatient, midday customers linger, and evening crossings mix workers with social visitors. High water can reduce or suspend service without changing the canonical river route.',
 'Samuel has a realistic plan to retain a smaller passenger and leisure service after the bridge, but pride has kept him from discussing it with Caleb.',
 ['A missed crossing complicates a promised meeting.','A compensation proposal divides the crew between retirement, new work, and continued service.'],
 ['crossing the river','waiting conversation','river observation','crew work by agreement'],['worn loading ramps','rope drums','ticket shed','cottonwood reflection'],
 'The pilot controls boarding. A familiar face does not overrule river conditions or the needs of other passengers.',[34,37,23]),
18:L(
 'A small clinic where dependable care, crowded hours, and household realities turn abstract town disputes into specific human needs.',
 'Lucía built the practice through house calls and modest fees. The clinic expanded into a courtyard room as patients and local donors supplied money, furniture, and labor.',
 'A waiting room opens to consultation rooms and a private courtyard. Records, medicine stores, and treatment rooms require appropriate permission. The nearby dispensary is a separate workplace.',
 'Routine visits occupy daylight, with urgent work interrupting plans when an authored event calls for it. Lucía’s presence must be checked rather than assumed from an open front door.',
 'A supplier is offering favorable transport rates tied to exclusive purchasing. Accepting would stabilize deliveries while reducing Lucía’s future choices.',
 ['A transport delay exposes the cost of an unreliable crossing.','A patient wants privacy from a well-intentioned relative.'],
 ['appointments','supply deliveries','community health discussion','courtyard conversation off duty'],['shaded waiting benches','wash basin','labeled cupboards','planted courtyard'],
 'Patient information remains private. Fictional clinical scenes offer character and story context rather than medical instructions; work and romance are kept distinct.',[2,17,15]),
19:L(
 'A cooperative washhouse where heavy physical work, exact bookkeeping, and conversation keep half the town present without any one person knowing every secret.',
 'Workers pooled funds after a landlord raised fees. Ruth now helps maintain the cooperative records while the older members decide how much authority to trust her with.',
 'Public receiving counters lead to staffed washing and drying areas. Private collection shelves are labeled; a meeting corner doubles as a place for workers to rest.',
 'The early rush gives way to washing, drying, and afternoon collection. Rain changes the whole workload. Conversations happen during pauses, not while a worker must handle every task at once.',
 'The cooperative is owed several substantial hotel accounts. Ruth wants to publish arrears to members; others fear losing the clients entirely.',
 ['A hotel’s unpaid bill threatens several households.','A misplaced item requires discretion rather than speculation.'],
 ['laundry service','cooperative meetings','deliveries','rest-break conversation'],['steaming tubs','long drying lines','collection shelves','communal accounts book'],
 'Laundry is not evidence of a person’s intimate life. Do not inspect private bundles or treat workers as automatic informants.',[14,11,18]),
20:L(
 'A boardinghouse offering solid meals, modest rooms, and a household rhythm that gives working residents somewhere to return to.',
 'Agnes rebuilt her livelihood after widowhood by renting rooms and feeding travelers. Over time she made the house dependable enough that employers recommend it and workers bring friends.',
 'A common dining room and sitting porch are public to guests and invited visitors. Bedrooms are private; kitchen and account desk are work spaces. Separate rooms are individually assigned.',
 'Breakfast is quick, supper communal, and late arrivals quiet. Agnes notices an absence but does not know its cause until someone tells her.',
 'She has delayed several evictions by drawing on her own repair savings. Her generosity has a limit she finds painful to name.',
 ['A wage delay becomes a household problem.','A departing boarder leaves a useful possession with conflicting instructions.'],
 ['lodging','shared meals','porch visits','household errands'],['long supper table','repaired stair rail','porch rocking chair','numbered room keys'],
 'Being a guest does not grant access to another resident’s room. Help with expenses should preserve dignity and clear terms.',[18,14,43]),
21:L(
 'A riverside market where local growers, household cooks, and travelers negotiate prices alongside recipes, favors, and news.',
 'Stalls returned quickly after the flood, often in different positions. Current rents and access lanes reflect compromises that longtime sellers remember differently.',
 'A central aisle runs between produce stalls and covered service counters. River steps and loading space stay clear. Individual stalls have storage that remains private.',
 'Early buying is practical; late morning becomes social. Afternoons are quieter and can bring discounts, spoiled stock, or arguments about who received the best shipment.',
 'Inés has collected evidence of unequal stall charges. Some differences have ordinary explanations; others appear to favor people close to the association.',
 ['Two sellers organize a fairer allocation of space.','An unusual fruit delivery creates a small festival and a business risk.'],
 ['shopping','produce selling','food discussion','public gathering'],['striped shade cloth','wooden produce crates','river steps','hanging scales'],
 'A seller’s friendliness is part of a public interaction, not proof of private interest. Ask before handling produce or moving a stall’s goods.',[15,9,25]),
22:L(
 'A small riverside chapel and relief hall where worship, music, practical aid, and disagreements about deservingness share the same benches.',
 'The congregation funded the first room; later contributions from across the neighborhood built a relief kitchen used by people of several faiths and none.',
 'The nave opens to a multipurpose hall and shaded yard. Jonah’s office, donation records, and stored relief goods are restricted. The building is modest rather than monumental.',
 'Services and visits vary by day. Adult community meetings and relief work can be busy after ordinary work hours. Quiet periods permit conversation if Jonah is present.',
 'A major donor wants private influence over the relief list. Jonah has postponed answering while depending on the money for winter supplies.',
 ['A donation carries a condition that would exclude a neighbor.','Music brings together people who avoid one another elsewhere.'],
 ['worship','relief work','music','community suppers'],['plain wooden benches','small harmonium','relief kitchen','river-facing windows'],
 'Relief creates no obligation to worship or disclose private beliefs. Confidences and donation records require permission to share.',[36,16,44]),
23:L(
 'A repair yard building and mending small river craft, with room for practical invention and the argument over what work will survive the bridge.',
 'Samuel’s ferry work supported the yard before Caleb began taking independent commissions. Its tools and reputation are partly shared, which complicates every discussion of ownership.',
 'A public waiting rail overlooks covered benches and hauled-out hulls. The timber store, launching slip, and private cottage beyond have separate access.',
 'Daylight work follows materials and river conditions. Quiet finishing work often allows conversation. A launch draws neighbors but requires a controlled working area.',
 'Caleb has designed a shallow-draft passenger boat for a service his father privately also imagines. Each thinks the other would dismiss the plan.',
 ['A joint project reveals how much father and son have misunderstood.','A repaired hull carries traces of an undocumented journey.'],
 ['boat repair','woodworking','launch observation','commission discussions'],['upturned hull','wood shavings','launching slip','hand-drawn boat plan'],
 'Do not step onto an unfinished craft or borrow a vessel without agreement. Craft skill does not make Caleb responsible for every river event.',[37,34,32]),
24:L(
 'A modest dispensary whose careful stock work and supervised service provide a young apprentice with meaningful responsibility.',
 'The shop expanded alongside Lucía’s clinic. Its proprietor uses qualified oversight and works closely with the clinic; Nell handles records and limited assigned tasks while learning.',
 'A customer counter separates public space from labeled stores and a record desk. Controlled supplies and preparation areas are restricted; the back door opens to a service yard.',
 'Daytime demand follows appointments and household errands. Deliveries and inventory occupy quieter hours. Nell has defined duties and does not independently become a physician in conversation.',
 'Nell has found a supplier’s recurring arithmetic error that costs small customers more than large ones. She fears being dismissed as overconfident before anyone checks it.',
 ['An apprentice’s careful observation deserves a fair hearing.','A misplaced order requires help identifying what happened without exposing patient details.'],
 ['supply collection','inventory work','supervised apprenticeship','ordinary conversation'],['labeled drawers','balance scale','clean counter','delivery ledger'],
 'Private health information and controlled stores are restricted. The setting does not supply instructions for preparing or misusing medicines.',[17,2,26]),
25:L(
 'The temporary station makes Calder’s Run’s new connection to distant places tangible through tickets, freight, delays, and people saying goodbye.',
 'A platform and office grew around construction traffic. Its temporary label increasingly irritates workers and businesses who have made permanent lives nearby.',
 'A public platform leads to a ticket counter and waiting room. Dispatch, freight handling, and the track area require staff direction. The rail line ends on the east bank until later story milestones.',
 'Early departures and scheduled arrivals determine the busiest intervals. Nate works dispatch details that most passengers notice only when something fails.',
 'Published connection times include a transfer margin that is unrealistic when the ferry is crowded. Nate has logged the problem without receiving a revised timetable.',
 ['A missed connection becomes a chance meeting or a painful departure.','Workers need accurate public timing more than another optimistic advertisement.'],
 ['travel arrangements','waiting','greetings and farewells','dispatch inquiries'],['timber platform','temporary station sign shape','ticket window','locomotive steam'],
 'Tickets and timing follow current story state. Staff areas and active tracks are not public paths; a timetable is not proof a particular character traveled.',[38,21,33]),
26:L(
 'A telegraph office where a few precise words can move money, change a plan, or reach someone far away, while privacy depends on the people handling them.',
 'The railway connection made the office indispensable to local businesses. Daniel has worked to keep commercial confidentiality credible in a town that expects staff to be useful gossip sources.',
 'A public counter fronts the writing shelf and waiting bench. Instruments, message storage, and the duty desk are staff-only. A small rear room handles maintenance.',
 'Daytime business can be intense; evening traffic includes urgent changes and personal messages. Daniel works a defined shift, and background coverage does not mean he is always present.',
 'Someone has asked him to delay a lawful message until after a land negotiation. He retained the request but has not complied.',
 ['An urgent message competes with pressure from a powerful customer.','A brief telegram is misunderstood because its recipient lacks context.'],
 ['sending messages','collecting messages','waiting conversation','technical discussion'],['telegraph instruments','message slots','writing shelf','thin timber walls'],
 'Message content belongs to the sender and recipient under the office’s rules. Curiosity, friendship, or payment does not authorize disclosure.',[33,19,40]),
27:L(
 'A working survey base where drawings, measurements, practical experience, and corporate instructions do not always agree.',
 'Tess helped organize the camp from a collection of supply tents. Its maps now influence land prices, yet the work behind them remains partly provisional.',
 'A visitor table stands outside the main drawing tent. Equipment racks, survey records, and crew sleeping areas are restricted. Field routes are scheduled separately from the base.',
 'Crews depart early, return with observations, and revise drawings in afternoon light. A person at the camp does not automatically know what a distant crew has discovered.',
 'Tess’s alternate approach meets technical needs while protecting more cultivated land. Its cost estimate is genuine but incomplete until additional ground checks are made.',
 ['A useful field observation challenges a confident plan.','A landowner wants a provisional sketch treated as a final promise.'],
 ['survey discussion','map review by invitation','field preparation','crew meals'],['weighted maps','surveying instruments','striped equipment tent','dusty sample boots'],
 'Provisional drawings are labeled as such. Entry to a field operation requires invitation, time, and suitable access; no casual visitor becomes an engineer by assertion.',[3,39,41]),
28:L(
 'The unfinished bridge is a visible argument about the future, made from demanding work rather than the confident language of a prospectus.',
 'Limited construction permission allowed preliminary works before the full franchise was settled. Crews now face the possibility that revised routing could change months of labor.',
 'A public observation rail sits away from active construction. Material yards, masonry, rigging, and the unfinished span are restricted. The bridge is not a usable crossing at baseline.',
 'Work follows daylight and conditions. Breaks gather tired crews with little patience for theatrical risk. Tom’s assigned jobs change as the project advances.',
 'A delivery substitution has reduced the reliability of a temporary work platform. Tom documented his concern; establishing responsibility requires purchasing records and inspection.',
 ['A young worker decides how to insist on a concern being heard.','Visitors argue about the project while overlooking the people building it.'],
 ['observing construction','authorized deliveries','crew conversations on breaks','public project discussion'],['unfinished span','stacked stone','timber staging','crew water barrels'],
 'Observation space is public; active works are not. A story should reward reporting concerns and respecting skilled work, not invent procedural stunt instructions.',[39,3,38]),
29:L(
 'The railway’s local office combines ordinary freight service with land negotiations whose consequences extend well beyond the building.',
 'Halden secured a substantial office before the station had reliable shelter. Its furniture and punctual correspondence deliberately communicate permanence.',
 'A public counter handles freight business. Appointments lead to a meeting room. Contracts, investor correspondence, and staff records remain private in locked offices.',
 'Mornings are transactional, afternoons negotiated. Evening appointments may be socially polished but remain business unless the participants explicitly choose otherwise.',
 'Halden’s authority to approve the alternative route is narrower than he implies. He needs investor consent and fears losing his local position if he cannot obtain it.',
 ['A negotiator discovers the agent also has a superior to answer to.','A helpful concession is tied to an exclusion hidden elsewhere in the draft.'],
 ['freight booking','business appointments','contract discussion','public information requests'],['large route map','new oak desk','freight scales','locked correspondence cabinet'],
 'Draft terms are not enacted law. Personal charm does not authorize private records, alter a contract, or substitute for freely chosen intimacy.',[40,3,20]),
30:L(
 'A photographic studio where people decide how they want to be remembered and discover how uncomfortable it can be to sit still under someone’s attention.',
 'Clara opened the studio with savings and a loan from Daniel. Its growing trade includes portraits, commercial views, and keepsakes for people preparing to leave.',
 'A daylight portrait room fronts a customer counter. Backdrops and prop chairs are available by agreement. The darkroom, stored negatives, and private correspondence are restricted.',
 'Good light determines appointments. Printing and retouching follow quieter hours. Clara can be socially confident while concentrating and unexpectedly shy once the work is done.',
 'A commercial image documents a survey marker’s earlier position. Clara owns the negative but has not interpreted the possible dispute around it.',
 ['A portrait becomes a difficult gift.','A background detail in an ordinary commission matters to an investigation.'],
 ['portrait sittings','photograph selection','commercial commissions','art discussion'],['large daylight window','folding camera','painted backdrops','drying prints'],
 'A sitting does not grant publication rights or romantic access. Private negatives and images are shared only with appropriate permission.',[19,33,12]),
31:L(
 'An east-bank supply business built around hungry workers, small deliveries, and the determination to make the railhead a neighborhood.',
 'Hazel used a limited family loan to organize the counter and delivery service. Adelaide sees it as useful experience; Hazel intends it to become an independent livelihood.',
 'The public shop and porch face the depot road. A packed store room, loading bay, and workers’ lodging behind have separate access. Personal rooms remain private.',
 'Early commuters buy breakfast supplies and collect orders. Afternoon stock work can become an argument about missing deliveries. The porch is a favored place to wait for an arrival.',
 'Hazel’s loan agreement allows Adelaide to call in the balance after a business disagreement. Neither likes acknowledging what that means for their relationship.',
 ['A young proprietor asks for fair terms from someone who loves her.','A practical delivery solution earns trust across the river.'],
 ['supplies','parcel delivery','porch conversation','small business planning'],['crowded provision shelves','canvas porch shade','delivery baskets','rail-facing bench'],
 'Family connection is not automatic managerial authority. Customers and relatives ask before entering stores or lodging spaces.',[21,38,13]),
32:L(
 'A substantial working ranch whose comfortable house and productive land make independence look effortless to people who do not see its accounts.',
 'The Whitcomb holding grew through work, marriage, purchases, and advantageous water arrangements. Adelaide inherited a business with obligations as well as privilege and expanded it through demanding management.',
 'A visitor gate leads to the office, work yard, and an agreed meeting porch. Grazing land, irrigation equipment, staff housing, and the family house have distinct access.',
 'Livestock and field work begin early. Business fills afternoon; invited suppers reveal a more relaxed household. Adelaide is not necessarily at the house when the ranch is operating.',
 'A smaller neighbor’s access relies on an informal promise Adelaide has treated as revocable. Her public defense of local rights makes the discrepancy politically sensitive.',
 ['A daughter’s independence tests a parent’s generosity.','A neighbor asks that a remembered promise become a written guarantee.'],
 ['ranch business','invited riding','work-yard visits','household supper by invitation'],['broad shaded porch','irrigated pasture','working corrals','well-used ranch office'],
 'The ranch is a workplace and home. Business access never grants family-room or bedroom access; employees have obligations and limits of their own.',[6,21,42]),
33:L(
 'A small schoolhouse whose adult evening classes and community meetings provide a place to ask a question without performing confidence.',
 'Local households built the first classroom together. Eliza now teaches daytime pupils offstage and organizes adult literacy sessions for workers whose schooling was interrupted.',
 'The classroom opens to a shaded yard and a small staff room. Adult companion encounters occur in staff areas or scheduled adult sessions; children’s teaching is background world activity.',
 'Daytime school hours restrict casual visits. Adult classes and community use happen in explicit evening windows. Quiet preparation offers Eliza time she often forgets to protect.',
 'Eliza has applied for funding to continue her own education. She fears residents will treat ambition as evidence that her care for the town was temporary.',
 ['An adult learner wants help without becoming a public example.','A teacher’s opportunity to leave complicates a friendship or romance.'],
 ['adult literacy classes','community meetings','staff appointments','reading'],['plain desks','slate board','shaded schoolyard','crowded book cupboard'],
 'Adult scenes use adult-only sessions or staff areas. Student privacy is protected, and romantic scenes never include minors or their activities.',[22,17,41]),
34:L(
 'A shaded river bend for guided fishing, picnics, swimming when conditions permit, and the feeling of being briefly beyond the town’s demands.',
 'The bend was used before the modern settlement. Lena guides visitors along agreed routes while keeping family places and restricted community knowledge separate from her commercial work.',
 'A public bank and small outfitting shelter lead to designated access points. Private holdings, sensitive banks, and deep-water routes require separate permission and appropriate conditions.',
 'Early fishing gives way to guided outings and late-afternoon leisure. Lena’s presence depends on her actual route; visitors cannot assume she is waiting at the water all day.',
 'A proposed leisure concession would give a single business control over access that several households currently share. Lena has not accepted its offer of a management role.',
 ['A pleasant outing reveals a disagreement over public access.','A guide wants a companion to enjoy silence without demanding an explanation of her heritage.'],
 ['guided fishing','picnics','permitted swimming','river walks'],['cottonwood shade','green shallows','small gear shelter','worn bank path'],
 'Conditions and land access govern activity. A guide’s cultural identity is not a service package, and an outing creates no intimate obligation.',[23,37,25]),
35:L(
 'A practical meeting house beside the headworks, where the flow of water becomes a schedule, a household argument, and occasionally a workable compromise.',
 'The building formalized the 1874 compact. Its ledgers retain old assumptions about holdings that have since divided, changed hands, or become more productive.',
 'A public meeting room and notice board face a shaded yard. The register desk is supervised; gates, measuring points, and equipment require authorized access.',
 'Early water checks and afternoon records lead into occasional evening meetings. Mateo spends part of his day in the field, so an open yard does not establish his presence.',
 'Several inherited priority entries are accurate copies of the compact yet produce unequal modern results. Other disputed entries may actually be copying errors.',
 ['A night diversion forces a debate about need and fairness.','A public meeting has to distinguish an old entitlement from a workable future rule.'],
 ['water-turn inquiries','public meetings','record comparison','cooperative work'],['water-turn board','heavy register','shaded meeting yard','headworks channel'],
 'Observation is different from permission to operate a gate. Record access is supervised, and no private favor alters everyone’s allocation automatically.',[41,6,15]),
36:L(
 'A small dairy and creamery whose demanding early work produces ordinary comforts the town notices most when they are missing.',
 'Several households pooled equipment to process milk reliably. Daisy’s apprenticeship gives her real tasks while experienced workers retain responsibility for the wider operation.',
 'A public collection counter stands apart from animal areas, processing rooms, and cold storage. Staff movement follows cleanliness and work needs.',
 'Work starts before most shops open. Deliveries occupy morning; cleaning and preparation fill later hours. Daisy often has free time when her friends are still working.',
 'Daisy wants to develop a small product line under her own name. She has kept careful trials, but the cooperative expects successful ideas to remain collective property.',
 ['A young worker asks who owns an improvement.','A delayed delivery forces friends to rearrange an anticipated meal.'],
 ['dairy collection','cooperative business','supervised apprenticeship','afternoon conversation'],['milk churns','whitewashed workroom','cool storage shelves','early sun in the yard'],
 'Production rooms require authorization. The location supplies fictional work and social context, not instructions for unsafe food handling.',[24,16,25]),
37:L(
 'A nursery and modest glasshouse where patience becomes visible through cuttings, orchard stock, and flowers residents buy for reasons they may not explain.',
 'The nursery grew from a household orchard. Flora learned through long practice and experiments, then began arguing for crops beyond the familiar varieties preferred by established buyers.',
 'Public rows and a sales bench sit outside the glasshouse. Propagation beds, tools, and experimental stock are staff-only. Paths lead to agreed orchard sections rather than unrestricted valley access.',
 'Early watering and propagation give way to orders and maintenance. Late-afternoon light makes the garden attractive for visitors, but work still comes before a promised stroll.',
 'Flora has proved a hardy graft could help smaller growers. A large buyer wants exclusivity before financing its expansion.',
 ['A promising plant creates a conflict between independence and capital.','A bouquet carries a message its recipient interprets differently.'],
 ['plant buying','orchard discussion','garden walks by invitation','flower selection'],['patched glass panes','labeled saplings','shaded propagation bench','flower rows'],
 'A living plant is not a disposable romantic prop. Ask before picking, taking cuttings, or entering experimental beds.',[25,15,24]),
38:L(
 'The livestock yard mixes practical judgment, competitive display, and the pleasure of knowing an animal well enough to see beyond a sales pitch.',
 'The yard formalized private trades as ranching expanded. Its commission structure favors volume, leaving smaller sellers dependent on a clerk willing to record their animals accurately.',
 'A public viewing rail and office surround controlled pens. Working lanes and loading areas require staff direction. The auction platform is used only during scheduled sales.',
 'Handling and inspection begin early. Sale days draw a crowd; ordinary afternoons are quieter and give Isaac time to practice calling bids and keeping records.',
 'Isaac has identified a pattern in how poor-condition animals are described differently depending on the seller. He needs corroboration before making an accusation.',
 ['A talented young clerk is pressured to flatter an influential seller.','A fair purchase helps someone begin an independent business.'],
 ['livestock viewing','scheduled auctions','stock records','work-break conversation'],['timber pens','auction rail','dusty weighing area','sale ledger'],
 'Animals and working lanes have priority over spectators. Bidding and ownership changes require an explicit fictional agreement.',[42,6,7]),
39:L(
 'A productive silver mine whose public office and surface yard reveal the gap between a profitable enterprise and the households waiting for wages.',
 'The 1881 collapse created a mutual-aid fund and lasting arguments about responsibility. Current crews work with the memory of that event without every shift becoming another catastrophe.',
 'The accessible area contains the checkweighing office, meeting shelter, and designated surface paths. Shafts, hoists, and active workings require specific authorized access.',
 'Early shifts and weighing occupy morning. Paperwork, supply movements, and relief meetings follow. Ben’s job gives him evidence of output and pay, not authority over the entire mine.',
 'A difference between weighing sheets and wage calculations may reflect systematic underpayment. Vera’s independent samples and Agnes’s household accounts can corroborate parts of the pattern.',
 ['A pay discrepancy becomes a collective demand.','A relief decision exposes different ideas of loyalty among workers.'],
 ['surface appointments','weighing records','mutual-aid meetings','authorized deliveries'],['ore wagons','checkweighing window','timber headframe','crew shade shelter'],
 'No casual underground access. Technical danger is treated through credible restrictions and qualified staff, not instructional descriptions of risky acts.',[43,26,18]),
40:L(
 'An independent assay office where patient measurement can determine whether someone has found a livelihood, made a mistake, or been deceived.',
 'Vera established the office to offer an alternative to buyer-controlled testing. Maintaining trust requires both accurate work and the money to remain independent of her largest customers.',
 'The customer counter and sample intake are public. The laboratory, records, and retained samples are restricted. Each accepted sample has an identified chain of custody.',
 'Intake and analysis occupy daylight. Results are discussed at appointments; uncompleted tests remain uncertain. A quiet room gives Vera space to be more personally direct than expected.',
 'Two apparently similar sample lots have inconsistent identifying seals. Vera cannot tell which account is true until the custody record is compared.',
 ['An honest result disappoints a friend.','A mismatched sample becomes evidence only when its handling is established.'],
 ['sample submissions','results appointments','mineral discussion','record comparison by permission'],['sample trays','precise scale','sealed packets','bright laboratory window'],
 'Results belong to the commissioning party under the agreed terms. The pack does not provide chemical procedures or hazardous processing instructions.',[26,29,43]),
41:L(
 'An isolated coach station offering rest, repairs, food, and the unusual intimacy of strangers waiting for the same road to become passable.',
 'The station survived a bypass by serving independent freight and local travelers. Sadie has kept it useful through reliable practical service and a willingness to work with people the railway ignores.',
 'A public waiting room and meal counter face the yard. Stables, stores, route records, and private rooms have separate access. The surrounding road is a travel route, not another room.',
 'Early departures and late arrivals bracket quieter maintenance hours. Bad conditions can extend stays, but those delays must be tied to actual weather and story state.',
 'Sadie has accepted a preliminary offer for scheduled railway feeder work. It would stabilize income while requiring her to stop carrying certain independent consignments.',
 ['A storm-bound evening creates an unexpected friendship.','A sensible contract would force a driver to disappoint people who relied on her.'],
 ['coach travel','meals','shelter','route planning'],['long water trough','coach yard','worn meal counter','road disappearing between bluffs'],
 'Travel requires time and available service. Shared shelter does not force companionship, room sharing, or romance.',[27,7,30]),
42:L(
 'A trading post where remote work becomes possible through credit, information, practical supplies, and a broker who remembers who kept a promise.',
 'Marisol expanded a family supply counter into a freight business. Its customers include small claims, road workers, and households too far from town to bargain effectively with larger merchants.',
 'Public shelves and a business table open to a shaded freight yard. Cargo storage, private correspondence, and living rooms are restricted.',
 'Early loading gives way to bargaining and supply work. Late travelers bring news; Marisol asks what they actually saw before allowing an account to become a fact.',
 'She has covered losses on several indispensable small clients by charging a profitable courier account more. The arrangement is legal within their terms but personally difficult to explain.',
 ['A broker must choose which customer can wait.','A sealed consignment tests how much ignorance someone can reasonably claim.'],
 ['supplies','freight agreements','credit discussions','traveler meals'],['mule shade pens','loaded shelves','large business table','canvas-covered freight'],
 'Cargo and correspondence are private. A broker’s help is an agreement with terms, not ownership over the person receiving it.',[28,30,29]),
43:L(
 'A small independent claim where hope, discipline, and borrowed resources meet a landscape that offers no guarantee of rewarding hard work.',
 'Kit took over the lease after an older prospecting partnership dissolved. The claim has modest evidence of value and a great deal of rumor attached to it.',
 'A visitor shelter and sample table stand beside approved surface workings. Excavations, stored tools, and the private camp require permission. Hazardous areas are not public exploration shortcuts.',
 'Work starts early to avoid the worst heat. Afternoon sorting and records allow conversation, while long supply trips occasionally replace a workday.',
 'Kit’s most exciting sample may have come from material deposited by an earlier owner. She wants to establish its origin before either celebrating or giving up.',
 ['A hopeful find requires an honest test.','A friend offers capital that would change who controls the claim.'],
 ['claim appointments','surface observation','sample discussion','camp meals by invitation'],['red earth','sample table','patched shade shelter','carefully repaired tools'],
 'The claim is a workplace and home. Visitors do not enter workings or remove material without a specific agreement.',[29,26,28]),
44:L(
 'A quiet cemetery and small service office where remembrance is practical work and the town’s history is attached to particular names.',
 'The burial ground expanded after the mine collapse. August works under established undertaking arrangements, maintaining plots, records, and services while learning a difficult trade.',
 'Public paths and memorial plots lead to a service room. Records, tools, and preparation areas are restricted. Family reservations and active ceremonies govern access.',
 'Maintenance and appointments fill daylight. Memorial visits are quiet and variable. August has private hobbies and friendships that do not revolve around other people’s grief.',
 'An old burial register includes a duplicated surname and an uncertain date. It may correct a family story but does not prove a concealed murder.',
 ['A memorial brings estranged relatives or friends together.','An ordinary record error changes how someone understands a loss.'],
 ['memorial visits','history by appointment','grounds work','quiet walking'],['red-stone boundary wall','simple markers','shade tree','carefully kept register'],
 'Ceremonies and mourners take priority. No grave disturbance, voyeuristic preparation-room access, or romantic scene intruding on an active funeral.',[44,36,18]),
45:L(
 'An old relay station that gives independent carriers a place to change animals, leave agreed consignments, and weigh how much they need to know.',
 'The route once served Calder’s original circuit. Railway speculation revived it for deliveries that benefit from flexibility, lower fees, or less attention.',
 'A public receiving bench faces the yard. Assigned cargo bays, animal areas, route records, and Eve’s living room are separately controlled. A private cache is never automatically visible.',
 'Scheduled riders arrive early or late, leaving long intervals for maintenance and ordinary life. Eve is mobile on assigned days rather than mysteriously available everywhere.',
 'Eve has refused one consignment after noticing that its stated owner and delivery instructions conflict. She retained only the authorized receipt, not omniscient knowledge of its contents.',
 ['A refusal tests loyalty within the carrier network.','A route book helps reconstruct a journey without proving its purpose.'],
 ['courier arrangements','animal changes','route discussion','shelter by agreement'],['old freight timbers','numbered cargo bays','water barrel','faded route board'],
 'A delivery agreement specifies what is carried and who may collect it. Private cargo and a rider’s personal history are not public property.',[30,27,28]),
46:L(
 'The Red Sash is a working brothel with a lively downstairs parlor, adult resident workers, and a practical struggle over how its profits and rules should be shared.',
 'The building began as a merchant’s lodging house and changed use as Lantern Row expanded. A nonresident owner collects rent and fees through a management agreement; Sabine and Bess want the resident workers to gain a meaningful say in that agreement.',
 'A public adult parlor and small music area lead to a staffed reception point. Private service rooms require a particular worker’s agreement. Resident bedrooms, the accounts desk, and the back kitchen are not public extensions of the parlor.',
 'Afternoons belong to errands, accounts, and preparation. Evening trade mixes conversation, music, and separately agreed appointments. The household also has ordinary meals, disagreements, friendships, and time away from work.',
 'The lease permits a resident association to submit a purchase proposal, but the owner’s agent has never volunteered that clause. Sabine has found it; financing and collective agreement remain unresolved.',
 ['Two workers seek a fair purchase arrangement without agreeing on how much risk to take.','A patron treats a professional preference as a personal promise and must be answered clearly.'],
 ['adult social company','music','agreed private appointments','resident business meetings'],['red sash above the entry','warm plaster parlor','upright music stand','separate residential stair'],
 'Every worker is an adult with independent choice over clients and services. Paid work does not create personal romantic availability. Bess and Sabine are unrelated coworkers, not siblings.',[48,49,8]),
47:L(
 'Crowcut Hollow is a remote bandit hideout in a side canyon, built around an abandoned freight shelter and the uneasy domestic life of people living beyond ordinary protection.',
 'An old supply shelter outlasted the freight route that justified it. Silas’s small crew now uses it as a refuge. Cole joined after railway work ended and discovered that resentment of an employer does not make robbing other workers harmless.',
 'The authored location contains a rough communal shelter, a stable enclosure, separate sleeping spaces, and a meeting area. Its precise discovery route is story-gated. No public map reveals entry merely because the player has heard the name.',
 'Life alternates repairs, arguments, rest, and planned absences. The bandits are not permanently waiting for a visitor. An invitation to speak can still carry uncertainty and does not grant access to private possessions or command of the crew.',
 'Cole knows that one recent robbery harmed ordinary wage earners after Silas described the cargo as company money. Silas knew the distinction and concealed it from some crew members.',
 ['A bandit must decide whether loyalty requires repeating a wrong he now understands.','Returning property, exposing the truth, negotiating surrender, or leaving each creates different continuing consequences.'],
 ['story-gated meetings','camp conversation','accountability negotiations','ordinary camp work'],['weathered freight shelter','red canyon walls','patched blankets','small stable enclosure'],
 'Entry requires discovery and an authored access state. An invitation to the communal shelter does not open private sleeping spaces or personal papers. Visitors can decline a meeting or leave; romance does not oblige anyone to join the crew.',[46,47,30]),
}
