"""Canonical authoring roster. Numbers identify characters and public places."""
ROSTER = [
 (1,'Virginia “Gin” Maddox',36,'woman',3,9,'Saloon proprietor','Irish American','evening'),
 (2,'Dr. Lucía Salcedo',34,'woman',2,18,'Physician and clinic proprietor','Mexican American','day'),
 (3,'Tess Corbett',28,'woman',2,27,'Railroad surveyor','English American','field'),
 (4,'Iris Keene',27,'woman',2,2,'Printer and newspaper publisher','Scottish American','day'),
 (5,'Rosalie Quinn',21,'woman',3,11,'Theater singer and company organizer','French and Irish American','evening'),
 (6,'Adelaide Whitcomb',42,'woman',3,32,'Ranch proprietor and water negotiator','German American','field'),
 (7,'June Dempsey',22,'woman',3,4,'Horse trainer and express rider','Irish American','field'),
 (8,'Mabel Arnett',47,'woman',3,10,'Proprietor of Marigold House','Black American','evening'),
 (9,'Alma Baptiste',21,'woman',2,12,'Night cook and kitchen partner','Louisiana Creole, Black American','evening'),
 (10,'Cora Dunleavy',19,'woman',3,13,'Dance caller and music-hall performer','Irish American','evening'),
 (11,'Edith Kovač',22,'woman',3,14,'Bathhouse attendant and accounts keeper','Croatian American','evening'),
 (12,'Pearl Merritt',20,'woman',3,16,'Independent courtesan and salon host','English American','evening'),
 (13,'Lottie Fenwick',19,'woman',3,5,'Mercantile buyer and shop assistant','German American','day'),
 (14,'Ruth Freeman',20,'woman',2,19,'Laundress and washhouse cooperative secretary','Black American','day'),
 (15,'Inés Salcedo',19,'woman',3,21,'Produce seller and market organizer','Mexican American','day'),
 (16,'Beatrice Bell',20,'woman',1,6,'Baker and pastry maker','Scottish American','early'),
 (17,'Nell Hewitt',18,'woman',1,24,'Dispensary apprentice','Welsh American','day'),
 (18,'Agnes Reed',39,'woman',1,20,'Boardinghouse proprietor','Black American','early'),
 (19,'Clara Chen',20,'woman',2,30,'Portrait photographer and photographic printer','Chinese American','day'),
 (20,'Esther Wynn',23,'woman',1,3,'Court copyist and petition clerk','German Jewish American','day'),
 (21,'Hazel Whitcomb',18,'woman',3,31,'Provisioner and delivery organizer','German and Irish American','day'),
 (22,'Eliza Morrow',21,'woman',1,33,'Schoolteacher and adult literacy tutor','English American','day'),
 (23,'Lena Velarde',22,'woman',3,34,'River guide and seasonal fishing outfitter','Mescalero Apache and Mexican heritage','field'),
 (24,'Daisy Cartwright',18,'woman',2,36,'Dairy worker and cheesemaking apprentice','English American','early'),
 (25,'Florence “Flora” Vale',19,'woman',3,37,'Nursery grower and orchard propagator','Hungarian American','early'),
 (26,'Vera Sutter',25,'woman',1,40,'Assayer and independent mineral analyst','Swiss American','day'),
 (27,'Sadie Rusk',22,'woman',3,41,'Coach-station keeper and driver','Scottish and Irish American','field'),
 (28,'Marisol Duarte',31,'woman',3,42,'Trading-post proprietor and freight broker','Mexican American','day'),
 (29,'Kit Calloway',20,'woman',3,43,'Independent prospector and claim worker','English American','field'),
 (30,'Evelyn “Eve” Mercer',21,'woman',2,45,'Relay keeper and private courier','Irish American','field'),
 (31,'Marshal Elias Reddick',41,'man',2,7,'Town marshal','English American','day'),
 (32,'Gabriel Soto',31,'man',3,8,'Farrier and wagon repairer','Mexican American','day'),
 (33,'Daniel Chen',30,'man',2,26,'Telegraph operator and office supervisor','Chinese American','day'),
 (34,'Samuel Pike',50,'man',1,17,'Ferry operator and river pilot','Black American','early'),
 (35,'Felix Avery',24,'man',3,15,'Cardroom dealer and gaming-room partner','French American','evening'),
 (36,'Reverend Jonah Bell',37,'man',1,22,'Minister and relief-fund organizer','Scottish American','day'),
 (37,'Caleb Pike',20,'man',3,23,'Boatwright and repair-yard worker','Black American','day'),
 (38,'Nathaniel “Nate” Brooks',22,'man',2,25,'Station clerk and freight dispatcher','English American','early'),
 (39,'Thomas “Tom” Archer',21,'man',3,28,'Bridge rigger and masonry apprentice','Irish American','field'),
 (40,'Victor Halden',46,'man',3,29,'Railroad land and freight agent','German American','day'),
 (41,'Mateo Varela',27,'man',2,35,'Irrigation steward and water-turn recorder','Mexican American','field'),
 (42,'Isaac Booker',19,'man',1,38,'Stock handler and auction clerk','Black American','field'),
 (43,'Benjamin “Ben” Crowell',22,'man',2,39,'Mine checkweigher and crew representative','Cornish American','early'),
 (44,'August Renn',18,'man',1,44,'Cemetery keeper and undertaker’s assistant','German American','day'),
 (45,'Rafael Ortiz',20,'man',3,1,'Hotel night clerk and guest liaison','Mexican American','evening'),
 (46,'Cole Hensley',22,'man',2,47,'Bandit and former railway laborer','English American','field'),
 (47,'Silas Quade',29,'man',2,47,'Bandit crew leader and former freight foreman','Irish American','field'),
 (48,'Bess Kincaid',21,'woman',3,46,'Brothel sex worker and evening entertainer','Scottish American','evening'),
 (49,'Sabine Roche',26,'woman',3,46,'Brothel sex worker and resident accounts representative','French American','evening'),
]

PLACES = [
 (1,1,'Calder House Hotel','calder-house-hotel','hotel','00:00','24:00'),
 (2,1,'Keene’s Print Shop','keenes-print-shop','print shop','08:00','20:00'),
 (3,1,'County Courthouse','county-courthouse','courthouse','08:00','18:00'),
 (4,1,'Dempsey Livery','dempsey-livery','livery stable','05:00','21:00'),
 (5,1,'Crown & Cotton Mercantile','crown-and-cotton','general store','07:00','20:00'),
 (6,1,'Hearthstone Bakery','hearthstone-bakery','bakery','05:00','18:00'),
 (7,1,'Marshal’s Office','marshals-office','law office','00:00','24:00'),
 (8,1,'Soto Forge','soto-forge','forge and repair yard','07:00','19:00'),
 (9,2,'Copper Mare Saloon','copper-mare-saloon','saloon','12:00','02:00'),
 (10,2,'Marigold House','marigold-house','adult companionship house','15:00','02:00'),
 (11,2,'Bellflower Theater','bellflower-theater','theater','12:00','24:00'),
 (12,2,'Night Kitchen','night-kitchen','restaurant','16:00','03:00'),
 (13,2,'Junebug Dance Hall','junebug-dance-hall','dance hall','16:00','01:00'),
 (14,2,'Blue Glass Baths','blue-glass-baths','bathhouse','10:00','24:00'),
 (15,2,'Argosy Cardroom','argosy-cardroom','cardroom','14:00','02:00'),
 (16,2,'Ribbon Room','ribbon-room','adult private salon','16:00','24:00'),
 (17,3,'Pike’s Ferry','pikes-ferry','ferry crossing','05:00','22:00'),
 (18,3,'Salcedo Clinic','salcedo-clinic','clinic','08:00','19:00'),
 (19,3,'Public Washhouse','public-washhouse','washhouse','06:00','19:00'),
 (20,3,'Boatmen’s Boardinghouse','boatmens-boardinghouse','boardinghouse','05:00','23:00'),
 (21,3,'River Market','river-market','market','06:00','19:00'),
 (22,3,'Riverside Chapel','riverside-chapel','chapel and relief hall','07:00','21:00'),
 (23,3,'Pike Boatworks','pike-boatworks','boat yard','07:00','19:00'),
 (24,3,'Cottonwood Dispensary','cottonwood-dispensary','dispensary','08:00','19:00'),
 (25,4,'Temporary Passenger Depot','temporary-passenger-depot','rail depot','05:00','23:00'),
 (26,4,'Telegraph Office','telegraph-office','telegraph office','06:00','23:00'),
 (27,4,'Survey Camp','survey-camp','survey base','06:00','20:00'),
 (28,4,'Bridge Works','bridge-works','construction works','06:00','19:00'),
 (29,4,'Railroad Freight Office','railroad-freight-office','freight and land office','08:00','19:00'),
 (30,4,'Calder Portrait Studio','calder-portrait-studio','photographic studio','08:00','19:00'),
 (31,4,'Eastbank Provisioners','eastbank-provisioners','supply store','06:00','20:00'),
 (32,5,'Whitcomb Ranch','whitcomb-ranch','working ranch','06:00','20:00'),
 (33,5,'Orchard Schoolhouse','orchard-schoolhouse','school and adult classroom','08:00','20:00'),
 (34,5,'Cottonwood Swimming Bend','cottonwood-swimming-bend','river recreation','06:00','21:00'),
 (35,5,'Irrigation Meeting House','irrigation-meeting-house','water cooperative','06:00','21:00'),
 (36,5,'Valley Creamery','valley-creamery','dairy and creamery','05:00','18:00'),
 (37,5,'Orchard Glasshouse','orchard-glasshouse','plant nursery','05:00','19:00'),
 (38,5,'Cattle Sale Yard','cattle-sale-yard','livestock yard','06:00','19:00'),
 (39,6,'Saint Agnes Mine','saint-agnes-mine','silver mine','05:00','19:00'),
 (40,6,'Assay Office','assay-office','mineral laboratory','08:00','19:00'),
 (41,6,'Widow’s Cut Coach Station','widows-cut-coach-station','coach station','05:00','22:00'),
 (42,6,'Mule Camp Trading Post','mule-camp-trading-post','trading post','06:00','21:00'),
 (43,6,'Red Wells Prospect','red-wells-prospect','independent claim','06:00','19:00'),
 (44,6,'Canyon Rest Cemetery','canyon-rest-cemetery','cemetery','07:00','19:00'),
 (45,6,'Old Calder Relay','old-calder-relay','courier relay','05:00','22:00'),
 (46,2,'The Red Sash','red-sash-brothel','brothel','16:00','02:00'),
 (47,6,'Crowcut Hollow','crowcut-hollow','bandit hideout','00:00','24:00'),
]

DISTRICTS = [(1,'Main Street','main-street'),(2,'Lantern Row','lantern-row'),(3,'River Ward','river-ward'),(4,'The Railhead','the-railhead'),(5,'Cottonwood Valley','cottonwood-valley'),(6,'Cinder Bluffs','cinder-bluffs')]

# Shared residences have separately identified private rooms; district nodes and
# homes are never counted as one of the 45 public places.
HOMES = [
 ('hotel-rooms',1,'Calder House staff and rented rooms',[4,13,20,31,35,40,45]),
 ('lantern-court',9,'Lantern Court upstairs lodgings',[1,5,9,10,11,12]),
 ('marigold-residence',10,'Marigold House proprietor’s flat',[8]),
 ('clinic-courtyard',18,'Salcedo courtyard household',[2,15,17]),
 ('boatmen-rooms',20,'Boatmen’s resident rooms',[14,18,33,43]),
 ('pike-cottage',23,'Pike river cottage',[34,37]),
 ('eastbank-rooms',31,'Eastbank workers’ lodging',[3,19,21,38,39]),
 ('whitcomb-house',32,'Whitcomb ranch house',[6]),
 ('valley-cottages',35,'Valley cottages with separate households',[16,22,23,24,25,36,41,42]),
 ('livery-cottage',4,'Livery cottage and separate forge room',[7,32]),
 ('bluff-lodgings',42,'Mule Camp and coach-station rooms',[26,27,28,29,30,44]),
 ('red-sash-residence',46,'The Red Sash private resident rooms',[48,49]),
 ('crowcut-camp',47,'Crowcut Hollow separate sleeping spaces',[46,47]),
]
