# These are shared, authored relationship facts, not automatically inferred
# mutual affection. The build emits two directed records per unique pair.
EXTRA_TIES = [
 (1,8,'district leadership','Gin and Mabel helped organize a shared lamp-maintenance fund and now disagree over whether owners should cover a larger share.'),
 (1,16,'neighborly exchange','Beatrice sends the saloon a celebration pastry after a good commission; Gin remembers to return the tray herself.'),
 (1,31,'working respect','Gin and Elias can resolve an ordinary disturbance through a quiet conversation, but she insists that respectable customers face the same rules as everyone else.'),
 (2,23,'trusted local contact','Lucía values Lena’s local travel observations and asks rather than assuming she is available to escort every urgent visitor.'),
 (2,28,'supply negotiation','Lucía and Marisol maintain a dependable clinic supply arrangement and disagree when a generous exception threatens the next delivery.'),
 (2,11,'care and discretion','Edith helped organize clean linens for the clinic; Lucía treats any personal care she provides as private, not district news.'),
 (3,19,'observational friendship','Tess and Clara enjoy comparing what a measured drawing and a photograph can each reveal or conceal.'),
 (3,34,'crossing knowledge','Samuel gives Tess practical accounts of the ferry’s seasonal limits and expects the survey to treat his observations seriously.'),
 (3,44,'quiet companionship','Tess and August share an interest in patient sketching and can sit together without turning silence into an obligation to speak.'),
 (4,9,'late supper regulars','Iris eats after press work at Alma’s counter; Alma will discuss a public argument but will not trade customers’ confidences for a mention in the paper.'),
 (4,36,'public disagreement','Iris and Jonah debate whether a carefully worded public appeal can conceal an unfair condition, then occasionally share breakfast anyway.'),
 (5,19,'creative collaboration','Rosalie trusts Clara to choose a portrait with her rather than turn a publicity sitting into someone else’s idea of glamour.'),
 (5,24,'unexpected friendship','Daisy supplies cream for theater refreshments and has become an honest listener for Rosalie’s songs in progress.'),
 (6,26,'qualified advice','Adelaide values Vera’s ability to say a sample proves less than a seller claims, even when the caution spoils a promising investment.'),
 (6,18,'civic friction','Adelaide and Agnes agree that the town needs stable housing and disagree about how much property owners should contribute to keeping it stable.'),
 (7,23,'outdoor friendship','June and Lena enjoy riding together on suitable ordinary routes and defend each other’s right to refuse a badly planned outing.'),
 (7,13,'shop friendship','Lottie keeps track of durable fabric June can afford, while June insists that a practical purchase may still deserve a handsome color.'),
 (8,14,'different kinds of ownership','Mabel and Ruth compare an established business with a cooperative still being built; each notices a kind of work the other has sometimes undervalued.'),
 (8,34,'longstanding neighbors','Mabel and Samuel remember several versions of the town’s prosperity and share an ability to puncture a grand prediction with a small remembered fact.'),
 (9,33,'off-duty refuge','Daniel finds Alma’s ordinary supper conversation a relief from messages that always seem urgent; she is interested in his reading rather than his customers.'),
 (9,24,'supply friendship','Alma and Daisy test dairy products for the kitchen and agree that the person who did the work should receive the credit.'),
 (10,25,'creative friendship','Flora helps Cora decorate the hall with suitable nursery cuttings, and Cora offers a dance lesson in return rather than assuming free supplies.'),
 (10,45,'late-hour friendship','Cora and Rafael meet during the overlap between a closing hall and an active hotel desk, trading harmless stories and saving food for each other.'),
 (11,17,'practical friendship','Nell and Edith share an interest in useful systems and enjoy admitting the small mistakes they would rather not describe in front of an employer.'),
 (11,28,'hard bargaining with affection','Marisol and Edith negotiate linen and repair supplies briskly and then ask after one another’s sleep.'),
 (12,4,'privacy and public words','Pearl has asked Iris to distinguish reporting on a business from speculating about the private lives of the women who work there.'),
 (12,16,'ordinary regulars','Pearl buys Beatrice’s bread on the same quiet morning each week; their conversation is usually about books or food, not either person’s reputation.'),
 (13,19,'a shop imagined','Clara has offered to photograph Lottie’s proposed displays if the new shop becomes real, without requiring it to look wealthier than it is.'),
 (13,42,'mutual encouragement','Lottie and Isaac understand being trusted with responsibility while someone else receives the public credit.'),
 (14,15,'neighborhood organizing','Ruth and Inés organize shared deliveries when useful and argue over whether a small immediate bargain distracts from a larger change.'),
 (14,44,'careful records','August helps Ruth compare public dates relevant to a mutual-society claim, respecting the difference between a record and a family story.'),
 (15,25,'grower friendship','Inés sells Flora’s ordinary nursery stock at the market and insists that enthusiasm for an experiment should not become a promise it will succeed.'),
 (15,45,'neighborly hospitality','Rafael directs late arrivals toward the next day’s market, and Inés makes sure the night clerk can collect food after the early rush.'),
 (16,22,'reading friendship','Beatrice joins Eliza’s adult reading circle and sometimes brings a recipe merely because she likes the language used to describe it.'),
 (17,44,'patient companionship','Nell and August share walks and books without assuming that mutual quiet must conceal either romance or distress.'),
 (18,49,'household accounting','Agnes and Sabine exchange practical ideas about reserves and resident privacy while keeping each household’s individual accounts separate.'),
 (19,41,'recording change','Clara asks Mateo which visible water changes are ordinary before captioning a photograph as evidence of a crisis.'),
 (20,26,'respect for uncertainty','Esther and Vera enjoy exact questions and have learned that an honestly unfinished answer can be more useful than a neat one.'),
 (20,37,'public process made ordinary','Caleb asks Esther how to obtain a public form for a possible venture; she helps him understand the process without turning into his unpaid business manager.'),
 (21,39,'east-bank friendship','Hazel and Tom like the feeling of building something local and disagree cheerfully about whether her shop sign or his architectural drawing will be finished first.'),
 (21,25,'small-enterprise solidarity','Hazel wants useful plants for the provisioner’s porch; Flora asks to be paid for the trial rather than promised exposure.'),
 (22,33,'reading correspondence','Daniel and Eliza exchange reading recommendations and the pleasure of discussing something that arrived by post without being urgent.'),
 (22,48,'performance and literacy','Bess brings a comic lyric to the adult reading group; Eliza treats its rhythm and word choice as work worth discussing.'),
 (23,27,'professional route knowledge','Lena and Sadie coordinate ordinary travel when the river changes, with each retaining authority to cancel her own part of a plan.'),
 (23,47,'a refused demand','Lena refused Silas’s request to treat his grievance as a claim on her guiding work; he knows she will name coercion plainly.'),
 (24,42,'work friendship','Daisy and Isaac enjoy discussing animals more than the people currently trying to sell them and are learning to claim credit publicly.'),
 (24,37,'unlikely design critics','Caleb sketches equipment improvements for Daisy; she is delighted when one solves a real problem and unimpressed when it is merely clever.'),
 (25,29,'optimists with different evidence','Flora and Kit enjoy one another’s ambition and frequently ask the other to separate a promising observation from a guaranteed fortune.'),
 (26,33,'careful transmission','Vera and Daniel value the small discipline of copying a figure correctly and meet socially to discuss almost anything except figures.'),
 (26,31,'evidence without theater','Elias relies on Vera to explain the limits of an assay in a disputed-property case; she will not inflate a result to help him close it.'),
 (27,35,'a familiar traveler','Felix often wants a late seat on Sadie’s coach; she enjoys his company and requires the same booking terms she gives other travelers.'),
 (28,48,'supply customer and friend','Bess and Marisol turn a clothing delivery into an animated discussion of colors, travel, and the difference between an invitation and a sales pitch.'),
 (29,39,'ambition and craft','Kit and Tom compare drawings of futures they cannot yet afford and are each useful at noticing where the other has skipped a practical step.'),
 (29,46,'old acquaintance with a limit','Kit knew Cole as an ordinary worker and will speak with him about returning to work; she has not agreed to hide him or store disputed property.'),
 (30,34,'relay and river','Eve and Samuel share practical transfer information and a fondness for travelers whose first claim is that they are never late.'),
 (30,45,'after-hours coordination','Rafael and Eve arrange ordinary late parcel collection through the public desk, preserving the recipient’s control of private correspondence.'),
 (31,36,'institutional friendship','Elias and Jonah discuss the difference between mercy and an unaccountable exception; their friendship survives an argument neither regards as settled.'),
 (32,42,'skills and recognition','Gabriel has taught Isaac simple equipment assessment appropriate to the sale yard and encourages him to charge fairly for skilled work.'),
 (32,49,'repair contract','Sabine asks Gabriel for a written repair estimate for the Red Sash, and he treats her as the resident representative authorized to decide.'),
 (34,38,'two kinds of timetable','Samuel and Nate coordinate a ferry and railway connection while refusing to pretend that weather will obey a printed hour.'),
 (35,47,'former cardroom acquaintance','Felix knew Silas in ordinary freight days and remembers his charm; that history gives him no current knowledge of the hideout or the theft.'),
 (35,49,'professional social boundaries','Sabine and Felix can enjoy cards and conversation while recognizing the different ways a customer may mistake paid attention for a personal claim.'),
 (36,44,'care for living people','Jonah and August coordinate memorial requests and believe the living family should choose what private history is told.'),
 (37,45,'young working neighbors','Caleb and Rafael make plans that fit an early yard and a late hotel shift, occasionally settling for breakfast and laughing at the difficulty.'),
 (38,43,'workplace comparison','Nate and Ben compare the frustration of being expected to repair a system with careful records alone.'),
 (39,41,'bridge and water','Tom asks Mateo how construction affects ordinary turns and learns that local work continues beyond the crew’s visible project.'),
 (40,8,'courteous rivalry','Victor and Mabel can enjoy the same music while negotiating fiercely over what a thriving evening district owes the railway.'),
 (40,4,'scrutiny and charm','Victor gives Iris polished public explanations and finds that she prints the qualification as prominently as the promise.'),
 (41,49,'collective decisions','Mateo and Sabine recognize the problem of keeping shared accounts without deciding for everyone whose interests appear in them.'),
 (42,46,'a damaged good memory','Isaac remembers Cole helping with an awkward freight job and wants a truthful account of the theft before offering a recommendation.'),
 (43,48,'ordinary closing-time company','Ben and Bess sometimes meet at Alma’s counter and are relieved when the subject is music rather than either person’s work.'),
 (44,49,'books without urgency','Sabine and August exchange books through the adult reading group and appreciate a recommendation that does not demand immediate improvement.'),
 (45,48,'evening-work friendship','Rafael and Bess trade practical news about released performance times and late suppers without sharing guests’ or clients’ private arrangements.'),
]

KINSHIP = [(2,15,'aunt and adult niece'),(6,21,'mother and adult daughter'),(19,33,'adult siblings'),(34,37,'father and adult son'),(16,36,'adult niece and uncle')]

def extend_world(world):
    world['CHAPTERS'].extend([
      ('The houses on Lantern Row',
       'The district contains several different businesses. Marigold House is Mabel’s established house of adult company and hospitality, with a long local history. The Ribbon Room is Pearl’s independent appointment salon. The Red Sash is a distinct brothel with a public parlor, separately agreed private appointment rooms, and resident housing. Its two named workers, Bess Kincaid and Sabine Roche, are unrelated colleagues. They retain individual control over appointments and personal earnings while sharing agreed house costs. Other staff remain background adults, not additional companion records.\n\nThe Red Sash’s ordinary life matters: rehearsal in the parlor, breakfast taken late, flowers that need changing, a dress repaired before work, a disagreement over the roof, and a resident who wants a free evening. Its lease creates a story about property and collective decision-making. Bess also wants to make audiences laugh; Sabine wants a life in which being dependable is one quality rather than her entire role. Either may enjoy her occupation and still want different terms. Their friendship can survive different choices about the house.\n\nPersonal romance develops through a separate, mutual invitation. Professional charm, an appointment, and a private relationship are three different facts. A character’s occupation does not assign her to the player, establish a sibling relationship, or require a story about being redeemed by leaving sex work. Public parlor scenes can be warm, flirtatious, theatrical, or contentious. Any sexual activity remains off page in this authoring bible.'),
      ('Beyond the old freight shelter',
       'Crowcut Hollow occupies an abandoned loading shelter in a side canyon of Cinder Bluffs. The town can know there are bandits in the hills without knowing where their supper table stands. The hideout is a visitable story location, not an unlocked destination on the initial public map. Its image is domestic as well as dangerous: laundry near old freight boards, an uneven table, animals needing care, an argument that cannot be ended by walking into the next town street.\n\nCole Hensley and Silas Quade are the two named bandits. Silas leads a small background crew; Cole joined after railway work ended. Their shared grievance has reached a breaking point over stolen workers’ wages. Silas knew the consignment’s nature before the theft. Cole learned afterward and retained a receipt. Neither becomes harmless because his motives are understandable. The people harmed have names, bills, and independent judgments in the rest of the world.\n\nThe first approach can happen through Cole at the Old Calder Relay, without entering the hideout. An arranged meeting, voluntary disclosure, return of property, exposure, restitution, surrender, or refusal to help can move the story. No route requires the player to join the crew. Crowcut access is granted by saved story state and may later close for a stated reason. Cole and Silas can leave the location through authored transitions; a change in allegiance or legal status must update their schedules and public descriptions together.'),
      ('A week with room for ordinary pleasure',
       'Recurring life gives a newcomer reasons to return even while the large disputes remain unresolved. Sunday supper gathers the River Ward. The market, reading circle, rehearsal, dance practice, forge meal, and Red Sash music evening each bring together people with different jobs and different levels of patience for being interrupted. A recurring event is an opportunity, not a demand that the same dramatic reveal repeat every week. A used clue stays known; a corrected account stays corrected.\n\nWork continues when a named character takes a day away: background staff, a reduced service, or an appointment book can explain the difference. A place being open does not imply its named companion is present. Characters can travel, take a break, refuse a visitor, attend an event, or invite someone into a private room. Baseline schedules describe a saved starting week; plot milestones, agreed dates, weather, and specific appointments can produce explicit overrides.\n\nThe best small scenes leave space for interpretation. A second cup has been set out. Someone remembers the food the player disliked. A joke lands badly and can be repaired. Two friends disagree and still save one another a seat. The town does not need a new emergency every time a relationship grows.')
    ])
    for f in world['FACTIONS']:
        if f['slug']=='lantern-business-circle': f['members'].extend([48,49])
    world['FACTIONS'].append(dict(slug='crowcut-crew',name='Crowcut Crew',seat=47,members=[46,47],publicAim='Survive outside the established freight economy and preserve the crew’s independence.',resources='Shared shelter, ordinary transport experience, personal loyalty, and disputed property.',fracture='Cole’s remorse over the payroll theft conflicts with Silas’s demand that loyalty protect the crew’s chosen account.',privatePressure='The retained receipt and Silas’s own note establish different knowledge at different times.',offer='A morally difficult relationship, a chance to hear an unpolished account of railway work, and an opportunity to support restitution or withdrawal.',cost='Association creates mistrust; aid involving disputed property may deepen harm. The player may decline involvement.'))
