WORLD = {
 'name': "Calder's Run", 'slug':'calders-run', 'year':1888,
 'tagline':'The river made the town. The railroad wants to own it.',
 'description':"A river-crossing town in the territorial Southwest, where a new railroad, an old water bargain, and the people caught between them turn work, desire, and everyday loyalties into consequential adventures.",
 'relationshipFantasy':"Arrive with your own reasons, find people worth staying for, and decide what kind of life you can build together while the town changes around you.",
 'centralQuestion':"When belonging gives you something to lose, what will you do to keep it without owning the people you love?",
 'era':"An original, historically inspired 1888 frontier. The fictional county, companies, municipal compact, river, and local legal procedures belong to this world; they are not claims about a real jurisdiction's law.",
 'geography':"A fictional river basin inspired by southern New Mexico and the adjoining Southwest. Red sandstone uplands drain into the Calder River, a dependable but variable stream with a short irrigated valley. Main Street and Lantern Row occupy west-bank terraces. River Ward slopes to the ferry. The Railhead is on the east bank. Cottonwood Valley extends upstream to the north. Cinder Bluffs rises south and southwest.",
 'population':4800,
 'launchSeason':'Late summer moving toward the autumn freight season',
 'genreTags':['historical Western','frontier community','outlaw adventure','romance','labor and land','reputation','mature drama'],
 'visualContext':{'palette':['sun-warmed ochre','brick red','cottonwood green','faded indigo','cream plaster','brass','lamplit amber'], 'hero':"An elevated view along a lively west-bank street toward a green river, the unfinished bridge, and an east-bank locomotive. Red bluffs define the horizon. The town contains working yards, planted courtyards, painted storefronts, ordinary pedestrians, and warm rooms visible at dusk.", 'portraitRule':'One adult character, one pose, occupation-specific clothing and background, no collage, no text, no logo; appearance diversity must remain faithful to each identity.'},
 'clock':{'dayOfWeekZero':'Sunday','scheduleTimezone':'user_local','diegeticYear':1888,'progression':'Weekdays and dayparts follow the user-local simulation clock. Major plot transitions follow saved story milestones, not a global countdown that expires while the player is away.'},
 'spiceDefinition':{
 '1':'Reserved romantic expression and patient courtship. Affection grows through repeated acts, explicit invitations, and trust; low spice never means childlike, naïve, or unavailable for a meaningful relationship.',
 '2':'Warm, responsive attraction with playful suggestion once interest is mutual. Emotional openness, privacy, and relationship history determine pace.',
 '3':'Confident, frank, or adventurous romantic expression. Initiative and chemistry remain character-specific; high spice never establishes consent, overrides a refusal, or turns every exchange into flirtation.'},
 'spiceAllocation':{'3':24,'2':15,'1':10,'requestedPercentages':{'3':50,'2':30,'1':20},'actualPercentages':{'3':48.979592,'2':30.612245,'1':20.408163},'rounding':'After the requested four additions, 49 × 50/30/20% gives 24.5/14.7/9.8. Largest-remainder rounding yields 24/15/10.'},
 'ageAllocation':{'18-22':29,'23-50':20,'women18to22':21,'men18to22':8},
 'scopeHistory':'The original request specified 45 characters, 30 women, and 45 matched public places. The subsequent explicit additions bring the final scope to 49 characters, 32 women and 17 men, plus 47 visitable places (46 with public frontage and one gated hideout) and 6 district nodes. Two male bandits and two unrelated female brothel workers are additional full companions.',
 'assets':{'status':'not_generated','heroKey':'calders-run-hero','rule':'All portrait, home, district, and place prompts are authoring slots. No generated image or production media readiness is claimed.'},
}

CHAPTERS = [
 ('The town people choose to stay in', """At first light the town smells of bread, damp rope, wood smoke, and horses. Freight crews argue over scales while women carrying market baskets walk around them without breaking conversation. The river is an inconvenience, an employer, a public meeting place, and the reason anything was built here. Late in the day, shade moves across the boardwalks and people begin using the streets for pleasure. A cheap meal can last two hours because three people join the table. A rehearsal runs late. Someone offers a ride home and means several possible things by it.

Calder's Run became a permanent settlement around Amelia Calder's freight-and-ferry circuit in 1859. Travelers called that route Calder's Run before they called the settlement a town. The official founding story begins with her crossing. The land's history does not: Indigenous travel routes, seasonal gathering, and older Mexican households and irrigation work precede it. Those histories persist in present claims, skills, relationships, and memories. Calder's Run is one community on that landscape, not the owner of its entire past.

By 1888, the town's prosperity depends on three movements: ore down from the bluffs, food and cattle out of the valley, and goods across the river. None works reliably alone. A mine payroll supports the theater; theater wages pay a rooming-house bill; that proprietor purchases milk from a valley family whose wagon needs the forge. Most residents understand this interdependence through particular people rather than speeches about economics.

The player may become useful, admired, desired, resented, comfortable, or compromised. There is space to be a friend, worker, investigator, lover, mischief-maker, or quiet regular. A newcomer is never assigned a criminal past, trauma, gender, or romantic orientation. Their reasons for arriving belong to them. The world supplies opportunities and consequences without dictating an identity."""),
 ('The bridge bargain', """The Arroyo & Western Railway has reached the east bank. Its temporary depot carries passengers and selected freight, while the permanent bridge remains unfinished. Victor Halden is seeking a twenty-five-year municipal franchise covering the new bridge, the expanded waterworks, and a west-bank freight easement. The company would finance construction, guarantee a limited period of published rates, and take over maintenance that the town has repeatedly postponed.

The proposal has real benefits. Medical supplies could arrive regularly. Mines could move ore more cheaply. Travelers could come without an uncertain ferry transfer. Eastbank workers need durable jobs, and a new depot could support businesses of their own. Halden also wants compensation exceptions, a restrictive freight-routing clause, and the right to reduce service to unprofitable users. These details are evidence to discover and negotiate, not things every resident already knows.

The existing crossing compact is equally complicated. The ferry and public water headworks are held under an 1874 local agreement administered through town trustees and the valley association. Long-standing families enjoy priority water turns. Smaller growers trade favors for exceptions. Samuel's crew has secured rights against casual replacement, but some fees disadvantage workers who live across the river. Adelaide can sincerely defend local control while benefiting from unequal arrangements.

Tess has identified an alternative bridge approach that would protect more cultivated land but increase construction costs. A workable settlement could combine public access guarantees, shared oversight, revised routing, and compensation. Another could give the company extensive control. A collapse of negotiations could preserve bad local arrangements while forcing some residents to leave. The story is about competing outcomes and specific costs. No faction possesses the single morally correct answer to every question.

At launch, the bridge bargain is pending. The world does not announce an unavoidable deadline every time a player returns. A public hearing, survey disclosure, negotiation, and final vote become available through saved story progress. Construction milestones alter routes and business prospects while preserving people and the town as an ongoing setting."""),
 ('Founding, memory, and the disputed past', """The town has three incompatible ideas of its origin. The hotel mural credits Amelia Calder and a handful of commercial backers. River Ward families remember communal rebuilding after the 1872 flood. The valley remembers orchards, gathering routes, and irrigation work that the mural treats as scenery. These are not interchangeable accounts: the archive can establish some dates, while an elder's memory may describe labor that was never recorded.

Calder was a capable organizer who charged steeply when freight was plentiful and waived debts when a stranded party could not pay. Her descendants are no longer active local powers. Her fame has become useful to people arguing positions she never encountered. Her surviving route book is a historical object, not a master key proving every claim in the county. Its omissions matter as much as its pages.

The 1872 flood displaced households, damaged the ferry, and destroyed a section of early county records. Rebuilding created an emergency water arrangement that later hardened into privilege. Some discrepancies in the register are deliberate; others reflect hurried copying, lost maps, inconsistent spellings, and the difficulty of measuring a riverbank that moved. A convincing investigation must distinguish fraud from ordinary uncertainty.

The 1881 shaft collapse at Saint Agnes created the miners' mutual fund. Survivors disagree about whether its practical compromises protected jobs or protected owners. The 1885 dry summer turned water shares into household politics. Last year's rail survey raised property prices before many tenants knew an expansion was planned. These events give older residents memories and younger residents inherited obligations. The younger cast has adult experience of its own; it does not exist merely to discover its parents' scandals."""),
 ('Institutions and the shape of power', """A five-seat municipal council handles the fictional town's local franchises, maintenance, and business rules. Only two seats are represented by named companions at launch: Adelaide holds the valley seat and Mabel the licensed-business seat. The other seats are background offices rather than additional interactive characters. Recorded council outcomes must be authored story state. A generated conversation cannot create a surprise sixth seat or give one councilor unilateral authority.

The courthouse stores property copies, petitions, probate records, and hearing notices. Esther prepares documents and can explain their local procedural meaning; she cannot invent a judgment or promise that a petition wins. Elias keeps order within the town and coordinates with county authority outside it. His badge permits questioning and specified local duties, not mind-reading, arbitrary intimacy, or access to every private room. Public notices distinguish an accusation, a warrant, and a conviction.

The association allocates water turns using a disputed register. Mateo maintains the day-to-day record, Adelaide negotiates for major users, and small growers increasingly organize together. The miners' mutual society provides relief and representation through dues. Ben keeps its current grievances; Agnes knows what unpaid wages do to households. The railway employs people who can support the project while opposing Halden's tactics.

Marigold House is a licensed adult business in this fictional town. The Ribbon Room is a separate independent salon that rents its premises and cooperates on referrals. Mabel and Pearl have a commercial agreement, not an ownership relationship over one another. Sex workers choose their clients and services. Characters may be close friends, rivals, or romantic interests outside work without turning fees, protection, lodging, or employment into personal entitlement.

The relay network carries ordinary letters and small consignments alongside goods whose owners want to avoid fees or attention. Marisol brokers freight; Eve manages a relay; Sadie knows routes; June occasionally rides for extra income. Each has a different understanding of the operation. Membership does not confer knowledge of every shipment or make every member an outlaw. Elias's accommodations are narrow, undocumented, and increasingly vulnerable to abuse."""),
 ('Work, money, food, and dependence', """The local fictional economy uses dollars and cents, plus individually recorded tabs, invoices, and disputed company credit. Company credit is redeemable only at participating businesses and can leave a worker unable to pay a landlord who wants cash. A wage promise, a debt, and a gift are distinct records. Economic amounts below are game-world anchors for coherent dialogue, not historical purchasing-power research or real financial advice.

A plain meal usually costs 15–30 cents, a better supper 50–90 cents, and a simple boarding bed about 35–60 cents for a night. A private hotel room can run $1–2; a day of hired horse use roughly $1–3 depending on the animal and purpose. Ordinary day work often earns $1–2 in this fictional economy, while skilled or dangerous work can pay more. Prices vary by service and scarcity. They are not an automatic shopping subsystem, and character wealth never converts into Kivelli subscription or credit balances.

The rich have land, credit, access to transport, or control over a bottleneck. Comfortable tradespeople own tools and a reliable customer base. Wage workers can have good weeks and no cushion. Independence might mean owning a sewing machine, two sound horses, a small press, or a lease without a hostile renewal clause. Every character has a concrete idea of what enough would look like.

Meals keep the social world connected: bread and preserves, beans and stew, roasted meat when available, dairy products, seasonal produce, and recipes carried through different households. Alma experiments with supper dishes; Inés argues for better market variety; Beatrice keeps affordable bread available after more profitable orders. Food descriptions should belong to particular people and kitchens rather than representing an entire culture with one dish.

Labor continues behind the picturesque frontage. Water must be carried or piped, lamps cleaned, dishes washed, horses rested, repairs done, and clothing dried. The most useful invitations often begin with an ordinary task. Helping may create gratitude and familiarity. It does not automatically create debt, friendship, or romance."""),
 ('Faith, custom, class, and community', """Jonah's chapel is a small Protestant congregation with a relief hall used more broadly than its services. Lucía and Inés carry Mexican family Catholic traditions into private life, though their observance differs. Esther maintains her Jewish identity and household practices without being assigned the job of educating everyone she meets. Other residents are devout, skeptical, irregularly observant, or simply attached to funerals, music, and shared meals. Faith influences choices; it does not reveal hidden facts.

Lena's Mescalero family connections extend beyond Calder's Run. Her routes, kinship, work, and loyalties belong to a living community with interests of its own. No sacred ceremony, invented translation, mystical racial ability, or confidential tribal knowledge is a purchasable attraction. The local history acknowledges dispossession and constrained choices without making every encounter a lesson or every Indigenous character an interpreter. Her guide work and attraction develop through her particular personality.

The community includes Black households, Mexican and Mexican-American families, Chinese workers and merchants, and migrants with several European backgrounds. The setting recognizes discrimination and unequal access through specific institutions and conflicts. Generated everyday dialogue does not default to slurs or compulsory harassment. People also joke, flirt, make music, cooperate, disagree, and lead ordinary complicated lives within and across these communities.

Respectability is contested. A church donor can be a cruel employer. A courtesan can be a reliable neighbor. A well-dressed arrival can be broke. Paid companionship, a previous marriage, unconventional dress, or public affection do not establish virtue or vice. Household labor and the practical consequences of gossip make reputation matter differently to different people.

Local habits are small and usable: a dry board is offered to someone arriving with wet boots; a borrowed tool is returned cleaned; ferry crews are allowed to eat before being asked for one more crossing; empty chairs are not assumed to be invitations. At community suppers, bringing something matters more than its cost. These customs can be broken, misunderstood, explained, or gently teased about. They should provide conversation, not a checklist of automatic punishments."""),
 ('Weather, movement, and the limits of access', """Late summer is hot in exposed places and cooler by the river after dusk. A storm can turn a dry wash into a temporary obstacle and make a quiet crossing difficult. Dust affects workshops, washing, photographic work, and patience. High water changes ferry availability; heat changes work hours. Weather creates practical choices and altered meetings without becoming a daily disaster.

Within a district, most public places are several minutes apart. The west-bank center and River Ward connect by sloping streets. River crossings depend on the ferry until the bridge is completed in saved story state. A place on the opposite bank is never treated as the next room. Valley and bluff journeys require sufficient time and sometimes a horse, guide, or scheduled coach. The content pack supplies a travel matrix and arrival buffers for schedule transitions.

Business hours describe visitor access. Workers may prepare or close outside those hours when their schedule specifies authorized duty. Private rooms, workshops, mine workings, construction areas, and the dispensary's controlled stores have separate access. Seeing someone leave a location does not imply permission to follow home. A location's street-facing public space may remain visible when its service is closed.

The schoolhouse operates daytime teaching in the background. Companion interactions there use adult staff areas or the authored adult evening class. Young students are never companion records, participants in romantic scenes, or props for adult content. The adult cast ranges from 18 to 50; age is explicit and stable.

District geography and weather rules are practical foundations for story. They prevent a character from being at a remote claim, a court hearing, and a late supper at once. Cancelled plans are opportunities for believable repair: a note, an explanation, a new invitation, or a favor passed through a known intermediary."""),
 ('A voice for Calder’s Run', """Use clear, original period-flavored English. The setting is 1888, but dialogue should be readable. Rhythm, subject matter, restraint, vocabulary, and personal habits carry the era more effectively than distorted spelling. Characters do not all call strangers partner, talk about whiskey, draw a weapon, or speak in proverbs. Education, occupation, household, and temperament create different voices.

Gin often offers a concrete option while making the listener comfortable enough to answer honestly. Tess distinguishes observation from assumption. June speaks quickly when interested and becomes more precise when her competence is questioned. Elias gives people room to correct themselves. Esther chooses the accurate word and can be funny about everyone else's impatience. Rosalie is socially bold and privately economical. Their voices should remain recognizable even when the subject is breakfast.

A reply starts from what the person is doing, what was said, what they know, and what they want. They can volunteer a thought, make a practical offer, tease, disagree, become distracted, or end a conversation because work calls. A question should be specific and useful. Several exchanges may pass without one. Characters are allowed to misunderstand; they should revise an opinion when new evidence reaches them.

Secrets have owners and discovery paths. An accusation stays an accusation until corroborated. A stranger cannot receive the town's entire history on arrival, and a friendly conversation does not reveal every private truth. Rumor may travel only through a plausible source. Group scenes apply knowledge and relationships to each participant separately; no character becomes a narrator for someone else's mind.

Spice affects expression and initiative after reciprocal interest. It does not determine intelligence, morality, occupation, or loyalty. A reserved person may be decisive and deeply passionate; a bold person may be shy about asking someone to stay for breakfast. Characters can pursue friendships, rivalries, and ordinary plans with the same depth as romance. Adult themes are part of the setting, and the authored bible expresses relationship dynamics without scripting graphic sexual scenes."""),
 ('Reputation, attachment, and continuing stories', """Reputation is a set of relationships and communicated claims. The player can be trusted by the ferry crew, disliked by a ranch office, admired by theater workers, and unknown to a miner. A private act changes the people involved. A witness can share an account with a reason, audience, and degree of certainty. Public printing can spread a claim widely, but printed text is not automatically truth.

Rumors track what was alleged, who observed or heard it, how it reached a listener, and whether later evidence corrected it. A secret promised to one person is not globally stored as common knowledge. Reconciliation requires recognition of the specific harm and a change in behavior. Gifts cannot erase betrayal, and romance cannot compel a person to abandon work, beliefs, or friends.

Every relationship can develop through repeated meetings: recognition, familiar routines, earned trust, shared responsibility, attraction if mutual, and chosen commitment. Friendship has its own rewards. A new room key, a preferred seat, a borrowed instrument, a business introduction, or an invitation to a family meal can matter as much as a dramatic confession.

Story arcs have several endings and continuing consequences. Someone can leave temporarily, return from a tour, lose a contract, gain a partner, or alter their work schedule. The town remains usable afterward. The bridge can open without ending the ferry crew's personal stories; a failed business can lead to new work rather than silently deleting a character. Baseline state, each evidence item, and each unlocked change are defined separately.

The content is designed for conversations and location visits. It supplies opportunities to observe, join, ask, refuse, leave, negotiate, or investigate. It does not require a combat engine, a real-money gambling product, or a new numerical economy to tell its stories. Any eventual mechanics should preserve these authored relationships and the player's ability to decline."""),
]

TIMELINE = [
 ('Before 1859','Routes before the town','Indigenous movement, older Mexican households, small-scale cultivation, and local irrigation precede the freight settlement. Specific communities have continuing interests; the river is not empty land awaiting discovery.'),
 ('1859','Calder’s Run','Amelia Calder organizes a reliable freight-and-ferry circuit. The route lends its name to the settlement; the ferry book begins as a practical business record.'),
 ('1864','Silver in the bluffs','Commercial workings expand at what becomes Saint Agnes. Supply yards and modest lodging follow the workers.'),
 ('1868','A permanent Main Street','Brick businesses replace several temporary fronts. A public reading room becomes the first court-record office.'),
 ('1872','The high-water year','Flooding damages River Ward and destroys a portion of county records. Collective rebuilding creates both solidarity and disputed obligations.'),
 ('1874','The crossing compact','A local trusteeship formalizes ferry maintenance, public headworks, and registered water turns. Emergency advantages become durable privileges.'),
 ('1877','Lantern Row expands','A theater, larger saloon rooms, and independent adult businesses make evening trade a substantial employer.'),
 ('1881','The Saint Agnes collapse','A shaft failure kills and injures workers. The miners’ mutual-aid fund forms; contemporary liability remains contested.'),
 ('1883','The relay revival','Older freight routes return to use as private couriers exploit demand for cheaper and less scrutinized transport.'),
 ('1885','The dry summer','Low water exposes inequalities in the allocation register. Small growers begin sharing copies of schedules and delivery receipts.'),
 ('1887','Survey stakes','Railway surveying raises land prices and rental speculation before many affected tenants know the likely route.'),
 ('1888','The east-bank terminus','The temporary depot opens. Bridge work begins under limited construction authority; the full franchise remains undecided.'),
]

FACTIONS = [
 {'slug':'arroyo-and-western','name':'Arroyo & Western Railway','seat':29,'members':[3,21,33,38,39,40], 'publicAim':'Complete a profitable through-route and establish reliable services.', 'resources':'Capital, freight contracts, surveying, outside suppliers, and access to investors.', 'fracture':'Workers and engineers can support construction while opposing land speculation or labor practices.', 'privatePressure':'The investors want dependable earnings before authorizing the expensive alternative approach.', 'offer':'Employment, introductions, transport, supplies, and a credible future for east-bank businesses.', 'cost':'Dependence on a company able to change rates, terminate contracts, or bypass local suppliers.'},
 {'slug':'valley-water-association','name':'Valley Water Association','seat':35,'members':[6,15,23,24,25,41,42], 'publicAim':'Keep water usable and local agriculture viable.', 'resources':'Turn registers, headworks crews, cultivated land, livestock, and council influence.', 'fracture':'Established holdings receive advantages that smaller growers want revised.', 'privatePressure':'A bad season will expose members who promised more water than they can deliver.', 'offer':'Local knowledge, work, household introductions, and support for independent ventures.', 'cost':'Pressure to defend neighbors even when their claims are unfair.'},
 {'slug':'miners-mutual','name':'Saint Agnes Mutual Society','seat':39,'members':[14,18,26,28,29,43,44], 'publicAim':'Honest weighing, timely wages, practical safety, and relief for affected households.', 'resources':'Dues, work records, collective labor, supply relationships, and neighborhood trust.', 'fracture':'Some members favor accommodation to preserve jobs; others believe delay costs lives.', 'privatePressure':'The relief fund cannot absorb another long interruption of wages.', 'offer':'Solidarity, useful work, testimony, and access to a community that notices who helps.', 'cost':'Public association can strain business ties and expose internal disagreements.'},
 {'slug':'town-compact','name':'Town Compact and Civic Offices','seat':3,'members':[4,6,8,17,20,22,31,36], 'publicAim':'Keep the settlement governable and preserve public services.', 'resources':'Records, public hearings, notices, licenses, relief work, and limited law enforcement.', 'fracture':'Order, fairness, prosperity, and institutional survival point toward different choices.', 'privatePressure':'Several officials rely on informal exceptions they would struggle to defend publicly.', 'offer':'Legitimate procedures, introductions, protection of records, and public recognition.', 'cost':'Working through institutions means delay, compromise, and accountability.'},
 {'slug':'lantern-business-circle','name':'Lantern Business Circle','seat':9,'members':[1,5,8,9,10,11,12,13,19,35,45], 'publicAim':'Keep the evening economy independent, solvent, and attractive.', 'resources':'Customers, performance, hospitality, private rooms, and information from voluntary conversation.', 'fracture':'Owners, employees, independent workers, and landlords have different ideas of a fair bargain.', 'privatePressure':'Rising rents could dismantle profitable businesses without reducing demand for their work.', 'offer':'Warmth, friendship, employment, introductions, and a place to build a social life.', 'cost':'Loyalty can mean taking sides in a friend’s dispute or losing a lucrative patron.'},
 {'slug':'old-road-network','name':'Old Road Carriers','seat':45,'members':[7,23,27,28,29,30,32,37], 'publicAim':'Keep goods and people moving beyond the expensive main crossing.', 'resources':'Riders, animals, caches, repair skills, alternate routes, and household trust.', 'fracture':'Ordinary delivery, fee evasion, and serious theft are different undertakings that some brokers blur.', 'privatePressure':'An increasingly valuable sealed consignment threatens the network’s narrow tolerances.', 'offer':'Work, mobility, practical assistance, and a chance to help people bypass a bottleneck.', 'cost':'Incomplete information, disputed cargo ownership, and exposure to accusations by association.'},
]

DISTRICT_LORE = {
 1:{'summary':'The west-bank commercial terrace, where the town puts on its public face and conducts the business everyone eventually needs.', 'history':'Permanent brick arrived after the first silver profits. Shopkeepers widened the boardwalks while moving older stalls downhill. The courthouse occupies an expanded reading-room building, and its piecemeal construction is visible from the alley.', 'sensory':['warm brick after sunset','horse tack and fresh bread','press machinery behind an open window'], 'rhythm':'Freight and shopping dominate morning; court business and repairs fill afternoon; hotel balconies and supper visits soften the evening.', 'fault':'Public frontage suggests stability while rents and credit determine who can remain behind it.', 'ritual':'Shop staff exchange small change and errands before the first coach arrival.', 'weather':'Dust gathers in doorways; runoff makes the lower steps slippery after rain.', 'story':'A disputed public notice can connect the press, courthouse, marshal, and hotel without any one worker knowing the whole story.'},
 2:{'summary':'The evening district, with music, good food, paid companionship, bathing, cards, and people whose labor lets others relax.', 'history':'Temporary drinking rooms gave way to purpose-built businesses when miners began receiving regular pay. Adult establishments and theaters funded improvements that more respectable neighbors also use.', 'sensory':['piano heard through two different walls','lamp oil and kitchen onions','washed linen in an upstairs corridor'], 'rhythm':'Late mornings belong to staff and deliveries. Rehearsal and preparation grow into crowded evenings; closing-time meals create their own community.', 'fault':'The people who attract customers may have the least control over leases and working conditions.', 'ritual':'After a difficult night, staff send a plate from the Night Kitchen to the business still closing.', 'weather':'Open windows cool crowded rooms; storms trap strangers together and dampen musical instruments.', 'story':'A changed lease, a touring offer, and a lucrative patron divide people who usually protect one another.'},
 3:{'summary':'The old working slope to the river, full of shared services, boarding rooms, small trades, and accumulated memory.', 'history':'The flood erased several streets but not their households. Rebuilt walls contain salvaged material; the headworks and ferry compact are part of family history.', 'sensory':['damp rope','soap and sun-dried cloth','food carried down a boardinghouse stair'], 'rhythm':'Early departures, clinic and market business, afternoon repairs, and communal supper create frequent encounters across occupations.', 'fault':'Improvement schemes describe the ward as inefficient while depending on its cheap rooms and labor.', 'ritual':'People leave dry boards near doors for arrivals with wet boots.', 'weather':'High water directly changes work and travel; summer shade makes the ward a refuge from hotter streets.', 'story':'A delayed ferry, unpaid wages, and a shortage at the clinic reveal whose needs a new transport system actually serves.'},
 4:{'summary':'The east-bank terminus, where temporary structures, demanding work, and speculative confidence compete to define the future.', 'history':'Last year’s survey camp is already a depot, supply street, office compound, and growing settlement. Its residents resent being treated as visitors to the west-bank town.', 'sensory':['coal smoke','fresh-cut timber','telegraph clicks through a thin wall'], 'rhythm':'Dispatch and deliveries begin early. Survey and bridge crews move through daylight; correspondence and repairs continue after passenger activity slows.', 'fault':'The railway speaks as one institution while its employees have different wages, risks, and long-term prospects.', 'ritual':'The day’s first passenger arrival is checked from the provisioner’s porch with mugs in hand.', 'weather':'Wind exposes temporary buildings; high water can strand workers away from friends and appointments.', 'story':'An alternative survey route forces the people building the bridge to ask who gets to decide what progress costs.'},
 5:{'summary':'The cultivated river corridor, with orchards, grazing, workshops, family homes, and disagreements that travel through irrigation channels.', 'history':'Several patterns of cultivation precede the modern town. The water register overlays older practices imperfectly, and later ranch consolidation has never settled every claim.', 'sensory':['cut grass beside dry earth','milk pails and shade cloth','moving water behind a locked gate'], 'rhythm':'Animals and irrigation require early work; afternoons shift toward repair and household business; evening brings adult lessons, porch visits, and shared meals.', 'fault':'Local independence can conceal dependence on a neighbor’s gate, money, or permission.', 'ritual':'At the first cool evening after a hot spell, households bring food to the meeting-house yard.', 'weather':'Heat changes tasks and swimming conditions; a distant storm can alter river access without rain falling locally.', 'story':'A night water diversion can be an act of desperation, advantage, or both, and solving it does not by itself settle allocation.'},
 6:{'summary':'The southern mining country and old road, with small claims, industrial workings, relay stations, and communities beyond easy supervision.', 'history':'Commercial silver connected scattered routes and camps. The 1881 collapse left a mutual society, a cemetery expansion, and unresolved arguments about responsibility.', 'sensory':['ore dust on cuffs','mules shifting under shade','wind through an abandoned loading frame'], 'rhythm':'Mining and travel start early. Supply exchanges fill midday; late arrivals gather at stations and trading rooms before the roads become difficult.', 'fault':'Independence often depends on credit, an accurate assay, a working animal, or someone willing to carry a message.', 'ritual':'A returned traveler is offered water before being asked for news.', 'weather':'Exposed routes become slow in heat and unsafe during sudden runoff; night travel requires an authored purpose.', 'story':'A borrowed horse and disputed mineral sample can link the livery, couriers, miners, and distant households.'},
}

SOURCES = [
 {'label':'Vharadren original world bible','url':'library:libfile_6f76cb4730b481919ae43d6f49786dd9','use':'Structural benchmark: 45 characters, 30 women, 45 public places, 6 districts, 1,890 schedule rows, 12 arcs, and authored retrieval layers.'},
 {'label':'Vharadren current repository generator','url':'https://github.com/tmoney2390test/kiveli-ai/blob/main/scripts/generate-vharadren-content.mjs','use':'Checked current integration expectations. Its expanded roster and world-specific age/identity assertions must not be copied into this new world.'},
 {'label':'National Park Service — Chinese Labor and the Iron Road','url':'https://www.nps.gov/gosp/learn/historyculture/chinese-labor-and-the-iron-road.htm','use':'Period texture: Chinese railway labor, surrounding communities, and the exclusion and violence affecting them. Individual Calder’s Run characters are fictional.'},
 {'label':'Mescalero Apache Tribe — Our Culture','url':'https://mescaleroapachetribe.com/our-culture/','use':'Community-authored reference for Mescalero identity and reservation history. No tribal ritual or private cultural knowledge has been invented as a game mechanic.'},
 {'label':'National Park Service — American Latino Theme Study: Business and Commerce','url':'https://www.nps.gov/articles/latinothemebuisness.htm','use':'Regional context for Mexican and Mexican-American commercial life in the Southwest.'},
 {'label':'National Park Service — Women Who Went to the Klondike','url':'https://www.nps.gov/articles/klgo-klondike-women.htm','use':'A later-period comparison for women’s mining, lodging, and restaurant enterprises; not evidence that a particular fictional 1888 career was typical.'},
]
