import type{LocationLore,LocationType}from'../types';

export function locationSeedLore(input:{world:string;district:string;name:string;description:string;category:string;type:LocationType;activities:string[];atmosphere:string[];sensory:string[];weather:string[]}):LocationLore{
  const residence=input.type==='residence',outdoor=['outdoor','landmark','district','transit'].includes(input.type),nightlife=/bar|club|lounge|night|music|cabaret/i.test(input.category);
  const layout=residence?['controlled arrival threshold','shared or guest-facing room','private areas available only through established access']:outdoor?['recognizable arrival approach','primary gathering or viewing area','quieter edge shaped by weather and distance']:['recognizable public entrance','primary activity area','quieter edge suited to conversation or observation'];
  const activityNotes=Object.fromEntries(input.activities.map((activity)=>[activity,residence?`${title(activity)} requires invitation and established co-presence.`:outdoor?`${title(activity)} depends on weather, light, and the current crowd.`:`${title(activity)} fits best when it follows the place's current operating rhythm.`]));
  return{version:2,authored:true,summary:input.description,atmosphere:[...input.atmosphere,nightlife?'energized after dark':'grounded in repeat routines'],sensoryDetails:[...input.sensory,`${input.name} carries the particular textures of ${input.description.toLowerCase()}`],signatureDetails:[`${input.name} is especially associated with ${input.activities[0]??input.category}.`,`${title(input.activities[1]??input.activities[0]??input.category)} changes how the place feels outside its busiest period.`,`Its identity remains tied to ${input.district}.`],layout,crowdRhythm:{morning:nightlife?'The public room is quiet, cleaning, or resetting.':'Workers and regulars establish the practical rhythm.',afternoon:nightlife?'Preparation begins before the main crowd arrives.':'The place reaches its clearest working rhythm.',evening:nightlife?'Arrivals and social attention make the room more performative.':'Workday traffic gives way to people with time to linger.',late_night:residence?'The setting is private and available only through established access.':nightlife?'Regulars, staff, and the least hurried guests define the room.':'Only late operations or explicitly established scenes remain.',overnight:residence?'This is private residential time.':'The place is closed or limited to essential workers unless authored hours say otherwise.'},conversationHooks:[`How ${input.activities[0]??input.category} changes between quiet and busy periods.`,`What regulars notice first about ${input.name}.`,`Whether ${input.activities[1]??input.activities[0]??input.category} is better planned or spontaneous.`],stableFacts:[`${input.name} is in ${input.district}.`,input.description],localEtiquette:[residence?'Entry requires an invitation or canonical shared scene.':'Follow posted access rules and the current activity’s pace.',residence?'Never imply the user is inside from remote conversation alone.':'Do not invent private or staff-only access from familiarity alone.'],publicHistory:[`${input.district} gives ${input.name} its local context and social rhythm.`],recurringPeople:[{label:'place regulars',role:'workers, neighbors, and repeat visitors',rhythm:'Their routines give the place continuity across different scenes.'}],activityNotes,accessNotes:[residence?'Private access requires an invitation or canonical shared scene.':outdoor?'Weather and local closing conditions may limit access.':'Do not assume access to staff-only or private areas.'],weatherNotes:input.weather,storySeeds:[`A routine ${input.activities[0]??input.category} visit at ${input.name} reveals a character-specific decision.`]};
}

function title(value:string){return value.replace(/[_-]+/g,' ').replace(/^./,(letter)=>letter.toUpperCase());}
