begin;

alter table public.together_worlds add column if not exists world_role text not null default 'home', add column if not exists social_rhythm text not null default 'balanced', add column if not exists dominant_dayparts text[] not null default '{}', add column if not exists relationship_themes text[] not null default '{}', add column if not exists activity_families text[] not null default '{}', add column if not exists mobility_style text not null default 'mixed', add column if not exists weather_profile jsonb not null default '{}'::jsonb;
alter table public.together_worlds drop constraint if exists together_worlds_world_role_check; alter table public.together_worlds add constraint together_worlds_world_role_check check(world_role in('home','destination','hybrid'));
alter table public.together_worlds drop constraint if exists together_worlds_social_rhythm_check; alter table public.together_worlds add constraint together_worlds_social_rhythm_check check(social_rhythm in('quiet','relaxed','balanced','busy','always_on'));
alter table public.together_worlds drop constraint if exists together_worlds_mobility_style_check; alter table public.together_worlds add constraint together_worlds_mobility_style_check check(mobility_style in('walkable','transit','car','mixed'));

create table if not exists public.together_world_familiarity(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,continuity_id uuid not null references public.together_continuities(id) on delete cascade,world_id uuid not null references public.together_worlds(id) on delete cascade,visit_count integer not null default 0 check(visit_count>=0),total_minutes integer not null default 0 check(total_minutes>=0),discovered_location_ids uuid[] not null default '{}',shared_location_ids uuid[] not null default '{}',favorite_location_ids uuid[] not null default '{}',people_met_template_ids uuid[] not null default '{}',first_visited_at timestamptz,last_visited_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(continuity_id,world_id));
create table if not exists public.together_relationship_places(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,character_instance_id uuid not null references public.together_character_instances(id) on delete cascade,location_id uuid not null references public.together_locations(id) on delete cascade,visit_count integer not null default 0 check(visit_count>=0),first_visited_at timestamptz,last_visited_at timestamptz,meaning_summary text,moment_ids uuid[] not null default '{}',metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(character_instance_id,location_id));
create table if not exists public.together_trips(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,continuity_id uuid not null references public.together_continuities(id) on delete cascade,character_instance_id uuid not null references public.together_character_instances(id) on delete cascade,world_id uuid not null references public.together_worlds(id) on delete restrict,lodging_location_id uuid references public.together_locations(id) on delete set null,status text not null default 'planning' check(status in('planning','upcoming','traveling','visiting','returning','completed','cancelled')),starts_at timestamptz,ends_at timestamptz,arrived_at timestamptz,departed_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists together_trips_continuity_time_idx on public.together_trips(continuity_id,status,starts_at); create index if not exists together_relationship_places_character_idx on public.together_relationship_places(character_instance_id,visit_count desc);
alter table public.together_world_familiarity enable row level security; alter table public.together_relationship_places enable row level security; alter table public.together_trips enable row level security;
drop policy if exists "Users read own together_world_familiarity" on public.together_world_familiarity; create policy "Users read own together_world_familiarity" on public.together_world_familiarity for select using(auth.uid()=user_id); grant select on public.together_world_familiarity to authenticated;
drop policy if exists "Users read own together_relationship_places" on public.together_relationship_places; create policy "Users read own together_relationship_places" on public.together_relationship_places for select using(auth.uid()=user_id); grant select on public.together_relationship_places to authenticated;
drop policy if exists "Users read own together_trips" on public.together_trips; create policy "Users read own together_trips" on public.together_trips for select using(auth.uid()=user_id); grant select on public.together_trips to authenticated;
alter table public.together_trip_templates add column if not exists world_id uuid references public.together_worlds(id) on delete cascade, add column if not exists lodging_location_id uuid references public.together_locations(id) on delete set null;

update public.together_entitlements set tier=tier where tier in('kivelle_plus','kivelle_max');
comment on column public.together_worlds.world_role is 'Home worlds support normal residence/routine simulation; destination worlds are primarily trip-scoped.';
comment on table public.together_trips is 'Continuity-scoped travel lifecycle. A trip changes temporary place/schedule context without rewriting character identity.';
commit;
