-- Authored possibilities, never authored companion lines or automatic outcomes.
-- Each seed row produces one dialogue opportunity and one co-present scene beat.

create temporary table kivelle_depth_seed(
  world_slug text,slug text,topic text,angle text,beat_title text,beat_seed text,location_slug text,
  tags text,triggers text,min_stage text,max_stage text,content_level text,min_spice integer,required_fact_slug text,required_story_slug text,
  interaction_type text,op_modes text,beat_modes text,required_participants integer,maximum_participants integer,
  dayparts text,activity_tags text,weight numeric,cooldown_turns integer,cooldown_hours integer,metadata jsonb
) on commit drop;

insert into kivelle_depth_seed values
-- Juniper City (25 opportunities + 25 beats)
('juniper-city','real-date','What counts as a real date in Juniper','Whether ordinary intention matters more than labels or expense.','Clarify the date','The shape of the outing creates a natural opening to clarify whether either person considers it a date.',null,'dating|expectations','real date|is this a date','acquaintance',null,'romance',1,null,null,'relationship_choice','remote|co_present|active_date','co_present|active_date',1,2,'','date|conversation',1.2,18,24,'{}'),
('juniper-city','sunday-market-serious','Why the Sunday market can feel more serious than nightlife','Whether being included in an ordinary routine signals growing commitment.','An ordinary invitation','A routine errand could be shared, creating room for an invitation without assuming the user accepts.','common-market','market|routine|commitment','sunday market|weekend routine','friend',null,'romance',1,'juniper-sunday-market-serious',null,'social','remote|co_present|active_plan','co_present|active_plan',1,2,'morning','market|errands|shopping',1.1,24,24,'{}'),
('juniper-city','pre-exclusivity-expectations','Dating multiple people before exclusivity','What honesty and expectation-setting require before commitment.','Expectation check','The conversation has room for one person to ask directly what exclusivity would mean without declaring it. ',null,'dating|exclusivity|honesty','dating multiple|exclusive|expectations','flirting',null,'romance',1,'juniper-pre-exclusivity',null,'relationship_choice','remote|co_present|active_date','co_present|active_date',1,2,'','conversation|date',1.2,20,36,'{}'),
('juniper-city','velvet-discretion','Velvet Hour''s reputation for discretion','Whether anonymity feels protective or suspicious.','A little privacy','The room and staff behavior create more privacy than expected, leaving the companion free to use or ignore it.','velvet-hour','privacy|nightlife','velvet hour|discreet|private booth','acquaintance',null,'standard',1,'juniper-velvet-discretion',null,'privacy','remote|co_present|active_date','co_present|active_date',1,3,'evening|late_night','drinks|conversation|nightlife',1.2,24,18,'{}'),
('juniper-city','velvet-raid','The infamous Velvet Hour raid','Whether discretion protects people or lets institutions avoid accountability.','A disputed history','Something in the venue recalls the old raid, creating an opening for the companion''s own view of privacy and transparency.','velvet-hour','history|privacy|scandal','velvet hour raid|raid','friend',null,'standard',1,'juniper-velvet-raid',null,'history','remote|co_present|story','co_present|active_date|story',1,3,'evening|late_night','drinks|history|conversation',1,30,72,'{}'),
('juniper-city','recording-boundary','Juniper''s rules against intimate recording','How consent changes when a phone or camera becomes visible.','Camera boundary','A visible phone or camera creates a natural chance to clarify comfort without assuming anyone records or objects.',null,'law|privacy|consent','record|camera|private photo','acquaintance',null,'mature',2,'juniper-intimate-recording-law',null,'privacy','remote|co_present|active_date','co_present|active_date',1,2,'','photo|conversation|date',1.3,24,48,'{}'),
('juniper-city','friendly-exes','Whether exes can remain friends','What friendship after romance requires from everyone involved.','History in the room','If an already-present participant is a former partner, that established history creates room for a measured response rather than generic jealousy.',null,'exes|friendship|social','ex|former partner|still friends','friend',null,'romance',1,'juniper-friendly-exes',null,'character_character','remote|co_present|group_chat','shared_scene',2,3,'','social|conversation',1,30,72,'{"requiredParticipantRelationshipTypes":["former_partner","ex"]}'),
('juniper-city','apartment-key','The meaning of giving someone an apartment key','Whether practical access and emotional commitment should advance together.','Access without assumption','A practical discussion of access creates an opening to offer, withhold, or postpone a key without changing canonical access state.',null,'home|trust|commitment','apartment key|spare key|access','dating',null,'romance',1,'juniper-apartment-key',null,'relationship_choice','remote|co_present','co_present|active_plan',1,2,'','home|conversation',1.2,28,72,'{}'),
('juniper-city','workplace-romance','Workplace romance disclosure rules','Where privacy ends when power or reporting lines are involved.','Coworkers notice','If canonically present coworkers already know both people, their attention can create an opening to discuss disclosure without inventing gossip.',null,'work|romance|law','coworker dating|workplace romance|disclose','friend',null,'standard',1,'juniper-workplace-romance',null,'social','remote|co_present','co_present|shared_scene',2,3,'','work|social',1,24,72,'{"requiresKnownParticipant":true}'),
('juniper-city','adult-venue-reputation','Juniper''s legal adult-entertainment scene','Whether legal protections and a venue''s reputation are the same thing.','A venue opinion','The surroundings create room for a strong personal opinion about adult nightlife without requiring participation. ',null,'adult|nightlife|law','adult venue|legal club|reputation','acquaintance',null,'mature',2,'juniper-adult-venue-licensing',null,'adult','remote|co_present','co_present|active_date',1,2,'evening|late_night','nightlife|conversation',1,30,72,'{}'),
('juniper-city','river-serious','What river serious means','Why repeated ordinary walks can signal more than dramatic dates.','A quieter turn','The Riverwalk pace creates room for the conversation to become more vulnerable without forcing a disclosure.','riverwalk','riverwalk|relationship|routine','river serious|riverwalk','flirting',null,'romance',1,'juniper-river-serious',null,'vulnerability','remote|co_present|active_date','co_present|active_date|active_plan',1,2,'evening','walk|conversation|riverwalk',1.3,20,24,'{}'),
('juniper-city','public-affection','Whether public affection is actually intimate','How visibility changes the meaning of a small gesture.','Public gesture opening','The scene creates room for a small public gesture or a clear choice not to make one; neither outcome is assumed.',null,'affection|public|intimacy','public affection|hold hands|kiss outside','flirting',null,'romance',1,'juniper-public-affection',null,'flirt','remote|co_present|active_date','co_present|active_date',1,2,'','walk|date|public',1.1,18,24,'{}'),
('juniper-city','public-arguments','Why public relationship arguments are judged harshly','Whether conflict can remain honest without making private life a spectacle.','Nearby contrast','A nearby disagreement may offer contrast, but the companion need not comment unless it fits the conversation.',null,'conflict|privacy|relationship','public argument|fight in public','friend',null,'standard',1,'juniper-public-arguments',null,'environment','remote|co_present','co_present|active_date',1,2,'','social|conversation',.9,30,48,'{}'),
('juniper-city','great-blackout-romances','The Great Blackout romances','Whether hardship-created intimacy is remembered more romantically than it felt.','Lights change','A brief, ordinary power interruption can change the atmosphere without recreating the historical blackout or forcing romance.',null,'blackout|history|romance','great blackout|power out|blackout romance','acquaintance',null,'romance',1,'juniper-great-blackout',null,'environment','remote|co_present|story','co_present|active_date|story',1,3,'evening|late_night','nightlife|home|dinner',1,30,120,'{}'),
('juniper-city','blackout-romanticized','Whether the blackout stories were romanticized','How public memory edits discomfort into a cleaner love story.','Challenge the sentimental version','A blackout reference creates room for the companion to question the popular version rather than repeat it.',null,'history|romance|disputed','blackout romance|romanticized','friend',null,'standard',1,'juniper-blackout-romances',null,'history','remote|co_present|story','co_present|story',1,2,'','history|conversation',1,30,96,'{}'),
('juniper-city','breakup-table','The breakup-table rumor','Whether choosing a supposedly symbolic table changes a conversation.','Staff recognition','A subtle staff reaction may create awkwardness, but it does not determine what either person intends to discuss.','sora-table','rumor|restaurant|dating','breakup table|sora table','dating',null,'romance',1,'juniper-breakup-table',null,'humor','remote|co_present|active_date','co_present|active_date',1,2,'evening','dinner|conversation',1,28,96,'{}'),
('juniper-city','across-town-dating','Dating someone across town','When travel effort becomes evidence of priority rather than mere inconvenience.','Transit complication','A canonical transit delay can complicate timing and reveal priorities without changing the saved plan. ',null,'transit|dating|effort','across town|late train|traffic','acquaintance',null,'standard',1,'juniper-across-town-dating',null,'interruption','remote|co_present|active_plan','co_present|active_plan',1,2,'','transit|travel|meeting',1,20,18,'{}'),
('juniper-city','moving-in-costs','Apartment costs and moving in too early','Whether financial convenience can obscure relationship readiness.','Practical pressure','Housing or rent talk creates room to separate practical need from emotional commitment.',null,'housing|relationship|economy','rent|move in|apartment cost','dating',null,'romance',1,'juniper-housing-costs',null,'relationship_choice','remote|co_present','co_present|active_plan',1,2,'','home|conversation',1.2,28,72,'{}'),
('juniper-city','short-stay-privacy','Short-stay hotel culture and privacy','Whether discretion is comforting or makes a moment feel less grounded.','Shelter from weather','Bad weather may make a hotel lobby a plausible refuge; entering a room or escalating intimacy is never assumed.',null,'hotel|privacy|weather','hotel privacy|short stay|storm','flirting',null,'mature',2,'juniper-short-stay-hotels',null,'privacy','remote|co_present|active_plan','co_present|active_plan',1,2,'evening|late_night','weather|hotel|conversation',1,24,48,'{}'),
('juniper-city','arena-proposals','Arena proposals: romantic or horrifying','How public spectacle changes the ethics of a private decision.','Proposal in view','A public proposal elsewhere in the arena creates room for reaction without making it about the user and companion.','juniper-civic-arena','proposal|public|romance','arena proposal|public proposal','acquaintance',null,'romance',1,'juniper-arena-proposals',null,'environment','remote|co_present|active_date','co_present|active_date',1,3,'evening','arena|event|crowd',1,24,72,'{}'),
('juniper-city','safe-walk','Safe-walk and bartender intervention customs','How care can be offered without demanding an explanation.','Notice a safety need','A canonically visible safety concern nearby creates room to alert staff or stay observant; no danger is invented.',null,'safety|nightlife|custom','safe walk|bartender help|unsafe','acquaintance',null,'standard',1,'juniper-safe-walk-custom',null,'social','remote|co_present','co_present|active_date',1,3,'evening|late_night','nightlife|bar',1.2,24,36,'{}'),
('juniper-city','bartenders-know','Whether bartenders know everyone''s relationships','Where attentive service ends and gossip begins.','Remembered order','Staff may remember an established order or prior companion only when canonical context supports it.',null,'bartender|reputation|social','bartender remembers|usual order','friend',null,'standard',1,'juniper-bartenders-remember',null,'social','remote|co_present','co_present|active_date',1,2,'evening|late_night','bar|drinks',1,24,48,'{"requiresCanonicalPriorVisit":true}'),
('juniper-city','surveillance-gap','The rumored Riverwalk surveillance gap','Whether privacy sought through a rumor is trustworthy privacy at all.','A questionable blind spot','A route passes the rumored area, creating room to investigate or dismiss the story without confirming it.','riverwalk','surveillance|rumor|privacy','surveillance gap|camera gap','friend',null,'standard',1,'juniper-riverwalk-gap',null,'mystery','remote|co_present|story','co_present|active_plan|story',1,2,'evening|late_night','walk|riverwalk|investigation',1,32,120,'{}'),
('juniper-city','underground-parties','Invitation-only underground parties','Whether exclusivity makes an event exciting, unsafe, or merely pretentious.','A credible invitation','A credible invitation may become available only when canonical story or social context supplies it; attendance is not assumed.',null,'party|nightlife|rumor','underground party|invitation only','friend',null,'mature',2,'juniper-underground-parties',null,'discovery','remote|co_present|story','co_present|story',1,3,'evening|late_night','nightlife|party',1,36,168,'{"requiresCanonicalInvitation":true}'),
('juniper-city','anonymous-connected','Whether Juniper feels anonymous or interconnected','How repeated familiar faces affect freedom and reputation.','Familiar faces','Several canonically known people may cross the evening naturally, creating social texture without inventing recognition.',null,'city|social|reputation','anonymous|everyone knows|familiar face','acquaintance',null,'standard',1,'juniper-anonymous-connected',null,'environment','remote|co_present|active_date','co_present|active_date|active_plan',1,3,'','walk|market|nightlife',1,20,24,'{}'),

-- Port Vervelle (25 + 25)
('port-vervelle','sunrise-intimacy','Why sunrise together is more intimate than midnight','Whether endurance into ordinary morning reveals more than nightlife.','The harbor wakes','A night can naturally reach the first harbor sounds, creating room to notice the shift without assuming either person stayed unwillingly.','porto-vecchio','sunrise|harbor|romance','sunrise together|harbor wakes','flirting',null,'romance',1,'vervelle-sunrise-intimacy',null,'romance','remote|co_present|active_date','co_present|active_date|active_plan',1,2,'dawn|morning','nightlife|conversation|walk',1.3,20,24,'{}'),
('port-vervelle','harbor-promise','The meaning of a harbor promise','Whether honesty before departure is kinder than confident promises.','Departure becomes real','A coming departure becomes concrete enough to invite honest discussion without creating a promise.','porto-marina','departure|promise|relationship','harbor promise|leaving|summer ends','friend',null,'romance',1,'vervelle-harbor-promise',null,'relationship_choice','remote|co_present|active_plan','co_present|active_plan|active_date',1,2,'','harbor|conversation|departure',1.2,24,48,'{}'),
('port-vervelle','vacation-permanence','Whether vacation romances can become permanent','What must survive once place, novelty, and free time change.','The calendar intrudes','A canonical departure date or seasonal change can enter the conversation without predetermining the relationship.',null,'summer|dating|future','vacation romance|become permanent','flirting',null,'romance',1,'vervelle-vacation-romance',null,'relationship_choice','remote|co_present','co_present|active_date',1,2,'','conversation|travel',1.2,24,48,'{}'),
('port-vervelle','beach-customs','Nude and topless beach customs','How privacy, looking, and photography etiquette shape comfort in secluded coves.','Before the cove','Approaching a secluded beach creates room to explain etiquette; entering, undressing, or consenting is never assumed.','spiaggia-solana','beach|adult|privacy','nude beach|topless|secluded cove','acquaintance',null,'mature',2,'vervelle-beach-customs',null,'adult','remote|co_present|active_plan','co_present|active_plan|active_date',1,2,'morning|afternoon','beach|swim|walk',1.3,30,72,'{}'),
('port-vervelle','beach-photography','Why photography rules are strict around private beaches','Whether a beautiful setting ever excuses capturing strangers.','A raised phone','A nearby phone becomes noticeable, creating room to address etiquette without declaring that a prohibited photo was taken.','spiaggia-solana','beach|photo|privacy','beach camera|private beach|photo','acquaintance',null,'standard',1,'vervelle-beach-photography',null,'privacy','remote|co_present','co_present|active_date',1,3,'morning|afternoon','beach|photo',1.2,24,48,'{}'),
('port-vervelle','hotel-discretion','How hotel discretion became culturally important','Whether practiced nonjudgment feels humane or evasive.','Professional discretion','Staff handle an established awkward detail without judgment, leaving the companion free to appreciate or question it.','hotel-celeste','hotel|privacy|culture','hotel discretion|late arrival','friend',null,'standard',1,'vervelle-hotel-discretion',null,'privacy','remote|co_present|active_plan','co_present|active_plan|active_date',1,2,'evening|late_night','hotel|arrival|conversation',1,24,48,'{}'),
('port-vervelle','market-gossip','Why morning-market sightings cause more gossip than clubs','Why ordinary routines read as commitment in a small town.','Recognized at the market','Only canonically known acquaintances may notice the pair, creating room to respond to social visibility.','mercato-vecchio','market|gossip|dating','morning market|seen together','friend',null,'romance',1,'vervelle-market-gossip',null,'social','remote|co_present|active_plan','co_present|active_plan|active_date',1,3,'morning','market|shopping|errands',1.2,24,48,'{"requiresKnownParticipant":true}'),
('port-vervelle','sunday-lunch','Family Sunday lunch as a relationship milestone','Whether inclusion in family routine should be named or allowed to speak for itself.','An introduction considered','The companion may consider an invitation or decide it is premature; no family meeting is created. ',null,'family|lunch|commitment','sunday lunch|meet family','dating',null,'romance',1,'vervelle-sunday-lunch',null,'relationship_choice','remote|co_present','co_present|active_date',1,2,'morning|afternoon','meal|conversation',1.2,28,72,'{}'),
('port-vervelle','villa-access','Giving someone access to a villa','How keys, family reputation, and private space make access consequential.','A spare key question','Practical access becomes relevant, allowing an offer, refusal, or delay without mutating canonical access.','villa-mirabelle','villa|key|trust','villa key|private home','dating',null,'romance',1,'vervelle-villa-key',null,'relationship_choice','remote|co_present','co_present|active_plan',1,2,'','home|conversation',1.2,28,72,'{}'),
('port-vervelle','balcony-serenade','Balcony serenades: romantic or embarrassing','Whether public romance becomes performance for neighbors.','Music from above','Music from another balcony interrupts briefly and may invite humor or reflection. ',null,'music|balcony|romance','serenade|balcony music','acquaintance',null,'romance',1,'vervelle-balcony-serenade',null,'environment','remote|co_present|active_date','co_present|active_date',1,2,'evening|late_night','dinner|walk|conversation',1,20,24,'{}'),
('port-vervelle','relaxed-exposed','Why Vervelle is relaxed but socially exposed','How adult freedom coexists with an observant community.','Private now, public later','A harmless sign that the town notices routines can create room to discuss privacy without inventing gossip. ',null,'adult|social|privacy','relaxed|everyone knows|gossip','friend',null,'mature',2,'vervelle-relaxed-exposed',null,'privacy','remote|co_present','co_present|active_date',1,2,'','conversation|town',1.1,24,48,'{}'),
('port-vervelle','former-lovers','Former lovers in the same social circles','What maturity, avoidance, and unresolved history look like in a small town.','An established former partner','Only if a former partner is canonically present may their presence create a social choice; the beat never summons them.',null,'exes|social|history','former lover|ex nearby','friend',null,'romance',1,'vervelle-exes-circle',null,'character_character','remote|co_present|group_chat','shared_scene',2,3,'','social|conversation',1,32,96,'{"requiredParticipantRelationshipTypes":["former_partner","ex"]}'),
('port-vervelle','lighthouse-affair','The Lighthouse Affair','How privacy and public hypocrisy collide in the town''s most famous scandal.','A family version','A relevant artifact or view creates room for the companion to share the version they legitimately know.','capo-vervelle','lighthouse|scandal|privacy','lighthouse affair|famous photo','friend',null,'standard',1,'vervelle-lighthouse-affair',null,'history','remote|co_present|story','co_present|story|active_plan',1,2,'','history|walk|lighthouse',1.2,30,96,'{}'),
('port-vervelle','lighthouse-photo-ethics','Whether the famous photograph should have been published','Whether exposing deception justified violating a private moment.','Privacy disagreement','The historical photograph creates room for genuine disagreement without forcing conflict.','capo-vervelle','photography|privacy|ethics','publish photo|lighthouse photograph','friend',null,'standard',1,'vervelle-lighthouse-photo-ethics',null,'conflict','remote|co_present','co_present|story',1,2,'','history|conversation',1.1,24,72,'{}'),
('port-vervelle','blue-tide','The Blue Tide Summer','Why a natural event became a shared romantic memory.','Water begins to glow','If the current canonical conditions include bioluminescence, the water changes the scene without forcing a swim.','spiaggia-solana','blue tide|sea|romance','glowing water|blue tide','acquaintance',null,'romance',1,'vervelle-blue-tide',null,'environment','remote|co_present|story','co_present|active_date|story',1,3,'evening|late_night','beach|swim|walk',1.3,30,168,'{"requiresCanonicalCondition":"blue_tide"}'),
('port-vervelle','blue-tide-disputed','Whether Blue Tide stories are exaggerated','How memory changes a townwide event into personal myth.','Contradicting memories','An already-present older local may contradict the account only when canonically part of the scene.','spiaggia-solana','blue tide|memory|disputed','blue tide exaggerated|older local','friend',null,'standard',1,'vervelle-blue-tide-stories',null,'group','remote|co_present|group_chat','shared_scene',2,3,'','conversation|history',1,30,120,'{"requiresKnownParticipant":true}'),
('port-vervelle','harbor-fire','The Harbor Fire','How rebuilding preserves or hides difficult history.','A surviving burn mark','A visible surviving mark creates room to notice history without inventing new damage.','porto-vecchio','fire|history|harbor','harbor fire|burn mark','acquaintance',null,'standard',1,'vervelle-harbor-fire',null,'discovery','remote|co_present|story','co_present|story|active_plan',1,2,'','walk|history|harbor',1.1,28,96,'{}'),
('port-vervelle','smuggling-trial','The Vervelle Smuggling Trial','How accusation, family loyalty, and incomplete proof shape reputation.','An uncomfortable name','A canonically relevant family name may change the tone, creating room for care rather than assumed guilt.','palazzo-civico','trial|family|crime','smuggling trial|shipping family','friend',null,'standard',1,'vervelle-smuggling-trial',null,'history','remote|co_present|story','co_present|story',1,3,'','history|conversation',1.1,30,120,'{}'),
('port-vervelle','missing-ledger','The missing hotel ledger pages','Whether absence in an archive is evidence or merely absence.','An archival inconsistency','A canonical record reveals a gap that can be noticed or investigated without inventing what the missing pages said.','locanda-vela','ledger|mystery|history','missing ledger|torn pages','friend',null,'standard',1,'vervelle-missing-ledger-pages','vervelle-ledger-pages','mystery','remote|co_present|story','co_present|story',1,2,'','archive|history|investigation',1.2,40,240,'{}'),
('port-vervelle','harbor-tunnels','Illegal or forgotten harbor tunnels','Whether old infrastructure invites curiosity, risk, or restraint.','A sealed doorway','An existing sealed doorway becomes noticeable; opening or entering it requires a separate canonical action.','porto-vecchio','tunnel|harbor|mystery','harbor tunnel|sealed door','friend',null,'standard',1,'vervelle-harbor-tunnels',null,'discovery','remote|co_present|story','co_present|story|active_plan',1,2,'','walk|investigation|harbor',1.2,32,168,'{}'),
('port-vervelle','three-sunsets','The three-sunset rule','Whether waiting clarifies desire or merely delays a difficult answer.','Invoke the custom','An impulsive proposal creates room to mention the custom, not to accept or reject on the user''s behalf.',null,'romance|custom|decision','three sunsets|romantic decision','flirting',null,'romance',1,'vervelle-three-sunsets',null,'relationship_choice','remote|co_present','co_present|active_date',1,2,'evening','conversation|sunset',1.2,24,48,'{}'),
('port-vervelle','summer-judgment','Whether locals judge casual summer relationships','The difference between casual, careless, and dishonest.','A friend teases','Only a canonically present friend may tease the companion, and the tone must follow established social state.',null,'summer|dating|social','casual summer|locals judge','friend',null,'romance',1,'vervelle-summer-judgment',null,'character_character','remote|co_present|group_chat','shared_scene',2,3,'','social|conversation',1,28,72,'{"requiresKnownParticipant":true}'),
('port-vervelle','love-letters','The anonymous lighthouse love letters','Whether anonymity makes a romantic gesture freer or less trustworthy.','A new letter','A new letter may appear only when canonical story state supplies it; finding one does not reveal its author.','capo-vervelle','letter|lighthouse|rumor','love letter|anonymous letter','friend',null,'romance',1,'vervelle-love-letters',null,'mystery','remote|co_present|story','co_present|story',1,2,'','lighthouse|walk|investigation',1.2,36,168,'{"requiresCanonicalStoryObject":true}'),
('port-vervelle','rare-table','The table locals rarely request casually','Whether a place''s reputation can burden an otherwise ordinary dinner.','Staff react subtly','A subtle staff reaction may be noticed but cannot define the pair''s intention.','osteria-rosa','restaurant|relationship|custom','special table|rare table','dating',null,'romance',1,'vervelle-special-table',null,'humor','remote|co_present|active_date','co_present|active_date',1,2,'evening','dinner|conversation',1,28,96,'{}'),
('port-vervelle','everyone-knows','What happens when everyone knows everyone''s business','Whether correcting a rumor protects truth or feeds attention.','Respond to a rumor','A canonically established rumor creates a choice to correct or ignore it; no new rumor is fabricated.',null,'gossip|reputation|privacy','everyone knows|correct rumor','friend',null,'standard',1,'vervelle-rumor-response',null,'relationship_choice','remote|co_present','co_present|active_date',1,2,'','conversation|town',1.1,24,72,'{"requiresCanonicalRumor":true}'),

-- NEON KYO (25 + 25)
('neon-kyo','unfiltered-face','Whether showing an unfiltered face is more intimate than nudity','How chosen visibility differs from physical exposure.','Appearance layers pause','The companion may choose to adjust an appearance layer; the beat never claims they did so or that the user reciprocated.',null,'identity|filter|intimacy','unfiltered face|turn off filter','flirting',null,'romance',1,'kyo-unfiltered-face',null,'vulnerability','remote|co_present|active_date','co_present|active_date',1,2,'','conversation|date',1.3,24,48,'{}'),
('neon-kyo','raw-hour','What a Raw Hour actually means','Whether temporary disconnection is trust, performance, or relief.','Offer a Raw Hour','The scene allows either person to propose privacy mode; devices are not changed until canonical consent is recorded.',null,'raw hour|privacy|authenticity','raw hour|offline together','friend',null,'romance',1,'kyo-raw-hour',null,'privacy','remote|co_present|active_date','co_present|active_date|active_plan',1,2,'evening|late_night','conversation|date|home',1.4,22,48,'{}'),
('neon-kyo','location-sharing','Whether constant location sharing is romantic or controlling','How revocability and expectation change the meaning of tracking.','Permission change','Location permissions become relevant, creating room to ask or decline without altering them automatically.',null,'tracking|relationship|privacy','location sharing|track me|controlling','friend',null,'romance',1,'kyo-location-sharing',null,'relationship_choice','remote|co_present','co_present|active_date',1,2,'','conversation|travel',1.3,22,48,'{}'),
('neon-kyo','ghost-window','Ghost Windows as acts of trust','Whether not knowing can be a deliberate form of respect.','A tracking gap proposed','A Ghost Window can be proposed, but the beat never turns tracking off or assumes agreement.',null,'ghost window|trust|privacy','ghost window|stop tracking','dating',null,'romance',1,'kyo-ghost-window',null,'relationship_choice','remote|co_present','co_present|active_date',1,2,'','conversation|date',1.2,28,72,'{}'),
('neon-kyo','consent-handshake','Why consent handshakes exist','What digital confirmation can clarify and what it cannot replace.','Authorization requested','A licensed adult system requests authorization; activation and consent remain unresolved until both canonical choices exist.',null,'consent|adult|technology','consent handshake|authorization','flirting',null,'mature',2,'kyo-consent-handshake',null,'adult','remote|co_present','co_present|active_date',1,2,'evening|late_night','adult venue|intimacy',1.4,30,72,'{}'),
('neon-kyo','spoken-no','Why digital consent cannot override a spoken no','Why revocability matters more than technical certainty.','System responds to withdrawal','Only after an actual canonical withdrawal may an intimate feature stop; the beat never invents consent or withdrawal.',null,'consent|law|technology','spoken no|digital consent|stop','flirting',null,'mature',2,'kyo-spoken-no',null,'adult','remote|co_present','co_present|active_date',1,2,'','intimacy|conversation',1.4,32,96,'{}'),
('neon-kyo','biometric-data','Ownership of biometric attraction data','Whether the body''s involuntary signals should become a product.','Privacy warning','A canonical device warning can reveal unexpected data collection without asserting what the signals mean.',null,'biometric|privacy|attraction','attraction data|pulse|arousal analytics','acquaintance',null,'mature',2,'kyo-biometric-attraction',null,'privacy','remote|co_present','co_present|active_date',1,2,'','device|date|conversation',1.2,24,72,'{}'),
('neon-kyo','attraction-analytics','Whether attraction analytics ruin spontaneous chemistry','Whether prediction makes feeling safer or less authentic.','Compatibility prediction','A system may display a prediction when canonically present; neither person must accept its interpretation.',null,'analytics|dating|chemistry','compatibility score|predict attraction','flirting',null,'romance',1,'kyo-attraction-analytics',null,'environment','remote|co_present|active_date','co_present|active_date',1,2,'','date|device|conversation',1.3,22,48,'{}'),
('neon-kyo','likeness-rights','Synthetic intimate media and likeness rights','How control of one''s image intersects with desire and technology.','Unauthorized simulation','Only canonical evidence may reveal an unauthorized image; the beat never generates or describes one. ',null,'synthetic media|privacy|law','deepfake|synthetic image|likeness','friend',null,'mature',2,'kyo-likeness-rights',null,'law','remote|co_present|story','co_present|story',1,2,'','device|investigation|conversation',1.3,30,120,'{"requiresCanonicalMedia":true}'),
('neon-kyo','memory-sharing','Whether memory sharing is more intimate than physical contact','What trust is involved in granting access to internal history.','A private memory considered','The companion may consider offering one established memory, but no access or disclosure is created automatically.',null,'memory|trust|intimacy','share memory|memory access','dating',null,'romance',1,'kyo-memory-sharing',null,'vulnerability','remote|co_present|active_date','co_present|active_date',1,2,'','conversation|memory',1.3,28,72,'{}'),
('neon-kyo','revoke-keys','Revoking relationship data keys after a breakup','Whether deletion can provide closure when copies and memories remain.','Old access surfaces','An established former access grant may surface during canonical account management; no former partner is invented.',null,'breakup|data|privacy','revoke key|relationship data','friend',null,'standard',1,'kyo-revoke-keys',null,'discovery','remote|co_present|story','co_present|story',1,2,'','device|conversation',1,28,96,'{"requiresCanonicalAccessGrant":true}'),
('neon-kyo','handwritten-notes','Why handwritten notes have become romantic','Whether permanence and lack of analytics make paper feel more honest.','A physical note','A note already canonically present can be noticed or offered; its content is not invented.',null,'paper|romance|privacy','handwritten note|paper letter','flirting',null,'romance',1,'kyo-handwritten-notes',null,'romance','remote|co_present|active_date','co_present|active_date',1,2,'','conversation|gift',1.2,20,48,'{"requiresCanonicalObject":true}'),
('neon-kyo','seven-minute-blackout','The Seven-Minute Blackout','Why a precisely bounded absence of surveillance still destabilizes public memory.','Observation cuts out','A canonical surveillance interruption can change the scene; no illegal act or hidden action is invented. ',null,'blackout|surveillance|history','seven minute blackout|surveillance cuts','acquaintance',null,'standard',1,'kyo-seven-minute-blackout',null,'environment','remote|co_present|story','co_present|story',1,3,'evening|late_night','city|travel|conversation',1.3,30,168,'{"requiresCanonicalCondition":"surveillance_outage"}'),
('neon-kyo','blackout-stories','What people really did during those seven minutes','How uncertainty invites self-serving stories.','A rarely told account','The companion may share only an account their canonical knowledge permits and must preserve its disputed status.',null,'blackout|history|secret','seven minutes|what happened blackout','friend',null,'standard',1,'kyo-blackout-accounts',null,'vulnerability','remote|co_present|story','co_present|story',1,2,'','conversation|history',1.2,32,120,'{}'),
('neon-kyo','ten-thousand-ghosts','Night of Ten Thousand Ghosts','Whether collective anonymity protected dissent or endangered accountability.','Anniversary crowds','A canonical anniversary gathering can alter the route and social atmosphere without forcing participation.',null,'protest|identity|history','ten thousand ghosts|protest anniversary','acquaintance',null,'standard',1,'kyo-ten-thousand-ghosts',null,'environment','remote|co_present|story','co_present|story|active_plan',1,3,'evening|late_night','city|crowd|travel',1.2,30,168,'{}'),
('neon-kyo','perfect-couple','The Perfect Couple Scandal','Whether public romance can remain authentic under sponsorship and optimization.','Curated romance questioned','A promotional display or reference creates room to question public romance without comparing the user to a campaign. ',null,'romance|scandal|authenticity','perfect couple|sponsored romance','friend',null,'standard',1,'kyo-perfect-couple',null,'conflict','remote|co_present|story','co_present|story|active_date',1,2,'','city|date|conversation',1.2,28,96,'{}'),
('neon-kyo','emotion-manipulation','Emotion manipulation by corporations','Where atmosphere ends and nonconsensual influence begins.','Suspiciously tailored ambience','A disclosed or canonically suspicious system can be noticed; it does not dictate anyone''s emotion. ',null,'emotion|corporation|consent','mood system|emotion manipulation','friend',null,'standard',1,'kyo-emotion-manipulation',null,'discovery','remote|co_present|story','co_present|story|active_date',1,2,'','venue|date|device',1.3,28,96,'{}'),
('neon-kyo','civic-rating','Civic Rating and romantic desirability','Whether access scores should influence attraction or partner choice.','Rating changes','A canonical rating change may become visible after a public choice, but the beat never changes the score itself.',null,'rating|dating|politics','civic rating|dating score','acquaintance',null,'standard',1,'kyo-civic-rating',null,'relationship_choice','remote|co_present','co_present|active_date',1,2,'','city|conversation|device',1.1,22,72,'{"requiresCanonicalRatingChange":true}'),
('neon-kyo','identity-layers','Whether people date identities or people','How selective presentation can be honest without being complete.','A hidden layer considered','The companion may choose whether to reveal an established identity layer; no new identity is invented. ',null,'identity|authenticity|dating','identity layer|real person|hidden self','friend',null,'romance',1,'kyo-identity-layers',null,'vulnerability','remote|co_present|active_date','co_present|active_date',1,2,'','conversation|date',1.3,24,72,'{}'),
('neon-kyo','synthetic-personhood','Synthetic personhood and relationships','Whether engineered origin changes moral or romantic equality.','Dismissive treatment','Only an already-present person''s canonical dismissive act can open this issue; prejudice is not invented for atmosphere.',null,'synthetic|personhood|relationship','synthetic person|ai rights','acquaintance',null,'standard',1,'kyo-synthetic-personhood',null,'character_character','remote|co_present|group_chat','shared_scene',2,3,'','social|conversation',1,26,72,'{"requiresCanonicalParticipantAction":true}'),
('neon-kyo','clean-break','Clean Break, the rumored erasure service','Whether forgetting a relationship is healing, avoidance, or a new form of control.','A clandestine lead','Information about Clean Break appears only through canonical story state; using the service is never assumed. ',null,'breakup|memory|rumor','clean break|erase relationship','friend',null,'standard',1,'kyo-clean-break',null,'mystery','remote|co_present|story','co_present|story',1,2,'','investigation|device|conversation',1.3,36,240,'{"requiresCanonicalLead":true}'),
('neon-kyo','blind-zones','Surveillance blind zones','Whether a place without tracking creates safety, danger, or genuine freedom.','Tracking disappears','A canonical blind zone may interrupt tracking, creating room to notice the change without inventing hidden actions.',null,'surveillance|privacy|city','blind zone|tracking disappears','friend',null,'standard',1,'kyo-blind-zones',null,'environment','remote|co_present|story','co_present|story|active_plan',1,2,'evening|late_night','travel|walk|city',1.3,26,96,'{}'),
('neon-kyo','private-hotels','Private hotels versus genuine privacy','Whether minimized human contact still counts as privacy when systems retain records.','The hotel knows','A disclosed retained detail can create discomfort or humor; the beat never invents a private record. ',null,'hotel|privacy|technology','private hotel|hotel knows','flirting',null,'mature',2,'kyo-private-hotels',null,'privacy','remote|co_present|active_plan','co_present|active_plan|active_date',1,2,'evening|late_night','hotel|arrival|conversation',1.2,24,72,'{"requiresCanonicalRecord":true}'),
('neon-kyo','unrecorded-matters','Whether something unrecorded matters more','How choosing not to preserve a moment can increase its meaning.','Leave it uncaptured','The companion may propose leaving the moment unrecorded; recording settings do not change without agreement.',null,'recording|authenticity|romance','do not record|unrecorded moment','flirting',null,'romance',1,'kyo-unrecorded-value',null,'relationship_choice','remote|co_present|active_date','co_present|active_date',1,2,'','date|conversation|photo',1.3,22,48,'{}'),
('neon-kyo','authenticity','Is authenticity possible in NEON KYO','Whether improvisation reveals more than carefully selected presentation.','Curation fails','A canonical plan or recommendation can go wrong, creating room to improvise without manufacturing failure. ',null,'authenticity|identity|city','authentic|curated date|real moment','acquaintance',null,'standard',1,'kyo-authenticity-question',null,'mistake','remote|co_present|active_date','co_present|active_date|active_plan',1,2,'','date|travel|conversation',1.2,20,36,'{"requiresCanonicalComplication":true}'),

-- Vespormoor (25 + 25)
('vespormoor','unequal-relationships','Whether supernatural-human relationships can be equal','How lifespan, secrecy, and power should be discussed rather than romanticized.','Power named honestly','The scene creates room to name a real power difference without deciding the relationship for either person.',null,'veiled|lifespan|relationship','supernatural relationship|equal|lifespan','friend',null,'romance',1,'vesper-unequal-lifespans',null,'vulnerability','remote|co_present|active_date','co_present|active_date',1,2,'','conversation|date',1.4,26,72,'{}'),
('vespormoor','unwilling-prey','Covenant rules around unwilling prey','How supernatural appetite remains subordinate to consent.','Boundary made explicit','A Veiled companion may establish or restate a boundary; feeding or intimacy is never assumed to occur.',null,'covenant|consent|veiled','unwilling prey|feeding consent','flirting',null,'mature',2,'vesper-unwilling-prey',null,'adult','remote|co_present','co_present|active_date',1,2,'evening|late_night','conversation|intimacy',1.5,30,96,'{}'),
('vespormoor','secrecy-control','Whether secrecy protects people or controls them','Who benefits when outsiders cannot know the underlying truth.','An outsider asks','A canonically present outsider''s innocent question may create pressure, but the beat does not fabricate a visitor. ',null,'covenant|secrecy|power','secrecy protect|covenant control','friend',null,'standard',1,'vesper-secrecy-purpose',null,'character_character','remote|co_present|group_chat','shared_scene',2,3,'','social|conversation',1.2,28,96,'{"requiresOutsiderParticipant":true}'),
('vespormoor','shared-room','What unmarried adults sharing a room signals','Whether private choice should answer to inherited social meaning.','Professional discretion','An innkeeper may respond only if canonically present; room sharing and entry are never assumed.',null,'inn|relationship|custom','share room|unmarried adults','flirting',null,'romance',1,'vesper-shared-room',null,'privacy','remote|co_present|active_plan','co_present|active_plan',1,3,'evening|late_night','inn|arrival|conversation',1.2,24,72,'{"requiresKnownParticipant":true}'),
('vespormoor','mourning-courtship','Mourning customs and dating again','How grief, loyalty, and present desire can coexist.','Interest becomes visible','Only established romantic interest may become noticeable; the beat never assigns desire to a grieving person. ',null,'mourning|dating|custom','widow dating|mourning period','friend',null,'romance',1,'vesper-mourning-courtship',null,'vulnerability','remote|co_present','co_present|active_date',1,2,'','conversation|social',1.2,30,120,'{}'),
('vespormoor','inheritance-pressure','Same-sex relationships and old-family inheritance pressure','How family obligation can conflict with an adult''s chosen life.','Family expectation surfaces','A canonically established family expectation may enter the moment without forcing compliance or conflict. ',null,'inheritance|family|relationship','same sex|heir pressure','friend',null,'romance',1,'vesper-inheritance-pressure',null,'conflict','remote|co_present|story','co_present|story|active_date',1,2,'','conversation|family',1.3,28,120,'{}'),
('vespormoor','first-names','Why first names matter among old families','Whether changing forms of address signals intimacy, equality, or rebellion.','A form of address shifts','The companion may choose a different established form of address; the user''s response is not scripted. ',null,'name|trust|custom','first name|surname|title','acquaintance',null,'romance',1,'vesper-first-names',null,'relationship_choice','remote|co_present|active_date','co_present|active_date',1,2,'','conversation|formal event',1.3,20,36,'{}'),
('vespormoor','glove-exchange','What exchanging gloves once meant','Whether an old symbol can carry meaning without binding anyone.','An old token','A glove already present may invite explanation or an offer; exchange and acceptance are never assumed. ',null,'gloves|courtship|history','exchange gloves|romantic token','flirting',null,'romance',1,'vesper-exchanged-gloves',null,'romance','remote|co_present|active_date','co_present|active_date',1,2,'','walk|formal event|conversation',1.2,24,72,'{"requiresCanonicalObject":true}'),
('vespormoor','midnight-tea','Midnight tea as a sign of trust','Why an after-hours invitation can matter more than formal entertainment.','An invitation considered','The companion may offer midnight tea or decide the trust is not there; arrival is not created. ',null,'tea|trust|night','midnight tea|late invitation','friend',null,'romance',1,'vesper-midnight-tea',null,'relationship_choice','remote|co_present','co_present|active_plan|active_date',1,2,'late_night','tea|conversation|home',1.3,24,72,'{}'),
('vespormoor','west-window-candle','The west-window candle tradition','How a private signal can communicate trust while preserving discretion.','A candle signal','A canonically lit candle may be noticed; the beat never grants access or makes someone enter. ',null,'candle|trust|visitor','west window candle|candle signal','friend',null,'romance',1,'vesper-west-window-candle',null,'discovery','remote|co_present|story','co_present|story|active_plan',1,2,'evening|late_night','walk|arrival|investigation',1.2,28,96,'{"requiresCanonicalCondition":"west_window_candle"}'),
('vespormoor','burning-winter','The Burning Winter','How the 1846 destruction still structures family memory and the rebuilt town.','Scars in the stone','A visible surviving trace creates room for history without replaying violence.','old-vesper','burning winter|history|fire','burning winter|1846','acquaintance',null,'standard',1,'vesper-burning-winter',null,'history','remote|co_present|story','co_present|story|active_plan',1,3,'','walk|history|investigation',1.3,28,96,'{}'),
('vespormoor','burning-winter-truth','Whether official Burning Winter history is truthful','How family records and public history compete for authority.','Competing accounts','Two canonically knowledgeable present participants may disagree; no account is promoted to truth merely by confidence. ',null,'history|disputed|family','official history|who started','friend',null,'standard',1,'vesper-burning-winter-accounts',null,'character_character','remote|co_present|group_chat','shared_scene|story',2,3,'','conversation|history',1.3,32,144,'{"requiresKnowledgeableParticipants":true}'),
('vespormoor','lucien-disappearance','Lucien Vesper''s disappearance','Why his absence matters more than any single rumor about his fate.','A name lands heavily','A companion''s reaction to Lucien may deepen only when their canonical knowledge supports it.','vesper-house','lucien|disappearance|history','lucien vesper|disappeared','friend',null,'standard',1,'vesper-lucien-disappearance',null,'mystery','remote|co_present|story','co_present|story',1,2,'','investigation|history|conversation',1.2,30,120,'{}'),
('vespormoor','isolde-disappearance','Isolde Vesper''s later disappearance','How her vanishing changed Covenant power and chronology.','Chronology contradicts itself','A canonical archive detail may conflict with the common account without supplying an invented answer. ',null,'isolde|disappearance|history','isolde vesper|chronology','friend',null,'standard',1,'vesper-isolde-disappearance',null,'discovery','remote|co_present|story','co_present|story',1,2,'','archive|investigation|history',1.2,32,144,'{}'),
('vespormoor','missing-clause','The missing Covenant clause','What kind of rule an institution would remove from its own public history.','Restricted text','Evidence of removed text may be examined only in an unlocked story; the missing wording remains unknown until revealed.','the-undercroft','covenant|clause|secret','missing clause|removed text','friend',null,'standard',1,'vesper-missing-clause','vesper-missing-clause','mystery','remote|co_present|story','co_present|story',1,2,'','archive|investigation',1.4,40,240,'{}'),
('vespormoor','blackwillow-bride','The Blackwillow Bride disappearance','Whether the legend preserves a victim, an escape, or a useful family fiction.','An old wedding object','A canonical object may reopen the legend; it does not establish which account is true. ',null,'bride|wedding|folklore','blackwillow bride|missing bride','friend',null,'standard',1,'vesper-blackwillow-bride',null,'mystery','remote|co_present|story','co_present|story',1,2,'','investigation|formal event|history',1.2,34,168,'{"requiresCanonicalObject":true}'),
('vespormoor','masked-ball','The masked-ball scandal','How anonymity at a formal event can reveal rather than hide allegiance.','The old atmosphere returns','A current formal event may echo the scandal through setting and social tension without recreating its outcome. ',null,'masked ball|scandal|family','masked ball scandal|formal mask','friend',null,'standard',1,'vesper-masked-ball',null,'environment','remote|co_present|story','co_present|story|active_date',1,3,'evening|late_night','formal event|dance|conversation',1.2,30,168,'{}'),
('vespormoor','gray-ledger','The apothecary gray ledger','When confidentiality protects people and when secrecy protects institutions.','A restricted purchase','Only a canonical purchase or ledger entry may be noticed; no medical or Veiled condition is inferred. ',null,'apothecary|privacy|ledger','gray ledger|private purchase','friend',null,'standard',1,'vesper-gray-ledger',null,'privacy','remote|co_present|story','co_present|story',1,2,'','apothecary|investigation|conversation',1.2,32,144,'{"requiresCanonicalRecord":true}'),
('vespormoor','romantic-dueling','Romantic dueling culture','Why theatrical challenge survives after actual violence became unacceptable.','A joking challenge','A joking challenge may be spoken only by a canonically present participant and cannot authorize violence. ',null,'duel|romance|custom','romantic duel|challenge','acquaintance',null,'romance',1,'vesper-romantic-duels',null,'humor','remote|co_present|group_chat','co_present|shared_scene|active_date',2,3,'','formal event|conversation|social',1.1,24,72,'{}'),
('vespormoor','long-fog','The Long Fog','How isolation changes priorities, trust, and the meaning of shelter.','Fog closes the route','Canonical weather may isolate the pair and create practical choices; becoming lost or entering shelter is not assumed. ',null,'fog|weather|isolation','long fog|road changed','acquaintance',null,'standard',1,'vesper-long-fog',null,'environment','remote|co_present|story','co_present|story|active_plan',1,3,'evening|late_night','travel|walk|weather',1.4,24,96,'{"requiresCanonicalWeather":"long_fog"}'),
('vespormoor','whisper-dock','Whisper Dock confessions','Why a place can create room for honesty without demanding it.','Room for confession','The setting creates a quiet opening for either person to ask, volunteer, or stay silent; no confession is forced.','whisper-dock','confession|dock|trust','whisper dock|confess','friend',null,'romance',1,'vesper-whisper-dock',null,'confession','remote|co_present|active_date','co_present|active_date|active_plan',1,2,'evening|late_night','walk|conversation|lake',1.5,22,72,'{}'),
('vespormoor','sunken-chapel','Sunken Chapel legends','Whether visible stone is history, coincidence, or warning.','Water reveals stone','Only canonical lake conditions may reveal more stone; approaching or entering remains a separate choice.','sunken-chapel','chapel|lake|folklore','sunken chapel|low water','friend',null,'standard',1,'vesper-sunken-chapel',null,'discovery','remote|co_present|story','co_present|story|active_plan',1,2,'','lake|walk|investigation',1.3,34,168,'{"requiresCanonicalCondition":"low_water"}'),
('vespormoor','lovers-route','The hidden lovers'' route through Thornwood','Whether secrecy enabled freedom or exposed people to danger.','An omitted trail','A path absent from a modern map may be noticed; following it requires user choice and safe canonical action.','thornwood','trail|lovers|history','lovers route|hidden trail','friend',null,'romance',1,'vesper-lovers-route',null,'discovery','remote|co_present|story','co_present|story|active_plan',1,2,'','trail|walk|investigation',1.3,32,144,'{}'),
('vespormoor','estate-staff','Why estate staff knew every secret first','How service work creates knowledge without erasing professional agency.','Understood before announced','An already-present estate employee may understand established dynamics, but cannot reveal private facts they do not know.','vesper-heights','estate|staff|social','servants knew|estate secret','friend',null,'standard',1,'vesper-servants-knew',null,'character_character','remote|co_present|group_chat','shared_scene',2,3,'','estate|social|conversation',1,28,96,'{"requiresEstateStaffParticipant":true}'),
('vespormoor','lake-remembers','What the lake actually remembers','Why people project memory and guilt onto a place that cannot verify them.','Lights interrupt the evening','Canonical lights beneath the water may interrupt the mood without proving the rumor.','lake-vesper','lake|memory|rumor','lake remembers|lights under lake','friend',null,'standard',1,'vesper-lake-remembers',null,'mystery','remote|co_present|story','co_present|story|active_date',1,2,'evening|late_night','lake|walk|conversation',1.4,30,120,'{}');

insert into public.together_dialogue_opportunities(
  world_id,slug,topic,angle,framing,location_id,topic_tags,trigger_terms,min_relationship_stage,max_relationship_stage,
  content_level,min_spice_level,required_fact_slug,required_story_slug,interaction_modes,weight,cooldown_turns,metadata
)
select world.id,seed.world_slug||'-'||seed.slug,seed.topic,seed.angle,
  'Optional only. Let the companion''s established personality, history, boundaries, and current relationship stance determine their view.',
  location.id,string_to_array(seed.tags,'|'),string_to_array(seed.triggers,'|'),seed.min_stage,seed.max_stage,
  seed.content_level,seed.min_spice,seed.required_fact_slug,seed.required_story_slug,string_to_array(seed.op_modes,'|'),seed.weight,seed.cooldown_turns,seed.metadata
from kivelle_depth_seed seed
join public.together_worlds world on world.slug=seed.world_slug
left join public.together_locations location on location.world_id=world.id and location.slug=seed.location_slug
on conflict(world_id,slug) do update set topic=excluded.topic,angle=excluded.angle,framing=excluded.framing,location_id=excluded.location_id,
  topic_tags=excluded.topic_tags,trigger_terms=excluded.trigger_terms,min_relationship_stage=excluded.min_relationship_stage,max_relationship_stage=excluded.max_relationship_stage,
  content_level=excluded.content_level,min_spice_level=excluded.min_spice_level,required_fact_slug=excluded.required_fact_slug,required_story_slug=excluded.required_story_slug,
  interaction_modes=excluded.interaction_modes,weight=excluded.weight,cooldown_turns=excluded.cooldown_turns,metadata=excluded.metadata,active=true,updated_at=now();

insert into public.together_scene_interaction_beats(
  world_id,slug,title,location_id,interaction_type,seed,affordances,topic_tags,min_relationship_stage,max_relationship_stage,
  content_level,min_spice_level,required_fact_slug,required_story_slug,interaction_modes,co_present_required,
  required_participant_count,maximum_participant_count,dayparts,activity_tags,weight,cooldown_hours,metadata
)
select world.id,seed.world_slug||'-'||seed.slug,seed.beat_title,location.id,seed.interaction_type,seed.beat_seed,
  jsonb_build_array('notice the opening without forcing it','respond in established character','leave the moment unused'),
  string_to_array(seed.tags,'|'),seed.min_stage,seed.max_stage,seed.content_level,seed.min_spice,seed.required_fact_slug,seed.required_story_slug,
  string_to_array(seed.beat_modes,'|'),true,seed.required_participants,seed.maximum_participants,
  case when seed.dayparts='' then '{}'::text[] else string_to_array(seed.dayparts,'|') end,
  case when seed.activity_tags='' then '{}'::text[] else string_to_array(seed.activity_tags,'|') end,
  seed.weight,seed.cooldown_hours,seed.metadata
from kivelle_depth_seed seed
join public.together_worlds world on world.slug=seed.world_slug
left join public.together_locations location on location.world_id=world.id and location.slug=seed.location_slug
on conflict(world_id,slug) do update set title=excluded.title,location_id=excluded.location_id,interaction_type=excluded.interaction_type,
  seed=excluded.seed,affordances=excluded.affordances,topic_tags=excluded.topic_tags,min_relationship_stage=excluded.min_relationship_stage,
  max_relationship_stage=excluded.max_relationship_stage,content_level=excluded.content_level,min_spice_level=excluded.min_spice_level,
  required_fact_slug=excluded.required_fact_slug,required_story_slug=excluded.required_story_slug,interaction_modes=excluded.interaction_modes,
  co_present_required=excluded.co_present_required,required_participant_count=excluded.required_participant_count,maximum_participant_count=excluded.maximum_participant_count,
  dayparts=excluded.dayparts,activity_tags=excluded.activity_tags,weight=excluded.weight,cooldown_hours=excluded.cooldown_hours,metadata=excluded.metadata,active=true,updated_at=now();

do $$
declare target_world text;opportunity_count integer;beat_count integer;
begin
  foreach target_world in array array['juniper-city','port-vervelle','neon-kyo','vespormoor'] loop
    select count(*) into opportunity_count from public.together_dialogue_opportunities item join public.together_worlds world on world.id=item.world_id where world.slug=target_world and item.active;
    select count(*) into beat_count from public.together_scene_interaction_beats item join public.together_worlds world on world.id=item.world_id where world.slug=target_world and item.active;
    if opportunity_count<25 or beat_count<25 then raise exception 'Depth pack incomplete for %: opportunities %, beats %',target_world,opportunity_count,beat_count;end if;
  end loop;
end $$;
