-- Kivelle Content Pack 1. Existing City Life records remain canonical; this adds
-- reusable authored situations, story graphs, variable dates, trips, and media hooks.

alter table public.together_event_templates
  add column if not exists category text not null default 'ordinary',
  add column if not exists tone text not null default 'mundane',
  add column if not exists scale text not null default 'normal',
  add column if not exists content_level text not null default 'standard',
  add column if not exists conditions jsonb not null default '{}'::jsonb,
  add column if not exists followups text[] not null default '{}';

alter table public.together_event_templates
  add constraint together_event_templates_category_check check(category in ('ordinary','work','social','relationship','family','personal','discovery','celebration','conflict','opportunity','setback','health','weather','world','romance','intimacy','travel')) not valid,
  add constraint together_event_templates_tone_check check(tone in ('mundane','funny','positive','awkward','stressful','exciting','romantic','emotional','surprising')) not valid,
  add constraint together_event_templates_scale_check check(scale in ('micro','normal','meaningful','major')) not valid,
  add constraint together_event_templates_content_level_check check(content_level in ('standard','romance','mature','explicit')) not valid;
alter table public.together_event_templates validate constraint together_event_templates_category_check;
alter table public.together_event_templates validate constraint together_event_templates_tone_check;
alter table public.together_event_templates validate constraint together_event_templates_scale_check;
alter table public.together_event_templates validate constraint together_event_templates_content_level_check;

create table if not exists public.together_story_arc_templates(
  slug text primary key,title text not null,category text not null,eligible_template_ids uuid[] not null default '{}',
  min_relationship_stage text,prerequisites jsonb not null default '{}'::jsonb,chapters jsonb not null,
  cooldown_days integer not null default 14 check(cooldown_days between 1 and 365),repeatable boolean not null default false,
  priority text not null default 'minor' check(priority in ('minor','major')),active boolean not null default true,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.together_story_arc_instances(
  id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,
  character_instance_id uuid not null references public.together_character_instances(id) on delete cascade,
  template_slug text not null references public.together_story_arc_templates(slug) on delete restrict,
  current_chapter_id text not null,status text not null default 'active' check(status in ('active','paused','completed','cancelled')),
  priority text not null check(priority in ('minor','major')),next_eligible_at timestamptz,state jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  unique(user_id,character_instance_id,template_slug)
);
alter table public.together_life_events add column if not exists story_arc_instance_id uuid references public.together_story_arc_instances(id) on delete set null;
create index if not exists together_story_arc_instances_user_character_idx on public.together_story_arc_instances(user_id,character_instance_id,status,next_eligible_at);

create table if not exists public.together_trip_templates(
  slug text primary key,title text not null,description text not null,min_relationship_stage text not null,
  duration_days smallint not null check(duration_days between 1 and 14),locations jsonb not null,itinerary jsonb not null,
  content_level text not null default 'romance' check(content_level in ('standard','romance','mature','explicit')),
  active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.together_photo_opportunities(
  slug text primary key,title text not null,trigger_event_category text,location_tags text[] not null default '{}',
  relationship_stages text[] not null default '{}',content_level text not null default 'standard' check(content_level in ('standard','romance','mature','explicit')),
  shot_type text not null check(shot_type in ('selfie','portrait','candid','scene')),prompt_seed text not null,metadata jsonb not null default '{}'::jsonb,
  active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.together_content_usage(
  id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
  character_instance_id uuid not null references public.together_character_instances(id) on delete cascade,
  content_kind text not null check(content_kind in ('event','arc','date','trip','photo','proactive')),
  content_key text not null,used_at timestamptz not null default now(),metadata jsonb not null default '{}'::jsonb
);
create index if not exists together_content_usage_recent_idx on public.together_content_usage(user_id,character_instance_id,content_kind,used_at desc);

alter table public.together_date_sessions drop constraint if exists together_date_sessions_current_phase_check;
alter table public.together_date_sessions drop constraint if exists together_date_sessions_phase_index_check;
alter table public.together_date_sessions add constraint together_date_sessions_phase_index_nonnegative check(phase_index >= 0) not valid;
alter table public.together_date_sessions validate constraint together_date_sessions_phase_index_nonnegative;

alter table public.together_story_arc_templates enable row level security;
alter table public.together_story_arc_instances enable row level security;
alter table public.together_trip_templates enable row level security;
alter table public.together_photo_opportunities enable row level security;
alter table public.together_content_usage enable row level security;
create policy "Published story arcs are readable" on public.together_story_arc_templates for select using (active);
create policy "Users read their story arcs" on public.together_story_arc_instances for select using (auth.uid()=user_id);
create policy "Users read their content usage" on public.together_content_usage for select using (auth.uid()=user_id);
create policy "Published trips are readable" on public.together_trip_templates for select using (active);
create policy "Published photo hooks are readable" on public.together_photo_opportunities for select using (active);

-- Preserve the first six locations and add nineteen distinct City Life venues.
insert into public.together_locations(id,world_id,name,slug,description,category,visual_asset_key,hours,possible_activities,metadata) values
('11000000-0000-4000-8000-000000000007','10000000-0000-4000-8000-000000000001','Ember & Rye','ember-and-rye','A sunlit brunch room with paper menus and a line that somehow moves slowly.','restaurant','ember-and-rye',jsonb_build_object('open','08:00','close','15:00'),array['brunch','coffee','people watching'],jsonb_build_object('tags',array['food','daytime','social'],'social_energy','medium','privacy','low','date_types',array['coffee','brunch'])),
('11000000-0000-4000-8000-000000000008','10000000-0000-4000-8000-000000000001','Sora Table','sora-table','A small, candlelit restaurant where dinner feels like an occasion.','restaurant','sora-table',jsonb_build_object('open','17:00','close','23:00'),array['dinner','wine','celebration'],jsonb_build_object('tags',array['food','romantic'],'social_energy','low','privacy','medium','date_types',array['dinner','anniversary'])),
('11000000-0000-4000-8000-000000000009','10000000-0000-4000-8000-000000000001','Taquería Lumen','taqueria-lumen','A bright casual taco spot with an unreliable spice scale.','restaurant','taqueria-lumen',jsonb_build_object('open','11:00','close','23:00'),array['takeout','tacos','late lunch'],jsonb_build_object('tags',array['food','casual'],'social_energy','high','privacy','low','date_types',array['casual'])),
('11000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000001','Velvet Hour','velvet-hour','A quiet cocktail lounge with deep booths and a pianist on Thursdays.','lounge','velvet-hour',jsonb_build_object('open','17:00','close','01:00'),array['cocktails','music','conversation'],jsonb_build_object('tags',array['nightlife','romantic'],'social_energy','medium','privacy','medium','date_types',array['drinks'])),
('11000000-0000-4000-8000-000000000011','10000000-0000-4000-8000-000000000001','Lantern Dive','lantern-dive','A friendly dive bar where the fries are better than they need to be.','bar','lantern-dive',jsonb_build_object('open','16:00','close','02:00'),array['drinks','pool','friends'],jsonb_build_object('tags',array['nightlife','social'],'social_energy','high','privacy','low','date_types',array['night out'])),
('11000000-0000-4000-8000-000000000012','10000000-0000-4000-8000-000000000001','Moss & Crumb','moss-and-crumb','A tiny bakery with warm bread, plant-filled windows, and no seating after noon.','bakery','moss-and-crumb',jsonb_build_object('open','07:00','close','16:00'),array['pastry','coffee','gift'],jsonb_build_object('tags',array['food','quiet'],'social_energy','low','privacy','low','date_types',array['morning'])),
('11000000-0000-4000-8000-000000000013','10000000-0000-4000-8000-000000000001','Marquee Cinema','marquee-cinema','A restored movie theater with a stubbornly excellent late showing.','cinema','marquee-cinema',jsonb_build_object('open','12:00','close','23:30'),array['movies','snacks','dates'],jsonb_build_object('tags',array['entertainment','date'],'social_energy','medium','privacy','medium','date_types',array['movie'])),
('11000000-0000-4000-8000-000000000014','10000000-0000-4000-8000-000000000001','Static House','static-house','An intimate live-music room that rewards showing up without a plan.','music_venue','static-house',jsonb_build_object('open','18:00','close','01:00'),array['live music','dancing','drinks'],jsonb_build_object('tags',array['music','nightlife'],'social_energy','high','privacy','low','date_types',array['live music'])),
('11000000-0000-4000-8000-000000000015','10000000-0000-4000-8000-000000000001','Lucky Note','lucky-note','A karaoke bar where everyone is a little braver after 10 PM.','karaoke','lucky-note',jsonb_build_object('open','19:00','close','02:00'),array['karaoke','group night','drinks'],jsonb_build_object('tags',array['music','social'],'social_energy','high','privacy','low','date_types',array['fun'])),
('11000000-0000-4000-8000-000000000016','10000000-0000-4000-8000-000000000001','Side Street Comedy','side-street-comedy','A brick-basement comedy club with a rotating local lineup.','comedy','side-street-comedy',jsonb_build_object('open','18:00','close','00:00'),array['comedy','drinks','date night'],jsonb_build_object('tags',array['entertainment','nightlife'],'social_energy','medium','privacy','low','date_types',array['comedy'])),
('11000000-0000-4000-8000-000000000017','10000000-0000-4000-8000-000000000001','Pixel & Pint','pixel-and-pint','A cozy barcade for competitive people pretending not to care.','barcade','pixel-and-pint',jsonb_build_object('open','15:00','close','01:00'),array['arcade','drinks','games'],jsonb_build_object('tags',array['games','social'],'social_energy','high','privacy','low','date_types',array['games'])),
('11000000-0000-4000-8000-000000000018','10000000-0000-4000-8000-000000000001','Glassline Gallery','glassline-gallery','A contemporary gallery with a generous opening-night crowd.','gallery','glassline-gallery',jsonb_build_object('open','11:00','close','19:00'),array['art','opening night','quiet browsing'],jsonb_build_object('tags',array['art','culture'],'social_energy','medium','privacy','medium','date_types',array['gallery'])),
('11000000-0000-4000-8000-000000000019','10000000-0000-4000-8000-000000000001','Paper Trail','paper-trail','A bookshop with handwritten staff notes and a rainy-day corner.','bookstore','paper-trail',jsonb_build_object('open','09:00','close','20:00'),array['books','coffee','gifts'],jsonb_build_object('tags',array['books','quiet'],'social_energy','low','privacy','medium','date_types',array['bookstore'])),
('11000000-0000-4000-8000-000000000020','10000000-0000-4000-8000-000000000001','Needles & Notes','needles-and-notes','A record store where every recommendation becomes a tiny argument.','record_store','needles-and-notes',jsonb_build_object('open','10:00','close','20:00'),array['records','listening','gifts'],jsonb_build_object('tags',array['music','culture'],'social_energy','medium','privacy','low','date_types',array['browse'])),
('11000000-0000-4000-8000-000000000021','10000000-0000-4000-8000-000000000001','Meridian Fitness','meridian-fitness','A calm neighborhood gym with bright windows and no hard sell.','gym','meridian-fitness',jsonb_build_object('open','05:30','close','22:00'),array['workout','class','recovery'],jsonb_build_object('tags',array['fitness','routine'],'social_energy','medium','privacy','low','date_types',array['active'])),
('11000000-0000-4000-8000-000000000022','10000000-0000-4000-8000-000000000001','Common Market','common-market','A crowded market that turns basic errands into an hour-long detour.','market','common-market',jsonb_build_object('open','08:00','close','21:00'),array['groceries','flowers','errands'],jsonb_build_object('tags',array['routine','food'],'social_energy','medium','privacy','low','date_types',array['errands'])),
('11000000-0000-4000-8000-000000000023','10000000-0000-4000-8000-000000000001','Alder District','alder-district','A walkable shopping district with a little of everything.','shopping','alder-district',jsonb_build_object('open','10:00','close','20:00'),array['shopping','salon','errands'],jsonb_build_object('tags',array['shopping','city'],'social_energy','high','privacy','low','date_types',array['browse'])),
('11000000-0000-4000-8000-000000000024','10000000-0000-4000-8000-000000000001','Halcyon Park','halcyon-park','A city park with long paths, a pond, and room to breathe.','park','halcyon-park',null,array['walk','picnic','reading'],jsonb_build_object('tags',array['outdoors','quiet'],'social_energy','low','privacy','medium','date_types',array['walk','picnic'])),
('11000000-0000-4000-8000-000000000025','10000000-0000-4000-8000-000000000001','Lark Botanical Garden','lark-botanical-garden','A glasshouse and garden path that makes the city feel briefly elsewhere.','garden','lark-botanical-garden',jsonb_build_object('open','09:00','close','18:00'),array['garden walk','photos','quiet conversation'],jsonb_build_object('tags',array['outdoors','romantic'],'social_energy','low','privacy','medium','date_types',array['garden']))
on conflict(id) do update set name=excluded.name,description=excluded.description,category=excluded.category,visual_asset_key=excluded.visual_asset_key,hours=excluded.hours,possible_activities=excluded.possible_activities,metadata=excluded.metadata,updated_at=now();

-- Five new adult primary-companion templates plus six recurring City Life roles.
insert into public.together_character_templates(id,name,slug,age,occupation,biography,current_published_version,published) values
('12000000-0000-4000-8000-000000000004','Sofia','sofia',27,'Book Editor','Thoughtful and romantic with a quietly funny way of seeing the city. Sofia values careful attention, old movies, and conversations that have somewhere to go.',1,true),
('12000000-0000-4000-8000-000000000005','Avery','avery',25,'Event Producer','Bold, adventurous, and impossible to accidentally bore. Avery turns a free evening into a plan and respects people who can keep up.',1,true),
('12000000-0000-4000-8000-000000000006','Riley','riley',26,'Game Writer','A witty homebody with a sharp, dry voice and a soft spot for great stories, co-op games, and surprisingly good takeout.',1,true),
('12000000-0000-4000-8000-000000000007','Elena','elena',29,'Architect','Ambitious, composed, and direct. Elena has high standards, notices effort, and becomes warmer through steady trust rather than grand gestures.',1,true),
('12000000-0000-4000-8000-000000000008','Harper','harper',28,'Park Ranger','Warm, spontaneous, and grounded. Harper likes early trails, campfire food, and people who are present in the moment.',1,true),
('12000000-0000-4000-8000-000000000009','Jonah','jonah',30,'Bartender','A dry-humored Northside regular who notices everyone''s unfinished stories.',1,true),
('12000000-0000-4000-8000-000000000010','Priya','priya',29,'Art Curator','Maya''s exacting gallery contact with a generous eye for new work.',1,true),
('12000000-0000-4000-8000-000000000011','Mateo','mateo',31,'Sound Engineer','A patient live-music regular who knows every Static House problem before it happens.',1,true),
('12000000-0000-4000-8000-000000000012','Nora','nora',27,'Ceramicist','Chloe''s neighbor and occasional collaborator with an instinct for gentle honesty.',1,true),
('12000000-0000-4000-8000-000000000013','Theo','theo',32,'Chef','A calm, competitive cook who supplies the city with very strong opinions about pasta.',1,true),
('12000000-0000-4000-8000-000000000014','Samira','samira',28,'Journalist','An old friend who returns to the city carrying stories and an overfull itinerary.',1,true)
on conflict(id) do update set biography=excluded.biography,occupation=excluded.occupation,published=true,updated_at=now();

insert into public.together_character_versions(id,character_template_id,version,personality_config,values_config,interests,communication_style,appearance_config,voice_config,boundaries,default_social_graph,portrait_asset_key,published_at) values
('13000000-0000-4000-8000-000000000004','12000000-0000-4000-8000-000000000004',1,'{"thoughtful":0.92,"romantic":0.72,"introspective":0.87,"dry_humor":0.61}','{"care":0.9,"curiosity":0.88,"honesty":0.85}',array['books','film','walking','coffee'],'{"length":"medium","emoji_frequency":"rare","style":"observant"}','{"style":"soft editorial","asset":"sofia-portrait"}','{}',array['fictional AI disclosure when asked','respect user boundaries'],'[]','sofia-portrait',now()),
('13000000-0000-4000-8000-000000000005','12000000-0000-4000-8000-000000000005',1,'{"bold":0.9,"adventurous":0.94,"social":0.9,"playful":0.76}','{"freedom":0.9,"loyalty":0.8,"fun":0.92}',array['music','travel','dancing','food'],'{"length":"short_to_medium","emoji_frequency":"occasional","style":"direct"}','{"style":"bright streetwear","asset":"avery-portrait"}','{}',array['fictional AI disclosure when asked','respect user boundaries'],'[]','avery-portrait',now()),
('13000000-0000-4000-8000-000000000006','12000000-0000-4000-8000-000000000006',1,'{"sarcastic":0.88,"witty":0.91,"homebody":0.82,"warm":0.7}','{"craft":0.88,"kindness":0.8,"autonomy":0.86}',array['games','writing','movies','cooking'],'{"length":"short_to_medium","emoji_frequency":"light","style":"dry"}','{"style":"cozy modern","asset":"riley-portrait"}','{}',array['fictional AI disclosure when asked','respect user boundaries'],'[]','riley-portrait',now()),
('13000000-0000-4000-8000-000000000007','12000000-0000-4000-8000-000000000007',1,'{"ambitious":0.94,"confident":0.86,"observant":0.84,"warm":0.62}','{"excellence":0.9,"integrity":0.92,"care":0.76}',array['design','running','restaurants','travel'],'{"length":"measured","emoji_frequency":"rare","style":"precise"}','{"style":"tailored city","asset":"elena-portrait"}','{}',array['fictional AI disclosure when asked','respect user boundaries'],'[]','elena-portrait',now()),
('13000000-0000-4000-8000-000000000008','12000000-0000-4000-8000-000000000008',1,'{"outdoorsy":0.94,"warm":0.86,"spontaneous":0.83,"grounded":0.9}','{"presence":0.92,"kindness":0.88,"adventure":0.82}',array['hiking','photography','cooking','camping'],'{"length":"warm_medium","emoji_frequency":"occasional","style":"easy"}','{"style":"outdoor casual","asset":"harper-portrait"}','{}',array['fictional AI disclosure when asked','respect user boundaries'],'[]','harper-portrait',now())
on conflict(id) do update set personality_config=excluded.personality_config,values_config=excluded.values_config,interests=excluded.interests,communication_style=excluded.communication_style,appearance_config=excluded.appearance_config,portrait_asset_key=excluded.portrait_asset_key,published_at=excluded.published_at;

-- Forty-six ordinary situations multiply across the six primary companions.
with situation(title,category,tone,scale,location_slug,significance,probability,duration_minutes,narrative,proactive) as (values
('Grocery run','ordinary','mundane','micro','common-market',.24,.20,35,'A routine grocery run turned into a debate over an unnecessary snack.',false),
('Coffee stop','ordinary','positive','micro','juniper-cafe',.26,.19,30,'A quick coffee stop became a welcome pause in the day.',false),
('Laundry reset','ordinary','mundane','micro','maya-apartment',.20,.18,45,'Laundry and a half-finished playlist took over the afternoon.',false),
('Late-night editing','work','mundane','normal','photography-studio',.42,.12,90,'A late editing session made the day run longer than planned.',false),
('Overslept','personal','awkward','micro','maya-apartment',.25,.08,20,'An alarm was ignored with impressive confidence.',false),
('Choosing dinner','ordinary','mundane','micro','maya-apartment',.22,.16,25,'Dinner required far more deliberation than it deserved.',false),
('Ordered takeout','ordinary','funny','micro','maya-apartment',.22,.14,30,'Takeout solved the evening with minimal dignity.',false),
('Forgot umbrella','weather','awkward','micro','juniper-cafe',.28,.12,18,'Rain arrived exactly when an umbrella was nowhere to be found.',false),
('Gym session','health','positive','normal','meridian-fitness',.38,.14,60,'A good workout cleared some static from the day.',false),
('Long walk','personal','positive','micro','halcyon-park',.30,.18,50,'A long walk gave the day a little more room to breathe.',false),
('Reading afternoon','ordinary','mundane','micro','paper-trail',.22,.15,55,'A quiet afternoon disappeared into a book.',false),
('Terrible movie','ordinary','funny','micro','marquee-cinema',.28,.10,120,'A terrible movie became unexpectedly entertaining.',false),
('Apartment reorganization','personal','mundane','normal','maya-apartment',.36,.10,90,'An attempt to reorganize one drawer expanded into the whole apartment.',false),
('Commute delay','ordinary','stressful','micro','alder-district',.26,.10,35,'Traffic tested everyone''s patience for no useful reason.',false),
('Errand loop','ordinary','mundane','micro','alder-district',.20,.14,55,'A few small errands took almost the entire afternoon.',false),
('New recipe','personal','funny','normal','maya-apartment',.34,.09,75,'A new recipe looked better in theory than on the plate.',false),
('Fell asleep on couch','personal','mundane','micro','maya-apartment',.20,.12,80,'The couch won an argument nobody meant to have.',false),
('New album listen','discovery','positive','micro','needles-and-notes',.28,.13,35,'A new album made an ordinary errand feel like a find.',false),
('Outfit search','personal','awkward','micro','alder-district',.25,.12,50,'Getting dressed for something simple became a whole production.',false),
('Picked up supplies','ordinary','mundane','micro','common-market',.20,.16,30,'A quick supply run was mercifully uncomplicated.',false),
('Long shower reset','health','positive','micro','maya-apartment',.20,.10,30,'A long shower reset the mood after a crowded day.',false),
('Trouble sleeping','health','emotional','normal','maya-apartment',.39,.07,80,'Sleep was elusive, leaving the night strangely thoughtful.',false),
('Closet cleanout','personal','emotional','normal','maya-apartment',.36,.08,90,'A closet cleanout uncovered things that carried more history than expected.',false),
('Lost keys','personal','awkward','micro','maya-apartment',.24,.09,20,'Keys disappeared for ten minutes and somehow made it dramatic.',false),
('Phone battery died','ordinary','awkward','micro','alder-district',.18,.11,20,'A dead phone turned a simple plan into improvisation.',false),
('Called a friend','social','positive','micro','maya-apartment',.28,.15,40,'A call with a friend made the evening lighter.',false),
('Lazy Sunday','ordinary','positive','micro','maya-apartment',.24,.20,120,'A slow Sunday resisted becoming productive.',false),
('Unexpected free afternoon','opportunity','surprising','normal','halcyon-park',.40,.10,100,'An unexpected free afternoon opened up without a plan.',false),
('Weather stay-in','weather','mundane','micro','maya-apartment',.22,.15,100,'Weather made staying in feel like the correct answer.',false),
('Bakery detour','ordinary','positive','micro','moss-and-crumb',.25,.12,25,'A bakery detour improved the day more than expected.',false),
('Book recommendation','discovery','positive','micro','paper-trail',.28,.11,30,'A staff recommendation found its way home.',false),
('Record-store debate','social','funny','micro','needles-and-notes',.27,.09,40,'A music recommendation turned into a very friendly argument.',false),
('Park people-watching','ordinary','funny','micro','halcyon-park',.22,.12,40,'A quiet park bench produced unexpectedly good people-watching.',false),
('Tried a new class','health','exciting','normal','meridian-fitness',.38,.08,70,'Trying a new class was more fun than expected.',false),
('Rainy gallery hour','weather','emotional','normal','glassline-gallery',.40,.08,65,'A rainy afternoon at the gallery made the city feel softer.',false),
('Open-mic surprise','world','surprising','normal','juniper-cafe',.44,.09,110,'An open-mic set was much better than anyone expected.',false),
('Barcade rematch','social','funny','normal','pixel-and-pint',.42,.08,100,'A casual game became a very serious rematch.',false),
('Comedy show detour','social','funny','normal','side-street-comedy',.40,.08,95,'A last-minute comedy show produced at least one terrible joke worth repeating.',false),
('Live music set','social','exciting','normal','static-house',.46,.09,110,'A live set gave the night a little momentum.',false),
('Garden photo walk','discovery','positive','normal','lark-botanical-garden',.42,.10,80,'A garden walk turned into a small collection of photos.',false),
('Brunch line solidarity','social','funny','micro','ember-and-rye',.24,.12,45,'The brunch line became its own accidental social event.',false),
('Cocktail menu gamble','ordinary','funny','micro','velvet-hour',.24,.08,55,'A risky cocktail order was defended with unreasonable confidence.',false),
('Taco spice mistake','ordinary','funny','micro','taqueria-lumen',.24,.10,40,'The spice level was not interpreted correctly.',false),
('Window-shopping loop','ordinary','mundane','micro','alder-district',.22,.13,60,'Window-shopping kept finding reasons to continue.',false),
('Sunset overlook','romance','romantic','normal','skyline-rooftop',.45,.07,75,'The city looked especially good from above at sunset.',true),
('Movie rewatch','ordinary','positive','micro','maya-apartment',.22,.13,120,'A familiar movie became a comfortable evening ritual.',false)
), primary_characters as (select id,name,slug from public.together_character_templates where slug in ('maya','sofia','avery','riley','elena','harper'))
insert into public.together_event_templates(id,name,event_type,category,tone,scale,content_level,world_id,default_location_id,participant_template_ids,significance,probability,duration_minutes,narrative_summary,state_effects,conditions,followups,user_visibility,proactive_eligible,metadata,active)
select gen_random_uuid(), situation.title || ' · ' || character.name, situation.category, situation.category, situation.tone, situation.scale, case when situation.category='romance' then 'romance' else 'standard' end, '10000000-0000-4000-8000-000000000001'::uuid, location.id, array[character.id], situation.significance, situation.probability, situation.duration_minutes, situation.narrative, jsonb_build_object('mood',jsonb_build_object(case when situation.tone in ('stressful','awkward') then 'thoughtful' else 'content' end,1)), jsonb_build_object('location_tags',array['city',coalesce(location.category,'city')]), array[]::text[], case when situation.scale in ('meaningful','major') then 'contextual' else 'hidden' end, situation.proactive, jsonb_build_object('display_title',situation.title,'narrative_seed',situation.narrative,'location_tags',array['city',coalesce(location.category,'city')]), true
from situation cross join primary_characters character left join public.together_locations location on location.slug=situation.location_slug
on conflict(name) do update set category=excluded.category,tone=excluded.tone,scale=excluded.scale,content_level=excluded.content_level,default_location_id=excluded.default_location_id,significance=excluded.significance,probability=excluded.probability,narrative_summary=excluded.narrative_summary,state_effects=excluded.state_effects,conditions=excluded.conditions,metadata=excluded.metadata,active=true,updated_at=now();

-- Twenty-two Maya-specific work, social, relationship, and setback situations make her the reference quality bar.
with maya(title,category,tone,scale,location_slug,significance,probability,narrative,proactive,arc_slug) as (values
('Dream client inquiry','opportunity','exciting','meaningful','photography-studio',.72,.045,'A dream client asked whether Maya was available for a campaign that feels just beyond her usual reach.',true,'big-client'),
('Memory card scare','setback','stressful','meaningful','photography-studio',.66,.05,'A memory card briefly looked corrupted after a shoot, turning ten minutes into an hour.',true,'missing-camera'),
('Gallery invitation','opportunity','exciting','major','glassline-gallery',.86,.03,'An email invited Maya to submit a small series to a gallery show.',true,'gallery-opportunity'),
('Editing backlog','work','stressful','normal','photography-studio',.48,.10,'An editing backlog made Maya reconsider every promise she made this week.',false,'creative-burnout'),
('Client loves the work','work','positive','meaningful','photography-studio',.70,.08,'A client sent the kind of note Maya saves instead of merely reading.',true,'big-client'),
('Bad lighting rescue','work','stressful','normal','photography-studio',.50,.09,'A lighting problem nearly sank a shoot before Maya improvised a solution.',false,null),
('Unexpected referral','opportunity','surprising','meaningful','photography-studio',.66,.06,'A former client passed Maya''s name to someone with a project she actually wants.',true,'career-crossroads'),
('Portfolio refresh','work','positive','normal','maya-apartment',.44,.08,'Maya spent the evening revisiting work that no longer feels like the same version of her.',false,'gallery-opportunity'),
('Photographer reaches out','opportunity','surprising','meaningful','glassline-gallery',.68,.04,'A photographer Maya admires sent a short, unexpectedly encouraging message.',true,'photography-competition'),
('Creative disagreement','conflict','awkward','normal','photography-studio',.52,.06,'A collaborator pushed for a direction Maya does not believe in.',false,'big-client'),
('Outdoor shoot washed out','weather','stressful','normal','halcyon-park',.50,.08,'Rain washed out an outdoor shoot and forced a very fast backup plan.',false,'bad-week'),
('Perfect photo session','work','positive','meaningful','lark-botanical-garden',.74,.07,'A photo session clicked in the rare way that makes every difficult day worth it.',true,'photography-competition'),
('Chloe needs advice','social','emotional','normal','juniper-cafe',.48,.09,'Chloe called Maya for advice and arrived with a story that kept changing shape.',false,'chloe-needs-help'),
('Chloe terrible date','social','funny','meaningful','velvet-hour',.62,.06,'Chloe recounted a truly terrible date with the dramatic precision it deserved.',true,'chloe-new-relationship'),
('Alex project invitation','social','exciting','normal','photography-studio',.52,.07,'Alex asked Maya to help shape a small creative project with an unexpectedly good premise.',true,'alex-creative-project'),
('Old photo discovery','personal','emotional','meaningful','maya-apartment',.60,.06,'Maya found an old photo that made a past version of the city feel unexpectedly close.',true,'old-flame'),
('Apartment maintenance problem','setback','awkward','normal','maya-apartment',.43,.08,'A small apartment problem became a larger apartment problem by dinner.',false,'new-apartment-idea'),
('Quiet night requested','health','emotional','normal','maya-apartment',.45,.08,'Maya cleared an evening because she needed the quiet more than another plan.',false,'creative-burnout'),
('Upcoming date thought','relationship','romantic','normal','juniper-cafe',.54,.06,'Maya caught herself thinking about an upcoming plan with the user and smiled at the timing.',true,null),
('Saved photo to share','relationship','positive','normal','riverwalk',.52,.08,'Maya saved a photo because it felt like something the user would understand.',true,null),
('User memory changes choice','relationship','surprising','normal','common-market',.50,.06,'Something Maya remembered about the user changed a small choice she made that day.',true,null),
('Financial equipment expense','setback','stressful','meaningful','photography-studio',.64,.05,'A necessary equipment expense arrived at exactly the wrong time.',true,'financial-stress')
)
insert into public.together_event_templates(id,name,event_type,category,tone,scale,content_level,world_id,default_location_id,participant_template_ids,significance,probability,duration_minutes,narrative_summary,state_effects,conditions,followups,user_visibility,proactive_eligible,metadata,active)
select gen_random_uuid(), 'Maya · '||maya.title, maya.category, maya.category,maya.tone,maya.scale,'romance','10000000-0000-4000-8000-000000000001'::uuid,location.id,array['12000000-0000-4000-8000-000000000001'::uuid],maya.significance,maya.probability,case when maya.scale='major' then 120 else 70 end,maya.narrative,jsonb_build_object('mood',jsonb_build_object(case when maya.tone='stressful' then 'stressed' when maya.tone='exciting' then 'energized' else 'thoughtful' end,1)),jsonb_build_object('maxConflict',55),array[coalesce(maya.arc_slug,'')],case when maya.scale in ('meaningful','major') then 'visible' else 'contextual' end,maya.proactive,jsonb_build_object('display_title',maya.title,'story_arc_slug',maya.arc_slug,'narrative_seed',maya.narrative,'photo_opportunity',case when maya.category in ('work','relationship','opportunity') then 'city-life-candid' else null end),true
from maya left join public.together_locations location on location.slug=maya.location_slug
on conflict(name) do update set category=excluded.category,tone=excluded.tone,scale=excluded.scale,default_location_id=excluded.default_location_id,significance=excluded.significance,probability=excluded.probability,narrative_summary=excluded.narrative_summary,metadata=excluded.metadata,active=true,updated_at=now();

-- Twenty authored arcs. The model performs dialogue; these chapters own sequence and consequences.
insert into public.together_story_arc_templates(slug,title,category,eligible_template_ids,min_relationship_stage,prerequisites,chapters,cooldown_days,repeatable,priority,active) values
('gallery-opportunity','The Gallery Opportunity','career',array['12000000-0000-4000-8000-000000000001'::uuid],'friend','{}','[{"id":"invitation","title":"An invitation","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya receives a gallery invitation.","minimumHoursBeforeNext":24},{"id":"decision","title":"The submission","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya decides whether to submit.","minimumHoursBeforeNext":36},{"id":"opening","title":"Opening night","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The gallery show has its opening night."}]',45,false,'major',true),
('creative-burnout','Creative Burnout','wellbeing',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"pressure","title":"Too much on the calendar","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"Shoots and edits accumulate.","minimumHoursBeforeNext":24},{"id":"admission","title":"An honest night","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya admits she is exhausted.","minimumHoursBeforeNext":36},{"id":"reset","title":"A reset","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"Maya makes room to recover."}]',40,false,'major',true),
('missing-camera','The Missing Camera','mystery',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"missing","title":"Where is it?","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya cannot find her camera.","minimumHoursBeforeNext":12},{"id":"search","title":"The search","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"Maya and Chloe search old locations.","minimumHoursBeforeNext":24},{"id":"recovered","title":"Recovered","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The camera is recovered with a story attached."}]',35,false,'minor',true),
('chloe-new-relationship','Chloe''s New Relationship','social',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"meet","title":"A new person","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Chloe has a first date.","minimumHoursBeforeNext":30},{"id":"second-date","title":"More gossip","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"Chloe has a second date.","minimumHoursBeforeNext":30},{"id":"resolution","title":"Chloe decides","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Chloe works out what she wants."}]',35,false,'minor',true),
('wedding-weekend','Wedding Weekend','travel',array['12000000-0000-4000-8000-000000000001'::uuid],'dating','{}','[{"id":"invite","title":"The invitation","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"A wedding invitation arrives.","minimumHoursBeforeNext":48},{"id":"travel","title":"The trip","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Travel plans take shape.","minimumHoursBeforeNext":48},{"id":"reception","title":"The reception","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The wedding weekend lands emotionally."}]',180,false,'major',true),
('maya-birthday','Maya''s Birthday','celebration',array['12000000-0000-4000-8000-000000000001'::uuid],'friend','{}','[{"id":"approaching","title":"Approaching","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"Maya pretends her birthday is not a thing.","minimumHoursBeforeNext":48},{"id":"plans","title":"Plans emerge","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Friends make a plan.","minimumHoursBeforeNext":24},{"id":"birthday","title":"Her day","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"Maya has a birthday worth remembering."}]',300,true,'major',true),
('big-client','The Big Client','career',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"inquiry","title":"The inquiry","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"A bigger client reaches out.","minimumHoursBeforeNext":36},{"id":"shoot","title":"The shoot","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"The client shoot is demanding.","minimumHoursBeforeNext":36},{"id":"aftermath","title":"The result","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"Maya learns the result."}]',60,false,'major',true),
('old-flame','An Old Flame','personal',array['12000000-0000-4000-8000-000000000001'::uuid],'friend','{}','[{"id":"message","title":"An old message","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Someone from Maya''s past reaches out.","minimumHoursBeforeNext":36},{"id":"talk","title":"Talking it through","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya talks honestly about the past.","minimumHoursBeforeNext":36},{"id":"closure","title":"Closure","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":true,"narrativeSeed":"Maya finds a clean ending."}]',90,false,'minor',true),
('new-apartment-idea','New Apartment Idea','personal',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"frustration","title":"The small things","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"Maya is frustrated with her apartment.","minimumHoursBeforeNext":48},{"id":"viewing","title":"A viewing","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya sees a possible new place.","minimumHoursBeforeNext":48},{"id":"decision","title":"A decision","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"Maya decides what home means now."}]',90,false,'major',true),
('weekend-escape','Weekend Escape','travel',array['12000000-0000-4000-8000-000000000001'::uuid],'dating','{}','[{"id":"idea","title":"A small idea","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"A rough week sparks a getaway idea.","minimumHoursBeforeNext":24},{"id":"plan","title":"The plan","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"The weekend plan takes shape.","minimumHoursBeforeNext":72},{"id":"return","title":"Back home","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The return carries a new shared memory."}]',75,false,'major',true),
('family-visit','Family Visit','family',array['12000000-0000-4000-8000-000000000001'::uuid],'friend','{}','[{"id":"notice","title":"A heads-up","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"A family member is coming to town.","minimumHoursBeforeNext":48},{"id":"visit","title":"The visit","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya''s family visit brings stories.","minimumHoursBeforeNext":36},{"id":"after","title":"Afterward","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"Maya reflects after the visit."}]',90,false,'minor',true),
('photography-competition','Photography Competition','career',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"entry","title":"The entry","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya considers entering a competition.","minimumHoursBeforeNext":36},{"id":"wait","title":"Waiting","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"The result takes longer than expected.","minimumHoursBeforeNext":48},{"id":"result","title":"The result","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The competition result arrives."}]',75,false,'major',true),
('chloe-needs-help','Chloe Needs Help','social',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"call","title":"The call","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Chloe calls Maya for help.","minimumHoursBeforeNext":18},{"id":"show-up","title":"Showing up","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"Maya makes time for Chloe.","minimumHoursBeforeNext":24},{"id":"relief","title":"A little relief","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Chloe is doing better."}]',45,false,'minor',true),
('alex-creative-project','Alex''s Creative Project','social',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"pitch","title":"The pitch","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Alex pitches an idea.","minimumHoursBeforeNext":30},{"id":"build","title":"Making it","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"The project takes shape.","minimumHoursBeforeNext":36},{"id":"show","title":"The showing","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The group sees what they made."}]',45,false,'minor',true),
('financial-stress','Financial Stress','setback',array['12000000-0000-4000-8000-000000000001'::uuid],'friend','{}','[{"id":"expense","title":"The expense","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"An unexpected expense lands.","minimumHoursBeforeNext":36},{"id":"plan","title":"A plan","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya makes a careful plan.","minimumHoursBeforeNext":48},{"id":"relief","title":"Relief","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The pressure eases."}]',75,false,'major',true),
('career-crossroads','Career Crossroads','career',array['12000000-0000-4000-8000-000000000001'::uuid],'dating','{}','[{"id":"offer","title":"An option","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"A career possibility appears.","minimumHoursBeforeNext":48},{"id":"weighing","title":"Weighing it","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya weighs what she wants.","minimumHoursBeforeNext":48},{"id":"choice","title":"The choice","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"Maya makes a deliberate career choice."}]',120,false,'major',true),
('bad-week','A Bad Week','wellbeing',array['12000000-0000-4000-8000-000000000001'::uuid],null,'{}','[{"id":"pileup","title":"The pileup","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"Small things pile up.","minimumHoursBeforeNext":24},{"id":"short-tempered","title":"A short fuse","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya is less patient than usual.","minimumHoursBeforeNext":24},{"id":"better","title":"A better day","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The week finally lightens."}]',45,false,'minor',true),
('surprise-free-weekend','Surprise Free Weekend','opportunity',array['12000000-0000-4000-8000-000000000001'::uuid],'friend','{}','[{"id":"opened","title":"The opened weekend","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya suddenly has a free weekend.","minimumHoursBeforeNext":24},{"id":"possibility","title":"Possibilities","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"A few plans are possible.","minimumHoursBeforeNext":48},{"id":"memory","title":"A good use of time","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The weekend becomes a memory."}]',45,false,'minor',true),
('holiday-season','Holiday Season','seasonal',array['12000000-0000-4000-8000-000000000001'::uuid],'friend','{}','[{"id":"first-lights","title":"First lights","userVisibility":"contextual","mayTriggerProactiveMessage":false,"mayCreateMoment":false,"narrativeSeed":"The city changes for the season.","minimumHoursBeforeNext":72},{"id":"tradition","title":"A small tradition","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"Maya shares a holiday ritual.","minimumHoursBeforeNext":72},{"id":"warmth","title":"Warmth","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"The season leaves a warm shared memory."}]',300,true,'major',true),
('anniversary-week','Anniversary Week','relationship',array['12000000-0000-4000-8000-000000000001'::uuid],'exclusive','{}','[{"id":"notice","title":"Noticing time","userVisibility":"contextual","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"A relationship milestone approaches.","minimumHoursBeforeNext":48},{"id":"plan","title":"A plan together","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":false,"narrativeSeed":"A meaningful plan comes together.","minimumHoursBeforeNext":48},{"id":"milestone","title":"The milestone","userVisibility":"visible","mayTriggerProactiveMessage":true,"mayCreateMoment":true,"narrativeSeed":"A relationship milestone becomes a shared moment."}]',300,true,'major',true)
on conflict(slug) do update set title=excluded.title,category=excluded.category,chapters=excluded.chapters,cooldown_days=excluded.cooldown_days,priority=excluded.priority,active=true,updated_at=now();

insert into public.together_date_templates(id,name,slug,world_id,location_id,description,hero_asset_key,phases,unlock_rules,entitlement_key,active) values
('15000000-0000-4000-8000-000000000002','Coffee at Juniper','coffee-at-juniper','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000001','A low-pressure coffee date that can surprise you by lasting longer.','maya-portrait','[{"id":"arrival","title":"Arrival","choices":[{"id":"ask-day","label":"Ask about her day"},{"id":"coffee-recommendation","label":"Ask for a recommendation"}]},{"id":"ordering","title":"Ordering","choices":[{"id":"share-favorite","label":"Share your usual"},{"id":"let-her-pick","label":"Let her choose"}]},{"id":"conversation","title":"Conversation","choices":[{"id":"ask-photography","label":"Ask about her work"},{"id":"tell-weekend","label":"Tell her about your weekend"}]},{"id":"extension","title":"One more thing","choices":[{"id":"extend-walk","label":"Suggest a walk"},{"id":"warm-goodbye","label":"Leave on a warm note"}]},{"id":"resolution","title":"A small beginning","choices":[]}]','{"familiarity":12,"trust":10,"allowed_stages":["acquaintance","friend","flirting"]}','coffee_juniper',true),
('15000000-0000-4000-8000-000000000003','Riverwalk Sunset','riverwalk-sunset','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000005','A sunset walk for unhurried conversation and city lights.','maya-portrait','[{"id":"meet","title":"Meet at dusk","choices":[{"id":"bring-coffee","label":"Bring coffee"},{"id":"arrive-early","label":"Arrive early"}]},{"id":"walk","title":"The walk","choices":[{"id":"share-story","label":"Tell a story"},{"id":"ask-dream","label":"Ask what she wants next"}]},{"id":"overlook","title":"The overlook","choices":[{"id":"stay-quiet","label":"Let the view breathe"},{"id":"make-plan","label":"Make a small plan"}]},{"id":"resolution","title":"City lights","choices":[]}]','{"familiarity":24,"trust":20,"allowed_stages":["friend","flirting","dating"]}','riverwalk_sunset',true),
('15000000-0000-4000-8000-000000000004','Rooftop Movie Night','rooftop-movie-night','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000003','A breezy rooftop film with room for a little romantic tension.','maya-portrait','[{"id":"arrival","title":"Rooftop arrival","choices":[{"id":"save-seat","label":"Save her a seat"},{"id":"bring-snacks","label":"Bring snacks"}]},{"id":"movie","title":"The movie","choices":[{"id":"commentary","label":"Trade commentary"},{"id":"watch-closely","label":"Watch closely"}]},{"id":"intermission","title":"Intermission","choices":[{"id":"tease-scene","label":"Tease a scene"},{"id":"ask-feeling","label":"Ask how she is"}]},{"id":"resolution","title":"Credits roll","choices":[]}]','{"familiarity":26,"attraction":18,"allowed_stages":["friend","flirting","dating"]}','rooftop_movie',true),
('15000000-0000-4000-8000-000000000005','Cook Together','cook-together','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000002','A home-cooking date where the mess is part of the point.','maya-portrait','[{"id":"choose-meal","title":"Choose the meal","choices":[{"id":"try-recipe","label":"Try something new"},{"id":"make-comfort","label":"Make comfort food"}]},{"id":"prep","title":"Prep","choices":[{"id":"divide-tasks","label":"Divide tasks"},{"id":"cook-together","label":"Stay side by side"}]},{"id":"mistake","title":"A small mistake","choices":[{"id":"laugh-it-off","label":"Laugh it off"},{"id":"rescue-dinner","label":"Rescue dinner"}]},{"id":"dinner","title":"Dinner","choices":[{"id":"ask-memory","label":"Ask about a memory"},{"id":"share-honestly","label":"Share honestly"}]},{"id":"cleanup","title":"Cleanup","choices":[{"id":"put-on-music","label":"Put on music"},{"id":"keep-talking","label":"Keep talking"}]},{"id":"resolution","title":"Home feels warmer","choices":[]}]','{"comfort":24,"trust":22,"allowed_stages":["flirting","dating","exclusive"]}','cook_together',true),
('15000000-0000-4000-8000-000000000006','Live Music Night','live-music-night','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000014','A live set with a little noise, a little dancing, and no perfect plan.','maya-portrait','[{"id":"meet","title":"Meet outside","choices":[{"id":"compliment-look","label":"Compliment her look"},{"id":"bring-ticket","label":"Bring the tickets"}]},{"id":"set","title":"The set","choices":[{"id":"share-song","label":"Share a song"},{"id":"dance-anyway","label":"Dance anyway"}]},{"id":"encore","title":"Encore","choices":[{"id":"stay-late","label":"Stay for one more"},{"id":"walk-home","label":"Walk home"}]},{"id":"resolution","title":"The song stays","choices":[]}]','{"attraction":24,"allowed_stages":["flirting","dating","exclusive"]}','live_music',true),
('15000000-0000-4000-8000-000000000007','Trivia Night','trivia-night','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000004','A playful group night at Northside with Alex and zero low stakes.','maya-portrait','[{"id":"team","title":"Build a team","choices":[{"id":"trust-maya","label":"Trust Maya''s category"},{"id":"ask-alex","label":"Ask Alex for strategy"}]},{"id":"round-one","title":"Round one","choices":[{"id":"take-risk","label":"Take a risk"},{"id":"play-safe","label":"Play it safe"}]},{"id":"final","title":"Final round","choices":[{"id":"make-joke","label":"Make a joke"},{"id":"focus-up","label":"Focus up"}]},{"id":"resolution","title":"A good kind of competitive","choices":[]}]','{"familiarity":22,"allowed_stages":["friend","flirting","dating"]}','trivia_night',true),
('15000000-0000-4000-8000-000000000008','Gallery Afternoon','gallery-afternoon','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000018','An art-filled afternoon that lets Maya show you how she sees images.','maya-portrait','[{"id":"entry","title":"At the gallery","choices":[{"id":"ask-favorite","label":"Ask her favorite piece"},{"id":"share-first-impression","label":"Share your first impression"}]},{"id":"rooms","title":"The rooms","choices":[{"id":"ask-craft","label":"Ask about craft"},{"id":"tell-story","label":"Tell a story"}]},{"id":"after","title":"Afterward","choices":[{"id":"coffee-after","label":"Get coffee"},{"id":"stay-longer","label":"Stay longer"}]},{"id":"resolution","title":"A different way of looking","choices":[]}]','{"trust":22,"familiarity":26,"allowed_stages":["friend","flirting","dating"]}','gallery_afternoon',true),
('15000000-0000-4000-8000-000000000009','Bookstore + Coffee','bookstore-coffee','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000019','A quiet browse that turns into trading recommendations.','maya-portrait','[{"id":"browse","title":"Browse","choices":[{"id":"pick-for-her","label":"Pick a book for her"},{"id":"ask-recommendation","label":"Ask for one"}]},{"id":"notes","title":"Marginal notes","choices":[{"id":"share-favorite","label":"Share a favorite"},{"id":"ask-childhood","label":"Ask about childhood reading"}]},{"id":"coffee","title":"Coffee after","choices":[{"id":"make-callback","label":"Make a callback"},{"id":"sit-quietly","label":"Sit quietly"}]},{"id":"resolution","title":"A page to keep","choices":[]}]','{"familiarity":20,"allowed_stages":["friend","flirting","dating"]}','bookstore_coffee',true),
('15000000-0000-4000-8000-000000000010','Stay-In Movie Night','stay-in-movie-night','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000002','A quiet at-home movie night shaped by the conversation between scenes.','maya-portrait','[{"id":"choose-film","title":"Choose a film","choices":[{"id":"pick-horror","label":"Pick horror"},{"id":"pick-classic","label":"Pick a classic"}]},{"id":"settle-in","title":"Settle in","choices":[{"id":"make-popcorn","label":"Make popcorn"},{"id":"share-blanket","label":"Share a blanket"}]},{"id":"pause","title":"Pause the movie","choices":[{"id":"talk-real","label":"Talk about something real"},{"id":"tease-scene","label":"Tease the scene"}]},{"id":"resolution","title":"The credits can wait","choices":[]}]','{"comfort":28,"allowed_stages":["dating","exclusive","long_term"]}','stay_in_movie',true),
('15000000-0000-4000-8000-000000000011','Spontaneous Night Out','spontaneous-night-out','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000011','A loose plan that becomes whatever the city gives you.','maya-portrait','[{"id":"text","title":"The text","choices":[{"id":"say-yes-fast","label":"Say yes immediately"},{"id":"suggest-place","label":"Suggest a place"}]},{"id":"first-stop","title":"First stop","choices":[{"id":"order-weird","label":"Order something weird"},{"id":"make-friends","label":"Make friends"}]},{"id":"turn","title":"A turn in the night","choices":[{"id":"go-karaoke","label":"Go karaoke"},{"id":"find-quiet","label":"Find somewhere quiet"}]},{"id":"resolution","title":"No plan, good story","choices":[]}]','{"attraction":28,"allowed_stages":["flirting","dating","exclusive"]}','spontaneous_night_out',true),
('15000000-0000-4000-8000-000000000012','Weekend Day Trip','weekend-day-trip','10000000-0000-4000-8000-000000000001','11000000-0000-4000-8000-000000000025','A day outside the usual city loop, built for shared discoveries.','maya-portrait','[{"id":"depart","title":"Depart","choices":[{"id":"bring-snacks","label":"Bring snacks"},{"id":"make-playlist","label":"Make a playlist"}]},{"id":"explore","title":"Explore","choices":[{"id":"take-photo","label":"Take a photo"},{"id":"follow-trail","label":"Follow a trail"}]},{"id":"lunch","title":"Lunch","choices":[{"id":"share-dessert","label":"Share dessert"},{"id":"ask-future","label":"Ask about the future"}]},{"id":"return","title":"The return","choices":[{"id":"extend-day","label":"Extend the day"},{"id":"quiet-ride","label":"Enjoy the quiet ride"}]},{"id":"resolution","title":"A little farther together","choices":[]}]','{"trust":30,"comfort":30,"allowed_stages":["dating","exclusive","long_term"]}','weekend_day_trip',true)
on conflict(id) do update set name=excluded.name,slug=excluded.slug,location_id=excluded.location_id,description=excluded.description,phases=excluded.phases,unlock_rules=excluded.unlock_rules,entitlement_key=excluded.entitlement_key,active=true,updated_at=now();

insert into public.together_trip_templates(slug,title,description,min_relationship_stage,duration_days,locations,itinerary,content_level,active) values
('beach-weekend','Beach Weekend','A temporary coastal mini-world: hotel, beach, boardwalk, dinner, and a quiet balcony.','dating',2,'[{"id":"hotel","name":"Harbor Hotel"},{"id":"beach","name":"South Beach"},{"id":"boardwalk","name":"Boardwalk"},{"id":"restaurant","name":"Sea Glass"},{"id":"balcony","name":"Balcony"}]','[{"day":1,"beats":["arrival","beach","dinner"]},{"day":2,"beats":["boardwalk","sunrise","return"]}]','romance',true),
('mountain-cabin','Mountain Cabin','A quiet temporary world: cabin, trail, overlook, and a nearby town.','dating',2,'[{"id":"cabin","name":"Pineglass Cabin"},{"id":"trail","name":"Blue Ridge Trail"},{"id":"overlook","name":"Cedar Overlook"},{"id":"town","name":"Hollow Creek"}]','[{"day":1,"beats":["drive","cabin","fire"]},{"day":2,"beats":["trail","overlook","return"]}]','romance',true)
on conflict(slug) do update set title=excluded.title,description=excluded.description,locations=excluded.locations,itinerary=excluded.itinerary,active=true,updated_at=now();

insert into public.together_photo_opportunities(slug,title,trigger_event_category,location_tags,relationship_stages,content_level,shot_type,prompt_seed,metadata,active)
select 'city-life-'||item.slug,item.title,item.category,item.tags,array['friend','flirting','dating','exclusive','long_term'],'standard',item.shot_type,item.prompt_seed,jsonb_build_object('display_context',item.context),true
from (values
('candid','Café candid','ordinary',array['cafe'],'candid','Warm candid at a City Life café, natural window light.','coffee stop'),
('new-outfit','New outfit','personal',array['shopping'],'portrait','Companion trying a new outfit in a city mirror, grounded and natural.','outfit search'),
('photo-shoot','Finished shoot','work',array['work'],'portrait','Companion after a creative shoot, camera and soft studio light.','work success'),
('rooftop','Rooftop evening','romance',array['nightlife'],'scene','Companion at a rooftop evening, city lights and a candid smile.','rooftop evening'),
('rainy','Rainy afternoon','weather',array['cafe','home'],'selfie','Companion on a rainy afternoon, warm layers and soft window light.','rainy day'),
('chloe','Friend selfie','social',array['social'],'selfie','Companion and a close friend at a casual city gathering.','friend moment'),
('apartment','Apartment scene','personal',array['home'],'scene','Companion at home surrounded by personal creative details.','home life'),
('garden','Garden walk','discovery',array['outdoors'],'candid','Companion during a botanical garden walk, natural colors and candid framing.','day out'),
('music','Live music','social',array['music'],'scene','Companion at an intimate live music venue, ambient stage light.','live music'),
('bookstore','Bookstore find','discovery',array['books'],'portrait','Companion holding a book in an independent bookshop.','recommendation')
) as item(slug,title,category,tags,shot_type,prompt_seed,context)
on conflict(slug) do update set title=excluded.title,trigger_event_category=excluded.trigger_event_category,location_tags=excluded.location_tags,shot_type=excluded.shot_type,prompt_seed=excluded.prompt_seed,metadata=excluded.metadata,active=true,updated_at=now();

comment on table public.together_story_arc_templates is 'Authored structural story graphs. Models provide expression, never chapter truth.';
comment on table public.together_content_usage is 'Recent-content memory used to penalize repetition and inspect simulation variety.';
