begin;

-- Direct video generation previously inherited a hard-coded standard content
-- level from v4. v5 persists the independently authorized website-adult policy
-- on both the hidden opening frame and final video. The database re-verifies
-- eligibility, paid entitlement, and the exact unexpired web session before it
-- reserves credits, so a forged function payload cannot unlock adult output.
create or replace function public.kivelle_reserve_direct_video_generation_v5(
  p_user_id uuid,p_continuity_id uuid,p_character_instance_id uuid,p_conversation_id uuid,p_request_key text,p_source_frame_request_key text,
  p_route_id text,p_motion_preset text,p_provider text,p_model text,p_requested_model text,p_resolved_model text,p_credit_cost integer,p_quote_usd numeric,p_baseline_usd numeric,
  p_duration_seconds integer,p_resolution text,p_audio_behavior text,p_sound_requested boolean,p_provider_audio_mode text,p_aspect_ratio text,p_user_prompt text,
  p_content_level text,p_adult_authorized boolean,p_adult_web_session_id uuid,p_anonymous_adult_partner boolean,p_reference_assets jsonb,
  p_route_concurrency_limit integer,p_location_id uuid,p_world_id uuid,p_place_context jsonb,p_source_frame_metadata jsonb
) returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare
  character_instance public.together_character_instances;existing_media public.together_generated_media;account public.together_credit_accounts;
  video_id uuid:=gen_random_uuid();source_frame_id uuid:=gen_random_uuid();transaction_id uuid:=gen_random_uuid();subscription_spend integer;permanent_spend integer;active_count integer;
  restricted boolean:=p_content_level in('suggestive','mature','explicit');adult_metadata jsonb;
begin
  if p_request_key is null or char_length(p_request_key)<12 or p_source_frame_request_key is null or char_length(p_source_frame_request_key)<12 then raise exception using errcode='22023',message='INVALID_VIDEO_REQUEST_KEY';end if;
  if p_provider<>'wavespeed' or p_model<>p_requested_model or p_model<>p_resolved_model or not public.kivelle_video_configuration_valid(p_route_id,p_model,p_duration_seconds,p_resolution,p_sound_requested,p_provider_audio_mode) then raise exception using errcode='22023',message='INVALID_VIDEO_ROUTE_CONFIGURATION';end if;
  if p_motion_preset not in('subtle','playful','cinematic') or p_aspect_ratio not in('9:16','16:9') or char_length(trim(coalesce(p_user_prompt,''))) not between 2 and 400 or p_audio_behavior<>(case when p_sound_requested then 'generated_audio' else 'silent' end) then raise exception using errcode='22023',message='INVALID_VIDEO_INTENT';end if;
  if p_content_level not in('standard','romance','suggestive','mature','explicit') or coalesce(p_adult_authorized,false)<>restricted or (not restricted and (p_adult_web_session_id is not null or coalesce(p_anonymous_adult_partner,false))) or (restricted and p_adult_web_session_id is null) then raise exception using errcode='22023',message='INVALID_VIDEO_CONTENT_POLICY';end if;
  if p_credit_cost<1 or p_credit_cost>100000 or p_quote_usd<0 or p_baseline_usd<0 or p_route_concurrency_limit not between 1 and 8 then raise exception using errcode='22023',message='INVALID_VIDEO_ECONOMICS';end if;
  if jsonb_typeof(coalesce(p_reference_assets,'[]'::jsonb))<>'array' or jsonb_array_length(coalesce(p_reference_assets,'[]'::jsonb))>12 or jsonb_typeof(coalesce(p_place_context,'{}'::jsonb))<>'object' or jsonb_typeof(coalesce(p_source_frame_metadata,'{}'::jsonb))<>'object' then raise exception using errcode='22023',message='INVALID_VIDEO_CONTEXT';end if;
  if restricted and not (
    exists(select 1 from public.together_profiles profile where profile.user_id=p_user_id and profile.adult_eligible_at is not null)
    and exists(select 1 from public.together_entitlements entitlement where entitlement.user_id=p_user_id and entitlement.tier<>'free' and (entitlement.expires_at is null or entitlement.expires_at>now()))
    and exists(select 1 from public.together_web_adult_sessions session where session.id=p_adult_web_session_id and session.user_id=p_user_id and session.adult_mode_enabled=true and session.revoked_at is null and session.expires_at>now())
  ) then raise exception using errcode='P0001',message='WEB_ADULT_VIDEO_AUTHORIZATION_REQUIRED';end if;
  perform pg_advisory_xact_lock(hashtextextended('kivelle-video-user:'||p_user_id::text,0));select * into existing_media from public.together_generated_media where user_id=p_user_id and request_key=p_request_key;
  if existing_media.id is not null then select * into account from public.together_credit_accounts where user_id=p_user_id;return jsonb_build_object('mediaId',existing_media.id,'sourceFrameId',existing_media.parent_media_id,'transactionId',existing_media.metadata->>'creditTransactionId','idempotent',true,'total',coalesce(account.permanent_balance,0)+coalesce(account.subscription_balance,0));end if;
  select * into character_instance from public.together_character_instances where id=p_character_instance_id and user_id=p_user_id and continuity_id=p_continuity_id for share;if character_instance.id is null then raise exception using errcode='P0001',message='VIDEO_CHARACTER_UNAVAILABLE';end if;
  if not exists(select 1 from public.together_worlds where id=p_world_id and published=true) then raise exception using errcode='P0001',message='VIDEO_WORLD_UNAVAILABLE';end if;if p_location_id is not null and not exists(select 1 from public.together_locations where id=p_location_id and world_id=p_world_id) then raise exception using errcode='P0001',message='VIDEO_LOCATION_UNAVAILABLE';end if;
  if not exists(select 1 from public.together_character_templates template join public.together_character_versions version on version.id=character_instance.character_version_id where template.id=character_instance.character_template_id and template.age>=18 and coalesce(template.discovery_metadata->>'fictional','true')<>'false' and coalesce(version.character_bible->>'fictional','true')<>'false' and coalesce(version.visual_identity->>'fictional','true')<>'false' and (case when jsonb_typeof(version.visual_identity->'referenceStoragePaths')='array' then jsonb_array_length(version.visual_identity->'referenceStoragePaths')>0 else false end or exists(select 1 from jsonb_array_elements(coalesce(p_reference_assets,'[]'::jsonb)) item where item->>'role'='character_identity'))) then raise exception using errcode='P0001',message='VIDEO_SINGLE_FICTIONAL_ADULT_REQUIRED';end if;
  if p_conversation_id is not null and not exists(select 1 from public.together_conversations where id=p_conversation_id and user_id=p_user_id and continuity_id=p_continuity_id and character_instance_id=p_character_instance_id) then raise exception using errcode='P0001',message='VIDEO_CONVERSATION_UNAVAILABLE';end if;
  select count(*) into active_count from public.together_generated_media where user_id=p_user_id and media_type='video' and status in('queued','generating');if active_count>0 then raise exception using errcode='P0001',message='ACTIVE_VIDEO_EXISTS';end if;
  insert into public.together_credit_accounts(user_id) values(p_user_id) on conflict(user_id) do nothing;select * into account from public.together_credit_accounts where user_id=p_user_id for update;if account.permanent_balance+account.subscription_balance<p_credit_cost then raise exception using errcode='P0001',message='INSUFFICIENT_KIVELLE_CREDITS';end if;
  subscription_spend=least(account.subscription_balance,p_credit_cost);permanent_spend=p_credit_cost-subscription_spend;update public.together_credit_accounts set subscription_balance=subscription_balance-subscription_spend,permanent_balance=permanent_balance-permanent_spend,updated_at=clock_timestamp() where user_id=p_user_id returning * into account;
  adult_metadata:=case when restricted then jsonb_build_object('adultAuthorized',true,'adultWebSessionId',p_adult_web_session_id,'moderationVersion','web-adult-video-v1') else '{}'::jsonb end||case when p_anonymous_adult_partner then jsonb_build_object('anonymousAdultPartner',true,'expectedAdultSubjectCount',2) else '{}'::jsonb end;
  insert into public.together_credit_ledger(id,user_id,event_type,permanent_delta,subscription_delta,idempotency_key,reference_type,reference_id,metadata) values(transaction_id,p_user_id,'spend',-permanent_spend,-subscription_spend,'media-video:'||p_request_key,'generated_media',video_id::text,jsonb_build_object('action','direct_video','characterInstanceId',p_character_instance_id,'videoRouteId',p_route_id,'requestedModel',p_requested_model,'durationSeconds',p_duration_seconds,'resolution',p_resolution,'soundRequested',p_sound_requested,'contentLevel',p_content_level,'locationId',p_location_id,'worldId',p_world_id));
  insert into public.together_generated_media(id,user_id,continuity_id,character_instance_id,subject_character_instance_ids,conversation_id,world_id,location_id,media_type,content_level,status,request_key,queue_priority,metadata) values(source_frame_id,p_user_id,p_continuity_id,p_character_instance_id,array[p_character_instance_id],p_conversation_id,p_world_id,p_location_id,'image',p_content_level,'queued',p_source_frame_request_key,0,coalesce(p_source_frame_metadata,'{}'::jsonb)||adult_metadata||jsonb_build_object('source','direct_video_frame','hiddenIntermediate',true,'directVideoTargetMediaId',video_id,'requestKey',p_source_frame_request_key,'referenceAssets',coalesce(p_reference_assets,'[]'::jsonb),'placeContext',coalesce(p_place_context,'{}'::jsonb),'routeConcurrencyLimit',1,'creditCost',0));
  insert into public.together_generated_media(id,user_id,continuity_id,character_instance_id,subject_character_instance_ids,conversation_id,world_id,location_id,parent_media_id,media_type,content_level,status,request_key,queue_priority,video_route_id,motion_preset,requested_duration_seconds,requested_resolution,requested_audio_behavior,sound_requested,provider_audio_mode,requested_model,resolved_model,source_aspect_ratio,provider_quote_usd,provider_baseline_cost_usd,testing_selection,video_source_mode,user_prompt,metadata)
  values(video_id,p_user_id,p_continuity_id,p_character_instance_id,array[p_character_instance_id],p_conversation_id,p_world_id,p_location_id,source_frame_id,'video',p_content_level,'queued',p_request_key,0,p_route_id,p_motion_preset,p_duration_seconds,p_resolution,p_audio_behavior,p_sound_requested,p_provider_audio_mode,p_requested_model,p_resolved_model,p_aspect_ratio,p_quote_usd,p_baseline_usd,true,'source_photo',trim(p_user_prompt),jsonb_build_object('source','user_request','videoSourceMode','source_photo','requestKey',p_request_key,'creditTransactionId',transaction_id,'creditCost',p_credit_cost,'creditAction','direct_video','creditRefunded',false,'routeConcurrencyLimit',p_route_concurrency_limit,'locationId',p_location_id,'worldId',p_world_id,'locationSource',p_source_frame_metadata->>'locationSource','activity',p_source_frame_metadata->>'activity','mood',character_instance.current_mood,'aspectRatio',p_aspect_ratio,'placeContext',coalesce(p_place_context,'{}'::jsonb),'referenceAssets',coalesce(p_reference_assets,'[]'::jsonb),'generationIntent',jsonb_build_object('requestText',trim(p_user_prompt),'requestedContentLevel',p_content_level),'directVideoGeneratedFirstFrame',true,'directVideoSourceFrameId',source_frame_id,'videoRequest',jsonb_build_object('routeId',p_route_id,'requestedModel',p_requested_model,'resolvedModel',p_resolved_model,'motionPreset',p_motion_preset,'durationSeconds',p_duration_seconds,'resolution',p_resolution,'soundRequested',p_sound_requested,'providerAudioMode',p_provider_audio_mode,'quotedCostUsd',p_quote_usd,'baselineCostUsd',p_baseline_usd,'aspectRatio',p_aspect_ratio,'testingSelection',true))||adult_metadata);
  return jsonb_build_object('mediaId',video_id,'sourceFrameId',source_frame_id,'transactionId',transaction_id,'idempotent',false,'permanentBalance',account.permanent_balance,'subscriptionBalance',account.subscription_balance,'total',account.permanent_balance+account.subscription_balance);
end $$;

revoke all on function public.kivelle_reserve_direct_video_generation_v5(uuid,uuid,uuid,uuid,text,text,text,text,text,text,text,text,integer,numeric,numeric,integer,text,text,boolean,text,text,text,text,boolean,uuid,boolean,jsonb,integer,uuid,uuid,jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.kivelle_reserve_direct_video_generation_v5(uuid,uuid,uuid,uuid,text,text,text,text,text,text,text,text,integer,numeric,numeric,integer,text,text,boolean,text,text,text,text,boolean,uuid,boolean,jsonb,integer,uuid,uuid,jsonb,jsonb) to service_role;

commit;
