import { z } from 'zod';
import { authenticated, enforceRateLimit } from '../_shared/context.ts';
import { parseBody } from '../_shared/body.ts';
import { json, serve } from '../_shared/http.ts';
import { AppError } from '../_shared/types.ts';
import { TOGETHER_IDS, track } from '../_shared/together.ts';

const schema=z.object({activity:z.enum(['riverwalk','open_mic','rooftop_movie']),choice:z.enum(['accept','defer'])});
const options={riverwalk:{title:'Sunset Walk at Riverwalk',summary:'You and Maya took an unhurried walk along the Riverwalk as the city lights came on.',location:TOGETHER_IDS.riverwalk},open_mic:{title:'Open Mic at Juniper',summary:'You and Maya found a table near the stage at Juniper and stayed later than planned.',location:TOGETHER_IDS.juniper},rooftop_movie:{title:'Rooftop Movie Night',summary:'You and Maya watched a movie under the city lights at Skyline Rooftop.',location:TOGETHER_IDS.rooftop}} as const;
serve(async(request,correlationId)=>{const{user,db}=await authenticated(request);await enforceRateLimit(db,user.id,'together_activity',20,3600);const input=await parseBody(request,schema);if(input.choice==='defer')return json({data:{accepted:false},correlationId});const maya=(await db.from('together_character_instances').select('*').eq('user_id',user.id).eq('character_template_id',TOGETHER_IDS.maya).maybeSingle()).data;if(!maya)throw new AppError('NOT_FOUND','Maya is unavailable.',404);if(!maya.contact_added_at)throw new AppError('CONFLICT','Get to know Maya a little first.',409);const item=options[input.activity];const now=new Date().toISOString();const event=(await db.from('together_life_events').insert({user_id:user.id,character_instance_id:maya.id,event_type:'shared_activity',title:item.title,narrative_summary:item.summary,participant_instance_ids:[maya.id],location_id:item.location,significance:.68,starts_at:now,resulting_state_changes:{sharedActivity:input.activity},user_should_know:true,proactive_message_appropriate:false}).select('*').single()).data;if(!event)throw new AppError('INTERNAL_ERROR','The plan could not be saved.',500,true);const moment=(await db.from('together_moments').insert({user_id:user.id,character_instance_id:maya.id,title:item.title,occurred_at:now,location_id:item.location,summary:item.summary,participant_instance_ids:[maya.id],relationship_impact:{familiarity:2,comfort:1},media:[{asset:'maya-portrait'}],moment_type:'shared_activity'}).select('*').single()).data;await track(db,user.id,'shared_activity_accepted',{activity:input.activity,eventId:event.id});return json({data:{accepted:true,event,moment},correlationId},201,correlationId);});
