import { catalogArtwork } from '../catalogArtwork';
import type {ImageSource} from 'expo-image';
import type {CaldersRunLocationSlug} from './calders-run-catalog';

export const caldersRunLocationAssets={
  'argosy-cardroom':catalogArtwork('locations/calders-run/argosy-cardroom.jpg'),
  'assay-office':catalogArtwork('locations/calders-run/assay-office.jpg'),
  'bellflower-theater':catalogArtwork('locations/calders-run/bellflower-theater.jpg'),
  'blue-glass-baths':catalogArtwork('locations/calders-run/blue-glass-baths.jpg'),
  'boatmens-boardinghouse':catalogArtwork('locations/calders-run/boatmens-boardinghouse.jpg'),
  'bridge-works':catalogArtwork('locations/calders-run/bridge-works.jpg'),
  'calder-house-hotel':catalogArtwork('locations/calders-run/calder-house-hotel.jpg'),
  'calder-portrait-studio':catalogArtwork('locations/calders-run/calder-portrait-studio.jpg'),
  'canyon-rest-cemetery':catalogArtwork('locations/calders-run/canyon-rest-cemetery.jpg'),
  'cattle-sale-yard':catalogArtwork('locations/calders-run/cattle-sale-yard.jpg'),
  'cinder-bluffs':catalogArtwork('locations/calders-run/cinder-bluffs.jpg'),
  'copper-mare-saloon':catalogArtwork('locations/calders-run/copper-mare-saloon.jpg'),
  'cottonwood-dispensary':catalogArtwork('locations/calders-run/cottonwood-dispensary.jpg'),
  'cottonwood-swimming-bend':catalogArtwork('locations/calders-run/cottonwood-swimming-bend.jpg'),
  'cottonwood-valley':catalogArtwork('locations/calders-run/cottonwood-valley.jpg'),
  'county-courthouse':catalogArtwork('locations/calders-run/county-courthouse.jpg'),
  'crowcut-hollow':catalogArtwork('locations/calders-run/crowcut-hollow.jpg'),
  'crown-and-cotton':catalogArtwork('locations/calders-run/crown-and-cotton.jpg'),
  'dempsey-livery':catalogArtwork('locations/calders-run/dempsey-livery.jpg'),
  'eastbank-provisioners':catalogArtwork('locations/calders-run/eastbank-provisioners.jpg'),
  'hearthstone-bakery':catalogArtwork('locations/calders-run/hearthstone-bakery.jpg'),
  'irrigation-meeting-house':catalogArtwork('locations/calders-run/irrigation-meeting-house.jpg'),
  'junebug-dance-hall':catalogArtwork('locations/calders-run/junebug-dance-hall.jpg'),
  'keenes-print-shop':catalogArtwork('locations/calders-run/keenes-print-shop.jpg'),
  'lantern-row':catalogArtwork('locations/calders-run/lantern-row.jpg'),
  'main-street':catalogArtwork('locations/calders-run/main-street.jpg'),
  'marigold-house':catalogArtwork('locations/calders-run/marigold-house.jpg'),
  'marshals-office':catalogArtwork('locations/calders-run/marshals-office.jpg'),
  'mule-camp-trading-post':catalogArtwork('locations/calders-run/mule-camp-trading-post.jpg'),
  'night-kitchen':catalogArtwork('locations/calders-run/night-kitchen.jpg'),
  'old-calder-relay':catalogArtwork('locations/calders-run/old-calder-relay.jpg'),
  'orchard-glasshouse':catalogArtwork('locations/calders-run/orchard-glasshouse.jpg'),
  'orchard-schoolhouse':catalogArtwork('locations/calders-run/orchard-schoolhouse.jpg'),
  'pike-boatworks':catalogArtwork('locations/calders-run/pike-boatworks.jpg'),
  'pikes-ferry':catalogArtwork('locations/calders-run/pikes-ferry.jpg'),
  'public-washhouse':catalogArtwork('locations/calders-run/public-washhouse.jpg'),
  'railroad-freight-office':catalogArtwork('locations/calders-run/railroad-freight-office.jpg'),
  'red-sash-brothel':catalogArtwork('locations/calders-run/red-sash-brothel.jpg'),
  'red-wells-prospect':catalogArtwork('locations/calders-run/red-wells-prospect.jpg'),
  'ribbon-room':catalogArtwork('locations/calders-run/ribbon-room.jpg'),
  'river-market':catalogArtwork('locations/calders-run/river-market.jpg'),
  'river-ward':catalogArtwork('locations/calders-run/river-ward.jpg'),
  'riverside-chapel':catalogArtwork('locations/calders-run/riverside-chapel.jpg'),
  'saint-agnes-mine':catalogArtwork('locations/calders-run/saint-agnes-mine.jpg'),
  'salcedo-clinic':catalogArtwork('locations/calders-run/salcedo-clinic.jpg'),
  'soto-forge':catalogArtwork('locations/calders-run/soto-forge.jpg'),
  'survey-camp':catalogArtwork('locations/calders-run/survey-camp.jpg'),
  'telegraph-office':catalogArtwork('locations/calders-run/telegraph-office.jpg'),
  'temporary-passenger-depot':catalogArtwork('locations/calders-run/temporary-passenger-depot.jpg'),
  'the-railhead':catalogArtwork('locations/calders-run/the-railhead.jpg'),
  'valley-creamery':catalogArtwork('locations/calders-run/valley-creamery.jpg'),
  'whitcomb-ranch':catalogArtwork('locations/calders-run/whitcomb-ranch.jpg'),
  'widows-cut-coach-station':catalogArtwork('locations/calders-run/widows-cut-coach-station.jpg'),
} satisfies Record<CaldersRunLocationSlug,ImageSource>;
