export const juniperCityMappedLocationSlugs=[
  'alder-house',
  'alder-district',
  'civic-commons',
  'common-market',
  'chloe-design-studio',
  'ember-and-rye',
  'glassline-gallery',
  'halcyon-green',
  'halcyon-park',
  'juniper-central-station',
  'juniper-city-hall',
  'juniper-medical-center',
  'lantern-dive',
  'lark-botanical-garden',
  'lucky-note',
  'juniper-civic-arena',
  'juniper-cafe',
  'marquee-cinema',
  'marquee-quarter',
  'maya-apartment',
  'meridian-fitness',
  'moss-and-crumb',
  'needles-and-notes',
  'northline-motor-lodge',
  'northside',
  'northside-bar',
  'paper-trail',
  'photography-studio',
  'pixel-and-pint',
  'red-hour',
  'riverhouse-apartments',
  'riverside',
  'riverside-landing',
  'riverwalk',
  'rivermark-hotel',
  'side-street-comedy',
  'skyline-rooftop',
  'sora-table',
  'static-house',
  'taqueria-lumen',
] as const;

// Geography v2 artwork can be staged here without creating unresolved Metro imports.
export const juniperCityPendingLocationAssetSlugs=[] as const;

export const neonKyoMappedLocationSlugs=[
  'hikari-core','shinjira','aoyama-nine','akiba-undergrid','tsuki-blocks','old-kyo-the-shade',
  'hikari-crossing','maison-vice','kissaten-88','hikari-capsule-club','mirror-hikari','pulse-arcade','hikari-skybridge',
  'velvet-static','room-thirteen','hotel-nocturne','scarlet-garden','ghost-line','red-lantern-alley','eden-shinjira',
  'glass-house','halo-aoyama','maison-nine','aoyama-modification-institute','gallery-null','saint-aoyama','the-atrium',
  'zeroday','syn-club','dollhouse-robotics','dreamscape','chrome-kiss','the-backroom','nova-arena',
  'tsuki-tower-17','twentyfour','laundry-nine','moonpool','the-balcony','kumo-gym','quiet-hours',
  'tsukimi-shrine','whisper-bridge','ryokan-kaze','velvet-shrine','koi-garden','soba-miyako','below-kyo',
  'paper-moon-books','lantern-street','tea-house-aoi',
] as const;
