import type { ImageSource } from 'expo-image';

// Every Eos Meridian district and venue has its own authored artwork. Keep this
// map explicit so Metro can statically bundle the assets on native and web.
export const eosMeridianLocationAssets: Record<string, ImageSource> = {
  'meridian-core': require('../../assets/locations/eos-meridian/meridian-core.jpg'),
  'meridian-concourse': require('../../assets/locations/eos-meridian/meridian-concourse.jpg'),
  'charter-hall': require('../../assets/locations/eos-meridian/charter-hall.jpg'),
  'blue-shift': require('../../assets/locations/eos-meridian/blue-shift.jpg'),
  'atlas-market': require('../../assets/locations/eos-meridian/atlas-market.jpg'),
  'pioneer-memorial': require('../../assets/locations/eos-meridian/pioneer-memorial.jpg'),
  'meridian-medical-center': require('../../assets/locations/eos-meridian/meridian-medical-center.jpg'),
  'common-room': require('../../assets/locations/eos-meridian/common-room.jpg'),
  'crown-habitat': require('../../assets/locations/eos-meridian/crown-habitat.jpg'),
  'solace-biome': require('../../assets/locations/eos-meridian/solace-biome.jpg'),
  'orchard-nine': require('../../assets/locations/eos-meridian/orchard-nine.jpg'),
  'rain-room': require('../../assets/locations/eos-meridian/rain-room.jpg'),
  'solace-reservoir': require('../../assets/locations/eos-meridian/solace-reservoir.jpg'),
  'hearth-kitchens': require('../../assets/locations/eos-meridian/hearth-kitchens.jpg'),
  'pollinator-house': require('../../assets/locations/eos-meridian/pollinator-house.jpg'),
  'verdant-clinic': require('../../assets/locations/eos-meridian/verdant-clinic.jpg'),
  'the-canopy': require('../../assets/locations/eos-meridian/the-canopy.jpg'),
  'solace-commons': require('../../assets/locations/eos-meridian/solace-commons.jpg'),
  'ascension-port': require('../../assets/locations/eos-meridian/ascension-port.jpg'),
  'ascension-terminal': require('../../assets/locations/eos-meridian/ascension-terminal.jpg'),
  'docking-spine': require('../../assets/locations/eos-meridian/docking-spine.jpg'),
  'wayfarer-hotel': require('../../assets/locations/eos-meridian/wayfarer-hotel.jpg'),
  'customs-hall': require('../../assets/locations/eos-meridian/customs-hall.jpg'),
  'last-window': require('../../assets/locations/eos-meridian/last-window.jpg'),
  'drift-gym': require('../../assets/locations/eos-meridian/drift-gym.jpg'),
  'cargo-exchange': require('../../assets/locations/eos-meridian/cargo-exchange.jpg'),
  'hangar-twelve': require('../../assets/locations/eos-meridian/hangar-twelve.jpg'),
  'forge-ward': require('../../assets/locations/eos-meridian/forge-ward.jpg'),
  'helix-fabrication': require('../../assets/locations/eos-meridian/helix-fabrication.jpg'),
  'caldera-reactor': require('../../assets/locations/eos-meridian/caldera-reactor.jpg'),
  'the-rivet': require('../../assets/locations/eos-meridian/the-rivet.jpg'),
  'forge-union-hall': require('../../assets/locations/eos-meridian/forge-union-hall.jpg'),
  'redline-garage': require('../../assets/locations/eos-meridian/redline-garage.jpg'),
  'foundry-baths': require('../../assets/locations/eos-meridian/foundry-baths.jpg'),
  'salvage-court': require('../../assets/locations/eos-meridian/salvage-court.jpg'),
  'pressure-school': require('../../assets/locations/eos-meridian/pressure-school.jpg'),
  'nightglass': require('../../assets/locations/eos-meridian/nightglass.jpg'),
  'nightglass-observatory': require('../../assets/locations/eos-meridian/nightglass-observatory.jpg'),
  'aurora-house': require('../../assets/locations/eos-meridian/aurora-house.jpg'),
  'kepler-iceworks': require('../../assets/locations/eos-meridian/kepler-iceworks.jpg'),
  'listening-station-seven': require('../../assets/locations/eos-meridian/listening-station-seven.jpg'),
  'black-lake': require('../../assets/locations/eos-meridian/black-lake.jpg'),
  'thermal-garden': require('../../assets/locations/eos-meridian/thermal-garden.jpg'),
  'farline-laboratory': require('../../assets/locations/eos-meridian/farline-laboratory.jpg'),
  'eventide-overlook': require('../../assets/locations/eos-meridian/eventide-overlook.jpg'),
  'old-meridian': require('../../assets/locations/eos-meridian/old-meridian.jpg'),
  'first-habitat': require('../../assets/locations/eos-meridian/first-habitat.jpg'),
  'velvet-gravity': require('../../assets/locations/eos-meridian/velvet-gravity.jpg'),
  'quiet-orbit': require('../../assets/locations/eos-meridian/quiet-orbit.jpg'),
  'static-garden': require('../../assets/locations/eos-meridian/static-garden.jpg'),
  'needle-and-thread': require('../../assets/locations/eos-meridian/needle-and-thread.jpg'),
  'the-airlock-diner': require('../../assets/locations/eos-meridian/the-airlock-diner.jpg'),
  'archive-zero': require('../../assets/locations/eos-meridian/archive-zero.jpg'),
  'ghost-junction': require('../../assets/locations/eos-meridian/ghost-junction.jpg'),
};
