import { catalogArtwork } from '../catalogArtwork';
import type { ImageSource } from 'expo-image';

// Every Eos Meridian district and venue has its own authored artwork. Keep this
// map explicit so Metro can statically bundle the assets on native and web.
export const eosMeridianLocationAssets: Record<string, ImageSource> = {
  'meridian-core': catalogArtwork('locations/eos-meridian/meridian-core.jpg'),
  'meridian-concourse': catalogArtwork('locations/eos-meridian/meridian-concourse.jpg'),
  'charter-hall': catalogArtwork('locations/eos-meridian/charter-hall.jpg'),
  'blue-shift': catalogArtwork('locations/eos-meridian/blue-shift.jpg'),
  'atlas-market': catalogArtwork('locations/eos-meridian/atlas-market.jpg'),
  'pioneer-memorial': catalogArtwork('locations/eos-meridian/pioneer-memorial.jpg'),
  'meridian-medical-center': catalogArtwork('locations/eos-meridian/meridian-medical-center.jpg'),
  'common-room': catalogArtwork('locations/eos-meridian/common-room.jpg'),
  'crown-habitat': catalogArtwork('locations/eos-meridian/crown-habitat.jpg'),
  'solace-biome': catalogArtwork('locations/eos-meridian/solace-biome.jpg'),
  'orchard-nine': catalogArtwork('locations/eos-meridian/orchard-nine.jpg'),
  'rain-room': catalogArtwork('locations/eos-meridian/rain-room.jpg'),
  'solace-reservoir': catalogArtwork('locations/eos-meridian/solace-reservoir.jpg'),
  'hearth-kitchens': catalogArtwork('locations/eos-meridian/hearth-kitchens.jpg'),
  'pollinator-house': catalogArtwork('locations/eos-meridian/pollinator-house.jpg'),
  'verdant-clinic': catalogArtwork('locations/eos-meridian/verdant-clinic.jpg'),
  'the-canopy': catalogArtwork('locations/eos-meridian/the-canopy.jpg'),
  'solace-commons': catalogArtwork('locations/eos-meridian/solace-commons.jpg'),
  'ascension-port': catalogArtwork('locations/eos-meridian/ascension-port.jpg'),
  'ascension-terminal': catalogArtwork('locations/eos-meridian/ascension-terminal.jpg'),
  'docking-spine': catalogArtwork('locations/eos-meridian/docking-spine.jpg'),
  'wayfarer-hotel': catalogArtwork('locations/eos-meridian/wayfarer-hotel.jpg'),
  'customs-hall': catalogArtwork('locations/eos-meridian/customs-hall.jpg'),
  'last-window': catalogArtwork('locations/eos-meridian/last-window.jpg'),
  'drift-gym': catalogArtwork('locations/eos-meridian/drift-gym.jpg'),
  'cargo-exchange': catalogArtwork('locations/eos-meridian/cargo-exchange.jpg'),
  'hangar-twelve': catalogArtwork('locations/eos-meridian/hangar-twelve.jpg'),
  'forge-ward': catalogArtwork('locations/eos-meridian/forge-ward.jpg'),
  'helix-fabrication': catalogArtwork('locations/eos-meridian/helix-fabrication.jpg'),
  'caldera-reactor': catalogArtwork('locations/eos-meridian/caldera-reactor.jpg'),
  'the-rivet': catalogArtwork('locations/eos-meridian/the-rivet.jpg'),
  'forge-union-hall': catalogArtwork('locations/eos-meridian/forge-union-hall.jpg'),
  'redline-garage': catalogArtwork('locations/eos-meridian/redline-garage.jpg'),
  'foundry-baths': catalogArtwork('locations/eos-meridian/foundry-baths.jpg'),
  'salvage-court': catalogArtwork('locations/eos-meridian/salvage-court.jpg'),
  'pressure-school': catalogArtwork('locations/eos-meridian/pressure-school.jpg'),
  'nightglass': catalogArtwork('locations/eos-meridian/nightglass.jpg'),
  'nightglass-observatory': catalogArtwork('locations/eos-meridian/nightglass-observatory.jpg'),
  'aurora-house': catalogArtwork('locations/eos-meridian/aurora-house.jpg'),
  'kepler-iceworks': catalogArtwork('locations/eos-meridian/kepler-iceworks.jpg'),
  'listening-station-seven': catalogArtwork('locations/eos-meridian/listening-station-seven.jpg'),
  'black-lake': catalogArtwork('locations/eos-meridian/black-lake.jpg'),
  'thermal-garden': catalogArtwork('locations/eos-meridian/thermal-garden.jpg'),
  'farline-laboratory': catalogArtwork('locations/eos-meridian/farline-laboratory.jpg'),
  'eventide-overlook': catalogArtwork('locations/eos-meridian/eventide-overlook.jpg'),
  'old-meridian': catalogArtwork('locations/eos-meridian/old-meridian.jpg'),
  'first-habitat': catalogArtwork('locations/eos-meridian/first-habitat.jpg'),
  'velvet-gravity': catalogArtwork('locations/eos-meridian/velvet-gravity.jpg'),
  'quiet-orbit': catalogArtwork('locations/eos-meridian/quiet-orbit.jpg'),
  'static-garden': catalogArtwork('locations/eos-meridian/static-garden.jpg'),
  'needle-and-thread': catalogArtwork('locations/eos-meridian/needle-and-thread.jpg'),
  'the-airlock-diner': catalogArtwork('locations/eos-meridian/the-airlock-diner.jpg'),
  'archive-zero': catalogArtwork('locations/eos-meridian/archive-zero.jpg'),
  'ghost-junction': catalogArtwork('locations/eos-meridian/ghost-junction.jpg'),
};
