import { catalogArtwork } from '../catalogArtwork';
import type { ImageSource } from 'expo-image';

export const gildedCoastLocationAssets: Record<string, ImageSource> = {
  'admiralty-quay': catalogArtwork('locations/gilded-coast/admiralty-quay.jpg'),
  'arrival-steps': catalogArtwork('locations/gilded-coast/admiralty-quay.jpg'),
  'customs-house': catalogArtwork('locations/gilded-coast/admiralty-quay.jpg'),
  'brass-compass': catalogArtwork('locations/gilded-coast/admiralty-quay.jpg'),
  'ferry-hall': catalogArtwork('locations/gilded-coast/admiralty-quay.jpg'),
  'sailors-exchange': catalogArtwork('locations/gilded-coast/admiralty-quay.jpg'),
  'harbor-court': catalogArtwork('locations/gilded-coast/admiralty-quay.jpg'),
  'gilt-row': catalogArtwork('locations/gilded-coast/gilt-row.jpg'),
  'pearl-salon': catalogArtwork('locations/gilded-coast/gilt-row.jpg'),
  'salt-ledger-bank': catalogArtwork('locations/gilded-coast/gilt-row.jpg'),
  'gilt-auction': catalogArtwork('locations/gilded-coast/gilt-row.jpg'),
  'glass-garden': catalogArtwork('locations/gilded-coast/gilt-row.jpg'),
  'velvet-balcony': catalogArtwork('locations/gilded-coast/gilt-row.jpg'),
  'montrose-jewels': catalogArtwork('locations/gilded-coast/gilt-row.jpg'),
  'ropewalk': catalogArtwork('locations/gilded-coast/ropewalk.jpg'),
  'shipwright-yard': catalogArtwork('locations/gilded-coast/ropewalk.jpg'),
  'sail-loft': catalogArtwork('locations/gilded-coast/ropewalk.jpg'),
  'ropewalk-kitchen': catalogArtwork('locations/gilded-coast/ropewalk.jpg'),
  'drydock-baths': catalogArtwork('locations/gilded-coast/ropewalk.jpg'),
  'rivet-school': catalogArtwork('locations/gilded-coast/ropewalk.jpg'),
  'lantern-foundry': catalogArtwork('locations/gilded-coast/ropewalk.jpg'),
  'lantern-market': catalogArtwork('locations/gilded-coast/lantern-market.jpg'),
  'night-market': catalogArtwork('locations/gilded-coast/lantern-market.jpg'),
  'honeyglass-theatre': catalogArtwork('locations/gilded-coast/honeyglass-theatre.jpg'),
  'house-of-hours': catalogArtwork('locations/gilded-coast/house-of-hours.jpg'),
  'mariners-table': catalogArtwork('locations/gilded-coast/lantern-market.jpg'),
  'blue-lantern-inn': catalogArtwork('locations/gilded-coast/lantern-market.jpg'),
  'spice-courtyard': catalogArtwork('locations/gilded-coast/lantern-market.jpg'),
  'breakwater-point': catalogArtwork('locations/gilded-coast/breakwater-point.jpg'),
  'lightkeep': catalogArtwork('locations/gilded-coast/breakwater-point.jpg'),
  'storm-clinic': catalogArtwork('locations/gilded-coast/storm-clinic.jpg'),
  'battery-yard': catalogArtwork('locations/gilded-coast/breakwater-point.jpg'),
  'tide-observatory': catalogArtwork('locations/gilded-coast/breakwater-point.jpg'),
  'breakwater-steps': catalogArtwork('locations/gilded-coast/breakwater-point.jpg'),
  'signal-house': catalogArtwork('locations/gilded-coast/breakwater-point.jpg'),
  'outer-cays': catalogArtwork('locations/gilded-coast/outer-cays.jpg'),
  'reef-landing': catalogArtwork('locations/gilded-coast/outer-cays.jpg'),
  'coconut-beach': catalogArtwork('locations/gilded-coast/outer-cays.jpg'),
  'tidepool-cove': catalogArtwork('locations/gilded-coast/outer-cays.jpg'),
  'windward-village': catalogArtwork('locations/gilded-coast/outer-cays.jpg'),
  'blackfin-anchorage': catalogArtwork('locations/gilded-coast/outer-cays.jpg'),
  'sable-reef': catalogArtwork('locations/gilded-coast/outer-cays.jpg'),
};
