import { catalogArtwork } from '../catalogArtwork';
import type { ImageSource } from 'expo-image';

export const juniperCityLocationAssets:Record<string,ImageSource>={
  'alder-house':catalogArtwork('locations/juniper-city/alder-house.jpg'),
  'alder-district':catalogArtwork('locations/juniper-city/alder-district.jpg'),
  'civic-commons':catalogArtwork('locations/juniper-city/civic-commons.jpg'),
  'common-market':catalogArtwork('locations/juniper-city/common-market.jpg'),
  'chloe-design-studio':catalogArtwork('locations/juniper-city/chloe-design-studio.jpg'),
  'ember-and-rye':catalogArtwork('locations/juniper-city/ember-and-rye.jpg'),
  'glassline-gallery':catalogArtwork('locations/juniper-city/glassline-gallery.jpg'),
  'halcyon-green':catalogArtwork('locations/juniper-city/halcyon-green.jpg'),
  'halcyon-park':catalogArtwork('locations/juniper-city/halcyon-park.jpg'),
  'juniper-cafe':catalogArtwork('locations/juniper-city/juniper-cafe.jpg'),
  'juniper-central-station':catalogArtwork('locations/juniper-city/juniper-central-station.jpg'),
  'juniper-city-hall':catalogArtwork('locations/juniper-city/juniper-city-hall.jpg'),
  'lantern-dive':catalogArtwork('locations/juniper-city/lantern-dive.jpg'),
  'lark-botanical-garden':catalogArtwork('locations/juniper-city/lark-botanical-garden.jpg'),
  'lucky-note':catalogArtwork('locations/juniper-city/lucky-note.jpg'),
  'juniper-civic-arena':catalogArtwork('locations/juniper-city/juniper-civic-arena.jpg'),
  'juniper-medical-center':catalogArtwork('locations/juniper-city/juniper-medical-center.jpg'),
  'marquee-cinema':catalogArtwork('locations/juniper-city/marquee-cinema.jpg'),
  'marquee-quarter':catalogArtwork('locations/juniper-city/marquee-quarter.jpg'),
  'maya-apartment':catalogArtwork('locations/juniper-city/maya-apartment.jpg'),
  'meridian-fitness':catalogArtwork('locations/juniper-city/meridian-fitness.jpg'),
  'moss-and-crumb':catalogArtwork('locations/juniper-city/moss-and-crumb.jpg'),
  'needles-and-notes':catalogArtwork('locations/juniper-city/needles-and-notes.jpg'),
  'northline-motor-lodge':catalogArtwork('locations/juniper-city/northline-motor-lodge.jpg'),
  'northside':catalogArtwork('locations/juniper-city/northside.jpg'),
  'northside-bar':catalogArtwork('locations/juniper-city/northside-bar.jpg'),
  'paper-trail':catalogArtwork('locations/juniper-city/paper-trail.jpg'),
  'photography-studio':catalogArtwork('locations/juniper-city/photography-studio.jpg'),
  'pixel-and-pint':catalogArtwork('locations/juniper-city/pixel-and-pint.jpg'),
  'red-hour':catalogArtwork('locations/juniper-city/red-hour.jpg'),
  'riverhouse-apartments':catalogArtwork('locations/juniper-city/riverhouse-apartments.jpg'),
  'riverside':catalogArtwork('locations/juniper-city/riverside.jpg'),
  'riverside-landing':catalogArtwork('locations/juniper-city/riverside-landing.jpg'),
  'riverwalk':catalogArtwork('locations/juniper-city/riverwalk.jpg'),
  'rivermark-hotel':catalogArtwork('locations/juniper-city/rivermark-hotel.jpg'),
  'side-street-comedy':catalogArtwork('locations/juniper-city/side-street-comedy.jpg'),
  'skyline-rooftop':catalogArtwork('locations/juniper-city/skyline-rooftop.jpg'),
  'sora-table':catalogArtwork('locations/juniper-city/sora-table.jpg'),
  'static-house':catalogArtwork('locations/juniper-city/static-house.jpg'),
  'taqueria-lumen':catalogArtwork('locations/juniper-city/taqueria-lumen.jpg'),
};
