import type { ImageSource } from 'expo-image';

export const juniperCityLocationAssets:Record<string,ImageSource>={
  'alder-district':require('../../assets/locations/juniper-city/alder-district.jpg'),
  'common-market':require('../../assets/locations/juniper-city/common-market.jpg'),
  'chloe-design-studio':require('../../assets/locations/juniper-city/chloe-design-studio.png'),
  'ember-and-rye':require('../../assets/locations/juniper-city/ember-and-rye.jpg'),
  'halcyon-park':require('../../assets/locations/juniper-city/halcyon-park.jpg'),
  'lantern-dive':require('../../assets/locations/juniper-city/lantern-dive.jpg'),
  'lark-botanical-garden':require('../../assets/locations/juniper-city/lark-botanical-garden.jpg'),
  'lucky-note':require('../../assets/locations/juniper-city/lucky-note.jpg'),
  'juniper-civic-arena':require('../../assets/locations/juniper-city/juniper-civic-arena.png'),
  'marquee-cinema':require('../../assets/locations/juniper-city/marquee-cinema.jpg'),
  'maya-apartment':require('../../assets/locations/juniper-city/maya-apartment.jpg'),
  'meridian-fitness':require('../../assets/locations/juniper-city/meridian-fitness.jpg'),
  'moss-and-crumb':require('../../assets/locations/juniper-city/moss-and-crumb.jpg'),
  'needles-and-notes':require('../../assets/locations/juniper-city/needles-and-notes.jpg'),
  'northside-bar':require('../../assets/locations/juniper-city/northside-bar.jpg'),
  'photography-studio':require('../../assets/locations/juniper-city/photography-studio.png'),
  'pixel-and-pint':require('../../assets/locations/juniper-city/pixel-and-pint.png'),
  'riverwalk':require('../../assets/locations/juniper-city/riverwalk.png'),
  'side-street-comedy':require('../../assets/locations/juniper-city/side-street-comedy.png'),
  'skyline-rooftop':require('../../assets/locations/juniper-city/skyline-rooftop.png'),
  'sora-table':require('../../assets/locations/juniper-city/sora-table.png'),
  'static-house':require('../../assets/locations/juniper-city/static-house.png'),
  'taqueria-lumen':require('../../assets/locations/juniper-city/taqueria-lumen.jpg'),
};
