import type { ImageSource } from 'expo-image';

export const portVervelleLocationAssets:Record<string,ImageSource>={
  'atelier-amelie':require('../../assets/locations/port-vervelle/atelier-amelie.png'),
  'bellavista':require('../../assets/locations/port-vervelle/bellavista.png'),
  'bellavista-apartments':require('../../assets/locations/port-vervelle/bellavista-apartments.png'),
  'bellavista-fitness-club':require('../../assets/locations/port-vervelle/bellavista-fitness-club.png'),
  'blue-lantern':require('../../assets/locations/port-vervelle/blue-lantern.png'),
  'cafe-marelle':require('../../assets/locations/port-vervelle/cafe-marelle.png'),
  'casa-del-mare':require('../../assets/locations/port-vervelle/casa-del-mare.png'),
  'farmacia-vervelle':require('../../assets/locations/port-vervelle/farmacia-vervelle.png'),
  'fiore-and-fig':require('../../assets/locations/port-vervelle/fiore-and-fig.png'),
  'forno-bellini':require('../../assets/locations/port-vervelle/forno-bellini.png'),
  'harbor-steps':require('../../assets/locations/port-vervelle/harbor-steps.png'),
  'la-sirena':require('../../assets/locations/port-vervelle/la-sirena.png'),
  'libreria-vervelle':require('../../assets/locations/port-vervelle/libreria-vervelle.png'),
  'lido-vervelle':require('../../assets/locations/port-vervelle/lido-vervelle.png'),
  'luna-terrace':require('../../assets/locations/port-vervelle/luna-terrace.png'),
  'maison-rouge':require('../../assets/locations/port-vervelle/maison-rouge.png'),
  'marina-solana':require('../../assets/locations/port-vervelle/marina-solana.png'),
  'osteria-rosa':require('../../assets/locations/port-vervelle/osteria-rosa.png'),
  'palazzo-civico':require('../../assets/locations/port-vervelle/palazzo-civico.png'),
  'piazza-aurelia':require('../../assets/locations/port-vervelle/piazza-aurelia.png'),
  'porto-marina':require('../../assets/locations/port-vervelle/porto-marina.png'),
  'porto-vecchio':require('../../assets/locations/port-vervelle/porto-vecchio.png'),
  'solana-beach-rentals':require('../../assets/locations/port-vervelle/solana-beach-rentals.png'),
  'spiaggia-solana':require('../../assets/locations/port-vervelle/spiaggia-solana.png'),
  'velours':require('../../assets/locations/port-vervelle/velours.png'),
  'vervelle-fish-market':require('../../assets/locations/port-vervelle/vervelle-fish-market.png'),
  'vervelle-sailing-house':require('../../assets/locations/port-vervelle/vervelle-sailing-house.png'),
  'villa-mirabelle':require('../../assets/locations/port-vervelle/villa-mirabelle.png'),
};
