import { describe, expect, it } from 'vitest';
import { generateScheduleWindow, localToUtc, resolvePresence, validateSchedule, type ActivityTemplate, type CharacterLifeProfile, type LifeLocation, type ScheduleBlock } from './life-engine.ts';

const profile:CharacterLifeProfile={version:1,occupation:{title:'photographer',primaryLocationId:'studio',workPattern:'freelance',flexibility:.6,workDays:[1,2,3,4,5],startRange:{startMinute:540,endMinute:600},durationMinutes:[390,450]},sleep:{preferredBedtime:{startMinute:1380,endMinute:60},preferredWakeTime:{startMinute:420,endMinute:510},variabilityMinutes:30,weekendShiftMinutes:60},lifestyle:{social:.68,adventurous:.72,spontaneous:.68,fitness:.42,nightlife:.54,outdoors:.78,homebody:.42,creativity:.96},interests:['photography','movies','music'],scheduling:{repetitionTolerance:.3,spontaneity:.68,preferredDailyActivityCount:[2,4]}};
const locations:LifeLocation[]=[
  {id:'home',worldId:'world',name:"Maya's Apartment",category:'home',locationType:'residence',supportedActivities:['home_evening','sleep'],tags:['home']},
  {id:'studio',worldId:'world',name:'Photography Studio',category:'work',locationType:'venue',supportedActivities:['work'],tags:['studio','work']},
  {id:'park',worldId:'world',name:'Halcyon Park',category:'outdoor',locationType:'outdoor',supportedActivities:['photo_walk','walk'],tags:['outdoors','photography']},
  {id:'cafe',worldId:'world',name:'Juniper Cafe',category:'cafe',locationType:'venue',supportedActivities:['coffee'],tags:['coffee'],hours:{open:'07:00',close:'22:00'}},
  {id:'gym',worldId:'world',name:'Meridian Fitness',category:'fitness',locationType:'venue',supportedActivities:['gym'],tags:['fitness'],hours:{default:'05:00-23:00'}},
];
const activities:ActivityTemplate[]=[
  {key:'photo_walk',title:'Taking photographs',category:'creative',validTimeWindows:[{startMinute:960,endMinute:1230}],durationMinutes:[60,120],locationCategories:['outdoor'],tags:['photography'],affinity:.96,preferredWeeklyFrequency:[2,5],maximumWeeklyFrequency:5,minimumGapHours:18,priority:'preferred_activity',visibility:'hint',interruptibility:'open'},
  {key:'coffee',title:'Coffee and editing',category:'cafe',validTimeWindows:[{startMinute:450,endMinute:1080}],durationMinutes:[40,90],locationCategories:['cafe'],tags:['coffee'],affinity:.82,preferredWeeklyFrequency:[2,4],maximumWeeklyFrequency:4,minimumGapHours:12,priority:'recurring_routine',visibility:'hidden',interruptibility:'open'},
  {key:'gym',title:'Getting a workout in',category:'fitness',validTimeWindows:[{startMinute:990,endMinute:1260}],durationMinutes:[45,75],locationCategories:['fitness'],tags:['fitness'],affinity:.55,preferredWeeklyFrequency:[2,4],maximumWeeklyFrequency:4,minimumGapHours:30,priority:'recurring_routine',visibility:'hidden',interruptibility:'limited'},
  {key:'home_evening',title:'Having a quiet night at home',category:'home',validTimeWindows:[{startMinute:1080,endMinute:1380}],durationMinutes:[75,150],locationCategories:['residence'],tags:['home'],affinity:.75,preferredWeeklyFrequency:[2,7],maximumWeeklyFrequency:7,minimumGapHours:6,priority:'preferred_activity',visibility:'hidden',interruptibility:'open'},
];

const generate=(overrides:Partial<Parameters<typeof generateScheduleWindow>[0]>={})=>generateScheduleWindow({characterInstanceId:'maya-instance',seed:'maya-user-a',timezone:'America/New_York',fromLocalDate:'2026-08-17',days:7,profile,locations,homeLocationId:'home',activityTemplates:activities,generationVersion:'life_engine_v1',...overrides});

describe('Character Life Engine',()=>{
  it('is deterministic and creates a stable seven-day reality',()=>{expect(generate()).toEqual(generate());expect(generate().length).toBeGreaterThan(20);});
  it('produces different lives for different user-companion seeds',()=>{expect(generate({seed:'maya-user-a'})).not.toEqual(generate({seed:'maya-user-b'}));});
  it('does not overlap routine events and adds travel between consecutive places',()=>{const events=generate();expect(validateSchedule(events,locations,'America/New_York').filter(issue=>issue.startsWith('overlap'))).toEqual([]);expect(events.some(event=>event.activityKey==='travel')).toBe(true);const nonTravel=events.filter(event=>event.activityKey!=='travel'),missing:string[]=[];for(let index=1;index<nonTravel.length;index++){const previous=nonTravel[index-1]!,event=nonTravel[index]!;if(previous.locationId&&event.locationId&&previous.locationId!==event.locationId&&new Date(event.startsAt).getTime()-new Date(previous.endsAt).getTime()<12*3600000&&!events.some(candidate=>candidate.activityKey==='travel'&&candidate.metadata?.['fromLocationId']===previous.locationId&&candidate.metadata?.['toLocationId']===event.locationId&&candidate.startsAt>=previous.endsAt&&candidate.endsAt<=event.startsAt))missing.push(`${previous.generationKey}->${event.generationKey}`);}expect(missing).toEqual([]);});
  it('keeps work meaningful but varies surrounding activity',()=>{const events=generate(),workDays=new Set(events.filter(event=>event.activityKey==='work').map(event=>event.startsAt.slice(0,10)));expect(workDays.size).toBeGreaterThanOrEqual(4);expect(new Set(events.filter(event=>!['work','sleep','travel'].includes(event.activityKey)).map(event=>event.activityKey)).size).toBeGreaterThan(1);});
  it('reserves user plans above generated life',()=>{const plan:ScheduleBlock={activityKey:'dinner',title:'Dinner with you',locationId:'cafe',startsAt:localToUtc('2026-08-18',19*60,'America/New_York').toISOString(),endsAt:localToUtc('2026-08-18',21*60,'America/New_York').toISOString(),priority:'user_commitment',visibility:'shared',source:'user_plan',interruptibility:'open',generationKey:'plan:one'};const events=generate({fixedCommitments:[plan]});expect(events).toContainEqual(plan);expect(events.filter(event=>event!==plan&&new Date(event.startsAt)<new Date(plan.endsAt)&&new Date(event.endsAt)>new Date(plan.startsAt))).toEqual([]);});
  it('enforces explicit weekly activity limits and minimum gaps',()=>{const events=generate(),coffee=events.filter(event=>event.activityKey==='coffee');expect(coffee.length).toBeLessThanOrEqual(4);for(let index=1;index<coffee.length;index++)expect((new Date(coffee[index]!.startsAt).getTime()-new Date(coffee[index-1]!.endsAt).getTime())/3600000).toBeGreaterThanOrEqual(12);});
  it('resolves travel, sleep, work, and next obligation from one presence service',()=>{const events=generate(),target=events.find(event=>event.activityKey==='work')!;const presence=resolvePresence(events,new Date(new Date(target.startsAt).getTime()+60000),{characterInstanceId:'maya-instance',locationId:'home'});expect(presence.activityKey).toBe('work');expect(presence.state).toBe('working');expect(presence.interruptibility).toBe('busy');expect(presence.nextEvent).toBeDefined();});
  it('converts local wall time safely across DST boundaries',()=>{const before=localToUtc('2026-11-01',90,'America/New_York'),after=localToUtc('2026-11-02',90,'America/New_York');expect(before.toISOString()).toMatch(/^2026-11-01T0[56]:30/);expect(after.toISOString()).toBe('2026-11-02T06:30:00.000Z');});
  it('understands production-style object opening hours',()=>{const closedEvent:ScheduleBlock={activityKey:'coffee',title:'Late coffee',locationId:'cafe',startsAt:localToUtc('2026-08-17',22*60+30,'America/New_York').toISOString(),endsAt:localToUtc('2026-08-17',23*60,'America/New_York').toISOString(),priority:'preferred_activity',visibility:'hidden',source:'generated',interruptibility:'open',generationKey:'closed:cafe'};expect(validateSchedule([closedEvent],locations,'America/New_York')).toContain('closed-location:closed:cafe');});
  it('uses authored occupation variants instead of vague work filler',()=>{const v2:CharacterLifeProfile={...profile,version:2,occupation:{title:'emergency physician',workPattern:'shifts',flexibility:.2,scheduleBlocks:[{key:'hospital-day',title:'emergency physician',activityKey:'occupation_hospital',workDays:[1],startRange:{startMinute:420,endMinute:420},durationMinutes:[600,600],primaryLocationId:'studio',activityVariants:['working an emergency department shift'],breakPolicy:'none',visibility:'known',interruptibility:'busy'}]}};const events=generate({profile:v2,generationVersion:'life_engine_v2'}),work=events.find(event=>event.activityKey==='occupation_hospital');expect(work?.title).toBe('working an emergency department shift');expect(work?.metadata?.['activityLabel']).toBe('working an emergency department shift');expect(events.some(event=>/Focused on work|In the middle of a project|taking care of a few things/i.test(event.title))).toBe(false);});
  it('supports cross-midnight shifts and recovery without overlap',()=>{const overnight:CharacterLifeProfile={...profile,version:2,occupation:{title:'emergency physician',workPattern:'shifts',flexibility:.2,scheduleBlocks:[{key:'hospital-night',title:'emergency physician',activityKey:'occupation_hospital_night',workDays:[1],startRange:{startMinute:19*60,endMinute:19*60},durationMinutes:[720,720],primaryLocationId:'studio',activityVariants:['working an overnight emergency shift'],breakPolicy:'none',recoverySleepMinutes:[360,360]}]}};const events=generate({profile:overnight,generationVersion:'life_engine_v2'}),shift=events.find(event=>event.activityKey==='occupation_hospital_night');expect(shift).toBeDefined();expect(new Date(shift!.endsAt).getTime()-new Date(shift!.startsAt).getTime()).toBe(12*3600000);expect(events.some(event=>event.metadata?.['recoveryFrom']==='hospital-night')).toBe(true);expect(validateSchedule(events,locations,'America/New_York').filter(issue=>issue.startsWith('overlap'))).toEqual([]);});
  it('keeps rare authored activities to one occurrence per rolling week',()=>{const rare:ActivityTemplate={...activities[0]!,key:'rare_signature',title:'A rare signature outing',maximumWeeklyFrequency:1,preferredWeeklyFrequency:[1,1],minimumGapHours:72,affinity:1,rare:true};const events=generate({activityTemplates:[rare,...activities],generationVersion:'life_engine_v2'});expect(events.filter(event=>event.activityKey==='rare_signature').length).toBeLessThanOrEqual(1);});
});
