/** Display copy is separate from activityNotes, which remain internal planning rules. */
const descriptions: Record<string,string> = {
 'shopping':'Browse the stalls and look for something worth bringing home.',
 'market stalls':'Compare what the vendors have brought to market.',
 'street food':'Try a bite from the street vendors.',
 'food':'Share something to eat and take a break.',
 'hot meals':'Sit down over a warm meal.',
 'meals':'Make time for a meal together.',
 'drinks':'Share a drink and an unhurried conversation.',
 'ale':'Compare ales over a conversation.',
 'wine tasting':'Compare flavors and choose a favorite wine.',
 'formal dining':'Arrange a dinner with a little ceremony.',
 'private dinners':'Plan a quiet dinner for two.',
 'music':'Listen together and trade favorite songs.',
 'sea songs':'Trade songs and stories from the sea.',
 'street performance':'Stop to watch a performance.',
 'gossip':'Compare the stories circulating around town.',
 'rumor exchange':'Trade rumors and decide which ones deserve a closer look.',
 'crew gossip':'Catch up on the stories passing between crews.',
 'veteran gossip':'Listen to stories from those who have served.',
 'people watching':'Watch the passing crowd and compare impressions.',
 'observation':'Take a closer look at your surroundings.',
 'local conversation':'Get to know the people who spend time here.',
 'private conversation':'Find time for a conversation away from the crowd.',
 'political conversation':'Compare views on the people and decisions shaping the realm.',
 'debate':'Take opposite sides and see where the discussion leads.',
 'salon debate':'Join a discussion of ideas, loyalties, and disagreements.',
 'archive research':'Look through the records for a clue or a forgotten connection.',
 'archive study':'Spend time with the records and compare what you find.',
 'research':'Explore a question together and compare your findings.',
 'ancient research':'Study traces of the past for something others have missed.',
 'genealogy research':'Trace a family connection through the records.',
 'genealogy':'Explore the branches of a family history.',
 'Name study':'Study the names and histories that shape the realm.',
 'bathing':'Plan a relaxing soak together.',
 'massage':'Arrange a massage and a little time to unwind.',
 'recovery':'Take things slowly and make room to rest.',
 'medical care':'Seek care and discuss what would help.',
 'healing':'Arrange care for an injury or a difficult recovery.',
 'herbal work':'Compare herbs and their traditional uses.',
 'herbs':'Browse herbs and ask about their uses.',
 'quiet prayer':'Take a quiet moment for reflection.',
 'meditation':'Set aside time to settle your thoughts.',
 'worship':'Attend a service or spend a moment in reflection.',
 'confession':'Speak privately about something weighing on you.',
 'memorial visits':'Visit a memorial and share what it means to you.',
 'memorials':'Remember someone and listen to the stories they left behind.',
 'training':'Practice a skill together.',
 'weapon inspection':'Examine the workmanship and condition of a weapon.',
 'smithing':'Discuss a piece of metalwork with a smith.',
 'forging':'Plan a piece of metalwork.',
 'repairs':'Bring something that needs mending.',
 'crafts':'Browse handmade work and talk about how it is made.',
 'apprenticeship':'Ask about learning a craft from someone experienced.',
 'trade':'Compare goods and negotiate an exchange.',
 'barter':'Find an exchange that works for both sides.',
 'produce trade':'Browse the harvest and compare produce.',
 'camp trade':'See what supplies are changing hands in camp.',
 'letters':'Write a letter or arrange for one to be delivered.',
 'message exchange':'Arrange to exchange a message.',
 'courier exchange':'Meet a courier to discuss a delivery.',
 'information exchange':'Compare what each of you has learned.',
 'contract review':'Read through an agreement and discuss its terms.',
 'banking':'Discuss savings, payments, or a financial arrangement.',
 'legal petitions':'Prepare a request and decide how to present it.',
 'petitions':'Put a request into words and seek a hearing.',
 'royal audiences':'Seek an audience to present a request.',
 'diplomacy':'Explore a disagreement and possible common ground.',
 'private negotiation':'Discuss terms away from the public eye.',
 'court intrigue':'Compare loyalties and the rumors moving through court.',
 'strategy councils':'Discuss a plan and weigh the alternatives.',
 'route planning':'Compare routes and prepare for the journey.',
 'navigation':'Study the route and work out your next bearing.',
 'cliff walks':'Plan a walk along the cliffs.',
 'forest travel':'Plan a journey through the forest.',
 'weather watching':'Watch the sky and compare signs of a change.',
 'tide monitoring':'Watch the tide and discuss the best time to travel.',
 'fishing':'Set aside time by the water to fish.',
 'games':'Choose a game and enjoy a little friendly competition.',
 'dice':'Play a round of dice.',
 'lodging':'Arrange a place to stay.',
 'safe lodging':'Look for a secure place to spend the night.',
 'shelter':'Arrange somewhere to rest and recover.',
 'mutual aid':'Find a practical way to help someone.',
 'community work':'Join a task that benefits the neighborhood.',
 'travel':'Plan your next journey.',
 'chance meetings':'Leave room for an unexpected conversation.',
 'ruin exploration':'Plan an expedition to examine what remains.',
 'scouting':'Discuss a scouting route and what to look for.',
 'dragon care':'Discuss the work of tending a dragon.',
 'egg study':'Examine what is known about the eggs.',
 'ritual observation':'Arrange to witness a ritual.',
 'private vows':'Find words for a promise that matters to you.',
 'feasts':'Plan to share a feast.',
 'formal feasts':'Arrange to attend a formal feast.',
 'masked balls':'Plan an evening of masks, music, and conversation.',
};
export function isInternalActivityCopy(value: unknown): boolean {
 return typeof value==='string' && /(?:must follow|follow the location|current access|story[- ](?:state|gated)|canonical|co-presence|operating rhythm|depends on weather, light|requires invitation and established|do not (?:invent|assume)|system prompt)/i.test(value);
}
export function activityDisplayDescription(activity:string, authored?:unknown):string|undefined {
 if(typeof authored==='string'&&authored.trim()&&!isInternalActivityCopy(authored))return authored.trim();
 return descriptions[activity.toLowerCase().replace(/[_-]+/g,' ').trim()];
}
export function activityDisplayDescriptions(activities:readonly string[],existing:Record<string,string>={}):Record<string,string>{
 return Object.fromEntries(activities.filter(a=>!isInternalActivityCopy(a)).flatMap(a=>{const d=activityDisplayDescription(a,existing[a]);return d?[[a,d]]:[];}));
}
export function activityPlanningPrompt(activity:string,location:string):string {
 return 'Let’s plan a visit to '+location+' for '+activity.replace(/[_-]+/g,' ').trim()+'.';
}
