export type MediaLevel='standard'|'romance'|'suggestive'|'mature'|'explicit';
export type PhotoIntent={requested:boolean;subject:'companion'|'location'|'activity'|'outfit'|'date'|'unknown';shotPreference?:'selfie'|'portrait'|'full_body'|'scene';requestedContentLevel?:MediaLevel;confidence:number};
export type MediaHistory={source:'user_request'|'life_event'|'date'|'moment'|'story';createdAt:string;locationId?:string;shotType?:string};

export function classifyPhotoIntent(text:string):PhotoIntent{
  const requested=/\b(send|show|take|share|see|want|lemme|let me)\b.{0,30}\b(photo|picture|pic|selfie|outfit|look|where you are|what you(?:'re| are) doing)\b|\b(selfie|photo|picture|pic)\s*\??$/i.test(text);const lower=text.toLowerCase();const subject:PhotoIntent['subject']=/where you are|studio|cafe|café|rooftop|riverwalk|place/.test(lower)?'location':/outfit|wearing|look/.test(lower)?'outfit':/doing|working/.test(lower)?'activity':/date/.test(lower)?'date':requested?'companion':'unknown';const shotPreference:PhotoIntent['shotPreference']=/selfie/.test(lower)?'selfie':/outfit|full.?body/.test(lower)?'full_body':subject==='location'?'scene':undefined;const requestedContentLevel:MediaLevel|undefined=/nude|naked|topless|explicit|tits?|boobs?/i.test(text)?'explicit':/suggestive|lingerie|sexy/i.test(text)?'suggestive':/romantic|kiss/i.test(text)?'romance':undefined;return{requested,subject,...(shotPreference?{shotPreference}:{}),...(requestedContentLevel?{requestedContentLevel}:{}),confidence:requested?.94:0};
}
export function automaticPhotoAllowed(history:MediaHistory[],now:Date):boolean{const automatic=history.filter((item)=>item.source!=='user_request'&&now.getTime()-new Date(item.createdAt).getTime()<86400000);if(automatic.length>=2)return false;return !automatic.some((item)=>now.getTime()-new Date(item.createdAt).getTime()<8*3600000);}
export function mediaCapabilityAllowed(level:MediaLevel,capabilities:Record<MediaLevel,boolean>,adult=true):boolean{return adult&&Boolean(capabilities[level]);}
export function trustedImagePrompt(input:{identity:{name:string;age:number;canonicalDescription:string;doNotChange:string[]};scene:{location:string;activity:string;mood:string};shot:string;contentLevel:'standard'|'romance'}):string{return `IDENTITY\n${input.identity.name}, fictional adult age ${input.identity.age}. ${input.identity.canonicalDescription}\nSCENE\n${input.scene.location}; ${input.scene.activity}; mood ${input.scene.mood}.\nCOMPOSITION\n${input.shot}; believable personal photography.\nCONTENT LEVEL\n${input.contentLevel}.\nDO-NOT-CHANGE IDENTITY\n${input.identity.doNotChange.join(', ')}. Do not redesign the person or imitate a real person.`;}
